EXEC DropTable ('XXMX_FA_MASS_ADDITIONS_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_FA_MASS_ADDITIONS_EXT" 
   (	
      FILE_SET_ID VARCHAR2(30 BYTE), 
      INTERFACE_LINE_NUM                   NUMBER,         
      BOOK_TYPE_CODE                       VARCHAR2(30),   
      TRANSACTION_NAME                     VARCHAR2(240),  
      ASSET_NUMBER                         VARCHAR2(30),   
      DESCRIPTION                          VARCHAR2(80),   
      TAG_NUMBER                           VARCHAR2(15),   
      MANUFACTURER_NAME                    VARCHAR2(360),  
      SERIAL_NUMBER                        VARCHAR2(35),   
      MODEL_NUMBER                         VARCHAR2(40),   
      ASSET_TYPE                           VARCHAR2(11),   
      FIXED_ASSETS_COST                    NUMBER,         
      DATE_PLACED_IN_SERVICE               VARCHAR2(20),           
      PRORATE_CONVENTION_CODE              VARCHAR2(10),   
      FIXED_ASSETS_UNITS                   NUMBER,         
      CATEGORY_SEGMENT1                    VARCHAR2(30),   
      CATEGORY_SEGMENT2                    VARCHAR2(30),   
      CATEGORY_SEGMENT3                    VARCHAR2(30),   
      CATEGORY_SEGMENT4                    VARCHAR2(30),   
      CATEGORY_SEGMENT5                    VARCHAR2(30),   
      CATEGORY_SEGMENT6                    VARCHAR2(30),   
      CATEGORY_SEGMENT7                    VARCHAR2(30),   
      POSTING_STATUS                       VARCHAR2(15),   
      QUEUE_NAME                           VARCHAR2(30),   
      FEEDER_SYSTEM_NAME                   VARCHAR2(40),   
      PARENT_ASSET_NUMBER                  VARCHAR2(30),   
      ADD_TO_ASSET_NUMBER                  VARCHAR2(30),   
      ASSET_KEY_SEGMENT1                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT2                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT3                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT4                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT5                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT6                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT7                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT8                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT9                   VARCHAR2(30),   
      ASSET_KEY_SEGMENT10                  VARCHAR2(30),   
      INVENTORIAL                          VARCHAR2(3),    
      PROPERTY_TYPE_CODE                   VARCHAR2(30),   
      PROPERTY_1245_1250_CODE              VARCHAR2(4),    
      IN_USE_FLAG                          VARCHAR2(3),    
      OWNED_LEASED                         VARCHAR2(15),   
      NEW_USED                             VARCHAR2(4),    
      MATERIAL_INDICATOR_FLAG              VARCHAR2(1),    
      COMMITMENT                           VARCHAR2(30),   
      INVESTMENT_LAW                       VARCHAR2(30),   
      AMORTIZE_FLAG                        VARCHAR2(3),    
      AMORTIZATION_START_DATE              VARCHAR2(20),           
      DEPRECIATE_FLAG                      VARCHAR2(3),    
      SALVAGE_TYPE                         VARCHAR2(30),   
      SALVAGE_VALUE                        NUMBER,         
      PERCENT_SALVAGE_VALUE                NUMBER,         
      YTD_DEPRN                            NUMBER,         
      DEPRN_RESERVE                        NUMBER,         
      BONUS_YTD_DEPRN                      NUMBER,         
      BONUS_DEPRN_RESERVE                  NUMBER,         
      YTD_IMPAIRMENT                       NUMBER,         
      IMPAIRMENT_RESERVE                   NUMBER,         
      METHOD_CODE                          VARCHAR2(12),   
      LIFE_IN_MONTHS                       NUMBER(4),      
      BASIC_RATE                           NUMBER,         
      ADJUSTED_RATE                        NUMBER,         
      UNIT_OF_MEASURE                      VARCHAR2(25),   
      PRODUCTION_CAPACITY                  NUMBER,         
      CEILING_NAME                         VARCHAR2(30),   
      BONUS_RULE                           VARCHAR2(30),   
      CASH_GENERATING_UNIT                 VARCHAR2(30),   
      DEPRN_LIMIT_TYPE                     VARCHAR2(30),   
      ALLOWED_DEPRN_LIMIT                  NUMBER,         
      ALLOWED_DEPRN_LIMIT_AMOUNT           NUMBER,         
      PAYABLES_COST                        NUMBER,         
      CLEARING_ACCT_SEGMENT1               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT2               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT3               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT4               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT5               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT6               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT7               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT8               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT9               VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT10              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT11              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT12              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT13              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT14              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT15              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT16              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT17              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT18              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT19              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT20              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT21              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT22              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT23              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT24              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT25              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT26              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT27              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT28              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT29              VARCHAR2(25),   
      CLEARING_ACCT_SEGMENT30              VARCHAR2(25),   
      ATTRIBUTE1                           VARCHAR2(150),  
      ATTRIBUTE2                           VARCHAR2(150),  
      ATTRIBUTE3                           VARCHAR2(150),  
      ATTRIBUTE4                           VARCHAR2(150),  
      ATTRIBUTE5                           VARCHAR2(150),  
      ATTRIBUTE6                           VARCHAR2(150),  
      ATTRIBUTE7                           VARCHAR2(150),  
      ATTRIBUTE8                           VARCHAR2(150),  
      ATTRIBUTE9                           VARCHAR2(150),  
      ATTRIBUTE10                          VARCHAR2(150),  
      ATTRIBUTE11                          VARCHAR2(150),  
      ATTRIBUTE12                          VARCHAR2(150),  
      ATTRIBUTE13                          VARCHAR2(150),  
      ATTRIBUTE14                          VARCHAR2(150),  
      ATTRIBUTE15                          VARCHAR2(150),  
      ATTRIBUTE16                          VARCHAR2(150),  
      ATTRIBUTE17                          VARCHAR2(150),  
      ATTRIBUTE18                          VARCHAR2(150),  
      ATTRIBUTE19                          VARCHAR2(150),  
      ATTRIBUTE20                          VARCHAR2(150),  
      ATTRIBUTE21                          VARCHAR2(150),  
      ATTRIBUTE22                          VARCHAR2(150),  
      ATTRIBUTE23                          VARCHAR2(150),  
      ATTRIBUTE24                          VARCHAR2(150),  
      ATTRIBUTE25                          VARCHAR2(150),  
      ATTRIBUTE26                          VARCHAR2(150),  
      ATTRIBUTE27                          VARCHAR2(150),  
      ATTRIBUTE28                          VARCHAR2(150),  
      ATTRIBUTE29                          VARCHAR2(150),  
      ATTRIBUTE30                          VARCHAR2(150),  
      ATTRIBUTE_NUMBER1                    NUMBER,         
      ATTRIBUTE_NUMBER2                    NUMBER,         
      ATTRIBUTE_NUMBER3                    NUMBER,         
      ATTRIBUTE_NUMBER4                    NUMBER,         
      ATTRIBUTE_NUMBER5                    NUMBER,         
      ATTRIBUTE_DATE1                      VARCHAR2(20),           
      ATTRIBUTE_DATE2                      VARCHAR2(20),           
      ATTRIBUTE_DATE3                      VARCHAR2(20),           
      ATTRIBUTE_DATE4                      VARCHAR2(20),           
      ATTRIBUTE_DATE5                      VARCHAR2(20),           
      ATTRIBUTE_CATEGORY_CODE              VARCHAR2(30),   
      CONTEXT                              VARCHAR2(250),  
      TH_ATTRIBUTE1                        VARCHAR2(150),  
      TH_ATTRIBUTE2                        VARCHAR2(150),  
      TH_ATTRIBUTE3                        VARCHAR2(150),  
      TH_ATTRIBUTE4                        VARCHAR2(150),  
      TH_ATTRIBUTE5                        VARCHAR2(150),  
      TH_ATTRIBUTE6                        VARCHAR2(150),  
      TH_ATTRIBUTE7                        VARCHAR2(150),  
      TH_ATTRIBUTE8                        VARCHAR2(150),  
      TH_ATTRIBUTE9                        VARCHAR2(150),  
      TH_ATTRIBUTE10                       VARCHAR2(150),  
      TH_ATTRIBUTE11                       VARCHAR2(150),  
      TH_ATTRIBUTE12                       VARCHAR2(150),  
      TH_ATTRIBUTE13                       VARCHAR2(150),  
      TH_ATTRIBUTE14                       VARCHAR2(150),  
      TH_ATTRIBUTE15                       VARCHAR2(150),  
      TH_ATTRIBUTE_NUMBER1                 NUMBER,         
      TH_ATTRIBUTE_NUMBER2                 NUMBER,         
      TH_ATTRIBUTE_NUMBER3                 NUMBER,         
      TH_ATTRIBUTE_NUMBER4                 NUMBER,         
      TH_ATTRIBUTE_NUMBER5                 NUMBER,         
      TH_ATTRIBUTE_DATE1                   VARCHAR2(20),           
      TH_ATTRIBUTE_DATE2                   VARCHAR2(20),           
      TH_ATTRIBUTE_DATE3                   VARCHAR2(20),           
      TH_ATTRIBUTE_DATE4                   VARCHAR2(20),           
      TH_ATTRIBUTE_DATE5                   VARCHAR2(20),           
      TH_ATTRIBUTE_CATEGORY_CODE           VARCHAR2(30),   
      TH2_ATTRIBUTE1                       VARCHAR2(150),  
      TH2_ATTRIBUTE2                       VARCHAR2(150),  
      TH2_ATTRIBUTE3                       VARCHAR2(150),  
      TH2_ATTRIBUTE4                       VARCHAR2(150),  
      TH2_ATTRIBUTE5                       VARCHAR2(150),  
      TH2_ATTRIBUTE6                       VARCHAR2(150),  
      TH2_ATTRIBUTE7                       VARCHAR2(150),  
      TH2_ATTRIBUTE8                       VARCHAR2(150),  
      TH2_ATTRIBUTE9                       VARCHAR2(150),  
      TH2_ATTRIBUTE10                      VARCHAR2(150),  
      TH2_ATTRIBUTE11                      VARCHAR2(150),  
      TH2_ATTRIBUTE12                      VARCHAR2(150),  
      TH2_ATTRIBUTE13                      VARCHAR2(150),  
      TH2_ATTRIBUTE14                      VARCHAR2(150),  
      TH2_ATTRIBUTE15                      VARCHAR2(150),  
      TH2_ATTRIBUTE_NUMBER1                NUMBER,         
      TH2_ATTRIBUTE_NUMBER2                NUMBER,         
      TH2_ATTRIBUTE_NUMBER3                NUMBER,         
      TH2_ATTRIBUTE_NUMBER4                NUMBER,         
      TH2_ATTRIBUTE_NUMBER5                NUMBER,         
      TH2_ATTRIBUTE_DATE1                  VARCHAR2(20),           
      TH2_ATTRIBUTE_DATE2                  VARCHAR2(20),           
      TH2_ATTRIBUTE_DATE3                  VARCHAR2(20),           
      TH2_ATTRIBUTE_DATE4                  VARCHAR2(20),           
      TH2_ATTRIBUTE_DATE5                  VARCHAR2(20),           
      TH2_ATTRIBUTE_CATEGORY_CODE          VARCHAR2(30),   
      AI_ATTRIBUTE1                        VARCHAR2(150),  
      AI_ATTRIBUTE2                        VARCHAR2(150),  
      AI_ATTRIBUTE3                        VARCHAR2(150),  
      AI_ATTRIBUTE4                        VARCHAR2(150),  
      AI_ATTRIBUTE5                        VARCHAR2(150),  
      AI_ATTRIBUTE6                        VARCHAR2(150),  
      AI_ATTRIBUTE7                        VARCHAR2(150),  
      AI_ATTRIBUTE8                        VARCHAR2(150),  
      AI_ATTRIBUTE9                        VARCHAR2(150),  
      AI_ATTRIBUTE10                       VARCHAR2(150),  
      AI_ATTRIBUTE11                       VARCHAR2(150),  
      AI_ATTRIBUTE12                       VARCHAR2(150),  
      AI_ATTRIBUTE13                       VARCHAR2(150),  
      AI_ATTRIBUTE14                       VARCHAR2(150),  
      AI_ATTRIBUTE15                       VARCHAR2(150),  
      AI_ATTRIBUTE_NUMBER1                 NUMBER,         
      AI_ATTRIBUTE_NUMBER2                 NUMBER,         
      AI_ATTRIBUTE_NUMBER3                 NUMBER,         
      AI_ATTRIBUTE_NUMBER4                 NUMBER,         
      AI_ATTRIBUTE_NUMBER5                 NUMBER,         
      AI_ATTRIBUTE_DATE1                   VARCHAR2(20),           
      AI_ATTRIBUTE_DATE2                   VARCHAR2(20),           
      AI_ATTRIBUTE_DATE3                   VARCHAR2(20),           
      AI_ATTRIBUTE_DATE4                   VARCHAR2(20),           
      AI_ATTRIBUTE_DATE5                   VARCHAR2(20),           
      AI_ATTRIBUTE_CATEGORY_CODE           VARCHAR2(30),   
      MASS_PROPERTY_FLAG                   VARCHAR2(1),    
      GROUP_ASSET_NUMBER                   VARCHAR2(30),   
      REDUCTION_RATE                       NUMBER,         
      REDUCE_ADDITION_FLAG                 VARCHAR2(1),    
      REDUCE_ADJUSTMENT_FLAG               VARCHAR2(1),    
      REDUCE_RETIREMENT_FLAG               VARCHAR2(1),    
      RECOGNIZE_GAIN_LOSS                  VARCHAR2(30),   
      RECAPTURE_RESERVE_FLAG               VARCHAR2(1),    
      LIMIT_PROCEEDS_FLAG                  VARCHAR2(1),    
      TERMINAL_GAIN_LOSS                   VARCHAR2(30),   
      TRACKING_METHOD                      VARCHAR2(30),   
      EXCESS_ALLOCATION_OPTION             VARCHAR2(30),   
      DEPRECIATION_OPTION                  VARCHAR2(30),   
      MEMBER_ROLLUP_FLAG                   VARCHAR2(1),    
      ALLOCATE_TO_FULLY_RSV_FLAG           VARCHAR2(1),    
      OVER_DEPRECIATE_OPTION               VARCHAR2(30),   
      PREPARER_EMAIL_ADDRESS               VARCHAR2(240),  
      MERGED_CODE                          VARCHAR2(3),    
      PARENT_INT_LINE_NUM                  NUMBER,         
      SUM_UNITS                            VARCHAR2(3),    
      NEW_MASTER_FLAG                      VARCHAR2(3),    
      UNITS_TO_ADJUST                      NUMBER(18),     
      SHORT_FISCAL_YEAR_FLAG               VARCHAR2(3),    
      CONVERSION_DATE                      VARCHAR2(20),           
      ORIGINAL_DEPRN_START_DATE            VARCHAR2(20),           
      GLOBAL_ATTRIBUTE1                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE2                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE3                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE4                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE5                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE6                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE7                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE8                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE9                    VARCHAR2(150),  
      GLOBAL_ATTRIBUTE10                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE11                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE12                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE13                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE14                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE15                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE16                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE17                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE18                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE19                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE20                   VARCHAR2(150),  
      GLOBAL_ATTRIBUTE_NUMBER1             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER2             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER3             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER4             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER5             NUMBER,         
      GLOBAL_ATTRIBUTE_DATE1               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE2               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE3               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE4               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE5               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_CATEGORY            VARCHAR2(30),   
      NBV_AT_SWITCH                        NUMBER,         
      PERIOD_NAME_FULLY_RESERVED           VARCHAR2(15),   
      PERIOD_NAME_EXTENDED                 VARCHAR2(15),   
      PRIOR_DEPRN_LIMIT_TYPE               VARCHAR2(30),   
      PRIOR_DEPRN_LIMIT                    NUMBER,         
      PRIOR_DEPRN_LIMIT_AMOUNT             NUMBER,         
      PRIOR_METHOD_CODE                    VARCHAR2(12),   
      PRIOR_LIFE_IN_MONTHS                 NUMBER(18),     
      PRIOR_BASIC_RATE                     NUMBER,         
      PRIOR_ADJUSTED_RATE                  NUMBER,         
      ASSET_SCHEDULE_NUM                   NUMBER(18),     
      LEASE_NUMBER                         VARCHAR2(30),   
      REVAL_RESERVE                        NUMBER,         
      REVAL_LOSS_BALANCE                   NUMBER,         
      REVAL_AMORTIZATION_BASIS             NUMBER,         
      IMPAIR_LOSS_BALANCE                  NUMBER,         
      REVAL_CEILING                        NUMBER,         
      FAIR_MARKET_VALUE                    NUMBER,         
      LAST_PRICE_INDEX_VALUE               NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER6             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER7             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER8             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER9             NUMBER,         
      GLOBAL_ATTRIBUTE_NUMBER10            NUMBER,         
      GLOBAL_ATTRIBUTE_DATE6               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE7               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE8               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE9               VARCHAR2(20),           
      GLOBAL_ATTRIBUTE_DATE10              VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE1                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE2                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE3                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE4                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE5                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE6                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE7                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE8                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE9                 VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE10                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE11                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE12                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE13                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE14                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE15                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE16                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE17                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE18                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE19                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE20                VARCHAR2(150),  
      BK_GLOBAL_ATTRIBUTE_NUMBER1          NUMBER,         
      BK_GLOBAL_ATTRIBUTE_NUMBER2          NUMBER,         
      BK_GLOBAL_ATTRIBUTE_NUMBER3          NUMBER,         
      BK_GLOBAL_ATTRIBUTE_NUMBER4          NUMBER,         
      BK_GLOBAL_ATTRIBUTE_NUMBER5          NUMBER,         
      BK_GLOBAL_ATTRIBUTE_DATE1            VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE_DATE2            VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE_DATE3            VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE_DATE4            VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE_DATE5            VARCHAR2(20),           
      BK_GLOBAL_ATTRIBUTE_CATEGORY         VARCHAR2(30),   
      TH_GLOBAL_ATTRIBUTE1                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE2                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE3                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE4                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE5                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE6                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE7                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE8                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE9                 VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE10                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE11                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE12                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE13                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE14                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE15                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE16                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE17                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE18                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE19                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE20                VARCHAR2(150),  
      TH_GLOBAL_ATTRIBUTE_NUMBER1          NUMBER,         
      TH_GLOBAL_ATTRIBUTE_NUMBER2          NUMBER,         
      TH_GLOBAL_ATTRIBUTE_NUMBER3          NUMBER,         
      TH_GLOBAL_ATTRIBUTE_NUMBER4          NUMBER,         
      TH_GLOBAL_ATTRIBUTE_NUMBER5          NUMBER,         
      TH_GLOBAL_ATTRIBUTE_DATE1            VARCHAR2(20),           
      TH_GLOBAL_ATTRIBUTE_DATE2            VARCHAR2(20),           
      TH_GLOBAL_ATTRIBUTE_DATE3            VARCHAR2(20),           
      TH_GLOBAL_ATTRIBUTE_DATE4            VARCHAR2(20),           
      TH_GLOBAL_ATTRIBUTE_DATE5            VARCHAR2(20),           
      TH_GLOBAL_ATTRIBUTE_CATEGORY         VARCHAR2(30),   
      AI_GLOBAL_ATTRIBUTE1                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE2                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE3                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE4                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE5                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE6                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE7                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE8                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE9                 VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE10                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE11                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE12                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE13                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE14                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE15                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE16                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE17                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE18                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE19                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE20                VARCHAR2(150),  
      AI_GLOBAL_ATTRIBUTE_NUMBER1          NUMBER,         
      AI_GLOBAL_ATTRIBUTE_NUMBER2          NUMBER,         
      AI_GLOBAL_ATTRIBUTE_NUMBER3          NUMBER,         
      AI_GLOBAL_ATTRIBUTE_NUMBER4          NUMBER,         
      AI_GLOBAL_ATTRIBUTE_NUMBER5          NUMBER,         
      AI_GLOBAL_ATTRIBUTE_DATE1            VARCHAR2(20),           
      AI_GLOBAL_ATTRIBUTE_DATE2            VARCHAR2(20),           
      AI_GLOBAL_ATTRIBUTE_DATE3            VARCHAR2(20),           
      AI_GLOBAL_ATTRIBUTE_DATE4            VARCHAR2(20),           
      AI_GLOBAL_ATTRIBUTE_DATE5            VARCHAR2(20),           
      AI_GLOBAL_ATTRIBUTE_CATEGORY         VARCHAR2(30),   
      VENDOR_NAME                          VARCHAR2(360),  
      VENDOR_NUMBER                        VARCHAR2(30),   
      PO_NUMBER                            VARCHAR2(30),   
      INVOICE_NUMBER                       VARCHAR2(50),   
      INVOICE_VOUCHER_NUMBER               VARCHAR2(50),   
      INVOICE_DATE                         VARCHAR2(20),           
      PAYABLES_UNITS                       NUMBER,         
      INVOICE_LINE_NUMBER                  NUMBER,         
      INVOICE_LINE_TYPE                    VARCHAR2(30),   
      INVOICE_LINE_DESCRIPTION             VARCHAR2(240),  
      INVOICE_PAYMENT_NUMBER               NUMBER(18),     
      PROJECT_NUMBER                       VARCHAR2(25),   
      PROJECT_TASK_NUMBER                  VARCHAR2(100),  
      FULLY_RESERVE_ON_ADD_FLAG            VARCHAR2(1),    
      DEPRN_ADJUSTMENT_FACTOR              NUMBER,         
      REVALUED_COST                        NUMBER,         
      BACKLOG_DEPRN_RESERVE                NUMBER,         
      YTD_BACKLOG_DEPRN                    NUMBER,         
      REVAL_AMORT_BALANCE                  NUMBER,         
      YTD_REVAL_AMORTIZATION               NUMBER         
  )
     ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_FA_MASS_ADDITIONS_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_FA_MASS_ADDITIONS_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;
  
  
EXEC DropTable ('XXMX_FA_MASS_ADDITIONS_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_FA_MASS_ADDITIONS_EXT" 
   (	
      FILE_SET_ID                   VARCHAR2(30 BYTE), 
      INTERFACE_LINE_NUM            NUMBER,        
      UNITS                         NUMBER,        
      EMPLOYEE_EMAIL_ADDRESS        VARCHAR2(240) ,
      LOCATION_SEGMENT1             VARCHAR2(30)  ,
      LOCATION_SEGMENT2             VARCHAR2(30)  ,
      LOCATION_SEGMENT3             VARCHAR2(30) , 
      LOCATION_SEGMENT4             VARCHAR2(30) , 
      LOCATION_SEGMENT5             VARCHAR2(30) , 
      LOCATION_SEGMENT6             VARCHAR2(30) , 
      LOCATION_SEGMENT7             VARCHAR2(30) , 
      DEPRN_EXPENSE_SEGMENT1        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT2        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT3        VARCHAR2(25) ,
      DEPRN_EXPENSE_SEGMENT4        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT5        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT6        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT7        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT8        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT9        VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT10       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT11       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT12       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT13       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT14       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT15       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT16       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT17       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT18       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT19       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT20       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT21       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT22       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT23       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT24       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT25       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT26       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT27       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT28       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT29       VARCHAR2(25) , 
      DEPRN_EXPENSE_SEGMENT30       VARCHAR2(25)  
   )
     ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_FA_MASS_ADDITION_DIST_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_FA_MASS_ADDITION_DIST_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;
  
EXEC DropTable ('XXMX_FA_MASS_RATES_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_FA_MASS_RATES_EXT" 
   (	
      FILE_SET_ID                   VARCHAR2(30 BYTE),
      INTERFACE_LINE_NUM            NUMBER       , 
      CURRENCY_CODE                 VARCHAR2(15) , 
      FIXED_ASSETS_COST             NUMBER       , 
      EXCHANGE_RATE                 NUMBER       
   )
     ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_FA_MASS_RATES_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_FA_MASS_RATES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;
  
  
  
  