--------------------------------------------------------
--  DDL for Index SYS_C0011143
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."SYS_C0011143" ON "XXMX_CORE"."XXMX_PPM_CLOUD_INVOICES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
