--------------------------------------------------------
--  DDL for Index SYS_C0011145
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."SYS_C0011145" ON "XXMX_CORE"."XXMX_PROJ_TASK_BILL_CHARG_TBL" ("S_NO", "INTEGRATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
