--------------------------------------------------------
--  DDL for Table XX_HISTORY_MAX_ASG_NUM
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_HISTORY_MAX_ASG_NUM" 
   (	"PERSON_NUMBER" VARCHAR2(20 BYTE), 
	"MAX_ASG_NUM" VARCHAR2(20 BYTE), 
	"EFF_START_DATE" VARCHAR2(20 BYTE), 
	"LEG_CODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
