--------------------------------------------------------
--  DDL for Table XX_SAL_HIST_ASG_DET
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_SAL_HIST_ASG_DET" 
   (	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"LOCATION" VARCHAR2(60 BYTE), 
	"GRADE" VARCHAR2(240 BYTE), 
	"JOB" VARCHAR2(700 BYTE), 
	"COMPANY" VARCHAR2(240 BYTE), 
	"DEPARTMENT" VARCHAR2(240 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"PERIOD_OF_SERVICE_ID" NUMBER(15,0), 
	"TERMINATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
