--------------------------------------------------------
--  Constraints for Table XXHR_OPERATING_UNITS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXHR_OPERATING_UNITS_STG" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXHR_OPERATING_UNITS_STG" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXHR_OPERATING_UNITS_STG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXHR_OPERATING_UNITS_STG" MODIFY ("DATE_FROM" NOT NULL ENABLE);
