--------------------------------------------------------
--  Constraints for Table XXMX_BUSINESS_UNITS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_BUSINESS_UNITS" MODIFY ("BU_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_BUSINESS_UNITS" ADD CONSTRAINT "XXMX_BUSINESS_UNITS_PK" PRIMARY KEY ("BU_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
