--------------------------------------------------------
--  Constraints for Table XXMX_SEEDED_EXTENSIONS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("APPLICATION_SUITE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("APPLICATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("BUSINESS_ENTITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("SCHEMA_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("EXTENSION_PACKAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("EXTENSION_PROCEDURE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("ORDER_TO_SUB_EXTENSIONS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SEEDED_EXTENSIONS" MODIFY ("EXECUTION_SEQUENCE" NOT NULL ENABLE);
