--------------------------------------------------------
--  Constraints for Table XXMX_GL_BALANCE_SUMMARY_V_BKP26072023
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP26072023" MODIFY ("LEDGER_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP26072023" MODIFY ("PERIOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP26072023" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP26072023" MODIFY ("CODE_COMBINATION_ID" NOT NULL ENABLE);
