--------------------------------------------------------
--  DDL for Index XXMX_CONTACT_POINTS_N1
--------------------------------------------------------

  CREATE INDEX "XXMX_CORE"."XXMX_CONTACT_POINTS_N1" ON "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS" ("OWNER_TABLE_ID", "CONTACT_POINT_TYPE", "PRIMARY_FLAG", "OWNER_TABLE_NAME", "STATUS", "CONTACT_POINT_PURPOSE", "PRIMARY_BY_PURPOSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
