--------------------------------------------------------
--  Constraints for Table XXMX_PA_EXPENDITURES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("EXPENDITURE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("EXPENDITURE_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("EXPENDITURE_ENDING_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("EXPENDITURE_CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("EXPENDITURE_GROUP" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" MODIFY ("ORG_ID" NOT NULL ENABLE);
