--------------------------------------------------------
--  DDL for Table XXMX_HCM_SALARY_ASS_HIST3
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_SALARY_ASS_HIST3" 
   (	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"JOB_NAME" VARCHAR2(700 BYTE), 
	"GRADE_NAME" VARCHAR2(240 BYTE), 
	"LOCATION" VARCHAR2(60 BYTE), 
	"ORG_NAME" VARCHAR2(240 BYTE), 
	"POSITION_CODE" VARCHAR2(1000 BYTE), 
	"LOCATION_CODE" VARCHAR2(150 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(150 BYTE), 
	"BG_NAME" VARCHAR2(150 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"ORIGINAL_DATE_OF_HIRE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
