--------------------------------------------------------
--  DDL for Table XXMX_XFM_TABLE_COLUMNS_MA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" 
   (	"XFM_TABLE_ID" NUMBER, 
	"XFM_TABLE_COLUMN_ID" NUMBER, 
	"XFM_COLUMN_SEQ" NUMBER, 
	"FUSION_TEMPLATE_FIELD_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"DATA_TYPE" VARCHAR2(128 BYTE), 
	"DATA_LENGTH" NUMBER, 
	"MANDATORY" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"INCLUDE_IN_OUTBOUND_FILE" VARCHAR2(1 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"USER_KEY_FLAG" VARCHAR2(1 BYTE), 
	"TRANSFORM_CODE" VARCHAR2(100 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(2000 BYTE), 
	"DEFAULT_OVERRIDES_SOURCE_VAL" VARCHAR2(1 BYTE), 
	"DEFAULT_ON_TRANSFORM_FAIL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" TO "XXMX_READONLY";
