--------------------------------------------------------
--  Constraints for Table XXMX_GL_BALANCE_SUMMARY_V_BKP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP" MODIFY ("LEDGER_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP" MODIFY ("PERIOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_BALANCE_SUMMARY_V_BKP" MODIFY ("CODE_COMBINATION_ID" NOT NULL ENABLE);
