--------------------------------------------------------
--  Constraints for Table XXMX_XFM_TABLE_COLUMNS_MA
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" MODIFY ("XFM_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" MODIFY ("XFM_TABLE_COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" MODIFY ("XFM_COLUMN_SEQ" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_XFM_TABLE_COLUMNS_MA" MODIFY ("DATA_TYPE" NOT NULL ENABLE);
