--------------------------------------------------------
--  Constraints for Table XXMX_PER_PERSONS_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_PERSONS_XFM_UATBKUP" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PERSONS_XFM_UATBKUP" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PERSONS_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
