--------------------------------------------------------
--  DDL for Table XXMX_PPM_CLOUD_CONTRACTS_ROWNUM_UAT_301123
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CLOUD_CONTRACTS_ROWNUM_UAT_301123" 
   (	"CONTRACT_ID" VARCHAR2(30 BYTE), 
	"CONTRACT_NUMBER" NUMBER(38,0), 
	"STS_CODE" VARCHAR2(26 BYTE), 
	"UNDER_MIGRATION_FLAG" VARCHAR2(26 BYTE), 
	"INV_TRX_TYPE_ID" VARCHAR2(26 BYTE), 
	"AUTO_RELEASE_INVOICE" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(100 BYTE), 
	"ROWN" NUMBER, 
	"ERROR_MESSAGE_ACTIVE" VARCHAR2(4000 BYTE), 
	"ERROR_MESSAGE_UPDATE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
