--------------------------------------------------------
--  DDL for Table XXMX_HCM_POSITION_LE_BU_TAB11092023
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_POSITION_LE_BU_TAB11092023" 
   (	"POSITION_CODE" VARCHAR2(250 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"LEG_CODE" VARCHAR2(8 BYTE), 
	"BU" VARCHAR2(24 BYTE), 
	"LEGAL_EMPLOYER" VARCHAR2(1000 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
