--------------------------------------------------------
--  DDL for Table XXMX_CANDIDATE_LOAD
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CANDIDATE_LOAD" 
   (	"COUNTRY" VARCHAR2(2000 BYTE), 
	"COUNTRY_CODE" NUMBER(10,0), 
	"AREA_CODE" NUMBER(10,0), 
	"PHONE_NUMBER" NUMBER(20,0), 
	"TERRITORY_CODE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
