--------------------------------------------------------
--  Constraints for Table XXMX_PER_RELIGION_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_STG_24OCT23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_STG_24OCT23" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_STG_24OCT23" MODIFY ("RELIGION" NOT NULL ENABLE);
