--------------------------------------------------------
--  Constraints for Table XXMX_SOURCE_OPERATING_UNITS_BKP23012024
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_SOURCE_OPERATING_UNITS_BKP23012024" MODIFY ("SOURCE_OPERATING_UNIT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SOURCE_OPERATING_UNITS_BKP23012024" MODIFY ("MIGRATION_ENABLED_FLAG" NOT NULL ENABLE);
