--------------------------------------------------------
--  Constraints for Table XXMX_PA_DRAFT_REVENUE_ITEMS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("DRAFT_REVENUE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("LINE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" MODIFY ("REVENUE_SOURCE" NOT NULL ENABLE);
