--------------------------------------------------------
--  DDL for Table XXMX_CUSTOMER_EXCLUSIONS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CUSTOMER_EXCLUSIONS" 
   (	"CUST_ACCOUNT_ID" NUMBER(15,0), 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE), 
	"CUST_ACCT_SITE_ID" NUMBER(15,0), 
	"PARTY_ID" NUMBER(15,0), 
	"PARTY_SITE_ID" NUMBER(15,0), 
	"LOCATION_ID" NUMBER(15,0), 
	"ORG_ID" NUMBER(15,0), 
	"PARTY_SITE_NUM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_CUSTOMER_EXCLUSIONS" TO "XXMX_READONLY";
