--------------------------------------------------------
--  DDL for Table XXMX_EBS_PA_TASKS_DIFFS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_EBS_PA_TASKS_DIFFS" 
   (	"BU_NAME" VARCHAR2(1000 BYTE), 
	"PROJECT_TEMPLATE_NUMBER" VARCHAR2(1000 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(1000 BYTE), 
	"PROJECT_TASK_NUMBER" VARCHAR2(1000 BYTE), 
	"PROJECT_CHARGEABLE_FLAG" VARCHAR2(1 BYTE), 
	"PROJECT_BILLABLE_FLAG" VARCHAR2(1 BYTE), 
	"TEMPLATE_TASK_NUMBER" VARCHAR2(1000 BYTE), 
	"CLOUD_MAPPED_TASK_NUMBER" VARCHAR2(1000 BYTE), 
	"TEMPLATE_CHARGEABLE_FLAG" VARCHAR2(1 BYTE), 
	"TEMPLATE_BILLABLE_FLAG" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1000 BYTE), 
	"STATUS_DESC" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
