--------------------------------------------------------
--  DDL for Table XXMX_PROJ_TASK_BILL_CHARG_TBL
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PROJ_TASK_BILL_CHARG_TBL" 
   (	"S_NO" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(2000 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(50 BYTE), 
	"TASK_ID" NUMBER, 
	"TASK_NAME" VARCHAR2(200 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"BILL_FLAG" VARCHAR2(1 BYTE), 
	"CHARGE_FLAG" VARCHAR2(1 BYTE), 
	"INTEGRATION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
