--------------------------------------------------------
--  DDL for Table XXMX_PAY_ELE_VALS_TAB
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" 
   (	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"ELEMENT_NAME" VARCHAR2(80 BYTE), 
	"IV_NAME" VARCHAR2(80 BYTE), 
	"DISPLAY_SEQUENCE" NUMBER(5,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"SCREEN_ENTRY_VALUE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
