--------------------------------------------------------
--  DDL for Table XXMX_FIN_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FIN_ERROR_LOG" 
   (	"ERROR_SEQ" NUMBER, 
	"LOG_ROWID" VARCHAR2(200 BYTE), 
	"ERROR_CODE" NUMBER, 
	"ERROR_MESG" VARCHAR2(1200 BYTE), 
	"LOG_DATE" DATE, 
	"LOG_USER" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_FIN_ERROR_LOG" TO "XXMX_READONLY";
