--------------------------------------------------------
--  Constraints for Table XXMX_PER_ADDRESS_F_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ADDRESS_F_STG_24OCT23" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ADDRESS_F_STG_24OCT23" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ADDRESS_F_STG_24OCT23" MODIFY ("ADDRESS_TYPE" NOT NULL ENABLE);
