--------------------------------------------------------
--  Constraints for Table XXMX_LICENSE_FEE_APINV
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_LICENSE_FEE_APINV" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_LICENSE_FEE_APINV" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_LICENSE_FEE_APINV" MODIFY ("INVOICE_CURRENCY_CODE" NOT NULL ENABLE);
