--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_PRJ_TASK_IDS_UAT_0609230350
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_PRJ_TASK_IDS_UAT_0609230350" 
   (	"PROJECT_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"SEGMENT1" VARCHAR2(100 BYTE), 
	"ELEMENT_NUMBER" VARCHAR2(100 BYTE), 
	"PROJECT_ID" NUMBER, 
	"PROJECT_ELEMENT_ID" NUMBER, 
	"STATUS" VARCHAR2(100 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"PROJECT_SEQ_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
