--------------------------------------------------------
--  Constraints for Table XXMX_PER_RELIGION_XFM_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_24JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_24JUL23" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_24JUL23" MODIFY ("RELIGION" NOT NULL ENABLE);
