--------------------------------------------------------
--  Constraints for Table XXMX_FUSION_LOCKBOX_DETAILS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" MODIFY ("BU_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" MODIFY ("ORG_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" MODIFY ("RECEIPT_METHOD" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" MODIFY ("BANK_ORIGINATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" MODIFY ("LOCKBOX_NUMBER" NOT NULL ENABLE);
