--------------------------------------------------------
--  DDL for Table XXMX_PA_DRAFT_REVENUES_ALL
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" 
   (	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"PROJECT_ID" NUMBER(15,0), 
	"DRAFT_REVENUE_NUM" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"AGREEMENT_ID" NUMBER(15,0), 
	"TRANSFER_STATUS_CODE" VARCHAR2(1 BYTE), 
	"GENERATION_ERROR_FLAG" VARCHAR2(1 BYTE), 
	"PA_DATE" DATE, 
	"REQUEST_ID" NUMBER(15,0), 
	"PROGRAM_APPLICATION_ID" NUMBER(15,0), 
	"PROGRAM_ID" NUMBER(15,0), 
	"RESOURCE_ACCUMULATED_FLAG" VARCHAR2(1 BYTE), 
	"PROGRAM_UPDATE_DATE" DATE, 
	"CUSTOMER_BILL_SPLIT" NUMBER(7,4), 
	"ACCRUE_THROUGH_DATE" DATE, 
	"RELEASED_DATE" DATE, 
	"TRANSFERRED_DATE" DATE, 
	"TRANSFER_REJECTION_REASON" VARCHAR2(250 BYTE), 
	"UNBILLED_RECEIVABLE_DR" NUMBER(22,5), 
	"UNEARNED_REVENUE_CR" NUMBER(22,5), 
	"UNBILLED_CODE_COMBINATION_ID" NUMBER(15,0), 
	"UNEARNED_CODE_COMBINATION_ID" NUMBER(15,0), 
	"UNBILLED_BATCH_NAME" VARCHAR2(30 BYTE), 
	"UNEARNED_BATCH_NAME" VARCHAR2(30 BYTE), 
	"GL_DATE" DATE, 
	"ACCUMULATED_FLAG" VARCHAR2(1 BYTE), 
	"DRAFT_REVENUE_NUM_CREDITED" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ORG_ID" NUMBER(15,0), 
	"GL_PERIOD_NAME" VARCHAR2(15 BYTE), 
	"PA_PERIOD_NAME" VARCHAR2(15 BYTE), 
	"ADJUSTING_REVENUE_FLAG" VARCHAR2(1 BYTE), 
	"UBR_SUMMARY_ID" NUMBER(15,0), 
	"UER_SUMMARY_ID" NUMBER(15,0), 
	"UBR_UER_PROCESS_FLAG" VARCHAR2(1 BYTE), 
	"PJI_SUMMARIZED_FLAG" VARCHAR2(1 BYTE), 
	"REALIZED_GAINS_AMOUNT" NUMBER, 
	"REALIZED_LOSSES_AMOUNT" NUMBER, 
	"REALIZED_GAINS_CCID" NUMBER(15,0), 
	"REALIZED_LOSSES_CCID" NUMBER(15,0), 
	"REALIZED_GAINS_BATCH_NAME" VARCHAR2(30 BYTE), 
	"REALIZED_LOSSES_BATCH_NAME" VARCHAR2(30 BYTE), 
	"EVENT_ID" NUMBER(15,0), 
	"REVTRANS_UBR_DR" NUMBER, 
	"REVTRANS_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"REVTRANS_UER_CR" NUMBER, 
	"LEGAL_ENTITY_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
