--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SUP_F_STG_14NOV23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_STG_14NOV23" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_STG_14NOV23" MODIFY ("MANAGER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_STG_14NOV23" MODIFY ("MANAGER_ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_STG_14NOV23" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_STG_14NOV23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
