--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_XFM_2908
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFM_2908" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFM_2908" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFM_2908" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFM_2908" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
