--------------------------------------------------------
--  DDL for Table XXMX_HCM_WORKERS_LOADED
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_WORKERS_LOADED" 
   (	"PERSON_NUMBER" VARCHAR2(200 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(200 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(200 BYTE), 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_HCM_WORKERS_LOADED" TO "XXMX_READONLY";
