--------------------------------------------------------
--  Constraints for Table XXMX_PA_CUST_EVENT_RDL_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("EVENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("LINE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("DRAFT_REVENUE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_EVENT_RDL_ALL" MODIFY ("DRAFT_REVENUE_ITEM_LINE_NUM" NOT NULL ENABLE);
