--------------------------------------------------------
--  Constraints for Table XXMX_HR_LOCATION
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HR_LOCATION" MODIFY ("LOCATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HR_LOCATION" MODIFY ("INTERNAL_LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HR_LOCATION" ADD CONSTRAINT "XXMX_HR_LOCATION_PK" PRIMARY KEY ("LOCATION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
