--------------------------------------------------------
--  DDL for View XXMX_HR_HCM_PERSON_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_HR_HCM_PERSON_V" ("MIGRATION_SET_ID", "PERSON_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "PPS_PERSON_NUMBER", "PPS_START_DATE", "DOB", "PNS_PERSON_NAME_ID", "PNS_LEGISLATION_CODE", "PNS_NAME_TYPE", "PNS_FIRST_NAME", "PNS_MIDDLE_NAMES", "PNS_LAST_NAME", "PNS_HONORS", "PNS_KNOWN_AS", "PNS_PRE_NAME_ADJUNCT", "PNS_MILITARY_RANK", "PNS_PREVIOUS_LAST_NAME", "PNS_SUFFIX", "PNS_TITLE", "PAF_ADDRESS_TYPE", "PAF_ADDRESS_LINE_1", "PAF_ADDRESS_LINE_2", "PAF_ADDRESS_LINE_3", "PAF_ADDRESS_LINE_4", "PAF_TOWN_OR_CITY", "PAF_REGION_1", "PAF_REGION_2", "PAF_COUNTRY_CODE", "PAF_POSTAL_CODE", "PAF_LONG_POSTAL_CODE", "PAF_PRIMARY_FLAG", "PAF_ADDRESS_STYLE", "PAF_ADDRESS_ID", "PEMAIL_EMAIL_ADDRESS_ID", "PEMAIL_DATE_FROM", "PEMAIL_DATE_TO", "PEMAIL_EMAIL_TYPE", "PEMAIL_EMAIL_ADDRESS", "PEMAIL_PRIMARY_FLAG", "PHONE_DATE_FROM", "PHONE_DATE_TO", "PHONE_PHONE_TYPE", "PHONE_AREA_CODE", "PHONE_PHONE_NUMBER", "PHONE_LEGISLATION_CODE", "PHONE_PRIMARY_FLAG", "PHONE_PHONE_ID", "PHONE_VALIDITY", "PE_LEGISLATION_CODE", "PE_ETHNICITY", "PE_PRIMARY_FLAG", "PE_ETHNICITY_ID", "NID_NATIONAL_IDENTIFIER_ID", "NID_LEGISLATION_CODE", "NID_NATIONAL_IDENTIFIER_TYPE", "NID_NATIONAL_IDENTIFIER_NUMBER", "NID_PRIMARY_FLAG", "NID_ISSUE_DATE", "NID_EXPIRATION_DATE", "PASS_LEGISLATIONCODE", "PASS_PASSPORTNUMBER", "PASS_ISSUE_DATE", "PASS_EXPIRATION_DATE", "PASS_ISSUING_COUNTRY", "CIT_CITIZENSHIP_ID", "CIT_DATE_FROM", "CIT_DATE_TO", "CIT_LEGISLATION_CODE", "CIT_CITIZENSHIP_STATUS", "PLD_PERSON_LEGISLATIVE_ID", "PLD_LEGISLATION_CODE", "PLD_HIGHEST_EDUCATION_LEVEL", "PLD_SEX", "PLD_MARITAL_STATUS", "PLD_MARITAL_STATUS_DATE", "BG_NAME", "BG_ID", "RELIGION", "REL_PRIMARY_FLAG", "PPS_ATTRIBUTE1", "PPS_ATTRIBUTE2", "PPS_ATTRIBUTE3", "PPS_ATTRIBUTE4", "PPS_ATTRIBUTE5", "PPS_ATTRIBUTE6", "PPS_ATTRIBUTE7", "PPS_ATTRIBUTE8", "PPS_ATTRIBUTE9", "PPS_ATTRIBUTE10", "PPS_ATTRIBUTE11", "PPS_ATTRIBUTE12", "PPS_ATTRIBUTE13", "PPS_ATTRIBUTE14", "PPS_ATTRIBUTE15", "PPS_ATTRIBUTE_NUMBER1", "PPS_ATTRIBUTE_NUMBER2", "PPS_ATTRIBUTE_NUMBER3", "PPS_ATTRIBUTE_NUMBER4", "PPS_ATTRIBUTE_NUMBER5", "PPS_ATTRIBUTE_NUMBER6", "PPS_ATTRIBUTE_NUMBER7", "PPS_ATTRIBUTE_NUMBER8", "PPS_ATTRIBUTE_NUMBER9", "PPS_ATTRIBUTE_NUMBER10", "PPS_ATTRIBUTE_NUMBER11", "PPS_ATTRIBUTE_NUMBER12", "PPS_ATTRIBUTE_NUMBER13", "PPS_ATTRIBUTE_NUMBER14", "PPS_ATTRIBUTE_NUMBER15", "PPS_ATTRIBUTE_DATE1", "PPS_ATTRIBUTE_DATE2", "PPS_ATTRIBUTE_DATE3", "PPS_ATTRIBUTE_DATE4", "PPS_ATTRIBUTE_DATE5", "PPS_ATTRIBUTE_DATE6", "PPS_ATTRIBUTE_DATE7", "PPS_ATTRIBUTE_DATE8", "PPS_ATTRIBUTE_DATE9", "PPS_ATTRIBUTE_DATE10", "PPS_ATTRIBUTE_DATE11", "PPS_ATTRIBUTE_DATE12", "PPS_ATTRIBUTE_DATE13", "PPS_ATTRIBUTE_DATE14", "PPS_ATTRIBUTE_DATE15", "PP_ATTRIBUTE1", "PP_ATTRIBUTE2", "PP_ATTRIBUTE3", "PP_ATTRIBUTE4", "PP_ATTRIBUTE5", "PP_ATTRIBUTE6", "PP_ATTRIBUTE7", "PP_ATTRIBUTE8", "PP_ATTRIBUTE9", "PP_ATTRIBUTE10", "PP_ATTRIBUTE11", "PP_ATTRIBUTE12", "PP_ATTRIBUTE13", "PP_ATTRIBUTE14", "PP_ATTRIBUTE15", "PP_ATTRIBUTE_NUMBER1", "PP_ATTRIBUTE_NUMBER2", "PP_ATTRIBUTE_NUMBER3", "PP_ATTRIBUTE_NUMBER4", "PP_ATTRIBUTE_NUMBER5", "PP_ATTRIBUTE_NUMBER6", "PP_ATTRIBUTE_NUMBER7", "PP_ATTRIBUTE_NUMBER8", "PP_ATTRIBUTE_NUMBER9", "PP_ATTRIBUTE_NUMBER10", "PP_ATTRIBUTE_NUMBER11", "PP_ATTRIBUTE_NUMBER12", "PP_ATTRIBUTE_NUMBER13", "PP_ATTRIBUTE_NUMBER14", "PP_ATTRIBUTE_NUMBER15", "PP_ATTRIBUTE_DATE1", "PP_ATTRIBUTE_DATE2", "PP_ATTRIBUTE_DATE3", "PP_ATTRIBUTE_DATE4", "PP_ATTRIBUTE_DATE5", "PP_ATTRIBUTE_DATE6", "PP_ATTRIBUTE_DATE7", "PP_ATTRIBUTE_DATE8", "PP_ATTRIBUTE_DATE9", "PP_ATTRIBUTE_DATE10", "PP_ATTRIBUTE_DATE11", "PP_ATTRIBUTE_DATE12", "PP_ATTRIBUTE_DATE13", "PP_ATTRIBUTE_DATE14", "PP_ATTRIBUTE_DATE15", "PNS_NAM_INFORMATION1", "PNS_NAM_INFORMATION2", "PNS_NAM_INFORMATION3", "PNS_NAM_INFORMATION4", "PNS_NAM_INFORMATION5", "PNS_NAM_INFORMATION6", "PNS_NAM_INFORMATION7", "PNS_NAM_INFORMATION8", "PNS_NAM_INFORMATION9", "PNS_NAM_INFORMATION10", "PNS_NAM_INFORMATION11", "PNS_NAM_INFORMATION12", "PNS_NAM_INFORMATION13", "PNS_NAM_INFORMATION14", "PNS_NAM_INFORMATION15", "PNS_ATTRIBUTE1", "PNS_ATTRIBUTE2", "PNS_ATTRIBUTE3", "PNS_ATTRIBUTE4", "PNS_ATTRIBUTE5", "PNS_ATTRIBUTE6", "PNS_ATTRIBUTE7", "PNS_ATTRIBUTE8", "PNS_ATTRIBUTE9", "PNS_ATTRIBUTE10", "PNS_ATTRIBUTE11", "PNS_ATTRIBUTE12", "PNS_ATTRIBUTE13", "PNS_ATTRIBUTE14", "PNS_ATTRIBUTE15", "PNS_NAM_INFORMATION_DATE1", "PNS_NAM_INFORMATION_DATE2", "PNS_NAM_INFORMATION_DATE3", "PNS_NAM_INFORMATION_DATE4", "PNS_NAM_INFORMATION_DATE5", "PNS_NAM_INFORMATION_DATE6", "PNS_NAM_INFORMATION_DATE7", "PNS_NAM_INFORMATION_DATE8", "PNS_NAM_INFORMATION_DATE9", "PNS_NAM_INFORMATION_DATE10", "PNS_NAM_INFORMATION_DATE11", "PNS_NAM_INFORMATION_DATE12", "PNS_NAM_INFORMATION_DATE13", "PNS_NAM_INFORMATION_DATE14", "PNS_NAM_INFORMATION_DATE15", "PNS_ATTRIBUTE_NUMBER1", "PNS_ATTRIBUTE_NUMBER2", "PNS_ATTRIBUTE_NUMBER3", "PNS_ATTRIBUTE_NUMBER4", "PNS_ATTRIBUTE_NUMBER5", "PNS_ATTRIBUTE_NUMBER6", "PNS_ATTRIBUTE_NUMBER7", "PNS_ATTRIBUTE_NUMBER8", "PNS_ATTRIBUTE_NUMBER9", "PNS_ATTRIBUTE_NUMBER10", "PNS_ATTRIBUTE_NUMBER11", "PNS_ATTRIBUTE_NUMBER12", "PNS_ATTRIBUTE_NUMBER13", "PNS_ATTRIBUTE_NUMBER14", "PNS_ATTRIBUTE_NUMBER15", "PNS_ATTRIBUTE_DATE1", "PNS_ATTRIBUTE_DATE2", "PNS_ATTRIBUTE_DATE3", "PNS_ATTRIBUTE_DATE4", "PNS_ATTRIBUTE_DATE5", "PNS_ATTRIBUTE_DATE6", "PNS_ATTRIBUTE_DATE7", "PNS_ATTRIBUTE_DATE8", "PNS_ATTRIBUTE_DATE9", "PNS_ATTRIBUTE_DATE10", "PNS_ATTRIBUTE_DATE11", "PNS_ATTRIBUTE_DATE12", "PNS_ATTRIBUTE_DATE13", "PNS_ATTRIBUTE_DATE14", "PNS_ATTRIBUTE_DATE15", "PAF_ADDL_ADDRESS_ATTRIBUTE1", "PAF_ADDL_ADDRESS_ATTRIBUTE2", "PAF_ADDL_ADDRESS_ATTRIBUTE3", "PAF_ADDL_ADDRESS_ATTRIBUTE4", "PAF_ADDL_ADDRESS_ATTRIBUTE5", "PAF_ADDR_ATTRIBUTE1", "PAF_ADDR_ATTRIBUTE2", "PAF_ADDR_ATTRIBUTE3", "PAF_ADDR_ATTRIBUTE4", "PAF_ADDR_ATTRIBUTE5", "PAF_ADDR_ATTRIBUTE6", "PAF_ADDR_ATTRIBUTE7", "PAF_ADDR_ATTRIBUTE8", "PAF_ADDR_ATTRIBUTE9", "PAF_ADDR_ATTRIBUTE10", "PAF_ADDR_ATTRIBUTE11", "PAF_ADDR_ATTRIBUTE12", "PAF_ADDR_ATTRIBUTE13", "PAF_ADDR_ATTRIBUTE14", "PAF_ADDR_ATTRIBUTE15", "PAF_ADDR_ATTRIBUTE_NUMBER1", "PAF_ADDR_ATTRIBUTE_NUMBER2", "PAF_ADDR_ATTRIBUTE_NUMBER3", "PAF_ADDR_ATTRIBUTE_NUMBER4", "PAF_ADDR_ATTRIBUTE_NUMBER5", "PAF_ADDR_ATTRIBUTE_NUMBER6", "PAF_ADDR_ATTRIBUTE_NUMBER7", "PAF_ADDR_ATTRIBUTE_NUMBER8", "PAF_ADDR_ATTRIBUTE_NUMBER9", "PAF_ADDR_ATTRIBUTE_NUMBER10", "PAF_ADDR_ATTRIBUTE_NUMBER11", "PAF_ADDR_ATTRIBUTE_NUMBER12", "PAF_ADDR_ATTRIBUTE_NUMBER13", "PAF_ADDR_ATTRIBUTE_NUMBER14", "PAF_ADDR_ATTRIBUTE_NUMBER15", "PAF_ADDR_ATTRIBUTE_DATE1", "PAF_ADDR_ATTRIBUTE_DATE2", "PAF_ADDR_ATTRIBUTE_DATE3", "PAF_ADDR_ATTRIBUTE_DATE4", "PAF_ADDR_ATTRIBUTE_DATE5", "PAF_ADDR_ATTRIBUTE_DATE6", "PAF_ADDR_ATTRIBUTE_DATE7", "PAF_ADDR_ATTRIBUTE_DATE8", "PAF_ADDR_ATTRIBUTE_DATE9", "PAF_ADDR_ATTRIBUTE_DATE10", "PAF_ADDR_ATTRIBUTE_DATE11", "PAF_ADDR_ATTRIBUTE_DATE12", "PAF_ADDR_ATTRIBUTE_DATE13", "PAF_ADDR_ATTRIBUTE_DATE14", "PAF_ADDR_ATTRIBUTE_DATE15", "PEMAIL_ATTRIBUTE1", "PEMAIL_ATTRIBUTE2", "PEMAIL_ATTRIBUTE3", "PEMAIL_ATTRIBUTE4", "PEMAIL_ATTRIBUTE5", "PEMAIL_ATTRIBUTE6", "PEMAIL_ATTRIBUTE7", "PEMAIL_ATTRIBUTE8", "PEMAIL_ATTRIBUTE9", "PEMAIL_ATTRIBUTE10", "PEMAIL_ATTRIBUTE11", "PEMAIL_ATTRIBUTE12", "PEMAIL_ATTRIBUTE13", "PEMAIL_ATTRIBUTE14", "PEMAIL_ATTRIBUTE15", "PEMAIL_ATTRIBUTE_NUMBER1", "PEMAIL_ATTRIBUTE_NUMBER2", "PEMAIL_ATTRIBUTE_NUMBER3", "PEMAIL_ATTRIBUTE_NUMBER4", "PEMAIL_ATTRIBUTE_NUMBER5", "PEMAIL_ATTRIBUTE_NUMBER6", "PEMAIL_ATTRIBUTE_NUMBER7", "PEMAIL_ATTRIBUTE_NUMBER8", "PEMAIL_ATTRIBUTE_NUMBER9", "PEMAIL_ATTRIBUTE_NUMBER10", "PEMAIL_ATTRIBUTE_NUMBER11", "PEMAIL_ATTRIBUTE_NUMBER12", "PEMAIL_ATTRIBUTE_NUMBER13", "PEMAIL_ATTRIBUTE_NUMBER14", "PEMAIL_ATTRIBUTE_NUMBER15", "PEMAIL_ATTRIBUTE_DATE1", "PEMAIL_ATTRIBUTE_DATE2", "PEMAIL_ATTRIBUTE_DATE3", "PEMAIL_ATTRIBUTE_DATE4", "PEMAIL_ATTRIBUTE_DATE5", "PEMAIL_ATTRIBUTE_DATE6", "PEMAIL_ATTRIBUTE_DATE7", "PEMAIL_ATTRIBUTE_DATE8", "PEMAIL_ATTRIBUTE_DATE9", "PEMAIL_ATTRIBUTE_DATE10", "PEMAIL_ATTRIBUTE_DATE11", "PEMAIL_ATTRIBUTE_DATE12", "PEMAIL_ATTRIBUTE_DATE13", "PEMAIL_ATTRIBUTE_DATE14", "PEMAIL_ATTRIBUTE_DATE15", "PHONE_ATTRIBUTE1", "PHONE_ATTRIBUTE2", "PHONE_ATTRIBUTE3", "PHONE_ATTRIBUTE4", "PHONE_ATTRIBUTE5", "PHONE_ATTRIBUTE6", "PHONE_ATTRIBUTE7", "PHONE_ATTRIBUTE8", "PHONE_ATTRIBUTE9", "PHONE_ATTRIBUTE10", "PHONE_ATTRIBUTE11", "PHONE_ATTRIBUTE12", "PHONE_ATTRIBUTE13", "PHONE_ATTRIBUTE14", "PHONE_ATTRIBUTE15", "PHONE_ATTRIBUTE_NUMBER1", "PHONE_ATTRIBUTE_NUMBER2", "PHONE_ATTRIBUTE_NUMBER3", "PHONE_ATTRIBUTE_NUMBER4", "PHONE_ATTRIBUTE_NUMBER5", "PHONE_ATTRIBUTE_NUMBER6", "PHONE_ATTRIBUTE_NUMBER7", "PHONE_ATTRIBUTE_NUMBER8", "PHONE_ATTRIBUTE_NUMBER9", "PHONE_ATTRIBUTE_NUMBER10", "PHONE_ATTRIBUTE_NUMBER11", "PHONE_ATTRIBUTE_NUMBER12", "PHONE_ATTRIBUTE_NUMBER13", "PHONE_ATTRIBUTE_NUMBER14", "PHONE_ATTRIBUTE_NUMBER15", "PHONE_ATTRIBUTE_DATE1", "PHONE_ATTRIBUTE_DATE2", "PHONE_ATTRIBUTE_DATE3", "PHONE_ATTRIBUTE_DATE4", "PHONE_ATTRIBUTE_DATE5", "PHONE_ATTRIBUTE_DATE6", "PHONE_ATTRIBUTE_DATE7", "PHONE_ATTRIBUTE_DATE8", "PHONE_ATTRIBUTE_DATE9", "PHONE_ATTRIBUTE_DATE10", "PHONE_ATTRIBUTE_DATE11", "PHONE_ATTRIBUTE_DATE12", "PHONE_ATTRIBUTE_DATE13", "PHONE_ATTRIBUTE_DATE14", "PHONE_ATTRIBUTE_DATE15", "PE_ATTRIBUTE1", "PE_ATTRIBUTE2", "PE_ATTRIBUTE3", "PE_ATTRIBUTE4", "PE_ATTRIBUTE5", "PE_ATTRIBUTE6", "PE_ATTRIBUTE7", "PE_ATTRIBUTE8", "PE_ATTRIBUTE9", "PE_ATTRIBUTE10", "PE_ATTRIBUTE11", "PE_ATTRIBUTE12", "PE_ATTRIBUTE13", "PE_ATTRIBUTE14", "PE_ATTRIBUTE15", "PE_ATTRIBUTE_NUMBER1", "PE_ATTRIBUTE_NUMBER2", "PE_ATTRIBUTE_NUMBER3", "PE_ATTRIBUTE_NUMBER4", "PE_ATTRIBUTE_NUMBER5", "PE_ATTRIBUTE_NUMBER6", "PE_ATTRIBUTE_NUMBER7", "PE_ATTRIBUTE_NUMBER8", "PE_ATTRIBUTE_NUMBER9", "PE_ATTRIBUTE_NUMBER10", "PE_ATTRIBUTE_NUMBER11", "PE_ATTRIBUTE_NUMBER12", "PE_ATTRIBUTE_NUMBER13", "PE_ATTRIBUTE_NUMBER14", "PE_ATTRIBUTE_NUMBER15", "PE_ATTRIBUTE_DATE1", "PE_ATTRIBUTE_DATE2", "PE_ATTRIBUTE_DATE3", "PE_ATTRIBUTE_DATE4", "PE_ATTRIBUTE_DATE5", "PE_ATTRIBUTE_DATE6", "PE_ATTRIBUTE_DATE7", "PE_ATTRIBUTE_DATE8", "PE_ATTRIBUTE_DATE9", "PE_ATTRIBUTE_DATE10", "PE_ATTRIBUTE_DATE11", "PE_ATTRIBUTE_DATE12", "PE_ATTRIBUTE_DATE13", "PE_ATTRIBUTE_DATE14", "PE_ATTRIBUTE_DATE15", "NID_ATTRIBUTE1", "NID_ATTRIBUTE2", "NID_ATTRIBUTE3", "NID_ATTRIBUTE4", "NID_ATTRIBUTE5", "NID_ATTRIBUTE6", "NID_ATTRIBUTE7", "NID_ATTRIBUTE8", "NID_ATTRIBUTE9", "NID_ATTRIBUTE10", "NID_ATTRIBUTE11", "NID_ATTRIBUTE12", "NID_ATTRIBUTE13", "NID_ATTRIBUTE14", "NID_ATTRIBUTE15", "NID_ATTRIBUTE_NUMBER1", "NID_ATTRIBUTE_NUMBER2", "NID_ATTRIBUTE_NUMBER3", "NID_ATTRIBUTE_NUMBER4", "NID_ATTRIBUTE_NUMBER5", "NID_ATTRIBUTE_NUMBER6", "NID_ATTRIBUTE_NUMBER7", "NID_ATTRIBUTE_NUMBER8", "NID_ATTRIBUTE_NUMBER9", "NID_ATTRIBUTE_NUMBER10", "NID_ATTRIBUTE_NUMBER11", "NID_ATTRIBUTE_NUMBER12", "NID_ATTRIBUTE_NUMBER13", "NID_ATTRIBUTE_NUMBER14", "NID_ATTRIBUTE_NUMBER15", "NID_ATTRIBUTE_DATE1", "NID_ATTRIBUTE_DATE2", "NID_ATTRIBUTE_DATE3", "NID_ATTRIBUTE_DATE4", "NID_ATTRIBUTE_DATE5", "NID_ATTRIBUTE_DATE6", "NID_ATTRIBUTE_DATE7", "NID_ATTRIBUTE_DATE8", "NID_ATTRIBUTE_DATE9", "NID_ATTRIBUTE_DATE10", "NID_ATTRIBUTE_DATE11", "NID_ATTRIBUTE_DATE12", "NID_ATTRIBUTE_DATE13", "NID_ATTRIBUTE_DATE14", "NID_ATTRIBUTE_DATE15", "PASS_ATTRIBUTE1", "PASS_ATTRIBUTE2", "PASS_ATTRIBUTE3", "PASS_ATTRIBUTE4", "PASS_ATTRIBUTE5", "PASS_ATTRIBUTE6", "PASS_ATTRIBUTE7", "PASS_ATTRIBUTE8", "PASS_ATTRIBUTE9", "PASS_ATTRIBUTE10", "PASS_ATTRIBUTE11", "PASS_ATTRIBUTE12", "PASS_ATTRIBUTE13", "PASS_ATTRIBUTE14", "PASS_ATTRIBUTE15", "PASS_ATTRIBUTE_NUMBER1", "PASS_ATTRIBUTE_NUMBER2", "PASS_ATTRIBUTE_NUMBER3", "PASS_ATTRIBUTE_NUMBER4", "PASS_ATTRIBUTE_NUMBER5", "PASS_ATTRIBUTE_NUMBER6", "PASS_ATTRIBUTE_NUMBER7", "PASS_ATTRIBUTE_NUMBER8", "PASS_ATTRIBUTE_NUMBER9", "PASS_ATTRIBUTE_NUMBER10", "PASS_ATTRIBUTE_NUMBER11", "PASS_ATTRIBUTE_NUMBER12", "PASS_ATTRIBUTE_NUMBER13", "PASS_ATTRIBUTE_NUMBER14", "PASS_ATTRIBUTE_NUMBER15", "PASS_ATTRIBUTE_DATE1", "PASS_ATTRIBUTE_DATE2", "PASS_ATTRIBUTE_DATE3", "PASS_ATTRIBUTE_DATE4", "PASS_ATTRIBUTE_DATE5", "PASS_ATTRIBUTE_DATE6", "PASS_ATTRIBUTE_DATE7", "PASS_ATTRIBUTE_DATE8", "PASS_ATTRIBUTE_DATE9", "PASS_ATTRIBUTE_DATE10", "PASS_ATTRIBUTE_DATE11", "PASS_ATTRIBUTE_DATE12", "PASS_ATTRIBUTE_DATE13", "PASS_ATTRIBUTE_DATE14", "PASS_ATTRIBUTE_DATE15", "CIT_ATTRIBUTE1", "CIT_ATTRIBUTE2", "CIT_ATTRIBUTE3", "CIT_ATTRIBUTE4", "CIT_ATTRIBUTE5", "CIT_ATTRIBUTE6", "CIT_ATTRIBUTE7", "CIT_ATTRIBUTE8", "CIT_ATTRIBUTE9", "CIT_ATTRIBUTE10", "CIT_ATTRIBUTE11", "CIT_ATTRIBUTE12", "CIT_ATTRIBUTE13", "CIT_ATTRIBUTE14", "CIT_ATTRIBUTE15", "CIT_ATTRIBUTE_NUMBER1", "CIT_ATTRIBUTE_NUMBER2", "CIT_ATTRIBUTE_NUMBER3", "CIT_ATTRIBUTE_NUMBER4", "CIT_ATTRIBUTE_NUMBER5", "CIT_ATTRIBUTE_NUMBER6", "CIT_ATTRIBUTE_NUMBER7", "CIT_ATTRIBUTE_NUMBER8", "CIT_ATTRIBUTE_NUMBER9", "CIT_ATTRIBUTE_NUMBER10", "CIT_ATTRIBUTE_NUMBER11", "CIT_ATTRIBUTE_NUMBER12", "CIT_ATTRIBUTE_NUMBER13", "CIT_ATTRIBUTE_NUMBER14", "CIT_ATTRIBUTE_NUMBER15", "CIT_ATTRIBUTE_DATE1", "CIT_ATTRIBUTE_DATE2", "CIT_ATTRIBUTE_DATE3", "CIT_ATTRIBUTE_DATE4", "CIT_ATTRIBUTE_DATE5", "CIT_ATTRIBUTE_DATE6", "CIT_ATTRIBUTE_DATE7", "CIT_ATTRIBUTE_DATE8", "CIT_ATTRIBUTE_DATE9", "CIT_ATTRIBUTE_DATE10", "CIT_ATTRIBUTE_DATE11", "CIT_ATTRIBUTE_DATE12", "CIT_ATTRIBUTE_DATE13", "CIT_ATTRIBUTE_DATE14", "CIT_ATTRIBUTE_DATE15", "PLD_PER_INFORMATION1", "PLD_PER_INFORMATION2", "PLD_PER_INFORMATION3", "PLD_PER_INFORMATION4", "PLD_PER_INFORMATION5", "PLD_PER_INFORMATION6", "PLD_PER_INFORMATION7", "PLD_PER_INFORMATION8", "PLD_PER_INFORMATION9", "PLD_PER_INFORMATION10", "PLD_PER_INFORMATION11", "PLD_PER_INFORMATION12", "PLD_PER_INFORMATION13", "PLD_PER_INFORMATION14", "PLD_PER_INFORMATION15", "PLD_ATTRIBUTE1", "PLD_ATTRIBUTE2", "PLD_ATTRIBUTE3", "PLD_ATTRIBUTE4", "PLD_ATTRIBUTE5", "PLD_ATTRIBUTE6", "PLD_ATTRIBUTE7", "PLD_ATTRIBUTE8", "PLD_ATTRIBUTE9", "PLD_ATTRIBUTE10", "PLD_ATTRIBUTE11", "PLD_ATTRIBUTE12", "PLD_ATTRIBUTE13", "PLD_ATTRIBUTE14", "PLD_ATTRIBUTE15", "PLD_PER_INFORMATION_NUMBER1", "PLD_PER_INFORMATION_NUMBER2", "PLD_PER_INFORMATION_NUMBER3", "PLD_PER_INFORMATION_NUMBER4", "PLD_PER_INFORMATION_NUMBER5", "PLD_PER_INFORMATION_NUMBER6", "PLD_PER_INFORMATION_NUMBER7", "PLD_PER_INFORMATION_NUMBER8", "PLD_PER_INFORMATION_NUMBER9", "PLD_PER_INFORMATION_NUMBER10", "PLD_PER_INFORMATION_NUMBER11", "PLD_PER_INFORMATION_NUMBER12", "PLD_PER_INFORMATION_NUMBER13", "PLD_PER_INFORMATION_NUMBER14", "PLD_PER_INFORMATION_NUMBER15", "PLD_PER_INFORMATION_DATE1", "PLD_PER_INFORMATION_DATE2", "PLD_PER_INFORMATION_DATE3", "PLD_PER_INFORMATION_DATE4", "PLD_PER_INFORMATION_DATE5", "PLD_PER_INFORMATION_DATE6", "PLD_PER_INFORMATION_DATE7", "PLD_PER_INFORMATION_DATE8", "PLD_PER_INFORMATION_DATE9", "PLD_PER_INFORMATION_DATE10", "PLD_PER_INFORMATION_DATE11", "PLD_PER_INFORMATION_DATE12", "PLD_PER_INFORMATION_DATE13", "PLD_PER_INFORMATION_DATE14", "PLD_PER_INFORMATION_DATE15", "PLD_ATTRIBUTE_NUMBER1", "PLD_ATTRIBUTE_NUMBER2", "PLD_ATTRIBUTE_NUMBER3", "PLD_ATTRIBUTE_NUMBER4", "PLD_ATTRIBUTE_NUMBER5", "PLD_ATTRIBUTE_NUMBER6", "PLD_ATTRIBUTE_NUMBER7", "PLD_ATTRIBUTE_NUMBER8", "PLD_ATTRIBUTE_NUMBER9", "PLD_ATTRIBUTE_NUMBER10", "PLD_ATTRIBUTE_NUMBER11", "PLD_ATTRIBUTE_NUMBER12", "PLD_ATTRIBUTE_NUMBER13", "PLD_ATTRIBUTE_NUMBER14", "PLD_ATTRIBUTE_NUMBER15", "PLD_ATTRIBUTE_DATE1", "PLD_ATTRIBUTE_DATE2", "PLD_ATTRIBUTE_DATE3", "PLD_ATTRIBUTE_DATE4", "PLD_ATTRIBUTE_DATE5", "PLD_ATTRIBUTE_DATE6", "PLD_ATTRIBUTE_DATE7", "PLD_ATTRIBUTE_DATE8", "PLD_ATTRIBUTE_DATE9", "PLD_ATTRIBUTE_DATE10", "PLD_ATTRIBUTE_DATE11", "PLD_ATTRIBUTE_DATE12", "PLD_ATTRIBUTE_DATE13", "PLD_ATTRIBUTE_DATE14", "PLD_ATTRIBUTE_DATE15", "REL_ATTRIBUTE1", "REL_ATTRIBUTE2", "REL_ATTRIBUTE3", "REL_ATTRIBUTE4", "REL_ATTRIBUTE5", "REL_ATTRIBUTE6", "REL_ATTRIBUTE7", "REL_ATTRIBUTE8", "REL_ATTRIBUTE9", "REL_ATTRIBUTE10", "REL_ATTRIBUTE11", "REL_ATTRIBUTE12", "REL_ATTRIBUTE13", "REL_ATTRIBUTE14", "REL_ATTRIBUTE15") AS 
  SELECT  DISTINCT
         pp.migration_set_id                                migration_set_id
        ,pp.person_id                                       person_id
        ,TO_CHAR(pps.effective_start_date,'RRRR/MM/DD')     effective_start_date
        ,TO_CHAR(pps.effective_end_date,'RRRR/MM/DD')       effective_end_date
        ,pps.personnumber                                  pps_person_number
        ,TO_CHAR(PPS.start_date,'RRRR/MM/DD')               pps_start_date
        ,TO_CHAR(trunc(PP.date_of_birth),'RRRR/MM/DD')      dob
        ,pns.person_name_id                                 pns_person_name_id
        ,pns.legislation_code                               pns_legislation_code
        ,pns.name_type                                      pns_name_type
        ,RTRIM(pns.first_name)                              pns_first_name
        ,RTRIM(pns.middle_names)                            pns_middle_names
        ,RTRIM(pns.last_name)                               pns_last_name
        ,pns.honors                                         pns_honors
        ,pns.known_as                                       pns_known_as
        ,pns.pre_name_adjunct                               pns_pre_name_adjunct
        ,pns.military_rank                                  pns_military_rank
        ,RTRIM(pns.previous_last_name)                      pns_previous_last_name
        ,pns.suffix                                         pns_suffix
        ,INITCAP(pns.title)                                 pns_title
        ,NULL                                             paf_address_type
        ,NULL                          paf_address_line_1
        ,NULL                          paf_address_line_2
        ,NULL                          paf_address_line_3
        ,NULL                          paf_address_line_4
        ,NULL                            paf_town_or_city
        ,NULL                                       paf_region_1
        ,NULL                                       paf_region_2
        ,NULL                                   paf_country_code
        ,NULL                                    paf_postal_code
        ,NULL                               paf_long_postal_code
        ,NULL                                   paf_primary_flag
        ,NULL                                  paf_address_style
        ,NULL                                     paf_address_id
        ,pemail.email_address_id                            pemail_email_address_id
        ,TO_CHAR(pemail.date_from,'RRRR/MM/DD')             pemail_date_from
        ,TO_CHAR(pemail.date_to,'RRRR/MM/DD')               pemail_date_to
        ,pemail.email_type                                  pemail_email_type
        ,pemail.email_address                               pemail_email_address
        ,pemail.primary_flag                                pemail_primary_flag
        ,TO_CHAR(phone.date_from,'RRRR/MM/DD')              phone_date_from
        ,TO_CHAR(phone.date_to,'RRRR/MM/DD')                phone_date_to
        ,phone.phone_type                                   phone_phone_type
        ,phone.area_code                                    phone_area_code
        ,phone.phone_number                                 phone_phone_number
        ,phone.legislation_code                             phone_legislation_code
        ,phone.primary_flag                                 phone_primary_flag
        ,phone.phone_id                                     phone_phone_id
        ,phone.validity                                     phone_validity
        ,pe.legislation_code                                pe_legislation_code
        ,pe.ethnicity                                       pe_ethnicity
        ,pe.primary_flag                                    pe_primary_flag
        ,pe.ethnicity_id                                    pe_ethnicity_id
        ,nid.national_identifier_id                         nid_national_identifier_id
        ,nid.legislation_code                               nid_legislation_code
        ,nid.national_identifier_type                       nid_national_identifier_type
        ,nid.national_identifier_number                     nid_national_identifier_number
        ,nid.primary_flag                                   nid_primary_flag
        ,TO_CHAR(nid.issue_date,'RRRR/MM/DD')               nid_issue_date
        ,TO_CHAR(nid.expiration_date,'RRRR/MM/DD')          nid_expiration_date
        ,pass.legislationcode                               pass_legislationcode
        ,pass.passportnumber                                pass_passportnumber
        ,substr(pass.issuedate,1,10)                        pass_issue_date
        ,substr(pass.expirationdate,1,10)                   pass_expiration_date
        ,pass.issuingcountry                                pass_issuing_country
        ,cit.citizenship_id                                 cit_citizenship_id
        ,TO_CHAR(cit.date_from,'RRRR/MM/DD')                cit_date_from
        ,TO_CHAR(cit.date_to,'RRRR/MM/DD')                  cit_date_to
        ,cit.legislation_code                               cit_legislation_code
        ,cit.citizenship_status                             cit_citizenship_status
        ,pld.person_legislative_id                          pld_person_legislative_id
        ,pld.legislation_code                               pld_legislation_code
        ,pld.highest_education_level                        pld_highest_education_level
        ,pld.sex                                            pld_sex
        ,pld.marital_status                                 pld_marital_status
        ,TO_CHAR(pld.marital_status_date,'RRRR/MM/DD')      pld_marital_status_date
        ,pp.BG_name                                         bg_name
        ,pp.bg_id                                           bg_id
          ,rel.RELIGION                                       religion
        ,rel.primary_flag                                   rel_primary_flag
		,pps.ATTRIBUTE1 									pps_ATTRIBUTE1
		,pps.ATTRIBUTE2                                     pps_ATTRIBUTE2
		,pps.ATTRIBUTE3                                     pps_ATTRIBUTE3
		,pps.ATTRIBUTE4                                     pps_ATTRIBUTE4
		,pps.ATTRIBUTE5                                     pps_ATTRIBUTE5
		,pps.ATTRIBUTE6                                     pps_ATTRIBUTE6
		,pps.ATTRIBUTE7                                     pps_ATTRIBUTE7
		,pps.ATTRIBUTE8                                     pps_ATTRIBUTE8
		,pps.ATTRIBUTE9                                     pps_ATTRIBUTE9
		,pps.ATTRIBUTE10                                    pps_ATTRIBUTE10
		,pps.ATTRIBUTE11                                    pps_ATTRIBUTE11
		,pps.ATTRIBUTE12                                    pps_ATTRIBUTE12
		,pps.ATTRIBUTE13                                    pps_ATTRIBUTE13
		,pps.ATTRIBUTE14                                    pps_ATTRIBUTE14
		,pps.ATTRIBUTE15                                    pps_ATTRIBUTE15
		,pps.ATTRIBUTE_NUMBER1 								pps_ATTRIBUTE_NUMBER1
		,pps.ATTRIBUTE_NUMBER2                              pps_ATTRIBUTE_NUMBER2
		,pps.ATTRIBUTE_NUMBER3                              pps_ATTRIBUTE_NUMBER3
		,pps.ATTRIBUTE_NUMBER4                              pps_ATTRIBUTE_NUMBER4
		,pps.ATTRIBUTE_NUMBER5                              pps_ATTRIBUTE_NUMBER5
		,pps.ATTRIBUTE_NUMBER6                              pps_ATTRIBUTE_NUMBER6
		,pps.ATTRIBUTE_NUMBER7                              pps_ATTRIBUTE_NUMBER7
		,pps.ATTRIBUTE_NUMBER8                              pps_ATTRIBUTE_NUMBER8
		,pps.ATTRIBUTE_NUMBER9                              pps_ATTRIBUTE_NUMBER9
		,pps.ATTRIBUTE_NUMBER10                             pps_ATTRIBUTE_NUMBER10
		,pps.ATTRIBUTE_NUMBER11                             pps_ATTRIBUTE_NUMBER11
		,pps.ATTRIBUTE_NUMBER12                             pps_ATTRIBUTE_NUMBER12
		,pps.ATTRIBUTE_NUMBER13                             pps_ATTRIBUTE_NUMBER13
		,pps.ATTRIBUTE_NUMBER14                             pps_ATTRIBUTE_NUMBER14
		,pps.ATTRIBUTE_NUMBER15                             pps_ATTRIBUTE_NUMBER15
		,pps.ATTRIBUTE_DATE1 								pps_ATTRIBUTE_DATE1
		,pps.ATTRIBUTE_DATE2                                pps_ATTRIBUTE_DATE2
		,pps.ATTRIBUTE_DATE3                                pps_ATTRIBUTE_DATE3
		,pps.ATTRIBUTE_DATE4                                pps_ATTRIBUTE_DATE4
		,pps.ATTRIBUTE_DATE5                                pps_ATTRIBUTE_DATE5
		,pps.ATTRIBUTE_DATE6                                pps_ATTRIBUTE_DATE6
		,pps.ATTRIBUTE_DATE7                                pps_ATTRIBUTE_DATE7
		,pps.ATTRIBUTE_DATE8                                pps_ATTRIBUTE_DATE8
		,pps.ATTRIBUTE_DATE9                                pps_ATTRIBUTE_DATE9
		,pps.ATTRIBUTE_DATE10                               pps_ATTRIBUTE_DATE10
		,pps.ATTRIBUTE_DATE11                               pps_ATTRIBUTE_DATE11
		,pps.ATTRIBUTE_DATE12                               pps_ATTRIBUTE_DATE12
		,pps.ATTRIBUTE_DATE13                               pps_ATTRIBUTE_DATE13
		,pps.ATTRIBUTE_DATE14                               pps_ATTRIBUTE_DATE14
		,pps.ATTRIBUTE_DATE15                               pps_ATTRIBUTE_DATE15
		,pp.ATTRIBUTE1 									    pp_ATTRIBUTE1
		,pp.ATTRIBUTE2                                      pp_ATTRIBUTE2
		,pp.ATTRIBUTE3                                      pp_ATTRIBUTE3
		,pp.ATTRIBUTE4                                      pp_ATTRIBUTE4
		,pp.ATTRIBUTE5                                      pp_ATTRIBUTE5
		,pp.ATTRIBUTE6                                      pp_ATTRIBUTE6
		,pp.ATTRIBUTE7                                      pp_ATTRIBUTE7
		,pp.ATTRIBUTE8                                      pp_ATTRIBUTE8
		,pp.ATTRIBUTE9                                      pp_ATTRIBUTE9
		,pp.ATTRIBUTE10                                     pp_ATTRIBUTE10
		,pp.ATTRIBUTE11                                     pp_ATTRIBUTE11
		,pp.ATTRIBUTE12                                     pp_ATTRIBUTE12
		,pp.ATTRIBUTE13                                     pp_ATTRIBUTE13
		,pp.ATTRIBUTE14                                     pp_ATTRIBUTE14
		,pp.ATTRIBUTE15                                     pp_ATTRIBUTE15
		,pp.ATTRIBUTE_NUMBER1 							    pp_ATTRIBUTE_NUMBER1
		,pp.ATTRIBUTE_NUMBER2                               pp_ATTRIBUTE_NUMBER2
		,pp.ATTRIBUTE_NUMBER3                               pp_ATTRIBUTE_NUMBER3
		,pp.ATTRIBUTE_NUMBER4                               pp_ATTRIBUTE_NUMBER4
		,pp.ATTRIBUTE_NUMBER5                               pp_ATTRIBUTE_NUMBER5
		,pp.ATTRIBUTE_NUMBER6                               pp_ATTRIBUTE_NUMBER6
		,pp.ATTRIBUTE_NUMBER7                               pp_ATTRIBUTE_NUMBER7
		,pp.ATTRIBUTE_NUMBER8                               pp_ATTRIBUTE_NUMBER8
		,pp.ATTRIBUTE_NUMBER9                               pp_ATTRIBUTE_NUMBER9
		,pp.ATTRIBUTE_NUMBER10                              pp_ATTRIBUTE_NUMBER10
		,pp.ATTRIBUTE_NUMBER11                              pp_ATTRIBUTE_NUMBER11
		,pp.ATTRIBUTE_NUMBER12                              pp_ATTRIBUTE_NUMBER12
		,pp.ATTRIBUTE_NUMBER13                              pp_ATTRIBUTE_NUMBER13
		,pp.ATTRIBUTE_NUMBER14                              pp_ATTRIBUTE_NUMBER14
		,pp.ATTRIBUTE_NUMBER15                              pp_ATTRIBUTE_NUMBER15
		,pp.ATTRIBUTE_DATE1 							    pp_ATTRIBUTE_DATE1
		,pp.ATTRIBUTE_DATE2                                 pp_ATTRIBUTE_DATE2
		,pp.ATTRIBUTE_DATE3                                 pp_ATTRIBUTE_DATE3
		,pp.ATTRIBUTE_DATE4                                 pp_ATTRIBUTE_DATE4
		,pp.ATTRIBUTE_DATE5                                 pp_ATTRIBUTE_DATE5
		,pp.ATTRIBUTE_DATE6                                 pp_ATTRIBUTE_DATE6
		,pp.ATTRIBUTE_DATE7                                 pp_ATTRIBUTE_DATE7
		,pp.ATTRIBUTE_DATE8                                 pp_ATTRIBUTE_DATE8
		,pp.ATTRIBUTE_DATE9                                 pp_ATTRIBUTE_DATE9
		,pp.ATTRIBUTE_DATE10                                pp_ATTRIBUTE_DATE10
		,pp.ATTRIBUTE_DATE11                                pp_ATTRIBUTE_DATE11
		,pp.ATTRIBUTE_DATE12                                pp_ATTRIBUTE_DATE12
		,pp.ATTRIBUTE_DATE13                                pp_ATTRIBUTE_DATE13
		,pp.ATTRIBUTE_DATE14                                pp_ATTRIBUTE_DATE14
		,pp.ATTRIBUTE_DATE15                                pp_ATTRIBUTE_DATE15
		,pns.NAM_INFORMATION1 								pns_NAM_INFORMATION1
		,pns.NAM_INFORMATION2                               pns_NAM_INFORMATION2
		,pns.NAM_INFORMATION3                               pns_NAM_INFORMATION3
		,pns.NAM_INFORMATION4                               pns_NAM_INFORMATION4
		,pns.NAM_INFORMATION5                               pns_NAM_INFORMATION5
		,pns.NAM_INFORMATION6                               pns_NAM_INFORMATION6
		,pns.NAM_INFORMATION7                               pns_NAM_INFORMATION7
		,pns.NAM_INFORMATION8                               pns_NAM_INFORMATION8
		,pns.NAM_INFORMATION9                               pns_NAM_INFORMATION9
		,pns.NAM_INFORMATION10                              pns_NAM_INFORMATION10
		,pns.NAM_INFORMATION11                              pns_NAM_INFORMATION11
		,pns.NAM_INFORMATION12                              pns_NAM_INFORMATION12
		,pns.NAM_INFORMATION13                              pns_NAM_INFORMATION13
		,pns.NAM_INFORMATION14                              pns_NAM_INFORMATION14
		,pns.NAM_INFORMATION15                              pns_NAM_INFORMATION15
		,pns.ATTRIBUTE1 									pns_ATTRIBUTE1
		,pns.ATTRIBUTE2                                     pns_ATTRIBUTE2
		,pns.ATTRIBUTE3                                     pns_ATTRIBUTE3
		,pns.ATTRIBUTE4                                     pns_ATTRIBUTE4
		,pns.ATTRIBUTE5                                     pns_ATTRIBUTE5
		,pns.ATTRIBUTE6                                     pns_ATTRIBUTE6
		,pns.ATTRIBUTE7                                     pns_ATTRIBUTE7
		,pns.ATTRIBUTE8                                     pns_ATTRIBUTE8
		,pns.ATTRIBUTE9                                     pns_ATTRIBUTE9
		,pns.ATTRIBUTE10                                    pns_ATTRIBUTE10
		,pns.ATTRIBUTE11                                    pns_ATTRIBUTE11
		,pns.ATTRIBUTE12                                    pns_ATTRIBUTE12
		,pns.ATTRIBUTE13                                    pns_ATTRIBUTE13
		,pns.ATTRIBUTE14                                    pns_ATTRIBUTE14
		,pns.ATTRIBUTE15                                    pns_ATTRIBUTE15
		,pns.NAM_INFORMATION_DATE1 							pns_NAM_INFORMATION_DATE1
		,pns.NAM_INFORMATION_DATE2                          pns_NAM_INFORMATION_DATE2
		,pns.NAM_INFORMATION_DATE3                          pns_NAM_INFORMATION_DATE3
		,pns.NAM_INFORMATION_DATE4                          pns_NAM_INFORMATION_DATE4
		,pns.NAM_INFORMATION_DATE5                          pns_NAM_INFORMATION_DATE5
		,pns.NAM_INFORMATION_DATE6                          pns_NAM_INFORMATION_DATE6
		,pns.NAM_INFORMATION_DATE7                          pns_NAM_INFORMATION_DATE7
		,pns.NAM_INFORMATION_DATE8                          pns_NAM_INFORMATION_DATE8
		,pns.NAM_INFORMATION_DATE9                          pns_NAM_INFORMATION_DATE9
		,pns.NAM_INFORMATION_DATE10                         pns_NAM_INFORMATION_DATE10
		,pns.NAM_INFORMATION_DATE11                         pns_NAM_INFORMATION_DATE11
		,pns.NAM_INFORMATION_DATE12                         pns_NAM_INFORMATION_DATE12
		,pns.NAM_INFORMATION_DATE13                         pns_NAM_INFORMATION_DATE13
		,pns.NAM_INFORMATION_DATE14                         pns_NAM_INFORMATION_DATE14
		,pns.NAM_INFORMATION_DATE15                         pns_NAM_INFORMATION_DATE15
		,pns.ATTRIBUTE_NUMBER1 								pns_ATTRIBUTE_NUMBER1
		,pns.ATTRIBUTE_NUMBER2                              pns_ATTRIBUTE_NUMBER2
		,pns.ATTRIBUTE_NUMBER3                              pns_ATTRIBUTE_NUMBER3
		,pns.ATTRIBUTE_NUMBER4                              pns_ATTRIBUTE_NUMBER4
		,pns.ATTRIBUTE_NUMBER5                              pns_ATTRIBUTE_NUMBER5
		,pns.ATTRIBUTE_NUMBER6                              pns_ATTRIBUTE_NUMBER6
		,pns.ATTRIBUTE_NUMBER7                              pns_ATTRIBUTE_NUMBER7
		,pns.ATTRIBUTE_NUMBER8                              pns_ATTRIBUTE_NUMBER8
		,pns.ATTRIBUTE_NUMBER9                              pns_ATTRIBUTE_NUMBER9
		,pns.ATTRIBUTE_NUMBER10                             pns_ATTRIBUTE_NUMBER10
		,pns.ATTRIBUTE_NUMBER11                             pns_ATTRIBUTE_NUMBER11
		,pns.ATTRIBUTE_NUMBER12                             pns_ATTRIBUTE_NUMBER12
		,pns.ATTRIBUTE_NUMBER13                             pns_ATTRIBUTE_NUMBER13
		,pns.ATTRIBUTE_NUMBER14                             pns_ATTRIBUTE_NUMBER14
		,pns.ATTRIBUTE_NUMBER15                             pns_ATTRIBUTE_NUMBER15
		,pns.ATTRIBUTE_DATE1 								pns_ATTRIBUTE_DATE1
		,pns.ATTRIBUTE_DATE2                                pns_ATTRIBUTE_DATE2
		,pns.ATTRIBUTE_DATE3                                pns_ATTRIBUTE_DATE3
		,pns.ATTRIBUTE_DATE4                                pns_ATTRIBUTE_DATE4
		,pns.ATTRIBUTE_DATE5                                pns_ATTRIBUTE_DATE5
		,pns.ATTRIBUTE_DATE6                                pns_ATTRIBUTE_DATE6
		,pns.ATTRIBUTE_DATE7                                pns_ATTRIBUTE_DATE7
		,pns.ATTRIBUTE_DATE8                                pns_ATTRIBUTE_DATE8
		,pns.ATTRIBUTE_DATE9                                pns_ATTRIBUTE_DATE9
		,pns.ATTRIBUTE_DATE10                               pns_ATTRIBUTE_DATE10
		,pns.ATTRIBUTE_DATE11                               pns_ATTRIBUTE_DATE11
		,pns.ATTRIBUTE_DATE12                               pns_ATTRIBUTE_DATE12
		,pns.ATTRIBUTE_DATE13                               pns_ATTRIBUTE_DATE13
		,pns.ATTRIBUTE_DATE14                               pns_ATTRIBUTE_DATE14
		,pns.ATTRIBUTE_DATE15                               pns_ATTRIBUTE_DATE15
		,NULL						paf_ADDL_ADDRESS_ATTRIBUTE1
		,NULL                        paf_ADDL_ADDRESS_ATTRIBUTE2
		,NULL                        paf_ADDL_ADDRESS_ATTRIBUTE3
		,NULL                        paf_ADDL_ADDRESS_ATTRIBUTE4
		,NULL                        paf_ADDL_ADDRESS_ATTRIBUTE5
		,NULL 								paf_ADDR_ATTRIBUTE1
		,NULL                                paf_ADDR_ATTRIBUTE2
		,NULL                                paf_ADDR_ATTRIBUTE3
		,NULL                                paf_ADDR_ATTRIBUTE4
		,NULL                                paf_ADDR_ATTRIBUTE5
		,NULL                               paf_ADDR_ATTRIBUTE6
		,NULL                               paf_ADDR_ATTRIBUTE7
		,NULL                               paf_ADDR_ATTRIBUTE8
		,NULL                               paf_ADDR_ATTRIBUTE9
		,NULL                               paf_ADDR_ATTRIBUTE10
		,NULL                               paf_ADDR_ATTRIBUTE11
		,NULL                               paf_ADDR_ATTRIBUTE12
		,NULL                               paf_ADDR_ATTRIBUTE13
		,NULL                               paf_ADDR_ATTRIBUTE14
		,NULL                               paf_ADDR_ATTRIBUTE15
		,null 						paf_ADDR_ATTRIBUTE_NUMBER1
		,null                         paf_ADDR_ATTRIBUTE_NUMBER2
		,null                         paf_ADDR_ATTRIBUTE_NUMBER3
		,null                         paf_ADDR_ATTRIBUTE_NUMBER4
		,null                         paf_ADDR_ATTRIBUTE_NUMBER5
		,null                         paf_ADDR_ATTRIBUTE_NUMBER6
		,null                         paf_ADDR_ATTRIBUTE_NUMBER7
		,null                         paf_ADDR_ATTRIBUTE_NUMBER8
		,null                         paf_ADDR_ATTRIBUTE_NUMBER9
		,null                        paf_ADDR_ATTRIBUTE_NUMBER10
		,null                        paf_ADDR_ATTRIBUTE_NUMBER11
		,null                       paf_ADDR_ATTRIBUTE_NUMBER12
		,null                      paf_ADDR_ATTRIBUTE_NUMBER13
		,null                      paf_ADDR_ATTRIBUTE_NUMBER14
		,null                      paf_ADDR_ATTRIBUTE_NUMBER15
		,null					paf_ADDR_ATTRIBUTE_DATE1
		,null                      paf_ADDR_ATTRIBUTE_DATE2
		,null                      paf_ADDR_ATTRIBUTE_DATE3
		,null                      paf_ADDR_ATTRIBUTE_DATE4
		,null                           paf_ADDR_ATTRIBUTE_DATE5
		,null                           paf_ADDR_ATTRIBUTE_DATE6
		,null                           paf_ADDR_ATTRIBUTE_DATE7
		,null                           paf_ADDR_ATTRIBUTE_DATE8
		,null                          paf_ADDR_ATTRIBUTE_DATE9
		,null                         paf_ADDR_ATTRIBUTE_DATE10
		,null                         paf_ADDR_ATTRIBUTE_DATE11
		,null                         paf_ADDR_ATTRIBUTE_DATE12
		,null                         paf_ADDR_ATTRIBUTE_DATE13
		,null                         paf_ADDR_ATTRIBUTE_DATE14
		,null                         paf_ADDR_ATTRIBUTE_DATE15 
		,pemail.ATTRIBUTE1 									pemail_ATTRIBUTE1
		,pemail.ATTRIBUTE2                                  pemail_ATTRIBUTE2
		,pemail.ATTRIBUTE3                                  pemail_ATTRIBUTE3
		,pemail.ATTRIBUTE4                                  pemail_ATTRIBUTE4
		,pemail.ATTRIBUTE5                                  pemail_ATTRIBUTE5
		,pemail.ATTRIBUTE6                                  pemail_ATTRIBUTE6
		,pemail.ATTRIBUTE7                                  pemail_ATTRIBUTE7
		,pemail.ATTRIBUTE8                                  pemail_ATTRIBUTE8
		,pemail.ATTRIBUTE9                                  pemail_ATTRIBUTE9
		,pemail.ATTRIBUTE10                                 pemail_ATTRIBUTE10
		,pemail.ATTRIBUTE11                                 pemail_ATTRIBUTE11
		,pemail.ATTRIBUTE12                                 pemail_ATTRIBUTE12
		,pemail.ATTRIBUTE13                                 pemail_ATTRIBUTE13
		,pemail.ATTRIBUTE14                                 pemail_ATTRIBUTE14
		,pemail.ATTRIBUTE15                                 pemail_ATTRIBUTE15
		,pemail.ATTRIBUTE_NUMBER1 							pemail_ATTRIBUTE_NUMBER1
		,pemail.ATTRIBUTE_NUMBER2                           pemail_ATTRIBUTE_NUMBER2
		,pemail.ATTRIBUTE_NUMBER3                           pemail_ATTRIBUTE_NUMBER3
		,pemail.ATTRIBUTE_NUMBER4                           pemail_ATTRIBUTE_NUMBER4
		,pemail.ATTRIBUTE_NUMBER5                           pemail_ATTRIBUTE_NUMBER5
		,pemail.ATTRIBUTE_NUMBER6                           pemail_ATTRIBUTE_NUMBER6
		,pemail.ATTRIBUTE_NUMBER7                           pemail_ATTRIBUTE_NUMBER7
		,pemail.ATTRIBUTE_NUMBER8                           pemail_ATTRIBUTE_NUMBER8
		,pemail.ATTRIBUTE_NUMBER9                           pemail_ATTRIBUTE_NUMBER9
		,pemail.ATTRIBUTE_NUMBER10                          pemail_ATTRIBUTE_NUMBER10
		,pemail.ATTRIBUTE_NUMBER11                          pemail_ATTRIBUTE_NUMBER11
		,pemail.ATTRIBUTE_NUMBER12                          pemail_ATTRIBUTE_NUMBER12
		,pemail.ATTRIBUTE_NUMBER13                          pemail_ATTRIBUTE_NUMBER13
		,pemail.ATTRIBUTE_NUMBER14                          pemail_ATTRIBUTE_NUMBER14
		,pemail.ATTRIBUTE_NUMBER15                          pemail_ATTRIBUTE_NUMBER15
		,pemail.ATTRIBUTE_DATE1 							pemail_ATTRIBUTE_DATE1
		,pemail.ATTRIBUTE_DATE2                             pemail_ATTRIBUTE_DATE2
		,pemail.ATTRIBUTE_DATE3                             pemail_ATTRIBUTE_DATE3
		,pemail.ATTRIBUTE_DATE4                             pemail_ATTRIBUTE_DATE4
		,pemail.ATTRIBUTE_DATE5                             pemail_ATTRIBUTE_DATE5
		,pemail.ATTRIBUTE_DATE6                             pemail_ATTRIBUTE_DATE6
		,pemail.ATTRIBUTE_DATE7                             pemail_ATTRIBUTE_DATE7
		,pemail.ATTRIBUTE_DATE8                             pemail_ATTRIBUTE_DATE8
		,pemail.ATTRIBUTE_DATE9                             pemail_ATTRIBUTE_DATE9
		,pemail.ATTRIBUTE_DATE10                            pemail_ATTRIBUTE_DATE10
		,pemail.ATTRIBUTE_DATE11                            pemail_ATTRIBUTE_DATE11
		,pemail.ATTRIBUTE_DATE12                            pemail_ATTRIBUTE_DATE12
		,pemail.ATTRIBUTE_DATE13                            pemail_ATTRIBUTE_DATE13
		,pemail.ATTRIBUTE_DATE14                            pemail_ATTRIBUTE_DATE14
		,pemail.ATTRIBUTE_DATE15                            pemail_ATTRIBUTE_DATE15
		,phone.ATTRIBUTE1 									phone_ATTRIBUTE1
		,phone.ATTRIBUTE2                                   phone_ATTRIBUTE2
		,phone.ATTRIBUTE3                                   phone_ATTRIBUTE3
		,phone.ATTRIBUTE4                                   phone_ATTRIBUTE4
		,phone.ATTRIBUTE5                                   phone_ATTRIBUTE5
		,phone.ATTRIBUTE6                                   phone_ATTRIBUTE6
		,phone.ATTRIBUTE7                                   phone_ATTRIBUTE7
		,phone.ATTRIBUTE8                                   phone_ATTRIBUTE8
		,phone.ATTRIBUTE9                                   phone_ATTRIBUTE9
		,phone.ATTRIBUTE10                                  phone_ATTRIBUTE10
		,phone.ATTRIBUTE11                                  phone_ATTRIBUTE11
		,phone.ATTRIBUTE12                                  phone_ATTRIBUTE12
		,phone.ATTRIBUTE13                                  phone_ATTRIBUTE13
		,phone.ATTRIBUTE14                                  phone_ATTRIBUTE14
		,phone.ATTRIBUTE15                                  phone_ATTRIBUTE15
		,phone.ATTRIBUTE_NUMBER1 							phone_ATTRIBUTE_NUMBER1
		,phone.ATTRIBUTE_NUMBER2                            phone_ATTRIBUTE_NUMBER2
		,phone.ATTRIBUTE_NUMBER3                            phone_ATTRIBUTE_NUMBER3
		,phone.ATTRIBUTE_NUMBER4                            phone_ATTRIBUTE_NUMBER4
		,phone.ATTRIBUTE_NUMBER5                            phone_ATTRIBUTE_NUMBER5
		,phone.ATTRIBUTE_NUMBER6                            phone_ATTRIBUTE_NUMBER6
		,phone.ATTRIBUTE_NUMBER7                            phone_ATTRIBUTE_NUMBER7
		,phone.ATTRIBUTE_NUMBER8                            phone_ATTRIBUTE_NUMBER8
		,phone.ATTRIBUTE_NUMBER9                            phone_ATTRIBUTE_NUMBER9
		,phone.ATTRIBUTE_NUMBER10                           phone_ATTRIBUTE_NUMBER10
		,phone.ATTRIBUTE_NUMBER11                           phone_ATTRIBUTE_NUMBER11
		,phone.ATTRIBUTE_NUMBER12                           phone_ATTRIBUTE_NUMBER12
		,phone.ATTRIBUTE_NUMBER13                           phone_ATTRIBUTE_NUMBER13
		,phone.ATTRIBUTE_NUMBER14                           phone_ATTRIBUTE_NUMBER14
		,phone.ATTRIBUTE_NUMBER15                           phone_ATTRIBUTE_NUMBER15
		,phone.ATTRIBUTE_DATE1 								phone_ATTRIBUTE_DATE1
		,phone.ATTRIBUTE_DATE2                              phone_ATTRIBUTE_DATE2
		,phone.ATTRIBUTE_DATE3                              phone_ATTRIBUTE_DATE3
		,phone.ATTRIBUTE_DATE4                              phone_ATTRIBUTE_DATE4
		,phone.ATTRIBUTE_DATE5                              phone_ATTRIBUTE_DATE5
		,phone.ATTRIBUTE_DATE6                              phone_ATTRIBUTE_DATE6
		,phone.ATTRIBUTE_DATE7                              phone_ATTRIBUTE_DATE7
		,phone.ATTRIBUTE_DATE8                              phone_ATTRIBUTE_DATE8
		,phone.ATTRIBUTE_DATE9                              phone_ATTRIBUTE_DATE9
		,phone.ATTRIBUTE_DATE10                             phone_ATTRIBUTE_DATE10
		,phone.ATTRIBUTE_DATE11                             phone_ATTRIBUTE_DATE11
		,phone.ATTRIBUTE_DATE12                             phone_ATTRIBUTE_DATE12
		,phone.ATTRIBUTE_DATE13                             phone_ATTRIBUTE_DATE13
		,phone.ATTRIBUTE_DATE14                             phone_ATTRIBUTE_DATE14
		,phone.ATTRIBUTE_DATE15                             phone_ATTRIBUTE_DATE15
		,pe.ATTRIBUTE1 										pe_ATTRIBUTE1
		,pe.ATTRIBUTE2                                      pe_ATTRIBUTE2
		,pe.ATTRIBUTE3                                      pe_ATTRIBUTE3
		,pe.ATTRIBUTE4                                      pe_ATTRIBUTE4
		,pe.ATTRIBUTE5                                      pe_ATTRIBUTE5
		,pe.ATTRIBUTE6                                      pe_ATTRIBUTE6
		,pe.ATTRIBUTE7                                      pe_ATTRIBUTE7
		,pe.ATTRIBUTE8                                      pe_ATTRIBUTE8
		,pe.ATTRIBUTE9                                      pe_ATTRIBUTE9
		,pe.ATTRIBUTE10                                     pe_ATTRIBUTE10
		,pe.ATTRIBUTE11                                     pe_ATTRIBUTE11
		,pe.ATTRIBUTE12                                     pe_ATTRIBUTE12
		,pe.ATTRIBUTE13                                     pe_ATTRIBUTE13
		,pe.ATTRIBUTE14                                     pe_ATTRIBUTE14
		,pe.ATTRIBUTE15                                     pe_ATTRIBUTE15
		,pe.ATTRIBUTE_NUMBER1 								pe_ATTRIBUTE_NUMBER1
		,pe.ATTRIBUTE_NUMBER2                               pe_ATTRIBUTE_NUMBER2
		,pe.ATTRIBUTE_NUMBER3                               pe_ATTRIBUTE_NUMBER3
		,pe.ATTRIBUTE_NUMBER4                               pe_ATTRIBUTE_NUMBER4
		,pe.ATTRIBUTE_NUMBER5                               pe_ATTRIBUTE_NUMBER5
		,pe.ATTRIBUTE_NUMBER6                               pe_ATTRIBUTE_NUMBER6
		,pe.ATTRIBUTE_NUMBER7                               pe_ATTRIBUTE_NUMBER7
		,pe.ATTRIBUTE_NUMBER8                               pe_ATTRIBUTE_NUMBER8
		,pe.ATTRIBUTE_NUMBER9                               pe_ATTRIBUTE_NUMBER9
		,pe.ATTRIBUTE_NUMBER10                              pe_ATTRIBUTE_NUMBER10
		,pe.ATTRIBUTE_NUMBER11                              pe_ATTRIBUTE_NUMBER11
		,pe.ATTRIBUTE_NUMBER12                              pe_ATTRIBUTE_NUMBER12
		,pe.ATTRIBUTE_NUMBER13                              pe_ATTRIBUTE_NUMBER13
		,pe.ATTRIBUTE_NUMBER14                              pe_ATTRIBUTE_NUMBER14
		,pe.ATTRIBUTE_NUMBER15                              pe_ATTRIBUTE_NUMBER15
		,pe.ATTRIBUTE_DATE1 								pe_ATTRIBUTE_DATE1
		,pe.ATTRIBUTE_DATE2                                 pe_ATTRIBUTE_DATE2
		,pe.ATTRIBUTE_DATE3                                 pe_ATTRIBUTE_DATE3
		,pe.ATTRIBUTE_DATE4                                 pe_ATTRIBUTE_DATE4
		,pe.ATTRIBUTE_DATE5                                 pe_ATTRIBUTE_DATE5
		,pe.ATTRIBUTE_DATE6                                 pe_ATTRIBUTE_DATE6
		,pe.ATTRIBUTE_DATE7                                 pe_ATTRIBUTE_DATE7
		,pe.ATTRIBUTE_DATE8                                 pe_ATTRIBUTE_DATE8
		,pe.ATTRIBUTE_DATE9                                 pe_ATTRIBUTE_DATE9
		,pe.ATTRIBUTE_DATE10                                pe_ATTRIBUTE_DATE10
		,pe.ATTRIBUTE_DATE11                                pe_ATTRIBUTE_DATE11
		,pe.ATTRIBUTE_DATE12                                pe_ATTRIBUTE_DATE12
		,pe.ATTRIBUTE_DATE13                                pe_ATTRIBUTE_DATE13
		,pe.ATTRIBUTE_DATE14                                pe_ATTRIBUTE_DATE14
		,pe.ATTRIBUTE_DATE15                                pe_ATTRIBUTE_DATE15
		,nid.ATTRIBUTE1 									nid_ATTRIBUTE1
		,nid.ATTRIBUTE2                                     nid_ATTRIBUTE2
		,nid.ATTRIBUTE3                                     nid_ATTRIBUTE3
		,nid.ATTRIBUTE4                                     nid_ATTRIBUTE4
		,nid.ATTRIBUTE5                                     nid_ATTRIBUTE5
		,nid.ATTRIBUTE6                                     nid_ATTRIBUTE6
		,nid.ATTRIBUTE7                                     nid_ATTRIBUTE7
		,nid.ATTRIBUTE8                                     nid_ATTRIBUTE8
		,nid.ATTRIBUTE9                                     nid_ATTRIBUTE9
		,nid.ATTRIBUTE10                                    nid_ATTRIBUTE10
		,nid.ATTRIBUTE11                                    nid_ATTRIBUTE11
		,nid.ATTRIBUTE12                                    nid_ATTRIBUTE12
		,nid.ATTRIBUTE13                                    nid_ATTRIBUTE13
		,nid.ATTRIBUTE14                                    nid_ATTRIBUTE14
		,nid.ATTRIBUTE15                                    nid_ATTRIBUTE15
		,nid.ATTRIBUTE_NUMBER1 								nid_ATTRIBUTE_NUMBER1
		,nid.ATTRIBUTE_NUMBER2                              nid_ATTRIBUTE_NUMBER2
		,nid.ATTRIBUTE_NUMBER3                              nid_ATTRIBUTE_NUMBER3
		,nid.ATTRIBUTE_NUMBER4                              nid_ATTRIBUTE_NUMBER4
		,nid.ATTRIBUTE_NUMBER5                              nid_ATTRIBUTE_NUMBER5
		,nid.ATTRIBUTE_NUMBER6                              nid_ATTRIBUTE_NUMBER6
		,nid.ATTRIBUTE_NUMBER7                              nid_ATTRIBUTE_NUMBER7
		,nid.ATTRIBUTE_NUMBER8                              nid_ATTRIBUTE_NUMBER8
		,nid.ATTRIBUTE_NUMBER9                              nid_ATTRIBUTE_NUMBER9
		,nid.ATTRIBUTE_NUMBER10                             nid_ATTRIBUTE_NUMBER10
		,nid.ATTRIBUTE_NUMBER11                             nid_ATTRIBUTE_NUMBER11
		,nid.ATTRIBUTE_NUMBER12                             nid_ATTRIBUTE_NUMBER12
		,nid.ATTRIBUTE_NUMBER13                             nid_ATTRIBUTE_NUMBER13
		,nid.ATTRIBUTE_NUMBER14                             nid_ATTRIBUTE_NUMBER14
		,nid.ATTRIBUTE_NUMBER15                             nid_ATTRIBUTE_NUMBER15
		,nid.ATTRIBUTE_DATE1 								nid_ATTRIBUTE_DATE1
		,nid.ATTRIBUTE_DATE2                                nid_ATTRIBUTE_DATE2
		,nid.ATTRIBUTE_DATE3                                nid_ATTRIBUTE_DATE3
		,nid.ATTRIBUTE_DATE4                                nid_ATTRIBUTE_DATE4
		,nid.ATTRIBUTE_DATE5                                nid_ATTRIBUTE_DATE5
		,nid.ATTRIBUTE_DATE6                                nid_ATTRIBUTE_DATE6
		,nid.ATTRIBUTE_DATE7                                nid_ATTRIBUTE_DATE7
		,nid.ATTRIBUTE_DATE8                                nid_ATTRIBUTE_DATE8
		,nid.ATTRIBUTE_DATE9                                nid_ATTRIBUTE_DATE9
		,nid.ATTRIBUTE_DATE10                               nid_ATTRIBUTE_DATE10
		,nid.ATTRIBUTE_DATE11                               nid_ATTRIBUTE_DATE11
		,nid.ATTRIBUTE_DATE12                               nid_ATTRIBUTE_DATE12
		,nid.ATTRIBUTE_DATE13                               nid_ATTRIBUTE_DATE13
		,nid.ATTRIBUTE_DATE14                               nid_ATTRIBUTE_DATE14
		,nid.ATTRIBUTE_DATE15                               nid_ATTRIBUTE_DATE15
		,pass.ATTRIBUTE1 									pass_ATTRIBUTE1
		,pass.ATTRIBUTE2                                    pass_ATTRIBUTE2
		,pass.ATTRIBUTE3                                    pass_ATTRIBUTE3
		,pass.ATTRIBUTE4                                    pass_ATTRIBUTE4
		,pass.ATTRIBUTE5                                    pass_ATTRIBUTE5
		,pass.ATTRIBUTE6                                    pass_ATTRIBUTE6
		,pass.ATTRIBUTE7                                    pass_ATTRIBUTE7
		,pass.ATTRIBUTE8                                    pass_ATTRIBUTE8
		,pass.ATTRIBUTE9                                    pass_ATTRIBUTE9
		,pass.ATTRIBUTE10                                   pass_ATTRIBUTE10
		,pass.ATTRIBUTE11                                   pass_ATTRIBUTE11
		,pass.ATTRIBUTE12                                   pass_ATTRIBUTE12
		,pass.ATTRIBUTE13                                   pass_ATTRIBUTE13
		,pass.ATTRIBUTE14                                   pass_ATTRIBUTE14
		,pass.ATTRIBUTE15                                   pass_ATTRIBUTE15
		,pass.ATTRIBUTE_NUMBER1 							pass_ATTRIBUTE_NUMBER1
		,pass.ATTRIBUTE_NUMBER2                             pass_ATTRIBUTE_NUMBER2
		,pass.ATTRIBUTE_NUMBER3                             pass_ATTRIBUTE_NUMBER3
		,pass.ATTRIBUTE_NUMBER4                             pass_ATTRIBUTE_NUMBER4
		,pass.ATTRIBUTE_NUMBER5                             pass_ATTRIBUTE_NUMBER5
		,pass.ATTRIBUTE_NUMBER6                             pass_ATTRIBUTE_NUMBER6
		,pass.ATTRIBUTE_NUMBER7                             pass_ATTRIBUTE_NUMBER7
		,pass.ATTRIBUTE_NUMBER8                             pass_ATTRIBUTE_NUMBER8
		,pass.ATTRIBUTE_NUMBER9                             pass_ATTRIBUTE_NUMBER9
		,pass.ATTRIBUTE_NUMBER10                            pass_ATTRIBUTE_NUMBER10
		,pass.ATTRIBUTE_NUMBER11                            pass_ATTRIBUTE_NUMBER11
		,pass.ATTRIBUTE_NUMBER12                            pass_ATTRIBUTE_NUMBER12
		,pass.ATTRIBUTE_NUMBER13                            pass_ATTRIBUTE_NUMBER13
		,pass.ATTRIBUTE_NUMBER14                            pass_ATTRIBUTE_NUMBER14
		,pass.ATTRIBUTE_NUMBER15                            pass_ATTRIBUTE_NUMBER15
		,pass.ATTRIBUTE_DATE1 								pass_ATTRIBUTE_DATE1
		,pass.ATTRIBUTE_DATE2                               pass_ATTRIBUTE_DATE2
		,pass.ATTRIBUTE_DATE3                               pass_ATTRIBUTE_DATE3
		,pass.ATTRIBUTE_DATE4                               pass_ATTRIBUTE_DATE4
		,pass.ATTRIBUTE_DATE5                               pass_ATTRIBUTE_DATE5
		,pass.ATTRIBUTE_DATE6                               pass_ATTRIBUTE_DATE6
		,pass.ATTRIBUTE_DATE7                               pass_ATTRIBUTE_DATE7
		,pass.ATTRIBUTE_DATE8                               pass_ATTRIBUTE_DATE8
		,pass.ATTRIBUTE_DATE9                               pass_ATTRIBUTE_DATE9
		,pass.ATTRIBUTE_DATE10                              pass_ATTRIBUTE_DATE10
		,pass.ATTRIBUTE_DATE11                              pass_ATTRIBUTE_DATE11
		,pass.ATTRIBUTE_DATE12                              pass_ATTRIBUTE_DATE12
		,pass.ATTRIBUTE_DATE13                              pass_ATTRIBUTE_DATE13
		,pass.ATTRIBUTE_DATE14                              pass_ATTRIBUTE_DATE14
		,pass.ATTRIBUTE_DATE15                              pass_ATTRIBUTE_DATE15
		,cit.ATTRIBUTE1 								    cit_ATTRIBUTE1
		,cit.ATTRIBUTE2                                     cit_ATTRIBUTE2
		,cit.ATTRIBUTE3                                     cit_ATTRIBUTE3
		,cit.ATTRIBUTE4                                     cit_ATTRIBUTE4
		,cit.ATTRIBUTE5                                     cit_ATTRIBUTE5
		,cit.ATTRIBUTE6                                     cit_ATTRIBUTE6
		,cit.ATTRIBUTE7                                     cit_ATTRIBUTE7
		,cit.ATTRIBUTE8                                     cit_ATTRIBUTE8
		,cit.ATTRIBUTE9                                     cit_ATTRIBUTE9
		,cit.ATTRIBUTE10                                    cit_ATTRIBUTE10
		,cit.ATTRIBUTE11                                    cit_ATTRIBUTE11
		,cit.ATTRIBUTE12                                    cit_ATTRIBUTE12
		,cit.ATTRIBUTE13                                    cit_ATTRIBUTE13
		,cit.ATTRIBUTE14                                    cit_ATTRIBUTE14
		,cit.ATTRIBUTE15                                    cit_ATTRIBUTE15
		,cit.ATTRIBUTE_NUMBER1 							    cit_ATTRIBUTE_NUMBER1
		,cit.ATTRIBUTE_NUMBER2                              cit_ATTRIBUTE_NUMBER2
		,cit.ATTRIBUTE_NUMBER3                              cit_ATTRIBUTE_NUMBER3
		,cit.ATTRIBUTE_NUMBER4                              cit_ATTRIBUTE_NUMBER4
		,cit.ATTRIBUTE_NUMBER5                              cit_ATTRIBUTE_NUMBER5
		,cit.ATTRIBUTE_NUMBER6                              cit_ATTRIBUTE_NUMBER6
		,cit.ATTRIBUTE_NUMBER7                              cit_ATTRIBUTE_NUMBER7
		,cit.ATTRIBUTE_NUMBER8                              cit_ATTRIBUTE_NUMBER8
		,cit.ATTRIBUTE_NUMBER9                              cit_ATTRIBUTE_NUMBER9
		,cit.ATTRIBUTE_NUMBER10                             cit_ATTRIBUTE_NUMBER10
		,cit.ATTRIBUTE_NUMBER11                             cit_ATTRIBUTE_NUMBER11
		,cit.ATTRIBUTE_NUMBER12                             cit_ATTRIBUTE_NUMBER12
		,cit.ATTRIBUTE_NUMBER13                             cit_ATTRIBUTE_NUMBER13
		,cit.ATTRIBUTE_NUMBER14                             cit_ATTRIBUTE_NUMBER14
		,cit.ATTRIBUTE_NUMBER15                             cit_ATTRIBUTE_NUMBER15
		,cit.ATTRIBUTE_DATE1 							    cit_ATTRIBUTE_DATE1
		,cit.ATTRIBUTE_DATE2                                cit_ATTRIBUTE_DATE2
		,cit.ATTRIBUTE_DATE3                                cit_ATTRIBUTE_DATE3
		,cit.ATTRIBUTE_DATE4                                cit_ATTRIBUTE_DATE4
		,cit.ATTRIBUTE_DATE5                                cit_ATTRIBUTE_DATE5
		,cit.ATTRIBUTE_DATE6                                cit_ATTRIBUTE_DATE6
		,cit.ATTRIBUTE_DATE7                                cit_ATTRIBUTE_DATE7
		,cit.ATTRIBUTE_DATE8                                cit_ATTRIBUTE_DATE8
		,cit.ATTRIBUTE_DATE9                                cit_ATTRIBUTE_DATE9
		,cit.ATTRIBUTE_DATE10                               cit_ATTRIBUTE_DATE10
		,cit.ATTRIBUTE_DATE11                               cit_ATTRIBUTE_DATE11
		,cit.ATTRIBUTE_DATE12                               cit_ATTRIBUTE_DATE12
		,cit.ATTRIBUTE_DATE13                               cit_ATTRIBUTE_DATE13
		,cit.ATTRIBUTE_DATE14                               cit_ATTRIBUTE_DATE14
		,cit.ATTRIBUTE_DATE15                               cit_ATTRIBUTE_DATE15
		,pld.PER_INFORMATION1								pld_PER_INFORMATION1
		,pld.PER_INFORMATION2								pld_PER_INFORMATION2
		,pld.PER_INFORMATION3								pld_PER_INFORMATION3
		,pld.PER_INFORMATION4								pld_PER_INFORMATION4
		,pld.PER_INFORMATION5								pld_PER_INFORMATION5
		,pld.PER_INFORMATION6								pld_PER_INFORMATION6
		,pld.PER_INFORMATION7								pld_PER_INFORMATION7
		,pld.PER_INFORMATION8								pld_PER_INFORMATION8
		,pld.PER_INFORMATION9								pld_PER_INFORMATION9
		,pld.PER_INFORMATION10								pld_PER_INFORMATION10
		,pld.PER_INFORMATION11								pld_PER_INFORMATION11
		,pld.PER_INFORMATION12								pld_PER_INFORMATION12
		,pld.PER_INFORMATION13								pld_PER_INFORMATION13
		,pld.PER_INFORMATION14								pld_PER_INFORMATION14
		,pld.PER_INFORMATION15								pld_PER_INFORMATION15
		,pld.ATTRIBUTE1 									pld_ATTRIBUTE1
		,pld.ATTRIBUTE2                                     pld_ATTRIBUTE2
		,pld.ATTRIBUTE3                                     pld_ATTRIBUTE3
		,pld.ATTRIBUTE4                                     pld_ATTRIBUTE4
		,pld.ATTRIBUTE5                                     pld_ATTRIBUTE5
		,pld.ATTRIBUTE6                                     pld_ATTRIBUTE6
		,pld.ATTRIBUTE7                                     pld_ATTRIBUTE7
		,pld.ATTRIBUTE8                                     pld_ATTRIBUTE8
		,pld.ATTRIBUTE9                                     pld_ATTRIBUTE9
		,pld.ATTRIBUTE10                                    pld_ATTRIBUTE10
		,pld.ATTRIBUTE11                                    pld_ATTRIBUTE11
		,pld.ATTRIBUTE12                                    pld_ATTRIBUTE12
		,pld.ATTRIBUTE13                                    pld_ATTRIBUTE13
		,pld.ATTRIBUTE14                                    pld_ATTRIBUTE14
		,pld.ATTRIBUTE15                                    pld_ATTRIBUTE15
		,pld.PER_INFORMATION_NUMBER1 						pld_PER_INFORMATION_NUMBER1
		,pld.PER_INFORMATION_NUMBER2                        pld_PER_INFORMATION_NUMBER2
		,pld.PER_INFORMATION_NUMBER3                        pld_PER_INFORMATION_NUMBER3
		,pld.PER_INFORMATION_NUMBER4                        pld_PER_INFORMATION_NUMBER4
		,pld.PER_INFORMATION_NUMBER5                        pld_PER_INFORMATION_NUMBER5
		,pld.PER_INFORMATION_NUMBER6                        pld_PER_INFORMATION_NUMBER6
		,pld.PER_INFORMATION_NUMBER7                        pld_PER_INFORMATION_NUMBER7
		,pld.PER_INFORMATION_NUMBER8                        pld_PER_INFORMATION_NUMBER8
		,pld.PER_INFORMATION_NUMBER9                        pld_PER_INFORMATION_NUMBER9
		,pld.PER_INFORMATION_NUMBER10                       pld_PER_INFORMATION_NUMBER10
		,pld.PER_INFORMATION_NUMBER11                       pld_PER_INFORMATION_NUMBER11
		,pld.PER_INFORMATION_NUMBER12                       pld_PER_INFORMATION_NUMBER12
		,pld.PER_INFORMATION_NUMBER13                       pld_PER_INFORMATION_NUMBER13
		,pld.PER_INFORMATION_NUMBER14                       pld_PER_INFORMATION_NUMBER14
		,pld.PER_INFORMATION_NUMBER15                       pld_PER_INFORMATION_NUMBER15
		,TO_CHAR(pld.PER_INFORMATION_DATE1,'RRRR/MM/DD')	pld_PER_INFORMATION_DATE1
		,TO_CHAR(pld.PER_INFORMATION_DATE2,'RRRR/MM/DD')	pld_PER_INFORMATION_DATE2
		,TO_CHAR(pld.PER_INFORMATION_DATE3,'RRRR/MM/DD')	pld_PER_INFORMATION_DATE3
		,TO_CHAR(pld.PER_INFORMATION_DATE4,'RRRR/MM/DD') 	pld_PER_INFORMATION_DATE4
		,TO_CHAR(pld.PER_INFORMATION_DATE5,'RRRR/MM/DD')    pld_PER_INFORMATION_DATE5
		,TO_CHAR(pld.PER_INFORMATION_DATE6,'RRRR/MM/DD')    pld_PER_INFORMATION_DATE6
		,TO_CHAR(pld.PER_INFORMATION_DATE7,'RRRR/MM/DD')    pld_PER_INFORMATION_DATE7
		,TO_CHAR(pld.PER_INFORMATION_DATE8,'RRRR/MM/DD')    pld_PER_INFORMATION_DATE8
		,TO_CHAR(pld.PER_INFORMATION_DATE9,'RRRR/MM/DD')    pld_PER_INFORMATION_DATE9
		,TO_CHAR(pld.PER_INFORMATION_DATE10,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE10
		,TO_CHAR(pld.PER_INFORMATION_DATE11,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE11
		,TO_CHAR(pld.PER_INFORMATION_DATE12,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE12
		,TO_CHAR(pld.PER_INFORMATION_DATE13,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE13
		,TO_CHAR(pld.PER_INFORMATION_DATE14,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE14
		,TO_CHAR(pld.PER_INFORMATION_DATE15,'RRRR/MM/DD')   pld_PER_INFORMATION_DATE15
		,pld.ATTRIBUTE_NUMBER1 								pld_ATTRIBUTE_NUMBER1
		,pld.ATTRIBUTE_NUMBER2                              pld_ATTRIBUTE_NUMBER2
		,pld.ATTRIBUTE_NUMBER3                              pld_ATTRIBUTE_NUMBER3
		,pld.ATTRIBUTE_NUMBER4                              pld_ATTRIBUTE_NUMBER4
		,pld.ATTRIBUTE_NUMBER5                              pld_ATTRIBUTE_NUMBER5
		,pld.ATTRIBUTE_NUMBER6                              pld_ATTRIBUTE_NUMBER6
		,pld.ATTRIBUTE_NUMBER7                              pld_ATTRIBUTE_NUMBER7
		,pld.ATTRIBUTE_NUMBER8                              pld_ATTRIBUTE_NUMBER8
		,pld.ATTRIBUTE_NUMBER9                              pld_ATTRIBUTE_NUMBER9
		,pld.ATTRIBUTE_NUMBER10                             pld_ATTRIBUTE_NUMBER10
		,pld.ATTRIBUTE_NUMBER11                             pld_ATTRIBUTE_NUMBER11
		,pld.ATTRIBUTE_NUMBER12                             pld_ATTRIBUTE_NUMBER12
		,pld.ATTRIBUTE_NUMBER13                             pld_ATTRIBUTE_NUMBER13
		,pld.ATTRIBUTE_NUMBER14                             pld_ATTRIBUTE_NUMBER14
		,pld.ATTRIBUTE_NUMBER15                             pld_ATTRIBUTE_NUMBER15
		,pld.ATTRIBUTE_DATE1 								pld_ATTRIBUTE_DATE1
		,pld.ATTRIBUTE_DATE2                                pld_ATTRIBUTE_DATE2
		,pld.ATTRIBUTE_DATE3                                pld_ATTRIBUTE_DATE3
		,pld.ATTRIBUTE_DATE4                                pld_ATTRIBUTE_DATE4
		,pld.ATTRIBUTE_DATE5                                pld_ATTRIBUTE_DATE5
		,pld.ATTRIBUTE_DATE6                                pld_ATTRIBUTE_DATE6
		,pld.ATTRIBUTE_DATE7                                pld_ATTRIBUTE_DATE7
		,pld.ATTRIBUTE_DATE8                                pld_ATTRIBUTE_DATE8
		,pld.ATTRIBUTE_DATE9                                pld_ATTRIBUTE_DATE9
		,pld.ATTRIBUTE_DATE10                               pld_ATTRIBUTE_DATE10
		,pld.ATTRIBUTE_DATE11                               pld_ATTRIBUTE_DATE11
		,pld.ATTRIBUTE_DATE12                               pld_ATTRIBUTE_DATE12
		,pld.ATTRIBUTE_DATE13                               pld_ATTRIBUTE_DATE13
		,pld.ATTRIBUTE_DATE14                               pld_ATTRIBUTE_DATE14
		,pld.ATTRIBUTE_DATE15                               pld_ATTRIBUTE_DATE15
		,Rel.ATTRIBUTE1 									Rel_ATTRIBUTE1
		,Rel.ATTRIBUTE2                                     Rel_ATTRIBUTE2
		,Rel.ATTRIBUTE3                                     Rel_ATTRIBUTE3
		,Rel.ATTRIBUTE4                                     Rel_ATTRIBUTE4
		,Rel.ATTRIBUTE5                                     Rel_ATTRIBUTE5
		,Rel.ATTRIBUTE6                                     Rel_ATTRIBUTE6
		,Rel.ATTRIBUTE7                                     Rel_ATTRIBUTE7
		,Rel.ATTRIBUTE8                                     Rel_ATTRIBUTE8
		,Rel.ATTRIBUTE9                                     Rel_ATTRIBUTE9
		,Rel.ATTRIBUTE10                                    Rel_ATTRIBUTE10
		,Rel.ATTRIBUTE11                                    Rel_ATTRIBUTE11
		,Rel.ATTRIBUTE12                                    Rel_ATTRIBUTE12
		,Rel.ATTRIBUTE13                                    Rel_ATTRIBUTE13
		,Rel.ATTRIBUTE14                                    Rel_ATTRIBUTE14
		,Rel.ATTRIBUTE15                                    Rel_ATTRIBUTE15
       FROM  xxmx_per_people_f_xfm      pps
           , xxmx_per_persons_xfm       pp
           , xxmx_per_names_f_xfm       pns
           --, xxmx_per_address_f_xfm     paf
           , xxmx_per_email_f_xfm       pemail
           , xxmx_per_phones_xfm        phone
           , xxmx_per_ethnicities_xfm   pe
           , xxmx_per_nid_f_xfm         nid
           , xxmx_per_passport_xfm      pass
           , xxmx_citizenships_xfm      cit
           , xxmx_per_leg_f_xfm         pld
           , XXMX_PER_RELIGION_XFM      Rel
       WHERE pp.person_id = pps.person_id
         AND pp.BG_name = pps.BG_name
         AND pps.migration_set_id = pp.migration_set_id
         AND pp.person_id        = pns.person_id(+)
         --AND pp.person_id        = paf.person_id(+)
         AND pp.person_id        = pemail.person_id(+)
         AND pp.person_id        = phone.person_id(+)
         AND pp.person_id        = pe.person_id(+)
         AND pp.person_id        = nid.person_id(+)
         AND pp.person_id        = pass.personid(+)
         AND pp.person_id        = cit.person_id(+)
         AND pp.person_id        = pld.person_id(+)
         AND pp.person_id        = rel.personid(+)
         AND pp.date_of_birth    IS NOT NULL
--         AND NVL(paf.primary_flag,'Y')    = 'Y'
         AND NVL(pemail.primary_flag,'Y') = 'Y'
         AND NVL(phone.primary_flag,'Y')  = 'Y'
         AND NVL(pe.PRIMARY_FLAG,'Y')     = 'Y'
         AND NVL(nid.PRIMARY_FLAG,'Y')    = 'Y'
		 AND pps.BG_name IN(select substr(position_code,1,6) from xx_position_map_temp)
 ORDER BY pp.person_id
;
