--------------------------------------------------------
--  Constraints for Table XXMX_DATA_FILE_PROPERTIES
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" MODIFY ("XFM_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" MODIFY ("GENERATION_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" MODIFY ("DATA_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" MODIFY ("DATA_FILE_EXTENSION" NOT NULL ENABLE);
