--------------------------------------------------------
--  DDL for Table XXMX_CONTRACT_REG_SCOPE_020523
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CONTRACT_REG_SCOPE_020523" 
   (	"EBS_REFERENCE_1" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
