--------------------------------------------------------
--  DDL for Table XXMX_SAAS_PARTY_SITES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_SAAS_PARTY_SITES" 
   (	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"SEGMENT1" NUMBER, 
	"PARTY_NUMBER" NUMBER, 
	"PARTY_SITE_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(240 BYTE), 
	"PARTY_SITE_NUMBER" NUMBER, 
	"BUSINESS_UNIT" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
