--------------------------------------------------------
--  Constraints for Table XXMX_GL_CODE_COMBINATIONS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("CODE_COMBINATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("CHART_OF_ACCOUNTS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("DETAIL_POSTING_ALLOWED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("DETAIL_BUDGETING_ALLOWED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("ENABLED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_CODE_COMBINATIONS" MODIFY ("SUMMARY_FLAG" NOT NULL ENABLE);
