--------------------------------------------------------
--  DDL for Table XXMX_TASKS_FLAG_XFM_DEV1
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" 
   (	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"PROJECT_TASK_NUMBER" VARCHAR2(25 BYTE), 
	"CREATE_UPDATE" CHAR(6 BYTE), 
	"PROJECT_CHARGEABLE_FLAG" VARCHAR2(3 BYTE), 
	"PROJECT_BILLABLE_FLAG" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT ALTER ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT DELETE ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT INDEX ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT INSERT ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT READ ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_DEV1" TO "XXMX_READONLY";
