--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_XFM_24NOV23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_24NOV23" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_24NOV23" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_24NOV23" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_24NOV23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
