--------------------------------------------------------
--  DDL for Table XXMX_PA_EXPENDITURE_COMMENTS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" 
   (	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"LINE_NUMBER" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 BYTE), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"PROGRAM_ID" NUMBER(15,0), 
	"PROGRAM_APPLICATION_ID" NUMBER(15,0), 
	"PROGRAM_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
