--------------------------------------------------------
--  DDL for Table XXMX_EMP_PHONES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_EMP_PHONES" 
   (	"PERSON_NUMBER" VARCHAR2(50 BYTE), 
	"PHONE_NUM" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
