--------------------------------------------------------
--  DDL for Table XXMX_HCM_GEO_MAP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_GEO_MAP" 
   (	"COUNTRY" VARCHAR2(1000 BYTE), 
	"COUNTRY_CODE" VARCHAR2(100 BYTE), 
	"COUNTRY_CODE_N" VARCHAR2(100 BYTE), 
	"AREA_CODE" VARCHAR2(100 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
