--------------------------------------------------------
--  DDL for Table XXMX_DM_STG_XFM_HEADER
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DM_STG_XFM_HEADER" 
   (	"TABLE_NAME" VARCHAR2(50 BYTE), 
	"HEADER_TEXT" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_DM_STG_XFM_HEADER" TO "XXMX_READONLY";
