--------------------------------------------------------
--  Constraints for Table XXMX_SUPPLIER_CONTACTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("CONTACT_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("CONTACT_POINT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("OWNER_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("OWNER_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("CONTENT_SOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_CONTACTS" MODIFY ("ACTUAL_CONTENT_SOURCE" NOT NULL ENABLE);
