--------------------------------------------------------
--  Constraints for Table XXMX_GL_SOURCE_STRUCTURES
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCTURES" MODIFY ("SOURCE_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCTURES" MODIFY ("SOURCE_SEGMENT_DELIMITER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCTURES" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
