--------------------------------------------------------
--  DDL for Table XXMX_MIGRATION_HEADERS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MIGRATION_HEADERS" 
   (	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"BUSINESS_ENTITY_SEQ" NUMBER(3,0), 
	"BUSINESS_ENTITY" VARCHAR2(100 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_MIGRATION_HEADERS" TO "XXMX_READONLY";
