--------------------------------------------------------
--  Constraints for Table XXMX_HZ_CONTACT_POINTS_310723_BKP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("CONTACT_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("CONTACT_POINT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("OWNER_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("OWNER_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("CONTENT_SOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_310723_BKP" MODIFY ("ACTUAL_CONTENT_SOURCE" NOT NULL ENABLE);
