--------------------------------------------------------
--  Constraints for Table XXMX_PA_DRAFT_REVENUES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("DRAFT_REVENUE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("AGREEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("TRANSFER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("GENERATION_ERROR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUES_ALL" MODIFY ("PA_DATE" NOT NULL ENABLE);
