--------------------------------------------------------
--  Constraints for Table XXMX_ENTITY_VALIDATION_ERRORS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("ENTITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("SUB_ENTITY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("KEY_VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("COLUMN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ENTITY_VALIDATION_ERRORS" MODIFY ("ERROR_MESSAGE" NOT NULL ENABLE);
