--------------------------------------------------------
--  DDL for Table XXMX_HCM_RELIGION_DFF
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_RELIGION_DFF" 
   (	"DESCRIPTIVE_FLEX_CONTEXT_CODE" VARCHAR2(30 BYTE), 
	"APPLICATION_COLUMN_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
