--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_PHONE_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_STG_24OCT23" MODIFY ("DATEFROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_STG_24OCT23" MODIFY ("PHONETYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_STG_24OCT23" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_STG_24OCT23" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_STG_24OCT23" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
