--------------------------------------------------------
--  Constraints for Table XXMX_FND_LOOKUP_VALUES
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("LOOKUP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("LOOKUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("MEANING" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("ENABLED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("SOURCE_LANG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("SECURITY_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FND_LOOKUP_VALUES" MODIFY ("VIEW_APPLICATION_ID" NOT NULL ENABLE);
