--------------------------------------------------------
--  DDL for Table XXMX_PPM_DUP_PROJECT_NAMES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" 
   (	"NUMBER_OF_RECS" NUMBER, 
	"PROJECT_NAME" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT ALTER ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT DELETE ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT INDEX ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT INSERT ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT READ ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_PPM_DUP_PROJECT_NAMES" TO "XXMX_READONLY";
