--------------------------------------------------------
--  DDL for Table XXMX_AR_RECEIPTS_REF_DATA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_AR_RECEIPTS_REF_DATA" 
   (	"COUNT_" VARCHAR2(100 BYTE), 
	"LOAD_REQUEST_ID" VARCHAR2(100 BYTE), 
	"ORG_ID" VARCHAR2(100 BYTE), 
	"BATCH_NAME" VARCHAR2(100 BYTE), 
	"LOCKBOX_NUMBER" VARCHAR2(100 BYTE), 
	"LOCKBOX_ID" VARCHAR2(100 BYTE), 
	"TRANSMISSION_FORMAT_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
