--------------------------------------------------------
--  Constraints for Table XXMX_GL_SEGMENT_1_TO_1_MAPS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_SEGMENT_1_TO_1_MAPS" MODIFY ("SOURCE_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SEGMENT_1_TO_1_MAPS" MODIFY ("SOURCE_SEGMENT_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SEGMENT_1_TO_1_MAPS" MODIFY ("FUSION_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SEGMENT_1_TO_1_MAPS" MODIFY ("FUSION_SEGMENT_COLUMN" NOT NULL ENABLE);
