--------------------------------------------------------
--  DDL for Table XXMX_PER_SAL_HIST_WORKER_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PER_SAL_HIST_WORKER_STG" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(50 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(20 BYTE), 
	"PERSON_NUMBER" VARCHAR2(20 BYTE), 
	"PERSON_START_DATE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(30 BYTE), 
	"ORIGINAL_DATE_OF_HIRE" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(10 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"MARITAL_STATUS" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(2 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(120 BYTE), 
	"LOCATION_CODE" VARCHAR2(20 BYTE), 
	"POSITION_CODE" VARCHAR2(50 BYTE), 
	"TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"EMPLOYEE_STATUS" VARCHAR2(10 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(50 BYTE), 
	"RECORD_TYPE" VARCHAR2(100 BYTE), 
	"ASSIGNMENT_STATUS_TYPE_ID" VARCHAR2(100 BYTE), 
	"DEFAULT_EXPENSE_ACCOUNT" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"NORMAL_HOURS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
