--------------------------------------------------------
--  Constraints for Table XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("VENDOR_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIER_SITES_ALL_TEMP_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
