--------------------------------------------------------
--  DDL for Table XXMX_GL_SOURCE_STRUCTURES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCTURES" 
   (	"SOURCE_LEDGER_NAME" VARCHAR2(30 BYTE), 
	"SOURCE_SEGMENT_DELIMITER" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"GL_BAL_FUSION_JRNL_SOURCE" VARCHAR2(25 BYTE), 
	"GL_BAL_FUSION_JRNL_CATEGORY" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_GL_SOURCE_STRUCTURES" TO "XXMX_READONLY";
