--------------------------------------------------------
--  DDL for Index XXMX_FA_DEPRN_METHODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_FA_DEPRN_METHODS_PK" ON "XXMX_CORE"."XXMX_FA_DEPRN_METHODS" ("METHOD_CODE", "LIFE_IN_MONTHS", "RATE_SOURCE_RULE", "DEPRN_BASIS_RULE", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
