--------------------------------------------------------
--  DDL for Table XXMX_XFM_TABLES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_XFM_TABLES" 
   (	"XFM_TABLE_ID" NUMBER, 
	"METADATA_ID" NUMBER, 
	"SCHEMA_NAME" VARCHAR2(128 BYTE), 
	"TABLE_NAME" VARCHAR2(128 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"SEQUENCE_NAME" VARCHAR2(30 BYTE), 
	"GENERATE_SEQUENCE" VARCHAR2(1 BYTE), 
	"SEQUENCE_START_VALUE" NUMBER, 
	"FUSION_TEMPLATE_NAME" VARCHAR2(100 BYTE), 
	"FUSION_TEMPLATE_SHEET_NAME" VARCHAR2(100 BYTE), 
	"FUSION_TEMPLATE_SHEET_ORDER" NUMBER, 
	"FIELD_DELIMITER" VARCHAR2(1 BYTE), 
	"INCLUDE_COLUMN_HEADING" VARCHAR2(1 BYTE), 
	"INCLUDE_COLUMN_HEADING_BY_ROW" VARCHAR2(1 BYTE), 
	"PURGE_FLAG" VARCHAR2(1 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT READ ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT SELECT ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT INSERT ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT INDEX ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT DELETE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT ALTER ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_STG";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT READ ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT SELECT ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT INSERT ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT INDEX ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT DELETE ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
  GRANT ALTER ON "XXMX_CORE"."XXMX_XFM_TABLES" TO "XXMX_XFM";
