--------------------------------------------------------
--  Constraints for Table XXMX_PPM_TEMPLATE_TASK_FLAGS24
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS24" MODIFY ("PROJECT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS24" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS24" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
