--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
