--------------------------------------------------------
--  DDL for Table XXMX_GL_ACCT_SEG_TRANSFORMS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" 
   (	"DATA_SOURCE" VARCHAR2(10 BYTE), 
	"SOURCE_LEDGER_NAME" VARCHAR2(30 BYTE), 
	"SOURCE_SEGMENT_NAME" VARCHAR2(30 BYTE), 
	"SOURCE_SEGMENT_COLUMN" VARCHAR2(30 BYTE), 
	"SOURCE_SEGMENT_VALUE" VARCHAR2(25 BYTE), 
	"SOURCE_SEGMENT_VALUE_ENABLED" VARCHAR2(1 BYTE), 
	"FUSION_SEGMENT_VALUE" VARCHAR2(25 BYTE), 
	"FROZEN_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" TO "XXMX_READONLY";
