--------------------------------------------------------
--  DDL for Table XXMX_DATA_FILE_PROPERTIES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" 
   (	"XFM_TABLE_ID" NUMBER, 
	"XFM_DATA_KEY_COLUMN" VARCHAR2(128 BYTE), 
	"XFM_DATA_KEY_VALUE" VARCHAR2(2000 BYTE), 
	"GENERATION_SEQUENCE" NUMBER, 
	"FILE_GROUP_NUMBER" NUMBER(3,0), 
	"DATA_FILE_NAME" VARCHAR2(1000 BYTE), 
	"DATA_FILE_EXTENSION" VARCHAR2(3 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" TO "XXMX_READONLY";
