--------------------------------------------------------
--  DDL for Table XXMX_CARRY_OVER_TEMP_PREDRYRUN
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CARRY_OVER_TEMP_PREDRYRUN" 
   (	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"PLANNAME" VARCHAR2(100 BYTE), 
	"VALUE" NUMBER, 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UDPATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
