--------------------------------------------------------
--  DDL for Materialized View XXMX_HCM_EXPERSON_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXMX_CORE"."XXMX_HCM_EXPERSON_MV" ("EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "ACTUAL_TERMINATION_DATE", "PERSON_ID", "BUSINESS_GROUP_ID", "SYSTEM_PERSON_TYPE", "USER_PERSON_TYPE", "CURRENT_OR_LEAVER", "EMAIL_ADDRESS", "EMPLOYEE_NUMBER", "ORIGINAL_DATE_OF_HIRE", "REHIRE_REASON", "REHIRE_AUTHORIZOR", "START_DATE", "PARTY_ID", "CORRESPONDENCE_LANGUAGE", "BLOOD_TYPE", "DATE_OF_BIRTH", "DATE_OF_DEATH", "COUNTRY_OF_BIRTH", "REGION_OF_BIRTH", "TOWN_OF_BIRTH", "PERSON_ID_CONTACT", "NAME_TYPE", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAMES", "FULL_NAME", "TITLE", "PRE_NAME_ADJUNCT", "SUFFIX", "KNOWN_AS", "HONORS", "PREVIOUS_LAST_NAME", "CURRENT_EMPLOYEE_FLAG", "APPLICANT_NUMBER", "PERSON_TYPE_ID", "NATIONAL_IDENTIFIER", "NATIONALITY", "PER_INFORMATION_CATEGORY", "INTERNAL_LOCATION", "PROJECTED_START_DATE", "EXPENSE_CHECK_SEND_TO_ADDRESS", "NPW_NUMBER", "PER_INFORMATION1", "PER_INFORMATION2", "PER_INFORMATION3", "PER_INFORMATION4", "PER_INFORMATION5", "PER_INFORMATION6", "PER_INFORMATION7", "PER_INFORMATION8", "PER_INFORMATION9", "PER_INFORMATION10", "PER_INFORMATION11", "PER_INFORMATION12", "PER_INFORMATION13", "PER_INFORMATION14", "PER_INFORMATION15", "PER_INFORMATION16", "PER_INFORMATION17", "PER_INFORMATION18", "PER_INFORMATION19", "PER_INFORMATION20", "PER_INFORMATION21", "PER_INFORMATION22", "PER_INFORMATION23", "PER_INFORMATION24", "PER_INFORMATION25", "PER_INFORMATION26", "PER_INFORMATION27", "PER_INFORMATION28", "PER_INFORMATION29", "PER_INFORMATION30", "SEX", "MARITAL_STATUS", "REHIRE_RECOMMENDATION", "ON_MILITARY_SERVICE", "FAST_PATH_EMPLOYEE", "DATE_EMPLOYEE_DATA_VERIFIED", "ATTRIBUTE8")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT * FROM XXMX_HCM_EXWORKERS_SCOPE;

   COMMENT ON MATERIALIZED VIEW "XXMX_CORE"."XXMX_HCM_EXPERSON_MV"  IS 'snapshot table for snapshot XXMX_CORE.XXMX_HCM_EXPERSON_MV';
