--------------------------------------------------------
--  Constraints for Table XXMX_PA_EXPENDITURE_COMMENTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("EXPENDITURE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURE_COMMENTS" MODIFY ("EXPENDITURE_COMMENT" NOT NULL ENABLE);
