--------------------------------------------------------
--  DDL for Table XXMX_PO_VALIDATION_BKP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PO_VALIDATION_BKP" 
   (	"VALIDATION_TYPE" VARCHAR2(200 BYTE), 
	"VALIDATION_VALUE" VARCHAR2(360 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
