--------------------------------------------------------
--  Constraints for Table XXMX_PER_IMAGES_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_IMAGES_STG_24OCT23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_IMAGES_STG_24OCT23" MODIFY ("IMAGENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_IMAGES_STG_24OCT23" MODIFY ("IMAGE_REF" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_IMAGES_STG_24OCT23" MODIFY ("IMAGETYPE" NOT NULL ENABLE);
