--------------------------------------------------------
--  DDL for Table XXMX_CARRY_OVER_XFM_UATBKUP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CARRY_OVER_XFM_UATBKUP" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"PERSONACCRUALDETAIL" VARCHAR2(30 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"WORKTERMSNUMBER" VARCHAR2(50 BYTE), 
	"PLANNAME" VARCHAR2(100 BYTE), 
	"ACCRUALTYPE" VARCHAR2(30 BYTE), 
	"PROCDDATE" DATE, 
	"VALUE" NUMBER, 
	"ADJUSTMENTREASON" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"PERSON_ID" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
