--------------------------------------------------------
--  DDL for Table XXMX_HCM_LE_DEPT_NAME
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_LE_DEPT_NAME" 
   (	"BU_NAME" VARCHAR2(200 BYTE), 
	"ORG_ID" NUMBER, 
	"ORG_CLASSIFICATION_ID" NUMBER, 
	"STATUS" VARCHAR2(100 BYTE), 
	"CLASSIFICATION_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
