--------------------------------------------------------
--  DDL for Sequence XXMX_MIGRATION_PARAMETER_IDS_S
--------------------------------------------------------

   CREATE SEQUENCE  "XXMX_CORE"."XXMX_MIGRATION_PARAMETER_IDS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1368 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
