--------------------------------------------------------
--  Constraints for Table XXMX_PRJ_UNBILLED_EVENTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
