--------------------------------------------------------
--  Constraints for Table XXMX_HCM_EXPERSON_ASG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("ASSIGNMENT_STATUS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("ASSIGNMENT_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("ASSIGNMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("PRIMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("PERSON_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("SYSTEM_PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("USER_PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG" MODIFY ("PPOS_ID" NOT NULL ENABLE);
