--------------------------------------------------------
--  Constraints for Table XXMX_QUANTITY_TOLERANCE
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_QUANTITY_TOLERANCE" MODIFY ("TOLERANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_QUANTITY_TOLERANCE" ADD CONSTRAINT "XXMX_QUANTITY_TOLERANCE_PK" PRIMARY KEY ("TOLERANCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
