--------------------------------------------------------
--  DDL for Table XXMX_PPM_CONT_PROJ_ASSOCIATES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CONT_PROJ_ASSOCIATES" 
   (	"ACTION_CODE" VARCHAR2(250 BYTE), 
	"EXT_SOURCE" VARCHAR2(250 BYTE), 
	"EXT_KEY" VARCHAR2(250 BYTE), 
	"LINE_EXT_SOURCE" VARCHAR2(250 BYTE), 
	"LINE_EXT_KEY" VARCHAR2(250 BYTE), 
	"PROJECT_ID" VARCHAR2(250 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(250 BYTE), 
	"TASK_ID" VARCHAR2(250 BYTE), 
	"TASK_NUMBER" VARCHAR2(250 BYTE), 
	"FUNDED_AMOUNT" VARCHAR2(250 BYTE), 
	"PERCENT_COMPLETE" VARCHAR2(250 BYTE), 
	"ACTIVE_FLAG" VARCHAR2(250 BYTE), 
	"BATCH_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
