--------------------------------------------------------
--  Constraints for Table XXMX_PA_EXP_ITEMS_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("EXPENDITURE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("EXPENDITURE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("EXPENDITURE_ITEM_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("EXPENDITURE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("COST_DISTRIBUTED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("REVENUE_DISTRIBUTED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("BILLABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("BILL_HOLD_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("SYSTEM_LINKAGE_FUNCTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("CC_CROSS_CHARGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("CC_BL_DISTRIBUTED_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_ITEMS_ALL" MODIFY ("CC_IC_PROCESSED_CODE" NOT NULL ENABLE);
