--------------------------------------------------------
--  DDL for Table XXMX_UPDATE_EVENT_TYPE_BKUP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_UPDATE_EVENT_TYPE_BKUP" 
   (	"EVENT_ID" VARCHAR2(240 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(240 BYTE), 
	"SOURCEREF" VARCHAR2(240 BYTE), 
	"ERROR_STATUS" VARCHAR2(240 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
