--------------------------------------------------------
--  DDL for Table XXMX_HCM_DATAFILE_XFM_MAP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_DATAFILE_XFM_MAP" 
   (	"DATAFILE_ID" NUMBER, 
	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"BUSINESS_ENTITY" VARCHAR2(100 BYTE), 
	"SUB_ENTITY" VARCHAR2(100 BYTE), 
	"DATA_FILE_NAME" VARCHAR2(100 BYTE), 
	"FUSION_DATA_FILE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_HCM_DATAFILE_XFM_MAP" TO "XXMX_READONLY";
