--------------------------------------------------------
--  DDL for Table XXMX_DM_FUSION_PREVAL_DATA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DM_FUSION_PREVAL_DATA" 
   (	"ITERATION" VARCHAR2(100 BYTE), 
	"LOAD_NAME" VARCHAR2(100 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"PARAMETER" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
