--------------------------------------------------------
--  DDL for Table XXMX_PPM_CLOUD_CONT_BILLPLANS_STS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CLOUD_CONT_BILLPLANS_STS" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"XFACE_REC_ID" NUMBER(18,0), 
	"CONTRACT_NUMBER" VARCHAR2(120 BYTE), 
	"CONTRACT_TYPE" VARCHAR2(150 BYTE), 
	"PLAN_NAME" VARCHAR2(30 BYTE), 
	"PLAN_TYPE" VARCHAR2(30 BYTE), 
	"CONTRACT_LINE_NUMBER" VARCHAR2(150 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"PERSON_NAME" VARCHAR2(240 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"PERSON_EMAIL" VARCHAR2(240 BYTE), 
	"JOB_CODE" VARCHAR2(30 BYTE), 
	"EXPENDITURE_TYPE_NAME" VARCHAR2(240 BYTE), 
	"RATE" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"RATE_OVERRIDE_REASON" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(300 BYTE), 
	"BATCH_ID" NUMBER, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"LOAD_STATUS" VARCHAR2(10 BYTE), 
	"IMPORT_STATUS" VARCHAR2(10 BYTE), 
	"DISCOUNT_PERCENTAGE" NUMBER, 
	"MARKUP_PERCENTAGE" VARCHAR2(30 BYTE), 
	"OVERRIDE_TYPE" VARCHAR2(17 BYTE), 
	"CONTRACT_ID" NUMBER, 
	"ID" NUMBER, 
	"CONT_MAJOR_VERSION" NUMBER, 
	"BILL_PLAN_ID" NUMBER, 
	"BP_MAJOR_VERSION" NUMBER, 
	"ERROR_STATUS" VARCHAR2(30 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
