--------------------------------------------------------
--  DDL for Index XXMX_STG_TABLES_U4
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_STG_TABLES_U4" ON "XXMX_CORE"."XXMX_STG_TABLES" ("STG_TABLE_ID", "TABLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
