--------------------------------------------------------
--  DDL for Table XXMX_CLOSED_AR_EXP_ITEMS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOSED_AR_EXP_ITEMS" 
   (	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"AR_INVOICE_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
