--------------------------------------------------------
--  DDL for Table XXMX_TF_EXCLUDE_TASKS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_TF_EXCLUDE_TASKS" 
   (	"PARENT_TASK" VARCHAR2(240 BYTE), 
	"TASK_NUMBER" VARCHAR2(240 BYTE), 
	"TASKNAME_TASKNUMBER" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
