--------------------------------------------------------
--  DDL for Table XXMX_TEST_SRC
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_TEST_SRC" 
   (	"SOURCE_OPERATING_UNIT_NAME" VARCHAR2(240 BYTE), 
	"FUSION_BUSINESS_UNIT_NAME" VARCHAR2(240 BYTE), 
	"FUSION_BUSINESS_UNIT_ID" NUMBER, 
	"AP_INV_FUSION_CLEARING_ACCT" VARCHAR2(2000 BYTE), 
	"AR_TRX_FUSION_CLEARING_ACCT" VARCHAR2(2000 BYTE), 
	"LOCKBOX_NUMBER" VARCHAR2(30 BYTE), 
	"LOCKBOX_ID" NUMBER, 
	"LOCKBOX_TRANSMISSION_FMT_NAME" VARCHAR2(100 BYTE), 
	"LOCKBOX_TRANSMISSION_FMT_ID" NUMBER, 
	"MIGRATION_ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"LOCKBOX_RECEIPT_METHOD" VARCHAR2(30 BYTE), 
	"SOURCE_ORG_ID" NUMBER, 
	"CUST_MIGRATION_ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"PPM_MIGRATION_ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"FIN_MIGRATION_ENABLED_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
