--------------------------------------------------------
--  DDL for Table XXMX_STG_TABLE_COLUMNS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" 
   (	"STG_TABLE_ID" NUMBER, 
	"STG_TABLE_COLUMN_ID" NUMBER, 
	"STG_COLUMN_SEQ" NUMBER, 
	"CV40_FIELD_NAME" VARCHAR2(128 BYTE), 
	"COLUMN_NAME" VARCHAR2(128 BYTE), 
	"DATA_TYPE" VARCHAR2(128 BYTE), 
	"DATA_LENGTH" NUMBER, 
	"MANDATORY" VARCHAR2(1 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"INCLUDE_IN_CONTROL_FILE" VARCHAR2(1 BYTE), 
	"CTL_DEFAULT_VALUE" VARCHAR2(240 BYTE), 
	"CTL_FORMAT_STRING" VARCHAR2(240 BYTE), 
	"CTL_FUNCTION_NAME" VARCHAR2(240 BYTE), 
	"LOOKUP_TABLE_NAME" VARCHAR2(128 BYTE), 
	"LOOKUP_TYPE_NAME" VARCHAR2(30 BYTE), 
	"LOOKUP_COLUMN1" VARCHAR2(128 BYTE), 
	"LOOKUP_COLUMN2" VARCHAR2(128 BYTE), 
	"LOOKUP_COLUMN3" VARCHAR2(128 BYTE), 
	"LOOKUP_WHERE_CLAUSE" VARCHAR2(2000 BYTE), 
	"VALIDATION_SQL1" VARCHAR2(2000 BYTE), 
	"VALIDATION_SQL2" VARCHAR2(2000 BYTE), 
	"VALIDATION_SQL3" VARCHAR2(2000 BYTE), 
	"XFM_TABLE_ID" NUMBER, 
	"XFM_TABLE_COLUMN_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT READ ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT SELECT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT INSERT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT INDEX ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT DELETE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT ALTER ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_XFM";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT READ ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT SELECT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT INSERT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT INDEX ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT DELETE ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
  GRANT ALTER ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" TO "XXMX_STG";
