--------------------------------------------------------
--  DDL for Table XXMX_PPM_CLOUD_INVOICES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CLOUD_INVOICES" 
   (	"INVOICE_ID" VARCHAR2(1000 BYTE), 
	"DOC_NUMBER" VARCHAR2(1000 BYTE), 
	"BATCH_NAME" VARCHAR2(1000 BYTE), 
	"AR_INV_NUMBER" VARCHAR2(1000 BYTE), 
	"AR_INV_DATE" VARCHAR2(1000 BYTE), 
	"TRANSFER_STATUS_CODE" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
