--------------------------------------------------------
--  DDL for Table XXMX_JOBVITE_JOB_DESC_STG_1003
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_JOBVITE_JOB_DESC_STG_1003" 
   (	"PROFILE_CODE" VARCHAR2(1000 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"POSITION_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"POSITION_RESPONSIBILITY" VARCHAR2(4000 BYTE), 
	"POSITION_QUALIFICATION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
