--------------------------------------------------------
--  Constraints for Table XXMX_PER_PASSPORT_XFM_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_PASSPORT_XFM_24JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PASSPORT_XFM_24JUL23" MODIFY ("PASSPORTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PASSPORT_XFM_24JUL23" MODIFY ("NAME" NOT NULL ENABLE);
