--------------------------------------------------------
--  DDL for Table XXMX_PA_EXPENDITURES_ALL
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA_EXPENDITURES_ALL" 
   (	"EXPENDITURE_ID" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"EXPENDITURE_STATUS_CODE" VARCHAR2(30 BYTE), 
	"EXPENDITURE_ENDING_DATE" DATE, 
	"EXPENDITURE_CLASS_CODE" VARCHAR2(2 BYTE), 
	"INCURRED_BY_PERSON_ID" NUMBER(15,0), 
	"INCURRED_BY_ORGANIZATION_ID" NUMBER(15,0), 
	"EXPENDITURE_GROUP" VARCHAR2(240 BYTE), 
	"CONTROL_TOTAL_AMOUNT" NUMBER(22,5), 
	"ENTERED_BY_PERSON_ID" NUMBER(15,0), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"INITIAL_SUBMISSION_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"PROGRAM_ID" NUMBER(15,0), 
	"PROGRAM_APPLICATION_ID" NUMBER(15,0), 
	"PROGRAM_UPDATE_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"PTE_REFERENCE" NUMBER(15,0), 
	"ORG_ID" NUMBER(15,0), 
	"DENOM_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_TYPE" VARCHAR2(30 BYTE), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ORIG_EXP_TXN_REFERENCE1" VARCHAR2(60 BYTE), 
	"ORIG_EXP_TXN_REFERENCE2" VARCHAR2(60 BYTE), 
	"ORIG_EXP_TXN_REFERENCE3" VARCHAR2(60 BYTE), 
	"ORIG_USER_EXP_TXN_REFERENCE" VARCHAR2(60 BYTE), 
	"VENDOR_ID" NUMBER, 
	"OVERRIDING_APPROVER_PERSON_ID" NUMBER, 
	"WF_STATUS_CODE" VARCHAR2(30 BYTE), 
	"TRANSFER_STATUS_CODE" VARCHAR2(1 BYTE), 
	"USER_BATCH_NAME" VARCHAR2(50 BYTE), 
	"PERSON_TYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
