--------------------------------------------------------
--  Constraints for Table XXMX_PAY_ELE_VALS_TAB
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" MODIFY ("ELEMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" MODIFY ("IV_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" MODIFY ("DISPLAY_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PAY_ELE_VALS_TAB" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
