--------------------------------------------------------
--  Constraints for Table XXMX_GL_FUSION_STRUCT_SEGMENTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_STRUCT_SEGMENTS" MODIFY ("FUSION_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_STRUCT_SEGMENTS" MODIFY ("FUSION_SEGMENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_STRUCT_SEGMENTS" MODIFY ("FUSION_SEGMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_STRUCT_SEGMENTS" MODIFY ("FUSION_SEGMENT_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_STRUCT_SEGMENTS" MODIFY ("FUSION_SEGMENT_LENGTH" NOT NULL ENABLE);
