--------------------------------------------------------
--  DDL for Table XXMX_SCHEDULED_REQUESTS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_SCHEDULED_REQUESTS" 
   (	"REQUEST_ID" NUMBER, 
	"MIGRATION_SET_ID" VARCHAR2(100 BYTE), 
	"PROCEDURE_NAME" VARCHAR2(100 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"REQUEST_STATUS" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_SCHEDULED_REQUESTS" TO "XXMX_READONLY";
