--------------------------------------------------------
--  Constraints for Table XXMX_HCM_ORG_LEGALEMP_MV
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HCM_ORG_LEGALEMP_MV" MODIFY ("LEGAL_ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_ORG_LEGALEMP_MV" MODIFY ("LE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_ORG_LEGALEMP_MV" MODIFY ("ORG_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_ORG_LEGALEMP_MV" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
