--------------------------------------------------------
--  DDL for Table XXMX_WORKER_SUSPEND_LIST
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_WORKER_SUSPEND_LIST" 
   (	"PERSON_NUMBER" VARCHAR2(20 BYTE), 
	"HC_CLASSIFICATION" VARCHAR2(100 BYTE), 
	"ASG_STATUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
