--------------------------------------------------------
--  DDL for Table XXMX_FILE_LOCATIONS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FILE_LOCATIONS" 
   (	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"BUSINESS_ENTITY" VARCHAR2(100 BYTE), 
	"FILE_GROUP_NUMBER" NUMBER(3,0), 
	"USED_BY" VARCHAR2(10 BYTE), 
	"FILE_TYPE" VARCHAR2(10 BYTE), 
	"FILE_LOCATION_TYPE" VARCHAR2(20 BYTE), 
	"FILE_LOCATION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_FILE_LOCATIONS" TO "XXMX_READONLY";
