--------------------------------------------------------
--  Constraints for Table XXPA_PROJECT_ROLE_TYPES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("ROW_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("PROJECT_ROLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("QUERY_LABOR_COST_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("START_DATE_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("PROJECT_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("ROLE_PARTY_CLASS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("SOURCE_LANG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("MEANING" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_ROLE_TYPES_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
