--------------------------------------------------------
--  Constraints for Table XXPA_PROJECT_PARTIES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("PROJECT_PARTY_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("RESOURCE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("RESOURCE_SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("PROJECT_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("START_DATE_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_PARTIES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
