--------------------------------------------------------
--  Constraints for Table XXPA_TASKS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("TOP_TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("WBS_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("READY_TO_BILL_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("READY_TO_DISTRIBUTE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("CARRYING_OUT_ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("ALLOW_CROSS_CHARGE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("CC_PROCESS_LABOR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TASKS_STG" MODIFY ("CC_PROCESS_NL_FLAG" NOT NULL ENABLE);
