--------------------------------------------------------
--  DDL for Table XXPA_EMP_BILL_RATE_OVERRIDES_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" 
   (	"PERSON_ID" NUMBER(9,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"RATE" NUMBER(22,5), 
	"BILL_RATE_UNIT" VARCHAR2(30 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"PROJECT_ID" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"END_DATE_ACTIVE" DATE, 
	"RECORD_VERSION_NUMBER" NUMBER(15,0), 
	"EMP_BILL_RATE_OVERRIDE_ID" NUMBER(15,0), 
	"RATE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"DISCOUNT_PERCENTAGE" NUMBER, 
	"RATE_DISC_REASON_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
