--------------------------------------------------------
--  Constraints for Table XXPA_NL_BILL_RATE_OVERRIDES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("EXPENDITURE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("START_DATE_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_NL_BILL_RATE_OVERRIDES_STG" MODIFY ("NL_BILL_RATE_OVERRIDE_ID" NOT NULL ENABLE);
