--------------------------------------------------------
--  Constraints for Table XXPA_PROJECTS_ALL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("SEGMENT1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("PROJECT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("CARRYING_OUT_ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("PUBLIC_SECTOR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("PROJECT_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("SUMMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("ENABLED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("PROJECT_CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("ALLOW_CROSS_CHARGE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("CC_PROCESS_LABOR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("CC_PROCESS_NL_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("AR_REC_NOTIFY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECTS_ALL_STG" MODIFY ("AUTO_RELEASE_PWP_INV" NOT NULL ENABLE);
