--------------------------------------------------------
--  Constraints for Table XXPA_EMP_BILL_RATE_OVERRIDES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("START_DATE_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_EMP_BILL_RATE_OVERRIDES_STG" MODIFY ("EMP_BILL_RATE_OVERRIDE_ID" NOT NULL ENABLE);
