--------------------------------------------------------
--  Constraints for Table XXPER_ALL_PEOPLE_F_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("PERSON_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_PEOPLE_F_STG" MODIFY ("START_DATE" NOT NULL ENABLE);
