--------------------------------------------------------
--  Constraints for Table XXXLE_ENTITY_PROFILES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("LEGAL_ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("PARTY_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("GEOGRAPHY_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXXLE_ENTITY_PROFILES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
