--------------------------------------------------------
--  File created - Thursday-February-01-2024   
--------------------------------------------------------
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TRX_CONTROL_SEQ.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ADDR_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_INVOICES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_INVOICES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_INVOICE_LINES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_INVOICE_LINES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPPLIERS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPPLIERS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPPLIER_SITES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPPLIER_SITES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_3RD_PTY_RELS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_3RD_PTY_RELS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_ADDRS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_ADDRS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_BANK_ACCTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_BANK_ACCTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_CONTACTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_CONTACTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_CONT_ADDRS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_CONT_ADDRS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_PAYEES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_PAYEES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_PMT_INSTRS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_PMT_INSTRS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_SITE_ASSIGNS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_TAX_PROF_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_TAX_PROF_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_TAX_REG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AP_SUPP_TAX_REG_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG_17072023.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CUST_BANKS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CUST_BANKS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_DISTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_DISTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_LINES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_LINES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_SALESCREDITS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_TRX_SALESCREDITS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_GRADESTEP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_GRADESTEP_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_PAYROLL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_PAYROLL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_WORKMSURE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_WORKMSURE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BANKS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BANKS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BANK_BRANCHES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BANK_BRANCHES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CARRY_OVER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CARRY_OVER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CITIZENSHIPS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CITIZENSHIPS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_EXT_BANK_ACC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_EXT_BANK_ACC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_ADDITIONS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_ADDITIONS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_ADDITION_DIST_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_ADDITION_DIST_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_RATES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_FA_MASS_RATES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_BALANCES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_BALANCES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_DAILYRATES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_DAILYRATES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_DETAIL_BALANCES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_DETAIL_BALANCES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_HISTORICALRATES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_HISTORICALRATES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_JOURNAL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_JOURNAL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_OPENING_BALANCES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_OPENING_BALANCES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_SUMMARY_BALANCES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GL_SUMMARY_BALANCES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_GEO_MAP.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_ADDRESS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_ADDRESS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_ATTMT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_EMAIL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_EMAIL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_EXTRA_INFO_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_INTERACT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_EXTRA_INFO_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_NAME_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_NAME_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_NAT_IDENFR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PHONE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PHONE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_INTERACT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_INTERACT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_MEMBR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_MEMBR_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_OWNER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_OWNER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_POOL_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PREFD_JOB_FAM_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PREFD_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PREFD_ORG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PREF_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_PROFL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CAN_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_CAN_INTERACT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_CAN_PER_INFO_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_CAN_PREFD_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_QSTNR_PARTCPNT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_QSTNR_RESP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CJA_QSTN_RESP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CL_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CL_POST_DESC_CNTXT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CON_LIB_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CON_LIB_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CON_LIB_VER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CON_LIB_VER_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CP_TAL_COMM_DET_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_CP_TAL_COMM_DET_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_GEO_HIER_NODE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_GEO_HIER_NODE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_GEO_HIER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_GEO_HIER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_SEC_PROFL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_TEMPL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_TEMPL_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JOB_REQ_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_APPL_SPEC_QSTN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_ASSMT_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_ASSMT_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_SCRN_PKG_V2_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_HIRE_TEAM_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_INTRVW_QSTNR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_JOB_PROFL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_LANG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_OTHER_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_OTHER_WORK_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_TAX_CRED_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_TAX_CRED_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JRT_TEMPL_MEDIA_LINK_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_APPL_SPEC_QSTN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_ASSMT_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_ASSMT_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_SCRN_PKG_V2_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_HIRE_TEAM_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_HIRE_TEAM_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_INTRVW_QSTNR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_JOB_PROFL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_LANG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_MEDIA_LINK_LANG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_MEDIA_LINK_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_OTHER_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_OTHER_WORK_LOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_POST_DET_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_POST_DET_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_TAX_CRED_CONFIG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_JR_TAX_CRED_SCRN_PKG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_MEDIA_LINK_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_PROSPECT_INTERACT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_PROSPECT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_PROSPECT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_REFERRAL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_REFERRAL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_REF_ATTMT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HCM_IREC_TEMPL_MEDIA_LINK_TRNSLN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_B_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_ESTB_B_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_ESTB_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PFL_ITEMS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_B_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_REL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_LVL_B_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_LVL_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_MDL_B_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_MDL_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CONTACT_POINTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CONTACT_POINTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCOUNTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCOUNTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_CONTACTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_CONTACTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_RELATE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_RELATE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_SITES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_ACCT_SITES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_PROFILES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_PROFILES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_SITE_USES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_CUST_SITE_USES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_LOCATIONS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_LOCATIONS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ORG_CONTACTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ORG_CONTACTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ORG_CONTACT_ROLES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ORG_CONTACT_ROLES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTIES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTIES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_CLASSIFS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_CLASSIFS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_SITES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_SITES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_SITE_USES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PARTY_SITE_USES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PERSON_LANGUAGE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_PERSON_LANGUAGE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_RELATIONSHIPS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_RELATIONSHIPS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ROLE_RESPS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HZ_ROLE_RESPS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_IBY_CUST_BANK_ACCTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LEARNER_RECORDS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LEARNER_RECORDS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOCATIONS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_ADDR_USG_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_DETAILS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_DETAILS_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_CERTIFICATION_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_CERTIFICATION_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_CLASS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_CLASS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_COURSE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLM_COURSE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_INFO_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNITS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNITS_F_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNIT_CLASS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PAY_ELE_ENTRY_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PAY_ELE_ENTRY_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ABSENCE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ABSENCE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDRESS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDRESS_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDR_USG_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDR_USG_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_AOR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SALARY_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SALARY_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SUP_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SUP_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_WORKSCH_EXP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_WORK_SCH_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASSIGNMENTS_M_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASSIGNMENTS_M_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_ADDR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_ADDR_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_PHONE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_PHONE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_REL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_REL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DISABILITY_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DISABILITY_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DOCUMENTATION_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_EMAIL_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_EMAIL_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ETHNICITIES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ETHNICITIES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_IMAGES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_IMAGES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_LEG_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_LEG_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_MAT_ABSENCE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_MAT_ABSENCE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NAMES_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NAMES_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NID_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NID_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PASSPORT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PASSPORT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PAY_METHOD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PAY_METHOD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PEOPLE_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PEOPLE_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PERSONS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PERSONS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PHONES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PHONES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_POS_WR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_POS_WR_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PROFILE_ITEM_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PROFILE_ITEM_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_RELIGION_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_RELIGION_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_SENIORITYDT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_SENIORITYDT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_TALENT_PROFILE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_TALENT_PROFILE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_VISA_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_VISA_F_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_POSITIONS_F_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_POSITIONS_F_TL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PLANRBS_HEADER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PLANRBS_HEADER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_CLASS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_CLASS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_LBRCOST_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_LBRCOST_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_MISCCOST_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_MISCCOST_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_NONLABCOST_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_NONLABCOST_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_SUPCOST_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_SUPCOST_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TASKS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TASKS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TEAM_MEM_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TEAM_MEM_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TRX_CONTROL_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_TRX_CONTROL_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PROJECTS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PROJECTS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_RATE_OVERRIDES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_RATE_OVERRIDES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_RESOURCES_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_RESOURCES_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RA_CUST_RCPT_METHODS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RA_CUST_RCPT_METHODS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RESP_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RESP_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_ATTR_VALUES_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_DISTRIBUTIONS_STD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_DISTRIBUTIONS_STD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_BPA_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_CPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_CPA_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_STD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_HEADERS_STD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINES_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINES_BPA_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINES_STD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINES_STD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_STD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_STD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_ADDR_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_ADDR_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_ORG_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_ORG_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_PAYMTHD_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_THIRD_PAYMTHD_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_DATA_ACCESS_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_DATA_ACCESS_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_PARTY_CLASSIFIC_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_PARTY_CLASSIFIC_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_TAX_PROFILE_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_TAX_PROFILE_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_TAX_REGISTRATION_STG.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ZX_TAX_REGISTRATION_STG_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG_N1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG_UK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG_I1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG_I2.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PROJECTS_STG_U1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_XTRT_HRT_CNT_ITEMS_B_PK.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_XTRT_HRT_CNT_ITEMS_B_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG_N1_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG_UK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG_PK_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\PK_PERSON_ID.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG_I1_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PRJ_BILLEVENT_STG_I2_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PPM_PROJECTS_STG_U1_1.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ADDR_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG_17072023_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_AR_CASH_RECEIPTS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_GRADESTEP_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_GRADESTEP_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_PAYROLL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_PAYROLL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_WORKMSURE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ASG_WORKMSURE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_DB_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_BE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_DD_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_DE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBB_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBG_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PBO_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_CO_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_BEN_PH_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CITIZENSHIPS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_CITIZENSHIPS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_EXT_BANK_ACC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_EXT_BANK_ACC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_GRADES_F_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_B_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_CNT_ITEMS_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_ESTB_B_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_ESTB_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PFL_ITEMS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_B_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_REL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_PROFILE_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_LVL_B_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_LVL_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_MDL_B_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_HRT_RATING_MDL_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_JOBS_F_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOCATIONS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_ADDR_USG_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_DETAILS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_LOC_DETAILS_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_MAP_LOOKUPS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_ADHOC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RESV_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_CLASS_RES_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COMM_RS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_ACC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_PRICE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_COURSE_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_GLOB_ACC_GRP_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_ACT_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_LED_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RESV_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_INSTR_RES_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEARN_RCD_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_LEG_LEARN_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_NONCAT_LEARN_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_ACC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_OFFER_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SELFPACE_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_DEF_ACC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_ACT_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_SXN_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_OLC_SPEC_TL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_INFO_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNITS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNITS_F_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_ORG_UNIT_CLASS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ABSENCE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ABSENCE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDRESS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDRESS_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDR_USG_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ADDR_USG_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SALARY_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SALARY_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SUP_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASG_SUP_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASSIGNMENTS_M_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ASSIGNMENTS_M_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACTS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACTS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_ADDR_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_ADDR_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_PHONE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_PHONE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_REL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_CONTACT_REL_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DISABILITY_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DISABILITY_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_DOCUMENTATION_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_EMAIL_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_EMAIL_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ETHNICITIES_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_ETHNICITIES_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_IMAGES_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_IMAGES_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_LEG_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_LEG_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_MAT_ABSENCE_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_MAT_ABSENCE_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NAMES_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NAMES_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NID_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_NID_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PASSPORT_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PASSPORT_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PAY_METHOD_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PAY_METHOD_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PEOPLE_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PEOPLE_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PERSONS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PERSONS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PHONES_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_PHONES_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_RELIGION_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_RELIGION_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_SENIORITYDT_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_SENIORITYDT_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_VISA_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_PER_VISA_F_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_POSITIONS_F_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_POSITIONS_F_TL_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RESP_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_RESP_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_DATA_ACCESS_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_DATA_ACCESS_STG_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_STG_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All stg bkp latest\XXMX_USER_STG_ARCH_CONSTRAINT.sql
