--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_ACT_TL_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_ACT_TL_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_ACT_TL_STG_ARCH" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_ACT_TL_STG_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
