--------------------------------------------------------
--  Constraints for Table XXMX_RESP_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("EBS_RESPONSIBILITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("EBS_RESPONSIBILITY_KEY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG_ARCH" MODIFY ("EBS_APPLICATION" NOT NULL ENABLE);
