--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_REL_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG_ARCH" MODIFY ("CONTACTTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG_ARCH" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG_ARCH" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
