--------------------------------------------------------
--  Constraints for Table XXMX_POSITIONS_F_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_POSITIONS_F_STG" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_POSITIONS_F_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_POSITIONS_F_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
