--------------------------------------------------------
--  Constraints for Table XXMX_USER_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_STG" MODIFY ("GENERATE_USER_ACCOUNT" NOT NULL ENABLE);
