--------------------------------------------------------
--  DDL for Index XXMX_PPM_PROJECTS_STG_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_STG"."XXMX_PPM_PROJECTS_STG_U1" ON "XXMX_STG"."XXMX_PPM_PROJECTS_STG" ("LAST_UPDATE_LOGIN", "PROJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
