--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
