--------------------------------------------------------
--  Constraints for Table XXMX_PER_DISABILITY_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_DISABILITY_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_DISABILITY_STG_ARCH" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_DISABILITY_STG_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
