--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG_ARCH" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG_ARCH" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ABSENCE_STG_ARCH" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
