--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASSIGNMENTS_M_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_ASSIGNMENTS_M_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASSIGNMENTS_M_STG_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASSIGNMENTS_M_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASSIGNMENTS_M_STG_ARCH" MODIFY ("PRIMARY_WORK_TERMS_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASSIGNMENTS_M_STG_ARCH" MODIFY ("PRIMARY_ASSIGNMENT_FLAG" NOT NULL ENABLE);
