--------------------------------------------------------
--  Constraints for Table XXMX_OLC_LEG_LEARN_TL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_LEG_LEARN_TL_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_LEG_LEARN_TL_STG" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_LEG_LEARN_TL_STG" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
