--------------------------------------------------------
--  Constraints for Table XXMX_BEN_PBB_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("BENEFIT_BALANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("BENEFIT_RELATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("UOM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_PBB_STG_ARCH" MODIFY ("VAL" NOT NULL ENABLE);
