--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_DEF_ACC_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_DEF_ACC_STG" MODIFY ("DEFAULT_ACCESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_DEF_ACC_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_DEF_ACC_STG" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
