--------------------------------------------------------
--  DDL for Index XXMX_OLC_LEG_LEARN_TL_STG_UK
--------------------------------------------------------

  CREATE INDEX "XXMX_STG"."XXMX_OLC_LEG_LEARN_TL_STG_UK" ON "XXMX_STG"."XXMX_OLC_LEG_LEARN_TL_STG" ("LEARNING_ITEM_NUMBER", "LANGUAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
