--------------------------------------------------------
--  Constraints for Table XXMX_BEN_BE_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("PARTICIPANT_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("PARTICIPANT_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("BENEFIT_RELATIONSHIP" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("LIFE_EVENT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_STG" MODIFY ("LIFE_EVENT_OCCURED_DATE" NOT NULL ENABLE);
