--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_TL_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_TL_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_TL_STG_ARCH" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_TL_STG_ARCH" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
