--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACTS_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG_ARCH" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG_ARCH" MODIFY ("CNTPERSONNUMBER" NOT NULL ENABLE);
