--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RESV_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG" MODIFY ("CLASSROOM_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
