--------------------------------------------------------
--  Constraints for Table XXMX_PER_PAY_METHOD_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("PERSONAL_PAYMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("ORG_PAYMENT_METHOD_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("BANK_ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
