--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_RESV_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG_ARCH" MODIFY ("INSTRUCTOR_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG_ARCH" MODIFY ("INSTRUCTOR_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
