--------------------------------------------------------
--  Constraints for Table XXMX_ORG_UNIT_CLASS_F_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_ORG_UNIT_CLASS_F_STG" MODIFY ("ORG_UNIT_CLASSIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ORG_UNIT_CLASS_F_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ORG_UNIT_CLASS_F_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
