--------------------------------------------------------
--  DDL for Table XXMX_OLM_CERTIFICATION_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(240 BYTE), 
	"CERT_ENROLLMENT_ID" NUMBER, 
	"CERTIFICATION_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"CERTIFICATION_STATUS_CODE" VARCHAR2(30 BYTE), 
	"ENROLLMENT_DATE" VARCHAR2(30 BYTE), 
	"COMPLETION_DATE" VARCHAR2(30 BYTE), 
	"IS_AUTOMATIC_SUBSCRIPTION" VARCHAR2(10 BYTE), 
	"CERTIFICATION_NAME" VARCHAR2(240 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_OLM_CERTIFICATION_STG" TO "XXMX_CORE";
