--------------------------------------------------------
--  DDL for Table XXMX_BEN_BE_DB_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'DesignateBeneficiary', 
	"PERSON_ID" NUMBER(18,0), 
	"BEN_PLAN" VARCHAR2(240 BYTE), 
	"BEN_PROGRAM" VARCHAR2(240 BYTE), 
	"BEN_OPTION" VARCHAR2(240 BYTE), 
	"BENEFICIARY_PERCENTAGE" NUMBER(18,0), 
	"ORIGINAL_ENROLLMENT_DATE" DATE, 
	"BENEFICIARY_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"BENEFICIARY_PERSON_ID" NUMBER(18,0), 
	"BENEFICIARY_TYPE" VARCHAR2(30 BYTE), 
	"LINE_NUMBER" NUMBER(18,0), 
	"BENEFICIARY_LINE_ID" NUMBER(18,0), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"BENEFICIARY_LAST_NAME" VARCHAR2(150 BYTE), 
	"BENEFICIARY_FIRST_NAME" VARCHAR2(150 BYTE), 
	"BENEFICIARY_DATE_OF_BIRTH" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_BEN_BE_DB_STG" TO "XXMX_CORE";
