--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_STG_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
