--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_STG" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_STG" MODIFY ("SECTION_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_STG" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
