--------------------------------------------------------
--  DDL for Sequence XXMX_PPM_PRJ_TRX_CONTROL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "XXMX_STG"."XXMX_PPM_PRJ_TRX_CONTROL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4461103 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "XXMX_STG"."XXMX_PPM_PRJ_TRX_CONTROL_SEQ" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_PPM_PRJ_TRX_CONTROL_SEQ" TO "XXMX_CORE";
