--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RECEIPTS_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_ARCH" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_ARCH" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_ARCH" MODIFY ("RECORD_SEQ" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_ARCH" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
