--------------------------------------------------------
--  Constraints for Table XXMX_PER_PAY_METHOD_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("PERSONAL_PAYMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("ORG_PAYMENT_METHOD_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("BANK_ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PAY_METHOD_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
