--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_RESV_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG" MODIFY ("INSTRUCTOR_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG" MODIFY ("INSTRUCTOR_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_INSTR_RESV_STG" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
