--------------------------------------------------------
--  Constraints for Table XXMX_OLC_NONCAT_LEARN_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_NONCAT_LEARN_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_NONCAT_LEARN_STG" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_NONCAT_LEARN_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_NONCAT_LEARN_STG" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
