--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_ADDR_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("ADDRESSTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("ADDRESSLINE1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG_ARCH" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
