--------------------------------------------------------
--  Constraints for Table XXMX_PER_IMAGES_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG_ARCH" MODIFY ("IMAGENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG_ARCH" MODIFY ("IMAGE_REF" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG_ARCH" MODIFY ("IMAGETYPE" NOT NULL ENABLE);
