--------------------------------------------------------
--  Constraints for Table XXMX_ASG_GRADESTEP_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG_ARCH" MODIFY ("GRADENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG_ARCH" MODIFY ("GRADESTEPNAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
