--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
