--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_ACC_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("DEFAULT_ACCESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("SELF_VIEW_MODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("SELF_INITIAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_ACC_STG" MODIFY ("MGR_INITIAL_STATUS" NOT NULL ENABLE);
