--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_ADDR_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("ADDRESSTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("ADDRESSLINE1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_ADDR_STG" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
