--------------------------------------------------------
--  DDL for Table XXMX_GL_HISTORICALRATES_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"LEDGER_NAME" VARCHAR2(30 BYTE), 
	"IMPORT_ACTION" VARCHAR2(30 BYTE), 
	"SEGMENT1" VARCHAR2(25 BYTE), 
	"SEGMENT2" VARCHAR2(25 BYTE), 
	"SEGMENT3" VARCHAR2(25 BYTE), 
	"SEGMENT4" VARCHAR2(25 BYTE), 
	"SEGMENT5" VARCHAR2(25 BYTE), 
	"SEGMENT6" VARCHAR2(25 BYTE), 
	"SEGMENT7" VARCHAR2(25 BYTE), 
	"SEGMENT8" VARCHAR2(25 BYTE), 
	"SEGMENT9" VARCHAR2(25 BYTE), 
	"SEGMENT10" VARCHAR2(25 BYTE), 
	"SEGMENT11" VARCHAR2(25 BYTE), 
	"SEGMENT12" VARCHAR2(25 BYTE), 
	"SEGMENT13" VARCHAR2(25 BYTE), 
	"SEGMENT14" VARCHAR2(25 BYTE), 
	"SEGMENT15" VARCHAR2(25 BYTE), 
	"SEGMENT16" VARCHAR2(25 BYTE), 
	"SEGMENT17" VARCHAR2(25 BYTE), 
	"SEGMENT18" VARCHAR2(25 BYTE), 
	"SEGMENT19" VARCHAR2(25 BYTE), 
	"SEGMENT20" VARCHAR2(25 BYTE), 
	"SEGMENT21" VARCHAR2(25 BYTE), 
	"SEGMENT22" VARCHAR2(25 BYTE), 
	"SEGMENT23" VARCHAR2(25 BYTE), 
	"SEGMENT24" VARCHAR2(25 BYTE), 
	"SEGMENT25" VARCHAR2(25 BYTE), 
	"SEGMENT26" VARCHAR2(25 BYTE), 
	"SEGMENT27" VARCHAR2(25 BYTE), 
	"SEGMENT28" VARCHAR2(25 BYTE), 
	"SEGMENT29" VARCHAR2(25 BYTE), 
	"SEGMENT30" VARCHAR2(25 BYTE), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"TARGET_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"VALUE_TYPE_CODE" VARCHAR2(30 BYTE), 
	"CREDIT_AMOUNT_RATE" NUMBER, 
	"AUTO_ROLL_FORWARD_FLAG" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT ALTER ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_GL_HISTORICALRATES_STG" TO "XXMX_READONLY";
