--------------------------------------------------------
--  DDL for Index XXMX_MAP_LOOKUPS_STG_N1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_STG"."XXMX_MAP_LOOKUPS_STG_N1" ON "XXMX_STG"."XXMX_MAP_LOOKUPS_STG" ("S_TYPE", "S_VIEW_APPLICATION_ID", "S_LOOKUP_TYPE", "S_LOOKUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
