--------------------------------------------------------
--  DDL for Table XXMX_GL_SOURCES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_GL_SOURCES" 
   (	"JE_SOURCE_KEY" VARCHAR2(360 BYTE), 
	"JE_SOURCE_NAME" VARCHAR2(360 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
