INSERT INTO XXMX_OLC_GLOB_ACC_GRP_STG(
MIGRATION_SET_ID,
MIGRATION_SET_NAME,
MIGRATION_STATUS,
BG_NAME,
METADATA,
OBJECTNAME,
EFFECTIVE_START_DATE,
RELATION_NUMBER,
GLOBAL_ACCESS_GROUP_NUMBER,
LEARNING_ITEM_NUMBER,
PRIORITY,
SOURCE_SYSTEM_OWNER,
SOURCE_SYSTEM_ID)

VALUES(
2031,
'TEST_MIGRATION_GLOB_ACC_GRP',
'EXTRACTED',
'TEST_BG',
'MERGE',
'GlobalAccessGroupRelation',
DATE '2021-08-15',
'RL229946',
'OLC138008',
'SPL111222',
1,
'DATAMIGRATION',
'GAGR2299461')
/