DROP table "XXMX_CORE"."XXMX_ASG_GRADESTEP_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_ASG_GRADESTEP_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSONNUMBER" VARCHAR2(150 BYTE), 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"LANGUAGE" VARCHAR2(30 BYTE), 
	"GRADENAME" VARCHAR2(80 BYTE), 
	"GRADESTEPID" NUMBER, 
	"GRADESTEPNAME" VARCHAR2(80 BYTE), 
	"NEWGRADESTEP" VARCHAR2(80 BYTE), 
	"PART_FULL_TIME" VARCHAR2(80 BYTE), 
	"GRADEID" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ACTION_CODE" VARCHAR2(100 BYTE), 
	"ASG_SSID" VARCHAR2(350 BYTE), 
	"REASON_CODE" VARCHAR2(200 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(30 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(200 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(200 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_ASG_GRADESTEP_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_ASG_GRADESTEP_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_ASG_PAYROLL_EXT" ;

  CREATE TABLE "XXMX_CORE"."XXMX_ASG_PAYROLL_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_ID" NUMBER, 
	"PERSONNUMBER" VARCHAR2(80 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(50 BYTE), 
	"PAYROLL_NAME" VARCHAR2(80 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"METADATA" VARCHAR2(150 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(256 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(200 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_ASG_PAYROLL_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_ASG_PAYROLL_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_ASG_WORKMSURE_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSONNUMBER" VARCHAR2(150 BYTE), 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"UNIT" VARCHAR2(30 BYTE), 
	"VALUE" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(50 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(300 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(300 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_ASG_WORKMSURE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_ASG_WORKMSURE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_BANK_BRANCHES_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_BANK_BRANCHES_EXT" 
   (	"BANK_TYPE" VARCHAR2(30 BYTE), 
	"SHORT_BANK_NAME" VARCHAR2(40 BYTE), 
	"BANK_ID" VARCHAR2(10 BYTE), 
	"BRANCH_ID" VARCHAR2(10 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"MIGRATION_ACTION" VARCHAR2(10 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"INSTITUTION_LEVEL" VARCHAR2(20 BYTE), 
	"BANK_NAME" VARCHAR2(360 BYTE), 
	"BANK_NUMBER" VARCHAR2(30 BYTE), 
	"COUNTRY" VARCHAR2(60 BYTE), 
	"BANK_BRANCH_NUMBER" VARCHAR2(30 BYTE), 
	"BANK_BRANCH_NAME" VARCHAR2(360 BYTE), 
	"ALTERNATE_BANK_BRANCH_NAME" VARCHAR2(320 BYTE), 
	"BANK_BRANCH_TYPE" VARCHAR2(30 BYTE), 
	"EFT_SWIFT_CODE" VARCHAR2(30 BYTE), 
	"EFT_USER_NUMBER" VARCHAR2(30 BYTE), 
	"RFC" VARCHAR2(30 BYTE), 
	"END_EFFECTIVE_DATE" VARCHAR2(20 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_BANK_BRANCHES_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_BANK_BRANCHES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_BANKS_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_BANKS_EXT" 
   (	"FILE_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"MIGRATION_ACTION" VARCHAR2(10 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"INSTITUTION_LEVEL" VARCHAR2(20 BYTE), 
	"BANK_TYPE" VARCHAR2(30 BYTE), 
	"SHORT_BANK_NAME" VARCHAR2(40 BYTE), 
	"BANK_ID" VARCHAR2(10 BYTE), 
	"BANK_NAME" VARCHAR2(360 BYTE), 
	"COUNTRY" VARCHAR2(60 BYTE), 
	"BANK_NUMBER" VARCHAR2(30 BYTE), 
	"ALTERNATE_BANK_NAME" VARCHAR2(320 BYTE), 
	"END_EFFECTIVE_DATE" VARCHAR2(20 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_BANKS_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_BANKS_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP table  "XXMX_CORE"."XXMX_EXT_BANK_ACC_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_EXT_BANK_ACC_EXT" 
   (	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(80 BYTE), 
	"BANK_NUMBER" VARCHAR2(80 BYTE), 
	"BANK_NAME" VARCHAR2(80 BYTE), 
	"BRANCH_NAME" VARCHAR2(80 BYTE), 
	"CURRENCY_CODE" VARCHAR2(30 BYTE), 
	"COUNTRY_CODE" VARCHAR2(30 BYTE), 
	"SEC_ACCOUNT_REF" VARCHAR2(80 BYTE), 
	"SORT_CODE" VARCHAR2(30 BYTE), 
	"PERSON_ID" VARCHAR2(265 BYTE), 
	"IBAN" VARCHAR2(265 BYTE), 
	"EXT_BANK_ACC_OWNER" VARCHAR2(265 BYTE), 
	"EXTERNALBANKACCOUNTID" VARCHAR2(265 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_EXT_BANK_ACC_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_EXT_BANK_ACC_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_OLC_COURSE_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_OLC_COURSE_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"METADATA" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"COURSE_ID" NUMBER, 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"COURSE_NUMBER" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(250 BYTE), 
	"SHORT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"SYLLABUS" CLOB, 
	"PUBLISH_START_DATE" VARCHAR2(20 BYTE), 
	"PUBLISH_END_DATE" VARCHAR2(20 BYTE), 
	"MINIMUM_EXPECTED_EFFORT" NUMBER, 
	"MAXIMUM_EXPECTED_EFFORT" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(30 BYTE), 
	"MINIMUM_PRICE" NUMBER, 
	"MAXIMUM_PRICE" NUMBER, 
	"COVER_ART_FILE" CLOB, 
	"COVER_ART_FILE_NAME" VARCHAR2(255 BYTE), 
	"OWNED_BY_PERSON_ID" NUMBER, 
	"OWNED_BY_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"SOURCE_ID" NUMBER, 
	"SOURCE_INFO" VARCHAR2(240 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE2" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE3" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE4" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE5" VARCHAR2(20 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_OLC_COURSE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_OLC_COURSE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_OLC_LEARN_RCD_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_OLC_LEARN_RCD_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"METADATA" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"LEARNING_RECORD_ID" NUMBER, 
	"LEARN_RECORD_EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"LEARN_RECORD_EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_ITEM_TYPE" VARCHAR2(30 BYTE), 
	"LEARNING_ITEM_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SUB_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SOURCE_ID" NUMBER, 
	"ASSIGNMENT_SOURCE_INFO" VARCHAR2(240 BYTE), 
	"ASSIGNED_BY_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_CODE" VARCHAR2(30 BYTE), 
	"LEARNER_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_STATUS" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_SOURCE_ID" NUMBER, 
	"LEARNING_RECORD_SOURCE_INFO" VARCHAR2(240 BYTE), 
	"LEARNING_RECORD_START_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_DUE_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_WITHDRAWN_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_DELETED_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_COMPLETION_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_RECORD_VALID_FROM_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_REC_EXPIRY_DATE" VARCHAR2(20 BYTE), 
	"LEARNING_REC_TOT_ACT_EFFORT" NUMBER, 
	"LEARNING_REC_TOT_ACT_EFFORT_UOM" VARCHAR2(30 BYTE), 
	"REQUEST_DETAIL_START_DATE" VARCHAR2(20 BYTE), 
	"REQUEST_DETAIL_COMPLETION_DATE" VARCHAR2(20 BYTE), 
	"REQUEST_DETAIL_COMMENTS" VARCHAR2(4000 BYTE), 
	"REQUEST_DETAIL_PO_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_REASON_CODE" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_COMMENTS" VARCHAR2(4000 BYTE), 
	"LEARNING_RECORD_REQUEST_APPV_DATE" VARCHAR2(20 BYTE), 
	"ACTUAL_SCORE" NUMBER, 
	"CPE_POINTS" NUMBER, 
	"CPE_TYPE" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE2" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE3" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE4" VARCHAR2(20 BYTE), 
	"ATTRIBUTE_DATE5" VARCHAR2(20 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_OLC_LEARN_RCD_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_OLC_LEARN_RCD_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PAY_ELEM_ENTRIES_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PAY_ELEM_ENTRIES_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(100 BYTE), 
	"MIGRATION_ACTION" VARCHAR2(20 BYTE), 
	"ELEMENT_ENTRY" VARCHAR2(100 BYTE), 
	"CREATE_ELEMENT_ENTRY" VARCHAR2(100 BYTE), 
	"ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(100 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(100 BYTE), 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"TERMS_NUMBER" VARCHAR2(100 BYTE), 
	"RELATIONSHIP_NUMBER" VARCHAR2(100 BYTE), 
	"PAYROLL" VARCHAR2(100 BYTE), 
	"REASON" VARCHAR2(100 BYTE), 
	"SUBPRIORITY" VARCHAR2(100 BYTE), 
	"VAL1" VARCHAR2(100 BYTE), 
	"VAL2" VARCHAR2(100 BYTE), 
	"VAL3" VARCHAR2(100 BYTE), 
	"VAL4" VARCHAR2(100 BYTE), 
	"VAL5" VARCHAR2(100 BYTE), 
	"VAL6" VARCHAR2(100 BYTE), 
	"VAL7" VARCHAR2(100 BYTE), 
	"VAL8" VARCHAR2(100 BYTE), 
	"VAL9" VARCHAR2(100 BYTE), 
	"VAL10" VARCHAR2(100 BYTE), 
	"VAL11" VARCHAR2(100 BYTE), 
	"VAL12" VARCHAR2(100 BYTE), 
	"VAL13" VARCHAR2(100 BYTE), 
	"VAL14" VARCHAR2(100 BYTE), 
	"VAL15" VARCHAR2(100 BYTE), 
	"VAL16" VARCHAR2(100 BYTE), 
	"VAL17" VARCHAR2(100 BYTE), 
	"VAL18" VARCHAR2(100 BYTE), 
	"VAL19" VARCHAR2(100 BYTE), 
	"VAL20" VARCHAR2(100 BYTE), 
	"VAL21" VARCHAR2(100 BYTE), 
	"VAL22" VARCHAR2(100 BYTE), 
	"VAL23" VARCHAR2(100 BYTE), 
	"VAL24" VARCHAR2(100 BYTE), 
	"VAL25" VARCHAR2(100 BYTE), 
	"VAL26" VARCHAR2(100 BYTE), 
	"VAL27" VARCHAR2(100 BYTE), 
	"VAL28" VARCHAR2(100 BYTE), 
	"VAL29" VARCHAR2(100 BYTE), 
	"VAL30" VARCHAR2(100 BYTE), 
	"VAL31" VARCHAR2(100 BYTE), 
	"VAL32" VARCHAR2(100 BYTE), 
	"VAL33" VARCHAR2(100 BYTE), 
	"VAL34" VARCHAR2(100 BYTE), 
	"VAL35" VARCHAR2(100 BYTE), 
	"VAL36" VARCHAR2(100 BYTE), 
	"VAL37" VARCHAR2(100 BYTE), 
	"VAL38" VARCHAR2(100 BYTE), 
	"VAL39" VARCHAR2(100 BYTE), 
	"VAL40" VARCHAR2(100 BYTE), 
	"VAL41" VARCHAR2(100 BYTE), 
	"VAL42" VARCHAR2(100 BYTE), 
	"VAL43" VARCHAR2(100 BYTE), 
	"VAL44" VARCHAR2(100 BYTE), 
	"VAL45" VARCHAR2(100 BYTE), 
	"VAL46" VARCHAR2(100 BYTE), 
	"VAL47" VARCHAR2(100 BYTE), 
	"VAL48" VARCHAR2(100 BYTE), 
	"VAL49" VARCHAR2(100 BYTE), 
	"VAL50" VARCHAR2(100 BYTE), 
	"SEGMENT1" VARCHAR2(100 BYTE), 
	"SEGMENT2" VARCHAR2(100 BYTE), 
	"SEGMENT3" VARCHAR2(100 BYTE), 
	"SEGMENT4" VARCHAR2(100 BYTE), 
	"SEGMENT5" VARCHAR2(100 BYTE), 
	"SEGMENT6" VARCHAR2(100 BYTE), 
	"SEGMENT7" VARCHAR2(100 BYTE), 
	"SEGMENT8" VARCHAR2(100 BYTE), 
	"SEGMENT9" VARCHAR2(100 BYTE), 
	"SEGMENT10" VARCHAR2(100 BYTE), 
	"SEGMENT11" VARCHAR2(100 BYTE), 
	"SEGMENT12" VARCHAR2(100 BYTE), 
	"SEGMENT13" VARCHAR2(100 BYTE), 
	"SEGMENT14" VARCHAR2(100 BYTE), 
	"SEGMENT15" VARCHAR2(100 BYTE), 
	"SEGMENT16" VARCHAR2(100 BYTE), 
	"SEGMENT17" VARCHAR2(100 BYTE), 
	"SEGMENT18" VARCHAR2(100 BYTE), 
	"SEGMENT19" VARCHAR2(100 BYTE), 
	"SEGMENT20" VARCHAR2(100 BYTE), 
	"SEGMENT21" VARCHAR2(100 BYTE), 
	"SEGMENT22" VARCHAR2(100 BYTE), 
	"SEGMENT23" VARCHAR2(100 BYTE), 
	"SEGMENT24" VARCHAR2(100 BYTE), 
	"SEGMENT25" VARCHAR2(100 BYTE), 
	"SEGMENT26" VARCHAR2(100 BYTE), 
	"SEGMENT27" VARCHAR2(100 BYTE), 
	"SEGMENT28" VARCHAR2(100 BYTE), 
	"SEGMENT29" VARCHAR2(100 BYTE), 
	"SEGMENT30" VARCHAR2(100 BYTE), 
	"EBS_ASG_NUMBER" VARCHAR2(40 BYTE), 
	"OVERRIDE_ENTRY" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PAY_ELEM_ENTRIES_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PAY_ELEM_ENTRIES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_ADDRESS_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_ADDRESS_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(240 BYTE), 
	"TOWN_OR_CITY" VARCHAR2(30 BYTE), 
	"REGION_1" VARCHAR2(120 BYTE), 
	"COUNTRY" VARCHAR2(60 BYTE), 
	"POSTAL_CODE" VARCHAR2(30 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(10 BYTE), 
	"ADDRESS_STYLE" VARCHAR2(50 BYTE), 
	"ADDRESS_TYPE" VARCHAR2(50 BYTE), 
	"COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(240 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(240 BYTE), 
	"ADDRESS_LINE_4" VARCHAR2(240 BYTE), 
	"BUILDING" VARCHAR2(240 BYTE), 
	"FLOOR_NUMBER" VARCHAR2(40 BYTE), 
	"REGION_2" VARCHAR2(120 BYTE), 
	"REGION_3" VARCHAR2(120 BYTE), 
	"LONG_POSTAL_CODE" VARCHAR2(30 BYTE), 
	"TIMEZONE_CODE" VARCHAR2(50 BYTE), 
	"DERIVED_LOCALE" VARCHAR2(240 BYTE), 
	"GEOMETRY" VARCHAR2(80 BYTE), 
	"TELEPHONE_NUMBER_1" VARCHAR2(60 BYTE), 
	"TELEPHONE_NUMBER_2" VARCHAR2(60 BYTE), 
	"TELEPHONE_NUMBER_3" VARCHAR2(60 BYTE), 
	"DQ_VALIDATION_LEVEL" NUMBER, 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"BG_ID" NUMBER, 
	"ADDRESS_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ADDR_ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ADDR_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE2" VARCHAR2(30 BYTE), 
	"ADDR_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ADDR_ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ADDRESS_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ADDRESS_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP table  "XXMX_CORE"."XXMX_PER_AOR_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_AOR_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"ASGRESPONSIBILITYID" VARCHAR2(18 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"RESPONSIBILITYNAME" VARCHAR2(240 BYTE), 
	"ASSIGNMENTCATEGORY" VARCHAR2(30 BYTE), 
	"ASSIGNMENTID" VARCHAR2(18 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"BARGAININGUNIT" VARCHAR2(30 BYTE), 
	"BENEFITGROUPID" VARCHAR2(18 BYTE), 
	"BENEFITGROUPNAME" VARCHAR2(240 BYTE), 
	"BUSINESSUNITID" VARCHAR2(18 BYTE), 
	"BUSINESSUNITSHORTCODE" VARCHAR2(150 BYTE), 
	"COUNTRY" VARCHAR2(30 BYTE), 
	"DEPARTMENTHIERARCHYVERSIONNAME" VARCHAR2(240 BYTE), 
	"DEPARTMENTTREECODE" VARCHAR2(30 BYTE), 
	"WORKCONTACTSFLAG" VARCHAR2(30 BYTE), 
	"ENDDATE" VARCHAR2(20 BYTE), 
	"LASTNAMESTART" VARCHAR2(30 BYTE), 
	"GRADE_CODE" VARCHAR2(30 BYTE), 
	"GRADEID" VARCHAR2(18 BYTE), 
	"GRADESETCODE" VARCHAR2(30 BYTE), 
	"HIERARCHYLEVELS" VARCHAR2(2 BYTE), 
	"INCLUDETOPHIERNODE" VARCHAR2(30 BYTE), 
	"JOB_CODE" VARCHAR2(30 BYTE), 
	"JOBFAMILYCODE" VARCHAR2(240 BYTE), 
	"JOBFAMILYID" VARCHAR2(18 BYTE), 
	"JOBFUNCTIONCODE" VARCHAR2(240 BYTE), 
	"JOBID" VARCHAR2(30 BYTE), 
	"JOBSETCODE" VARCHAR2(18 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(30 BYTE), 
	"LEGALENTITYID" VARCHAR2(240 BYTE), 
	"LEGISLATIVEDATAGROUPID" VARCHAR2(18 BYTE), 
	"LEGISLATIVEDATAGROUPNAME" VARCHAR2(18 BYTE), 
	"LOCATION_CODE" VARCHAR2(240 BYTE), 
	"LOCATIONID" VARCHAR2(150 BYTE), 
	"TOPORGANIZATIONCLASSIFICATIONCODE" VARCHAR2(18 BYTE), 
	"TOPORGANIZATIONID" VARCHAR2(30 BYTE), 
	"TOPHIERARCHYORGANIZATIONNAME" VARCHAR2(40 BYTE), 
	"ORGANIZATIONTREECODE" VARCHAR2(18 BYTE), 
	"ORGANIZATIONHIERARCHYVERSIONNAME" VARCHAR2(240 BYTE), 
	"ORGANIZATIONID" VARCHAR2(30 BYTE), 
	"ORGANIZATIONNAME" VARCHAR2(30 BYTE), 
	"PAYROLLID" VARCHAR2(18 BYTE), 
	"PAYROLLNAME" VARCHAR2(240 BYTE), 
	"PAYROLLORGANIZATIONNAME" VARCHAR2(18 BYTE), 
	"PAYROLLSTATUNITID" VARCHAR2(80 BYTE), 
	"PERSONID" VARCHAR2(240 BYTE), 
	"POSITIONBUSINESSUNITSHORTCODE" VARCHAR2(18 BYTE), 
	"POSITION_CODE" VARCHAR2(18 BYTE), 
	"POSITIONHIERARCHYID" VARCHAR2(150 BYTE), 
	"POSITIONHIERARCHYVERSIONNAME" VARCHAR2(30 BYTE), 
	"POSITIONID" VARCHAR2(32 BYTE), 
	"POSITIONTREECODE" VARCHAR2(240 BYTE), 
	"RECRUITINGLOCHIERARCHY" VARCHAR2(18 BYTE), 
	"RECRUITINGLOCHIERARCHYID" VARCHAR2(30 BYTE), 
	"RECRUITINGORGHIERARCHY" VARCHAR2(360 BYTE), 
	"RECRUITINGORGHIERARCHYID" VARCHAR2(18 BYTE), 
	"RECRUITINGORGTREECODE" VARCHAR2(240 BYTE), 
	"RECORGTREESTRUCTURECODE" VARCHAR2(18 BYTE), 
	"RECRUITINGORGTREEVER" VARCHAR2(1000 BYTE), 
	"RECRUITINGTYPECODE" VARCHAR2(80 BYTE), 
	"RESPONSIBILITYTYPE" VARCHAR2(1000 BYTE), 
	"STARTDATE" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"TRU" VARCHAR2(240 BYTE), 
	"TAXREPORTINGUNITID" VARCHAR2(30 BYTE), 
	"LASTNAMEEND" VARCHAR2(240 BYTE), 
	"TOPDEPARTMENTID" VARCHAR2(18 BYTE), 
	"TOPHIERARCHYDEPARTMENTNAME" VARCHAR2(30 BYTE), 
	"TOPHIERARCHYPOSITIONBUSINESSUNITSHORTCODE" VARCHAR2(18 BYTE), 
	"TOPHIERARCHYPOSITIONCODE" VARCHAR2(240 BYTE), 
	"TOPMANAGERID" VARCHAR2(150 BYTE), 
	"TOPMANAGERNUMBER" VARCHAR2(30 BYTE), 
	"TOPPOSITIONID" VARCHAR2(18 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(30 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(18 BYTE), 
	"METADATA" VARCHAR2(2000 BYTE), 
	"OBJECTNAME" VARCHAR2(50 BYTE), 
	"ATTRIBUTE1" VARCHAR2(10 BYTE), 
	"ATTRIBUTE2" VARCHAR2(10 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_AOR_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_AOR_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_ASG_SALARY_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"DATE_FROM" VARCHAR2(20 BYTE), 
	"DATE_TO" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(80 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"NAME" VARCHAR2(240 BYTE), 
	"PAY_BASIS_TYPE" VARCHAR2(240 BYTE), 
	"MULTIPLE_COMPONENTS" VARCHAR2(30 BYTE), 
	"APPROVED" VARCHAR2(30 BYTE), 
	"PROPOSED_SALARY" NUMBER, 
	"NEXT_SAL_REVIEW_DATE" VARCHAR2(20 BYTE), 
	"FTE_VALUE" NUMBER, 
	"GRADE_VALUE" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(150 BYTE), 
	"PAYROLL_NAME" VARCHAR2(200 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"METADATA" VARCHAR2(15 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ASG_SALARY_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ASG_SALARY_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP table "XXMX_CORE"."XXMX_PER_ASG_SUP_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_ASG_SUP_F_EXT" 
   (	"PRIMARY_FLAG" VARCHAR2(30 BYTE), 
	"MANAGER_TYPE" VARCHAR2(30 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"MANAGER_ASG_NUMBER" VARCHAR2(80 BYTE), 
	"MANAGER_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(80 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"MANAGER_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"MANAGER_ID" VARCHAR2(264 BYTE), 
	"SUP_ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"SUP_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"SUP_ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ACTION_OCCURRENCE_ID" NUMBER, 
	"WORKING_PERCENTAGE" NUMBER, 
	"FREEZE_START_DATE" VARCHAR2(20 BYTE), 
	"FREEZE_UNTIL_DATE" VARCHAR2(20 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"BG_ID" NUMBER, 
	"ASSIGNMENT_SUPERVISOR_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ASG_SUP_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ASG_SUP_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_ASG_WORK_SCH_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_ASG_WORK_SCH_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" NUMBER, 
	"MIGRATION_STATUS" NUMBER, 
	"BG_NAME" NUMBER, 
	"BG_ID" VARCHAR2(30 BYTE), 
	"RESOURCETYPE" VARCHAR2(30 BYTE), 
	"SCHEDULENAME" VARCHAR2(240 BYTE), 
	"STARTDATE" NUMBER, 
	"ENDDATE" NUMBER, 
	"ASSIGNMENTNUMBER" NUMBER, 
	"ENTERPRISENAME" NUMBER, 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENTNAME" VARCHAR2(60 BYTE), 
	"INTERNALLOCATIONCODE" VARCHAR2(240 BYTE), 
	"LOCATIONSETCODE" VARCHAR2(240 BYTE), 
	"JOBCODE" VARCHAR2(240 BYTE), 
	"JOBSETCODE" VARCHAR2(240 BYTE), 
	"BUSINESSUNITNAME" VARCHAR2(240 BYTE), 
	"POSITIONCODE" VARCHAR2(240 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(10 BYTE), 
	"PERSONNUMBER" VARCHAR2(80 BYTE), 
	"WORKTERMSASSIGNMENTNUMBER" VARCHAR2(30 BYTE), 
	"METADATA" VARCHAR2(15 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ASG_WORK_SCH_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ASG_WORK_SCH_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP table  "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"PAYROLLNAME" VARCHAR2(100 BYTE), 
	"PERSONNUMBER" VARCHAR2(100 BYTE), 
	"WORKERCATEGORY" VARCHAR2(150 BYTE), 
	"GRADE_CODE" VARCHAR2(264 BYTE), 
	"GRADE_LADDER_PGM_NAME" VARCHAR2(264 BYTE), 
	"JOB_CODE" VARCHAR2(264 BYTE), 
	"POSITION_CODE" VARCHAR2(264 BYTE), 
	"LOCATION_CODE" VARCHAR2(264 BYTE), 
	"PEOPLE_GROUP_NAME" VARCHAR2(264 BYTE), 
	"USER_PERSON_TYPE" VARCHAR2(264 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"DEPARTMENT_NAME" VARCHAR2(264 BYTE), 
	"EMPLOYEE_CATEGORY" VARCHAR2(30 BYTE), 
	"EMPLOYMENT_CATEGORY" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_STATUS_TYPE_CODE" VARCHAR2(30 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(264 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"PRIMARY_WORK_TERMS_FLAG" VARCHAR2(30 BYTE), 
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(30 BYTE), 
	"PRIMARY_WORK_RELATION_FLAG" VARCHAR2(30 BYTE), 
	"SYSTEM_PERSON_TYPE" VARCHAR2(30 BYTE), 
	"BUSINESS_UNIT_NAME" VARCHAR2(264 BYTE), 
	"PROPOSED_WORKER_TYPE" VARCHAR2(30 BYTE), 
	"CONTRACTTYPE" VARCHAR2(100 BYTE), 
	"SPEC_CEILING_STEP" VARCHAR2(264 BYTE), 
	"COLLECT_AGREE_NAME" VARCHAR2(264 BYTE), 
	"RETIREMENT_DATE" VARCHAR2(20 BYTE), 
	"POSITION_OVERRIDE_FLAG" VARCHAR2(30 BYTE), 
	"EFFECTIVE_LATEST_CHANGE" VARCHAR2(30 BYTE), 
	"ALLOW_ASG_OVERRIDE_FLAG" VARCHAR2(30 BYTE), 
	"BARGAINING_UNIT_CODE" VARCHAR2(30 BYTE), 
	"LABOUR_UNION_MEMBER_FLAG" VARCHAR2(30 BYTE), 
	"CAGR_ID_FLEX_NUM" VARCHAR2(264 BYTE), 
	"MANAGER_FLAG" VARCHAR2(30 BYTE), 
	"DATE_PROBATION_END" VARCHAR2(20 BYTE), 
	"PROBATION_PERIOD" NUMBER, 
	"PROBATION_UNIT" VARCHAR2(30 BYTE), 
	"NORMAL_HOURS" NUMBER, 
	"FREQUENCY" VARCHAR2(30 BYTE), 
	"WORK_AT_HOME_FLAG" VARCHAR2(30 BYTE), 
	"TIME_NORMAL_FINISH" VARCHAR2(5 BYTE), 
	"TIME_NORMAL_START" VARCHAR2(5 BYTE), 
	"NOTICE_PERIOD" NUMBER, 
	"NOTICE_PERIOD_UOM" VARCHAR2(30 BYTE), 
	"DEFAULT_CODE_COMB_ID" VARCHAR2(264 BYTE), 
	"ESTABLISHMENT_ID" VARCHAR2(264 BYTE), 
	"HOURLY_SALARIED_CODE" VARCHAR2(30 BYTE), 
	"SAL_REVIEW_PERIOD" NUMBER, 
	"SAL_REVIEW_PERIOD_FREQUENCY" VARCHAR2(30 BYTE), 
	"JOB_POST_SOURCE_NAME" VARCHAR2(240 BYTE), 
	"PERSON_REFERRED_BY_ID" VARCHAR2(264 BYTE), 
	"PROJECTED_ASSIGNMENT_END" VARCHAR2(20 BYTE), 
	"VENDOR_ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"VENDOR_EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"RETIREMENT_AGE" NUMBER, 
	"EXPENSE_CHECK_ADDRESS" VARCHAR2(30 BYTE), 
	"INTERNAL_BUILDING" VARCHAR2(45 BYTE), 
	"INTERNAL_FLOOR" VARCHAR2(45 BYTE), 
	"INTERNAL_MAILSTOP" VARCHAR2(45 BYTE), 
	"INTERNAL_OFFICE_NUMBER" VARCHAR2(45 BYTE), 
	"LINKAGE_TYPE" VARCHAR2(30 BYTE), 
	"PROJECTED_START_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_SEQUENCE" NUMBER, 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"WORKTERMS_SSID" VARCHAR2(350 BYTE), 
	"WORKREL_SSID" VARCHAR2(350 BYTE), 
	"TRU" VARCHAR2(250 BYTE), 
	"ID_FLEX_NUM" NUMBER, 
	"BG_ID" NUMBER, 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERIOD_OF_SERVICE_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_STATUS_TYPE_ID" VARCHAR2(264 BYTE), 
	"JOB_ID" VARCHAR2(264 BYTE), 
	"LOCATION_ID" VARCHAR2(264 BYTE), 
	"POSITION_ID" VARCHAR2(264 BYTE), 
	"GRADE_ID" VARCHAR2(264 BYTE), 
	"GRADE_LADDER_PGM_ID" VARCHAR2(264 BYTE), 
	"PEOPLE_GROUP_ID" VARCHAR2(264 BYTE), 
	"COLLECTIVE_AGREEMENT_ID" VARCHAR2(264 BYTE), 
	"CAGR_GRADE_DEF_ID" VARCHAR2(264 BYTE), 
	"CONTRACT_ID" VARCHAR2(264 BYTE), 
	"PO_HEADER_ID" VARCHAR2(264 BYTE), 
	"PO_LINE_ID" VARCHAR2(264 BYTE), 
	"RECRUITER_ID" VARCHAR2(264 BYTE), 
	"RECRUITMENT_ACTIVITY_ID" VARCHAR2(264 BYTE), 
	"VACANCY_ID" NUMBER, 
	"APPLICANT_RANK" NUMBER, 
	"POSTING_CONTENT_ID" VARCHAR2(264 BYTE), 
	"SOURCE_ORGANIZATION_ID" VARCHAR2(264 BYTE), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"SET_OF_BOOKS_ID" VARCHAR2(264 BYTE), 
	"SOFT_CODING_KEYFLEX_ID" VARCHAR2(264 BYTE), 
	"SPECIAL_CEILING_STEP_ID" VARCHAR2(264 BYTE), 
	"VENDOR_ID" VARCHAR2(264 BYTE), 
	"VENDOR_SITE_ID" VARCHAR2(264 BYTE), 
	"ASS_ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ASS_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"WORK_TERMS_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ACTION_CODE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NAME" VARCHAR2(80 BYTE), 
	"AUTO_END_FLAG" VARCHAR2(30 BYTE), 
	"DUTIES_TYPE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_SEQUENCE" NUMBER, 
	"PARENT_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"PERSON_TYPE_ID" VARCHAR2(264 BYTE), 
	"REASON_CODE" VARCHAR2(30 BYTE), 
	"STEP_ENTRY_DATE" VARCHAR2(20 BYTE), 
	"TAX_ADDRESS_ID" VARCHAR2(264 BYTE), 
	"RECORD_CREATOR" VARCHAR2(30 BYTE), 
	"ACTION_OCCURRENCE_ID" NUMBER, 
	"CONTRACT_END_DATE" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ASSIGNMENTS_M_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ASSIGNMENTS_M_STG*.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_BANK_PAYMENT_METHOD_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_BANK_PAYMENT_METHOD_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"METADATA" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(150 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(150 BYTE), 
	"PERSON_NUMBER" VARCHAR2(150 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(50 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(50 BYTE), 
	"INFORMATION_TYPE" VARCHAR2(150 BYTE), 
	"PEI_INFORMATION_CATEGORY" VARCHAR2(150 BYTE), 
	"PAYMENT_METHODS" VARCHAR2(150 BYTE), 
	"BANK_NAME" VARCHAR2(250 BYTE), 
	"BRANCH_NAME" VARCHAR2(250 BYTE), 
	"IBAN" VARCHAR2(250 BYTE), 
	"BIC_SWIFT" VARCHAR2(250 BYTE), 
	"COUNTRY" VARCHAR2(250 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(150 BYTE), 
	"CATEGORY_CODE" VARCHAR2(50 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_BANK_PAYMENT_METHOD_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_BANK_PAYMENT_METHOD_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_EXT" 
   (	"METADATA" VARCHAR2(30 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"CONTACT_PERSONNUM" VARCHAR2(30 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"EFFECTIVESTARTDATE" VARCHAR2(30 BYTE), 
	"EFFECTIVEENDDATE" VARCHAR2(30 BYTE), 
	"CONTPERSONID" VARCHAR2(30 BYTE), 
	"ADDRESSTYPE" VARCHAR2(30 BYTE), 
	"ADDRESSLINE1" VARCHAR2(150 BYTE), 
	"ADDRESSLINE2" VARCHAR2(150 BYTE), 
	"ADDRESSLINE3" VARCHAR2(150 BYTE), 
	"TOWNORCITY" VARCHAR2(150 BYTE), 
	"REGION1" VARCHAR2(150 BYTE), 
	"COUNTRY" VARCHAR2(150 BYTE), 
	"POSTALCODE" VARCHAR2(150 BYTE), 
	"PRIMARYFLAG" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_CONTACT_ADDR_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_CONTACT_ADDR_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_CONTACT_PHONE_EXT" 
   (	"METADATA" VARCHAR2(30 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"CONTACT_PERSONNUM" VARCHAR2(30 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"DATEFROM" VARCHAR2(30 BYTE), 
	"DATETO" VARCHAR2(30 BYTE), 
	"CONTPERSONID" NUMBER, 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"COUNTRYCODENUMBER" VARCHAR2(30 BYTE), 
	"PHONETYPE" VARCHAR2(30 BYTE), 
	"PHONENUMBER" VARCHAR2(100 BYTE), 
	"PRIMARYFLAG" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_CONTACT_PHONE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_CONTACT_PHONE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_CONTACT_REL_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_CONTACT_REL_EXT" 
   (	"METADATA" VARCHAR2(30 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"CONTACT_PERSONNUM" VARCHAR2(30 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"EFFECTIVESTARTDATE" VARCHAR2(30 BYTE), 
	"EFFECTIVEENDDATE" VARCHAR2(30 BYTE), 
	"CONTPERSONID" NUMBER, 
	"RELATEDPERSONID" NUMBER, 
	"RELATEDPERSONNUM" VARCHAR2(80 BYTE), 
	"CONTACTTYPE" VARCHAR2(100 BYTE), 
	"EMERGENCYCONTACTFLAG" VARCHAR2(30 BYTE), 
	"PRIMARYCONTACTFLAG" VARCHAR2(30 BYTE), 
	"EXISTINGPERSON" VARCHAR2(30 BYTE), 
	"PERSONALFLAG" VARCHAR2(30 BYTE), 
	"SEQUENCENUMBER" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_CONTACT_REL_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_CONTACT_REL_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_CONTACTS_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_CONTACTS_EXT" 
   (	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(200 BYTE), 
	"PERSONNUMBER" VARCHAR2(80 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"PARTY_ID" VARCHAR2(264 BYTE), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(30 BYTE), 
	"BLOOD_TYPE" VARCHAR2(30 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"DATE_OF_DEATH" VARCHAR2(20 BYTE), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240 BYTE), 
	"REGION_OF_BIRTH" VARCHAR2(240 BYTE), 
	"TOWN_OF_BIRTH" VARCHAR2(240 BYTE), 
	"NAMETYPE" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(80 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(4 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"PRE_NAME_ADJUNCT" VARCHAR2(150 BYTE), 
	"SUFFIX" VARCHAR2(80 BYTE), 
	"KNOWN_AS" VARCHAR2(80 BYTE), 
	"PREVIOUS_LAST_NAME" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_CONTACTS_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_CONTACTS_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_EMAIL_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_EMAIL_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"DATE_FROM" VARCHAR2(20 BYTE), 
	"DATE_TO" VARCHAR2(20 BYTE), 
	"PERSON_ID" VARCHAR2(80 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"EMAIL_TYPE" VARCHAR2(30 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(240 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"MASTERED_IN_LDAP_FLAG" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_EMAIL_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_EMAIL_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_LEG_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_LEG_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(150 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(50 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(30 BYTE), 
	"BG_ID" VARCHAR2(240 BYTE), 
	"PERSON_LEGISLATIVE_ID" VARCHAR2(20 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"PERSON_ID" VARCHAR2(150 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"SEX" VARCHAR2(30 BYTE), 
	"MARITAL_STATUS" VARCHAR2(2000 BYTE), 
	"MARITAL_STATUS_DATE" VARCHAR2(80 BYTE), 
	"HIGHEST_EDUCATION_LEVEL" VARCHAR2(150 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(80 BYTE), 
	"METADATA" VARCHAR2(80 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(80 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(80 BYTE), 
	"PERSONNUMBER" VARCHAR2(240 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_LEG_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_LEG_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_NAMES_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_NAMES_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"NAME_TYPE" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(4 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(2000 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(80 BYTE), 
	"PRE_NAME_ADJUNCT" VARCHAR2(150 BYTE), 
	"SUFFIX" VARCHAR2(80 BYTE), 
	"KNOWN_AS" VARCHAR2(80 BYTE), 
	"PREVIOUS_LAST_NAME" VARCHAR2(150 BYTE), 
	"HONORS" VARCHAR2(80 BYTE), 
	"MILITARY_RANK" VARCHAR2(80 BYTE), 
	"DISPLAY_NAME" VARCHAR2(240 BYTE), 
	"LIST_NAME" VARCHAR2(240 BYTE), 
	"ORDER_NAME" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"CHAR_SET_CONTEXT" VARCHAR2(4 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_NAME_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_NAMES_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_NAMES_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_NID_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_NID_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"PLACE_OF_ISSUE" VARCHAR2(30 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"NATIONAL_IDENTIFIER_TYPE" VARCHAR2(30 BYTE), 
	"NATIONAL_IDENTIFIER_NUMBER" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(30 BYTE), 
	"ISSUE_DATE" VARCHAR2(20 BYTE), 
	"EXPIRATION_DATE" VARCHAR2(20 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"NATIONAL_IDENTIFIER_ID" VARCHAR2(264 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"BG_ID" NUMBER, 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_NID_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_NID_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_PAY_METHOD_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_PAY_METHOD_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSONNUMBER" VARCHAR2(150 BYTE), 
	"PERSONAL_PAYMENT_NAME" VARCHAR2(250 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(80 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"PAYROLL_SHIP_NUMBER" NUMBER, 
	"PAYMENT_AMOUNT_TYPE" VARCHAR2(30 BYTE), 
	"REMAINING_AMOUNT_FLAG" VARCHAR2(1 BYTE), 
	"ORG_PAYMENT_METHOD_CODE" VARCHAR2(100 BYTE), 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(80 BYTE), 
	"BANK_NUMBER" VARCHAR2(80 BYTE), 
	"BANK_NAME" VARCHAR2(80 BYTE), 
	"BRANCH_NAME" VARCHAR2(80 BYTE), 
	"CURRENCY_CODE" VARCHAR2(30 BYTE), 
	"SORT_CODE" VARCHAR2(30 BYTE), 
	"SEC_ACCOUNT_REF" VARCHAR2(80 BYTE), 
	"AMOUNT" NUMBER, 
	"PERCENTAGE" NUMBER, 
	"PRIORITY" NUMBER, 
	"RUN_TYPE_ID" NUMBER, 
	"PROCESSING_ORDER" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"METADATA" VARCHAR2(15 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_PAY_METHOD_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_PAY_METHOD_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_PERSONS_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_PERSONS_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"START_DATE" VARCHAR2(20 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(30 BYTE), 
	"BLOOD_TYPE" VARCHAR2(30 BYTE), 
	"DATE_OF_DEATH" VARCHAR2(20 BYTE), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240 BYTE), 
	"REGION_OF_BIRTH" VARCHAR2(240 BYTE), 
	"TOWN_OF_BIRTH" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"ACTION_CODE" VARCHAR2(100 BYTE), 
	"REASON_CODE" VARCHAR2(100 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PARTY_ID" VARCHAR2(264 BYTE), 
	"PERSON_TYPE" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_PERSONS_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_PERSONS_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_PHONES_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_PHONES_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"VALIDITY" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(4 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"DATE_FROM" VARCHAR2(20 BYTE), 
	"DATE_TO" VARCHAR2(20 BYTE), 
	"PHONE_TYPE" VARCHAR2(30 BYTE), 
	"PHONE_NUMBER" VARCHAR2(60 BYTE), 
	"COUNTRY_CODE_NUMBER" VARCHAR2(30 BYTE), 
	"EXTENSION" VARCHAR2(60 BYTE), 
	"SPEED_DIAL_NUMBER" VARCHAR2(60 BYTE), 
	"AREA_CODE" VARCHAR2(30 BYTE), 
	"SEARCH_PHONE_NUMBER" VARCHAR2(240 BYTE), 
	"MEANING" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"BG_ID" NUMBER, 
	"PHONE_ID" VARCHAR2(264 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_PHONES_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_PHONES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_SENIORITYDT_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"PERSONNUMBER" VARCHAR2(264 BYTE), 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"SENIORITYDATECODE" VARCHAR2(18 BYTE), 
	"ENTRYDATE" VARCHAR2(30 BYTE), 
	"EFFECTIVESTARTDATE" VARCHAR2(30 BYTE), 
	"EFFECTIVEENDDATE" VARCHAR2(30 BYTE), 
	"BUSINESSUNITSHORTCODE" VARCHAR2(30 BYTE), 
	"MANUALADJUSTMENTDAYS" VARCHAR2(100 BYTE), 
	"MANUALADJUSTMENTCOMMENTS" VARCHAR2(30 BYTE), 
	"LEGALEMPLOYERNAME" VARCHAR2(150 BYTE), 
	"DATESTART" VARCHAR2(100 BYTE), 
	"WORKERTYPE" VARCHAR2(100 BYTE), 
	"JOBCODE" VARCHAR2(30 BYTE), 
	"GRADECODE" VARCHAR2(30 BYTE), 
	"BARGAININGUNITCODE" VARCHAR2(30 BYTE), 
	"COLLECTIVEAGREEMENTCODE" VARCHAR2(30 BYTE), 
	"PERSONID" VARCHAR2(100 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(200 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_SENIORITYDT_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_SENIORITYDT_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP table  "XXMX_CORE"."XXMX_PER_TERMASG_WRKMSURE_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMASG_WRKMSURE_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSONNUMBER" VARCHAR2(150 BYTE), 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"UNIT" VARCHAR2(30 BYTE), 
	"VALUE" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(50 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(300 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(300 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMASG_WRKMSURE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMASG_WRKMSURE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_TERMASSIGN_M_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMASSIGN_M_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"PAYROLLNAME" VARCHAR2(100 BYTE), 
	"PERSONNUMBER" VARCHAR2(100 BYTE), 
	"WORKERCATEGORY" VARCHAR2(150 BYTE), 
	"GRADE_CODE" VARCHAR2(264 BYTE), 
	"GRADE_LADDER_PGM_NAME" VARCHAR2(264 BYTE), 
	"JOB_CODE" VARCHAR2(264 BYTE), 
	"POSITION_CODE" VARCHAR2(264 BYTE), 
	"LOCATION_CODE" VARCHAR2(264 BYTE), 
	"PEOPLE_GROUP_NAME" VARCHAR2(264 BYTE), 
	"USER_PERSON_TYPE" VARCHAR2(264 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"DEPARTMENT_NAME" VARCHAR2(264 BYTE), 
	"EMPLOYEE_CATEGORY" VARCHAR2(30 BYTE), 
	"EMPLOYMENT_CATEGORY" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_STATUS_TYPE_CODE" VARCHAR2(30 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(264 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"PRIMARY_WORK_TERMS_FLAG" VARCHAR2(30 BYTE), 
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(30 BYTE), 
	"PRIMARY_WORK_RELATION_FLAG" VARCHAR2(30 BYTE), 
	"SYSTEM_PERSON_TYPE" VARCHAR2(30 BYTE), 
	"BUSINESS_UNIT_NAME" VARCHAR2(264 BYTE), 
	"PROPOSED_WORKER_TYPE" VARCHAR2(30 BYTE), 
	"CONTRACTTYPE" VARCHAR2(100 BYTE), 
	"SPEC_CEILING_STEP" VARCHAR2(264 BYTE), 
	"COLLECT_AGREE_NAME" VARCHAR2(264 BYTE), 
	"RETIREMENT_DATE" VARCHAR2(20 BYTE), 
	"POSITION_OVERRIDE_FLAG" VARCHAR2(30 BYTE), 
	"EFFECTIVE_LATEST_CHANGE" VARCHAR2(30 BYTE), 
	"ALLOW_ASG_OVERRIDE_FLAG" VARCHAR2(30 BYTE), 
	"BARGAINING_UNIT_CODE" VARCHAR2(30 BYTE), 
	"LABOUR_UNION_MEMBER_FLAG" VARCHAR2(30 BYTE), 
	"CAGR_ID_FLEX_NUM" VARCHAR2(264 BYTE), 
	"MANAGER_FLAG" VARCHAR2(30 BYTE), 
	"DATE_PROBATION_END" VARCHAR2(20 BYTE), 
	"PROBATION_PERIOD" NUMBER, 
	"PROBATION_UNIT" VARCHAR2(30 BYTE), 
	"NORMAL_HOURS" NUMBER, 
	"FREQUENCY" VARCHAR2(30 BYTE), 
	"WORK_AT_HOME_FLAG" VARCHAR2(30 BYTE), 
	"TIME_NORMAL_FINISH" VARCHAR2(5 BYTE), 
	"TIME_NORMAL_START" VARCHAR2(5 BYTE), 
	"NOTICE_PERIOD" NUMBER, 
	"NOTICE_PERIOD_UOM" VARCHAR2(30 BYTE), 
	"DEFAULT_CODE_COMB_ID" VARCHAR2(264 BYTE), 
	"ESTABLISHMENT_ID" VARCHAR2(264 BYTE), 
	"HOURLY_SALARIED_CODE" VARCHAR2(30 BYTE), 
	"SAL_REVIEW_PERIOD" NUMBER, 
	"SAL_REVIEW_PERIOD_FREQUENCY" VARCHAR2(30 BYTE), 
	"JOB_POST_SOURCE_NAME" VARCHAR2(240 BYTE), 
	"PERSON_REFERRED_BY_ID" VARCHAR2(264 BYTE), 
	"PROJECTED_ASSIGNMENT_END" VARCHAR2(20 BYTE), 
	"VENDOR_ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"VENDOR_EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"RETIREMENT_AGE" NUMBER, 
	"EXPENSE_CHECK_ADDRESS" VARCHAR2(30 BYTE), 
	"INTERNAL_BUILDING" VARCHAR2(45 BYTE), 
	"INTERNAL_FLOOR" VARCHAR2(45 BYTE), 
	"INTERNAL_MAILSTOP" VARCHAR2(45 BYTE), 
	"INTERNAL_OFFICE_NUMBER" VARCHAR2(45 BYTE), 
	"LINKAGE_TYPE" VARCHAR2(30 BYTE), 
	"PROJECTED_START_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_SEQUENCE" NUMBER, 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"WORKTERMS_SSID" VARCHAR2(350 BYTE), 
	"WORKREL_SSID" VARCHAR2(350 BYTE), 
	"TRU" VARCHAR2(250 BYTE), 
	"ID_FLEX_NUM" NUMBER, 
	"BG_ID" NUMBER, 
	"ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PERIOD_OF_SERVICE_ID" VARCHAR2(264 BYTE), 
	"ASSIGNMENT_STATUS_TYPE_ID" VARCHAR2(264 BYTE), 
	"JOB_ID" VARCHAR2(264 BYTE), 
	"LOCATION_ID" VARCHAR2(264 BYTE), 
	"POSITION_ID" VARCHAR2(264 BYTE), 
	"GRADE_ID" VARCHAR2(264 BYTE), 
	"GRADE_LADDER_PGM_ID" VARCHAR2(264 BYTE), 
	"PEOPLE_GROUP_ID" VARCHAR2(264 BYTE), 
	"COLLECTIVE_AGREEMENT_ID" VARCHAR2(264 BYTE), 
	"CAGR_GRADE_DEF_ID" VARCHAR2(264 BYTE), 
	"CONTRACT_ID" VARCHAR2(264 BYTE), 
	"PO_HEADER_ID" VARCHAR2(264 BYTE), 
	"PO_LINE_ID" VARCHAR2(264 BYTE), 
	"RECRUITER_ID" VARCHAR2(264 BYTE), 
	"RECRUITMENT_ACTIVITY_ID" VARCHAR2(264 BYTE), 
	"VACANCY_ID" NUMBER, 
	"APPLICANT_RANK" NUMBER, 
	"POSTING_CONTENT_ID" VARCHAR2(264 BYTE), 
	"SOURCE_ORGANIZATION_ID" VARCHAR2(264 BYTE), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"SET_OF_BOOKS_ID" VARCHAR2(264 BYTE), 
	"SOFT_CODING_KEYFLEX_ID" VARCHAR2(264 BYTE), 
	"SPECIAL_CEILING_STEP_ID" VARCHAR2(264 BYTE), 
	"VENDOR_ID" VARCHAR2(264 BYTE), 
	"VENDOR_SITE_ID" VARCHAR2(264 BYTE), 
	"ASS_ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ASS_ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ASS_ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"WORK_TERMS_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ACTION_CODE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NAME" VARCHAR2(80 BYTE), 
	"AUTO_END_FLAG" VARCHAR2(30 BYTE), 
	"DUTIES_TYPE" VARCHAR2(30 BYTE), 
	"EFFECTIVE_SEQUENCE" NUMBER, 
	"PARENT_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"PERSON_TYPE_ID" VARCHAR2(264 BYTE), 
	"REASON_CODE" VARCHAR2(30 BYTE), 
	"STEP_ENTRY_DATE" VARCHAR2(20 BYTE), 
	"TAX_ADDRESS_ID" VARCHAR2(264 BYTE), 
	"RECORD_CREATOR" VARCHAR2(30 BYTE), 
	"ACTION_OCCURRENCE_ID" NUMBER, 
	"CONTRACT_END_DATE" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMASSIGN_M_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMASSIGN_M_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table  "XXMX_CORE"."XXMX_PER_TERMLEG_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMLEG_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(150 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(50 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(30 BYTE), 
	"BG_ID" VARCHAR2(240 BYTE), 
	"PERSON_LEGISLATIVE_ID" VARCHAR2(20 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"PERSON_ID" VARCHAR2(150 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"SEX" VARCHAR2(30 BYTE), 
	"MARITAL_STATUS" VARCHAR2(2000 BYTE), 
	"MARITAL_STATUS_DATE" VARCHAR2(80 BYTE), 
	"HIGHEST_EDUCATION_LEVEL" VARCHAR2(150 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(80 BYTE), 
	"METADATA" VARCHAR2(80 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(80 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(80 BYTE), 
	"PERSONNUMBER" VARCHAR2(240 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMLEG_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMLEG_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_TERMNAMES_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMNAMES_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"NAME_TYPE" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(20 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(4 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(2000 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(80 BYTE), 
	"PRE_NAME_ADJUNCT" VARCHAR2(150 BYTE), 
	"SUFFIX" VARCHAR2(80 BYTE), 
	"KNOWN_AS" VARCHAR2(80 BYTE), 
	"PREVIOUS_LAST_NAME" VARCHAR2(150 BYTE), 
	"HONORS" VARCHAR2(80 BYTE), 
	"MILITARY_RANK" VARCHAR2(80 BYTE), 
	"DISPLAY_NAME" VARCHAR2(240 BYTE), 
	"LIST_NAME" VARCHAR2(240 BYTE), 
	"ORDER_NAME" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"CHAR_SET_CONTEXT" VARCHAR2(4 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_NAME_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMNAMES_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMNAMES_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_TERMNID_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMNID_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"PLACE_OF_ISSUE" VARCHAR2(30 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"NATIONAL_IDENTIFIER_TYPE" VARCHAR2(30 BYTE), 
	"NATIONAL_IDENTIFIER_NUMBER" VARCHAR2(30 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(30 BYTE), 
	"ISSUE_DATE" VARCHAR2(20 BYTE), 
	"EXPIRATION_DATE" VARCHAR2(20 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"NATIONAL_IDENTIFIER_ID" VARCHAR2(264 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"BG_ID" NUMBER, 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMNID_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMNID_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_TERMPERSONS_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMPERSONS_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"START_DATE" VARCHAR2(20 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(30 BYTE), 
	"BLOOD_TYPE" VARCHAR2(30 BYTE), 
	"DATE_OF_DEATH" VARCHAR2(20 BYTE), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240 BYTE), 
	"REGION_OF_BIRTH" VARCHAR2(240 BYTE), 
	"TOWN_OF_BIRTH" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"ACTION_CODE" VARCHAR2(100 BYTE), 
	"REASON_CODE" VARCHAR2(100 BYTE), 
	"BG_ID" NUMBER, 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"PARTY_ID" VARCHAR2(264 BYTE), 
	"PERSON_TYPE" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMPERSONS_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMPERSONS_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_TERMWORKREL_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_TERMWORKREL_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"PAYROLL_NAME" VARCHAR2(100 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(30 BYTE), 
	"DATE_START" VARCHAR2(20 BYTE), 
	"ACCEPTED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"ACTUAL_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(264 BYTE), 
	"ON_MILITARY_SERVICE_FLAG" VARCHAR2(30 BYTE), 
	"ORIGINAL_DATE_OF_HIRE" VARCHAR2(20 BYTE), 
	"PERIOD_TYPE" VARCHAR2(30 BYTE), 
	"REHIRE_AUTHORIZOR" VARCHAR2(30 BYTE), 
	"REHIRE_REASON" VARCHAR2(60 BYTE), 
	"REHIRE_RECOMMENDATION_FLAG" VARCHAR2(30 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"REHIRE_AUTHORIZER_PERSON_ID" VARCHAR2(264 BYTE), 
	"REVOKE_USER_ACCESS" VARCHAR2(30 BYTE), 
	"NOTIFIED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"PROJECTED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"DATE_EMPLOYEE_DATA_VERIFIED" VARCHAR2(20 BYTE), 
	"WORKER_TYPE" VARCHAR2(30 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"FAST_PATH_EMPLOYEE" VARCHAR2(30 BYTE), 
	"LAST_WORKING_DATE" VARCHAR2(20 BYTE), 
	"WORKER_NUMBER" VARCHAR2(30 BYTE), 
	"ACTION_OCCURRENCE_ID" VARCHAR2(264 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"BG_ID" NUMBER, 
	"PERIOD_OF_SERVICE_ID" VARCHAR2(264 BYTE), 
	"TERMINATION_ACCEPTED_PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ADJUSTED_SVC_DATE" VARCHAR2(20 BYTE), 
	"ACTION_CODE" VARCHAR2(30 BYTE), 
	"REASON_CODE" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_TERMWORKREL_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_TERMWORKREL_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;

DROP table "XXMX_CORE"."XXMX_PER_WORKREL_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_WORKREL_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"PAYROLL_NAME" VARCHAR2(100 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(150 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(30 BYTE), 
	"DATE_START" VARCHAR2(20 BYTE), 
	"ACCEPTED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"ACTUAL_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(264 BYTE), 
	"ON_MILITARY_SERVICE_FLAG" VARCHAR2(30 BYTE), 
	"ORIGINAL_DATE_OF_HIRE" VARCHAR2(20 BYTE), 
	"PERIOD_TYPE" VARCHAR2(30 BYTE), 
	"REHIRE_AUTHORIZOR" VARCHAR2(30 BYTE), 
	"REHIRE_REASON" VARCHAR2(60 BYTE), 
	"REHIRE_RECOMMENDATION_FLAG" VARCHAR2(30 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"REHIRE_AUTHORIZER_PERSON_ID" VARCHAR2(264 BYTE), 
	"REVOKE_USER_ACCESS" VARCHAR2(30 BYTE), 
	"NOTIFIED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"PROJECTED_TERMINATION_DATE" VARCHAR2(20 BYTE), 
	"DATE_EMPLOYEE_DATA_VERIFIED" VARCHAR2(20 BYTE), 
	"WORKER_TYPE" VARCHAR2(30 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(350 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(50 BYTE), 
	"FAST_PATH_EMPLOYEE" VARCHAR2(30 BYTE), 
	"LAST_WORKING_DATE" VARCHAR2(20 BYTE), 
	"WORKER_NUMBER" VARCHAR2(30 BYTE), 
	"ACTION_OCCURRENCE_ID" VARCHAR2(264 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(100 BYTE), 
	"BG_ID" NUMBER, 
	"PERIOD_OF_SERVICE_ID" VARCHAR2(264 BYTE), 
	"TERMINATION_ACCEPTED_PERSON_ID" VARCHAR2(264 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(20 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" VARCHAR2(20 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ADJUSTED_SVC_DATE" VARCHAR2(20 BYTE), 
	"ACTION_CODE" VARCHAR2(30 BYTE), 
	"REASON_CODE" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_WORKREL_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_WORKREL_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP TABLE "XXMX_CORE"."XXMX_PER_CONTACT_NAMES_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_CONTACT_NAMES_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER, 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(30 BYTE), 
	"RELATEDPERSONNUM" VARCHAR2(80 BYTE), 
	"CONTACT_PERSONNUM" VARCHAR2(80 BYTE), 
	"PERSON_ID" VARCHAR2(150 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(20 BYTE), 
	"PARTY_ID" VARCHAR2(264 BYTE), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(30 BYTE), 
	"BLOOD_TYPE" VARCHAR2(30 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"DATE_OF_DEATH" VARCHAR2(20 BYTE), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240 BYTE), 
	"REGION_OF_BIRTH" VARCHAR2(240 BYTE), 
	"TOWN_OF_BIRTH" VARCHAR2(240 BYTE), 
	"NAMETYPE" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(80 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(4 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"PRE_NAME_ADJUNCT" VARCHAR2(150 BYTE), 
	"SUFFIX" VARCHAR2(80 BYTE), 
	"KNOWN_AS" VARCHAR2(80 BYTE), 
	"PREVIOUS_LAST_NAME" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_CONTACT_NAMES_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_CONTACT_NAMES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP TABLE "XXMX_CORE"."XXMX_PER_VISA_F_EXT" ;
  CREATE TABLE "XXMX_CORE"."XXMX_PER_VISA_F_EXT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"VISAPERMITTYPE" VARCHAR2(30 BYTE), 
	"EFFECTIVESTARTDATE" VARCHAR2(240 BYTE), 
	"EFFECTIVEENDDATE" VARCHAR2(240 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"ENTRYDATE" VARCHAR2(240 BYTE), 
	"EXPIRATIONDATE" VARCHAR2(240 BYTE), 
	"CURRENTVISAPERMIT" VARCHAR2(30 BYTE), 
	"ISSUEDATE" VARCHAR2(240 BYTE), 
	"ISSUINGAUTHORITY" VARCHAR2(30 BYTE), 
	"ISSUINGCOUNTRY" VARCHAR2(30 BYTE), 
	"ISSUINGLOCATION" VARCHAR2(100 BYTE), 
	"PROFESSION" VARCHAR2(30 BYTE), 
	"VISAPERMITCATEGORY" VARCHAR2(30 BYTE), 
	"VISAPERMITNUMBER" VARCHAR2(30 BYTE), 
	"VISAPERMITSTATUS" VARCHAR2(30 BYTE), 
	"VISAPERMITSTATUSDATE" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"PERSON_ID" VARCHAR2(150 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(30 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_VISA_F_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_VISA_F_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


DROP TABLE XXMX_CORE.XXMX_PER_ASG_WORK_SCH_EXT;
CREATE TABLE XXMX_CORE.XXMX_PER_ASG_WORK_SCH_EXT
(
FILE_SET_ID	VARCHAR2(30),
MIGRATION_SET_NAME                   	VARCHAR2(150),
MIGRATION_STATUS	VARCHAR2(50),
RESOURCETYPE	VARCHAR2(30),
SCHEDULENAME	VARCHAR2(240),
STARTDATE	VARCHAR2(20),
ENDDATE	VARCHAR2(20),
ASSIGNMENTNUMBER	VARCHAR2(80),
PRIMARY_FLAG	VARCHAR2(10),
PERSONNUMBER	VARCHAR2(80),
METADATA	VARCHAR2(10),
OBJECTNAME	VARCHAR2(50),
SOURCESYSTEMID	VARCHAR2(2000),
SOURCESYSTEMOWNER	VARCHAR2(50)
)
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_ASG_WORK_SCH_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ASG_WORK_SCH_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  CREATE TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_EXT" 
   (	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"STARTDATEDURATION" NUMBER, 
	"ENDDATEDURATION" NUMBER, 
	"ABSENCEREASON" VARCHAR2(1000 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"LEAVE_DURATION" NUMBER, 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"EMPLOYER" VARCHAR2(150 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"ABSENCESTATUS" VARCHAR2(100 BYTE), 
	"APPROVALSTATUS" VARCHAR2(100 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"STARTTIME" VARCHAR2(100 BYTE), 
	"ENDDATE" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(100 BYTE), 
	"ABSENCETYPE" VARCHAR2(100 BYTE), 
	"OPEN_ENDED_FLAG" VARCHAR2(30 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline logfile 'XXMX_PER_ABSENCE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_ABSENCE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;



  CREATE TABLE "XXMX_CORE"."XXMX_PER_MAT_ABSENCE_EXT" 
   (	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(350 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"STARTDATEDURATION" NUMBER, 
	"ENDDATEDURATION" NUMBER, 
	"PLANNEDENDDATE" DATE, 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"LEAVE_DURATION" NUMBER, 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"EMPLOYER" VARCHAR2(150 BYTE), 
	"INTENDTORETFLAG" VARCHAR2(30 BYTE), 
	"ACTUAL_BIRTH_DATE" VARCHAR2(20 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"ABSENCESTATUS" VARCHAR2(100 BYTE), 
	"APPROVALSTATUS" VARCHAR2(100 BYTE), 
	"STARTDATE" VARCHAR2(20 BYTE), 
	"STARTTIME" VARCHAR2(100 BYTE), 
	"ENDDATE" VARCHAR2(20 BYTE), 
	"ENDTIME" VARCHAR2(100 BYTE), 
	"ABSENCETYPE" VARCHAR2(100 BYTE), 
	"ACTUAL_START_DATE" VARCHAR2(20 BYTE), 
	"ACTUAL_RETURN_DATE" VARCHAR2(20 BYTE), 
	"OPEN_ENDED_FLAG" VARCHAR2(30 BYTE), 
	"EXPECTED_DATE_OF_CHILD_BIRTH" VARCHAR2(20 BYTE), 
	"AVERAGE_EARNINGS" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_PER_MAT_ABSENCE_STG.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_PER_MAT_ABSENCE_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;









