
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_HR_HCM_SUPERVISOR_HDL_V" ("METADATA") AS 
  select 'METADATA|AssignmentSupervisor|SourceSystemOwner|SourceSystemId|AssignmentId(SourceSystemId)|EffectiveStartDate|EffectiveEndDate|ManagerType|PrimaryFlag|ManagerPersonNumber' METADATA FROM DUAL
UNION ALL
SELECT 'MERGE|AssignmentSupervisor|EBS|'||PERSONNUMBER||'-'||ASG_TYPE||ASG_NUMBER||'|Assignment-'||ASG_TYPE||ASG_NUMBER||'|'||
START_DATE||'|'||END_DATE||'|LINE_MANAGER|Y|'||MANAGER_PERSON_NUMBER val
FROM(
SELECT SUP.PERSONNUMBER,
CASE WHEN
(SELECT UNIQUE USER_PERSON_TYPE FROM XXMX_PER_ASSIGNMENTS_M_XFM WHERE PERSONNUMBER = SUP.PERSONNUMBER AND ACTION_CODE='CURRENT') ='Employee'
then 'E'
when (SELECT UNIQUE USER_PERSON_TYPE FROM XXMX_PER_ASSIGNMENTS_M_XFM WHERE PERSONNUMBER = SUP.PERSONNUMBER AND ACTION_CODE='CURRENT') ='Contingent Worker'
then 'C'
else 'N' end asg_type
,NVL(ASG.MAX_ASG_NUM,SUP.ASSIGNMENT_NUMBER) ASG_NUMBER
,TO_CHAR(EFFECTIVE_START_DATE,'RRRR/MM/DD') start_date
,TO_CHAR(EFFECTIVE_END_DATE,'RRRR/MM/DD') end_date,SUP.MANAGER_PERSON_NUMBER
--SUP.PERSONNUMBER,ASG.PERSON_NUMBER,NVL(ASG.MAX_ASG_NUM,SUP.ASSIGNMENT_NUMBER)
FROM xxmx_per_asg_sup_f_stg SUP,XX_HISTORY_MAX_ASG_NUM ASG
WHERE 1=1--SUP.PERSONNUMBER IN('111','10004','10007')
AND SUP.PERSONNUMBER = ASG.PERSON_NUMBER(+)
AND SUP.MANAGER_PERSON_NUMBER IS NOT NULL);

