CREATE INDEX XXMX_CONTACT_POINTS_N1 ON XXMX_HZ_CONTACT_POINTS (OWNER_TABLE_ID, CONTACT_POINT_TYPE, PRIMARY_FLAG, OWNER_TABLE_NAME, STATUS, 
                                                   CONTACT_POINT_PURPOSE, PRIMARY_BY_PURPOSE);
												   
CREATE INDEX XXMX_CONTACT_POINTS_N10 ON XXMX_HZ_CONTACT_POINTS (EFT_SWIFT_CODE);
CREATE INDEX XXMX_CONTACT_POINTS_N11 ON XXMX_HZ_CONTACT_POINTS (UPPER("EMAIL_ADDRESS"));
CREATE INDEX XXMX_CONTACT_POINTS_N12 ON XXMX_HZ_CONTACT_POINTS ("LAST_UPDATE_DATE", CONTACT_POINT_ID, STATUS);
CREATE INDEX XXMX_CONTACT_POINTS_N13 ON XXMX_HZ_CONTACT_POINTS (CONTACT_POINT_TYPE, UPPER("URL"));

CREATE INDEX XXMX_CONTACT_POINTS_N17 ON XXMX_HZ_CONTACT_POINTS (REQUEST_ID);


