--
--
--*****************************************************************************
--**
--**                 Copyright (c) 2022 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  XXMX_hCM_pay_dbi.sql
--**
--** FILEPATH  :  ????
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  XXMX_XFM
--**
--** AUTHORS   :  
--**
--** PURPOSE   :  This script installs the XXMX_XFM DB Objects for the Maximise
--**              Inventory Transaction Data Migration.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    None
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--** [ 1.0  DD-Mon-YYYY  Change Author       Created.                          ]
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  ------------------------------------------------------------
--**   
--**
--*******************************************************************************************************
--


  CREATE TABLE "XXMX_PAY_PENSION_UPLIFT_DATA" 
   (	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"PERCENTAGE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;
/


  CREATE TABLE "XXMX_PAY_PENS_OVERRIDE" 
   (	"PERSON_NUMBER" NUMBER, 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"EE_PERCENT" NUMBER, 
	"ER_PERCENT" NUMBER, 
	"OVERRIDE_PERCENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;
 / 
  
  
  CREATE TABLE "XXMX_PAY_EBS_FUS_PE_PENSCH" 
   (	"EBS_PENSION" VARCHAR2(300 BYTE), 
	"FUSION_PENSION" VARCHAR2(300 BYTE), 
	"FUSION_PENSION_SCHEME_ID" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(10 BYTE),
	"PAYROLL_NAME" VARCHAR2(100),
    "5050_Flag" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/


  

  CREATE TABLE "XXMX_PAY_LOOKUP_MAP" 
   (	"ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"INPUT_VALUE" VARCHAR2(100 BYTE), 
	"EBS_VALUE" VARCHAR2(100 BYTE), 
	"FUSION_LOOKUP_CODE" VARCHAR2(100 BYTE), 
	"FUSION_MEANING" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/


  CREATE TABLE "XXMX_PAY_FUSION_ELEM_INP_VALS" 
   (	"FUSION_ELEMENT_NAME" VARCHAR2(200 BYTE), 
	"FUSION_INPUT_VALUE_NAME" VARCHAR2(200 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(200 BYTE), 
	"INPUT_VALUE_RANK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/


  CREATE TABLE "XXMX_PAY_FUSION_EBS_ASG_MAP" 
   (	"FUSION_ASG_NUMBER" VARCHAR2(100 BYTE), 
	"EBS_ASG_NUMBER" VARCHAR2(100 BYTE), 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"USER_PERSON_TYPE" VARCHAR2(100 BYTE), 
	"ASG_ORG" VARCHAR2(1000 BYTE), 
	"FUSION_ASG_WITHOUT_E" VARCHAR2(100 BYTE), 
	"CHECK_VALUE" VARCHAR2(100 BYTE), 
	"LEGAL_EMPLOYER" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
/



  CREATE TABLE "XXMX_PAY_FUSION_DEPT_COST_CTRS" 
   (	"EFFECTIVE_START_DATE" VARCHAR2(100 BYTE), 
	"DEPARTMENT_SET_CODE" VARCHAR2(100 BYTE), 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"COST_CENTRE" VARCHAR2(100 BYTE), 
	"COST_CENTRE_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/


EXEC DropTable ('XXMX_PAY_EBS_PAE_DTLS_TEMP')
  
  CREATE Global Temporary TABLE "XXMX_PAY_EBS_PAE_DTLS_TEMP" 
   (	"ASSIGNMENT_NUMBER" VARCHAR2(90 BYTE), 
	"ELEMENT_NAME" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"PAE_AGGEARN_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_AUTO_ENRL_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_ELIJ_JOB_HOLD_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_ENTRY_FOR_AGG_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_OPT_OUT_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_OPT_OUT_PERIOD_END_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_OPT_IN_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_PENS_CLASS_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_POSTPN_END_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_POSTPN_TYPE_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_QUAL_SCHM_NAME_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_QUAL_SCHM_EXISTS_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_TOT_EARN_PRP_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_MEMBER_END_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_EXCLUSION_RSN_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"FUSION_ASG_NUMBER" VARCHAR2(93 BYTE)
   )  ON COMMIT DELETE ROWS ;

/


  CREATE TABLE "XXMX_PAY_EBS_PAE_ALL_ROWS_DTLS_V" 
   (	"ASSIGNMENT_NUMBER" VARCHAR2(90 BYTE), 
	"ELEMENT_NAME" VARCHAR2(240 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"PAE_OPT_OUT_DT_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE), 
	"PAE_QUAL_SCHM_NAME_SCRN_ENTRY_VAL" VARCHAR2(180 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/




  CREATE TABLE "XXMX_PAY_EBS_BALANCES" 
   (	"MIGRATION_SET_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BALANCE_NAME" VARCHAR2(80 BYTE), 
	"ASSIGNMENT_ID" NUMBER(10,0), 
	"BALANCE_VALUE" NUMBER, 
	"DIMENSION_NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"ASSIGNMENT_ACTION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"PAYROLL_ACTION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"BALANCE_TYPE_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"BALANCE_DIMENSION_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"DEFINED_BALANCE_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"EBS_ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"CURSOR_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/


  CREATE TABLE "XXMX_PAY_BALANCES_MAP" 
   (	"EBS_BALANCE_NAME" VARCHAR2(200 BYTE), 
	"EBS_BALANCE_DIMENSION" VARCHAR2(50 BYTE), 
	"FUSION_BALANCE_NAME" VARCHAR2(200 BYTE), 
	"FUSION_BALANCE_DIMENSION" VARCHAR2(50 BYTE),
	"ENABLED_FLAG"  VARCHAR2(20 BYTE),
	"BALANCE_TYPE"  VARCHAR2(100),
	"EBS_ELEMENT_NAME"  VARCHAR2(300)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;

/

  CREATE TABLE "XXMX_PAY_BALANCE_PERIODS" 
   (	"EFFECTIVE_DATE" DATE, 
	"PERIOD" VARCHAR2(7 BYTE)
	"PAYROLLNAME" VARCHAR2(100)
   ) as
select distinct prb.effective_date, NULL PERIOD, ppf.payroll_name
from pay_run_balances@mxdm_nvis_extract prb
    ,per_all_Assignments_f@mxdm_nvis_extract paaf
    ,pay_payrolls_f@mxdm_nvis_extract ppf
where prb.assignment_id = paaf.assignment_id 
and paaf.payroll_id = ppf.payroll_id
and prb.effective_date BETWEEN '01-APR-2020'  AND '28-FEB-2021'
and  trunc(sysdate) between paaf.effective_start_date and paaf.effective_end_date
and  trunc(sysdate) between ppf.effective_start_date and ppf.effective_end_date;

/



  CREATE TABLE "XXMX_PAY_BALANCE_CONTEXTS" 
   (	"ASSIGNMENTNUMBER" VARCHAR2(100 BYTE), 
	"TERMNUMBER" VARCHAR2(100 BYTE), 
	"PAYROLLRELATIONSHIPNUMBER" VARCHAR2(100 BYTE), 
	"EMPLOYEE_HIRE_DATE" VARCHAR2(100 BYTE), 
	"AGGREGATION_INFORMATION" NUMBER, 
	"NI_CATEGORY" VARCHAR2(100 BYTE), 
	"PENSION_BASIS" VARCHAR2(100 BYTE), 
	"PROCESS_TYPE" VARCHAR2(100 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(100 BYTE), 
	"NI_REPORTING_HMRC_PAYROLL_ID" NUMBER, 
	"PAYROLL_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/

  CREATE TABLE "XXMX_EBS_PAE_EXCLUSION_LIST_EMP" 
   (	"PERSON_NUMBER" VARCHAR2(80 BYTE), 
	"PAYROLL" VARCHAR2(80 BYTE), 
	"REASON_FOR_EXCLUSION" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;

/

  CREATE TABLE "XXMX_FUSION_CALC_CARD_BP_DTLS" 
   (	"ASSIGNMENT_NUMBER" VARCHAR2(240 BYTE), 
	"PAYROLL_RELATIONSHIP_NUMBER" VARCHAR2(240 BYTE), 
	"DISPLAY_NAME" VARCHAR2(240 BYTE), 
	"DIR_CARD_ID" VARCHAR2(240 BYTE), 
	"CARD_EFFECTIVE_START_DATE" DATE, 
	"CARD_EFFECTIVE_END_DATE" DATE, 
	"DIR_CARD_COMP_ID" VARCHAR2(240 BYTE), 
	"CONTEXT_VALUE1" VARCHAR2(240 BYTE), 
	"CARD_COMP_EFFECTIVE_START_DATE" DATE, 
	"CARD_COMP_EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;

/

  CREATE TABLE "XXMX_FUSION_CALC_CARD_PAE_DTLS" 
   (	"DISPLAY_NAME" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CALC_CARD" VARCHAR2(200 BYTE), 
	"LDG" VARCHAR2(200 BYTE), 
	"PAYROLL_RELATIONSHIP_NUMBER" VARCHAR2(200 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(200 BYTE), 
	"DIR_CARD_ID" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_OWNER_CALC_CARD" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_ID_CALC_CARD" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CARD_COMP" VARCHAR2(200 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"DIR_CARD_COMP_ID" VARCHAR2(200 BYTE), 
	"COMPONENT_NAME" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_OWNER_CARD_COMP" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_ID_CARD_COMP" VARCHAR2(200 BYTE), 
	"CONTEXT_VALUE1" VARCHAR2(200 BYTE), 
	"CONTEXT_VALUE2" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CARD_COMP_DTLS" VARCHAR2(200 BYTE), 
	"DIR_COMP_DETAIL_ID" VARCHAR2(200 BYTE), 
	"DIR_INFORMATION_CATEGORY" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_OWNER_CARD_COMP_DTLS" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_ID_CARD_COMP_DTLS" VARCHAR2(200 BYTE), 
	"TRU" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/

  CREATE TABLE "XXMX_FUSION_CALC_CARD_PAYE_NI_DTLS" 
   (	"DISPLAY_NAME" VARCHAR2(200 BYTE), 
	"PAYROLL_RELATIONSHIP_NUMBER" VARCHAR2(200 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(200 BYTE), 
	"DIR_CARD_ID" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CALCULATIONCARD" VARCHAR2(200 BYTE), 
	"LDG" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CARDCOMPONENT" VARCHAR2(200 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"DIR_CARD_COMP_ID" VARCHAR2(200 BYTE), 
	"COMPONENT_NAME" VARCHAR2(200 BYTE), 
	"PARENT_COMPONENT_NAME" VARCHAR2(200 BYTE), 
	"CONTEXT_VALUE1" VARCHAR2(200 BYTE), 
	"CONTEXT_VALUE2" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CARDCOMPONENTDETAILS" VARCHAR2(200 BYTE), 
	"DIR_COMP_DETAIL_ID" VARCHAR2(200 BYTE), 
	"OBJECT_NAME_CARDASSOCATIONS" VARCHAR2(200 BYTE), 
	"DIR_REP_CARD_ID" VARCHAR2(200 BYTE), 
	"TRU" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;

/



  CREATE TABLE "XXMX_FUSION_EBS_ELE_MAP" 
   (	"FUSION_ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"FUSION_INPUT_VALUE_NAME" VARCHAR2(100 BYTE), 
	"EBS_ELEMENT_NAME" VARCHAR2(100 BYTE), 
	"EBS_INPUT_VALUE_NAME" VARCHAR2(100 BYTE), 
	"MANDATORY" VARCHAR2(100 BYTE), 
	"DATA_TYPE" VARCHAR2(100 BYTE), 
	"LIST_OF_VALUES" VARCHAR2(100 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;


/



  CREATE TABLE "XXMX_FUSION_WORKERS" 
   (	"PERSON_NUMBER" NUMBER, 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"WORKER_PAYROLL_NAME" VARCHAR2(100 BYTE), 
	"LEGISLATIVE_DATA_GROUP" VARCHAR2(100 BYTE), 
	"SYSTEM_PERSON_TYPE" VARCHAR2(100 BYTE), 
	"USER_PERSON_TYPE" VARCHAR2(100 BYTE), 
	"HIRE_DATE" VARCHAR2(100 BYTE), 
	"ASG_START_DATE" VARCHAR2(100 BYTE), 
	"ASG_END_DATE" VARCHAR2(100 BYTE), 
	"BU_NAME" VARCHAR2(100 BYTE), 
	"PRIMARY_ASG_FLAG" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"ASSIGNMENT_STATUS" VARCHAR2(100 BYTE), 
	"TERMINATION_DATE" VARCHAR2(200 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(100 BYTE), 
	"PAYROLL_REL_NO" VARCHAR2(100 BYTE), 
	"LAST_STD_PDATE" VARCHAR2(100 BYTE), 
	"FINAL_CLOSE_DATE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "XXMX_CORE" ;
