--*****************************************************************************
--**
--**                 Copyright (c) 2022 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  XXMX_HCM_BEN_STG_TAB.sql
--**
--** FILEPATH  :  /home/oracle/MXDM/install/STG
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  XXMX_STG
--**
--** AUTHORS   :  Shaik Latheef
--**
--** PURPOSE   :  This script installs the XXMX_STG DB Objects for the Maximise
--**              HCM Benefits Data Migration.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    None
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  ------------------------------------------
--** [ 1.0  29-JUL-2021  Shaik Latheef  	 Created Benefits STG tables for Maximise.]
--**
--*************************************************************************************
--
--
PROMPT
PROMPT
PROMPT ********************************************************************
PROMPT **
PROMPT ** Installing Database Objects for Maximise Customers Data Migration
PROMPT **
PROMPT ********************************************************************
PROMPT
PROMPT

--
--
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Dropping Tables
PROMPT ******************
PROMPT
PROMPT
--
--

EXEC DropTable ('XXMX_BEN_PE_STG')		
EXEC DropTable ('XXMX_BEN_PE_CO_STG')	
EXEC DropTable ('XXMX_BEN_DE_STG')		
EXEC DropTable ('XXMX_BEN_DE_DD_STG')	
EXEC DropTable ('XXMX_BEN_BE_STG')		
EXEC DropTable ('XXMX_BEN_BE_DB_STG')	
EXEC DropTable ('XXMX_BEN_PBG_STG')		
EXEC DropTable ('XXMX_BEN_PBB_STG')		
EXEC DropTable ('XXMX_BEN_PH_STG')		
EXEC DropTable ('XXMX_BEN_PBO_STG')		

--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Creating Tables
PROMPT ******************
--
--

-- ******************************
-- **Participant Enrollment Table
-- ******************************
CREATE TABLE XXMX_BEN_PE_STG
   (
	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'ParticipantEnrollment',
	---
	PERSON_ID					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	PARTICIPANT_LAST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	PARTICIPANT_FIRST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	BENEFIT_RELATIONSHIP		VARCHAR2(240) NOT NULL ENABLE,
	LIFE_EVENT					VARCHAR2(240) NOT NULL ENABLE,
	LIFE_EVENT_OCCURED_DATE		DATE NOT NULL ENABLE,
	CLOSE_LIFE_EVENT			VARCHAR2(30) DEFAULT 'N',
	CLOSE_LIFE_EVENT_DATE		DATE,
	EFFECTIVE_DATE				DATE NOT NULL ENABLE,
	LEGAL_EMPLOYER				VARCHAR2(240),
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ********************************
-- **Participant Compensation Table
-- ********************************
CREATE TABLE XXMX_BEN_PE_CO_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'CompensationObject',
	---
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL ENABLE,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL ENABLE,
	ORIGINAL_ENROLLMENT_DATE	DATE NOT NULL ENABLE,
	RATE						NUMBER(18),
	COVERAGE					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	DENROLL_BEN_PROGRAM			VARCHAR2(240),
	DENROLL_BEN_PLAN			VARCHAR2(240),
	DENROLL_BEN_OPTION			VARCHAR2(240),
	LINE_NUMBER					NUMBER(18) NOT NULL ENABLE,
	ENROLLMENT_LINE_ID			NUMBER(18) NOT NULL ENABLE,
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ****************************
-- **Dependent Enrollment Table
-- ****************************
CREATE TABLE XXMX_BEN_DE_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'DependentEnrollment',
	---
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	PARTICIPANT_LAST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	PARTICIPANT_FIRST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	BENEFIT_RELATIONSHIP		VARCHAR2(240) NOT NULL ENABLE,
	EFFECTIVE_DATE				DATE NOT NULL ENABLE,
	CLOSE_LIFE_EVENT			VARCHAR2(30) DEFAULT 'N',
	CLOSE_LIFE_EVENT_DATE		DATE,
	LIFE_EVENT					VARCHAR2(240) NOT NULL ENABLE,
	LIFE_EVENT_OCCURED_DATE		DATE NOT NULL ENABLE,
	PERSON_ID					NUMBER(18),
	LEGAL_EMPLOYER				VARCHAR2(240),
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- *****************************
-- **Dependent Designation Table
-- *****************************
CREATE TABLE XXMX_BEN_DE_DD_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'DesignateDependent',
	---
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL ENABLE,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL ENABLE,
	ORIGINAL_ENROLLMENT_DATE	DATE NOT NULL ENABLE,
	DEPENDENT_PERSON_NUMBER		VARCHAR2(30) NOT NULL ENABLE,
	DEPENDENT_PERSON_ID			NUMBER(18),
	LINE_NUMBER					NUMBER(18) NOT NULL ENABLE,
	DEPENDENT_LINE_ID			NUMBER(18) NOT NULL ENABLE,
	DEPENDENT_FIRST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	DEPENDENT_LAST_NAME			VARCHAR2(150) NOT NULL ENABLE,
	DEPENDENT_DATE_OF_BIRTH		DATE,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ******************************
-- **Beneficiary Enrollment Table
-- ******************************
CREATE TABLE XXMX_BEN_BE_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'BeneficiaryEnrollment',
	---
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	PARTICIPANT_LAST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	PARTICIPANT_FIRST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	BENEFIT_RELATIONSHIP		VARCHAR2(240) NOT NULL ENABLE,
	EFFECTIVE_DATE				DATE NOT NULL ENABLE,
	CLOSE_LIFE_EVENT			VARCHAR2(30) DEFAULT 'N',
	CLOSE_LIFE_EVENT_DATE		DATE,
	LIFE_EVENT					VARCHAR2(240) NOT NULL ENABLE,
	LIFE_EVENT_OCCURED_DATE		DATE NOT NULL ENABLE,
	PERSON_ID					NUMBER(18),
	LEGAL_EMPLOYER				VARCHAR2(240),
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- *******************************
-- **Beneficiary Designation Table
-- *******************************
CREATE TABLE XXMX_BEN_BE_DB_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'DesignateBeneficiary',
	---
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL ENABLE,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL ENABLE,
	BENEFICIARY_PERCENTAGE		NUMBER(18) NOT NULL ENABLE,
	ORIGINAL_ENROLLMENT_DATE	DATE NOT NULL ENABLE,
	BENEFICIARY_PERSON_NUMBER	VARCHAR2(30) NOT NULL ENABLE,
	BENEFICIARY_PERSON_ID		NUMBER(18),
	BENEFICIARY_TYPE			VARCHAR2(30) NOT NULL ENABLE,
	LINE_NUMBER					NUMBER(18) NOT NULL ENABLE,
	BENEFICIARY_LINE_ID			NUMBER(18) NOT NULL ENABLE,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	BENEFICIARY_LAST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	BENEFICIARY_FIRST_NAME		VARCHAR2(150) NOT NULL ENABLE,
	BENEFICIARY_DATE_OF_BIRTH	DATE,
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ****************************
-- **Person Benefit Group Table
-- ****************************
CREATE TABLE XXMX_BEN_PBG_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'PersonBenefitGroup',
	---
	BENEFIT_GROUP_NAME			VARCHAR2(240) NOT NULL ENABLE,
	EFFECTIVE_END_DATE			DATE,
	EFFECTIVE_START_DATE		DATE NOT NULL ENABLE,
	GUID						VARCHAR2(32),
	LE_BENEFIT_GROUP_ID			VARCHAR2(30),
	PERSON_ID					NUMBER(18),
	SOURCE_SYSTEM_ID			VARCHAR2(100),
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ******************************
-- **Person Benefit Balance Table
-- ******************************
CREATE TABLE XXMX_BEN_PBB_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'PersonBenefitBalance',
	---
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	BENEFIT_BALANCE_NAME		VARCHAR2(240) NOT NULL ENABLE,
	BENEFIT_RELATION_NAME		VARCHAR2(240) NOT NULL ENABLE,
	ASSIGNMENT_NUMBER			VARCHAR2(50),
	LEGAL_EMPLOYER				VARCHAR2(240),
	EFFECTIVE_END_DATE			DATE,
	EFFECTIVE_START_DATE		DATE NOT NULL ENABLE,
	LEGAL_ENTITY_ID				NUMBER(18),
	PER_BNFTS_BAL_ID			NUMBER(18),
	PERSON_ID					NUMBER(18),
	UOM							VARCHAR2(30) NOT NULL ENABLE,
	VAL							NUMBER NOT NULL ENABLE,
	SOURCE_SYSTEM_ID			VARCHAR2(100),
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	GUID						VARCHAR2(32),
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );
   
-- *********************
-- **Person Habits Table
-- *********************
CREATE TABLE XXMX_BEN_PH_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'PersonHabits',
	---		
	LEGAL_EMPLOYER				VARCHAR2(240) NOT NULL ENABLE,
	COORD_MED_PL_NAME			VARCHAR2(240),
	CVRD_IN_ANTHR_PL			VARCHAR2(30) DEFAULT 'N',
	DISABILITY_STATUS			VARCHAR2(30),
	EFFECTIVE_END_DATE			DATE,	
	EFFECTIVE_START_DATE		DATE NOT NULL ENABLE,
	GUID						VARCHAR2(32),
	LE_HABITS_COV_ID			VARCHAR2(30),	
	PERSON_ID					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	REGISTERED_DISABLED_FLAG	VARCHAR2(30) DEFAULT 'N',
	SOURCE_SYSTEM_ID			VARCHAR2(100),		
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	STUDENT_STATUS				VARCHAR2(30),
	TOBACCO_TYPE_USAGE			VARCHAR2(30) DEFAULT 'N',
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );

-- ***************************************
-- **Person Beneficiary Organization Table
-- ***************************************
CREATE TABLE XXMX_BEN_PBO_STG
   (	
   	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),	
	METADATA					VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME					VARCHAR2(150) DEFAULT 'PersonBeneficiaryOrganization',
	---			
	PER_BNF_ORG_ID				NUMBER(22),
	START_DATE					DATE NOT NULL ENABLE,
	END_DATE					DATE,
	PERSON_ID					NUMBER(18),
	BNF_TYP_CD					VARCHAR2(30) DEFAULT 'ORG',
	BNF_ORGANIZATION_ID			NUMBER(22),
	TRUSTEE_ORG_NAME			VARCHAR2(240),
	TRUSTEE_ORG_REG_CD			VARCHAR2(240),
	TRUSTEE_ORG_DESCRIPTION		VARCHAR2(600),
	TRUSTEE_ADDL_DETAILS		VARCHAR2(600),
	TRUSTEE_EXECUTOR_NAME		VARCHAR2(240), 
	ORGANIZATION_NAME			VARCHAR2(240), 
	PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	GUID						VARCHAR2(32),
	SOURCE_SYSTEM_ID			VARCHAR2(100),	
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	---
	ATTRIBUTE_CATEGORY 			VARCHAR2(30),
	ATTRIBUTE1 					VARCHAR2(150),
	ATTRIBUTE2 					VARCHAR2(150),
	ATTRIBUTE3 					VARCHAR2(150),
	ATTRIBUTE4 					VARCHAR2(150),
	ATTRIBUTE5 					VARCHAR2(150),
	ATTRIBUTE6 					VARCHAR2(150),
	ATTRIBUTE7 					VARCHAR2(150),
	ATTRIBUTE8 					VARCHAR2(150),
	ATTRIBUTE9 					VARCHAR2(150),
	ATTRIBUTE10 				VARCHAR2(150),
	ATTRIBUTE_NUMBER1 			NUMBER, 
	ATTRIBUTE_NUMBER2 			NUMBER, 
	ATTRIBUTE_NUMBER3 			NUMBER, 
	ATTRIBUTE_NUMBER4 			NUMBER, 
	ATTRIBUTE_NUMBER5 			NUMBER, 
	ATTRIBUTE_DATE1 			DATE, 
	ATTRIBUTE_DATE2 			DATE, 
	ATTRIBUTE_DATE3 			DATE, 
	ATTRIBUTE_DATE4 			DATE, 
	ATTRIBUTE_DATE5 			DATE
   );



--------------------------
---SYNONYMS AND GRANTS
--------------------------

--
--
PROMPT
PROMPT
PROMPT ****************************
PROMPT ** CREATE OR REPLACE SYNONYM
PROMPT ****************************
--
--


CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PE_STG FOR XXMX_BEN_PE_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PE_CO_STG FOR XXMX_BEN_PE_CO_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_DE_STG FOR XXMX_BEN_DE_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_DE_DD_STG FOR XXMX_BEN_DE_DD_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_BE_STG FOR XXMX_BEN_BE_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_BE_DB_STG FOR XXMX_BEN_BE_DB_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PBG_STG FOR XXMX_BEN_PBG_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PBB_STG FOR XXMX_BEN_PBB_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PH_STG FOR XXMX_BEN_PH_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_BEN_PBO_STG FOR XXMX_BEN_PBO_STG;


--
--
PROMPT
PROMPT
PROMPT *****************
PROMPT ** Creating Index
PROMPT *****************
--
--


CREATE INDEX XXMX_BEN_PE_STG_PK ON XXMX_BEN_PE_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_PE_CO_STG_PK ON XXMX_BEN_PE_CO_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_DE_STG_PK ON XXMX_BEN_DE_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_DE_DD_STG_PK ON XXMX_BEN_DE_DD_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_BE_STG_PK ON XXMX_BEN_BE_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_BE_DB_STG_PK ON XXMX_BEN_BE_DB_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_PBG_STG_PK ON XXMX_BEN_PBG_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_PBB_STG_PK ON XXMX_BEN_PBB_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_PH_STG_PK ON XXMX_BEN_PH_STG(PERSON_NUMBER);
CREATE INDEX XXMX_BEN_PBO_STG_PK ON XXMX_BEN_PBO_STG(PERSON_NUMBER);


--
--
PROMPT
PROMPT
PROMPT ***********************
PROMPT ** Granting permissions
PROMPT ***********************
--
--


GRANT ALL ON XXMX_BEN_PE_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_PE_CO_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_DE_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_DE_DD_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_BE_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_BE_DB_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_PBG_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_PBB_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_PH_STG TO XXMX_CORE;
GRANT ALL ON XXMX_BEN_PBO_STG TO XXMX_CORE;


--
--
--
--
PROMPT
PROMPT
PROMPT **********************************
PROMPT **                                
PROMPT ** End of Database Object Creation
PROMPT **                                
PROMPT **********************************
PROMPT
PROMPT
--
--
