---Creating Invoice Table---

CREATE TABLE XXMX_INVOICE_DOCUMENT_EXTRACTION 
(
    DOCUMENT_TYPE      VARCHAR2(250),
    INVOICE_NUMBER     VARCHAR2(20),
    INVOICE_DATE       DATE,
    VENDOR_NAME        VARCHAR2(2000),
    VENDOR_ADDRESS     VARCHAR2(2000),
    INVOICE_TOTAL      VARCHAR2(200),
    FILENAME           VARCHAR2(250),
    SEQUENCE_ID        NUMBER,
    SUB_TOTAL          VARCHAR2(200)
);
--
--
---Creating Receipt Table---

CREATE TABLE XXMX_RECEIPT_DOCUMENT_EXTRACTION 
(
    DOCUMENT_TYPE      VARCHAR2(250),
    MERCHANT_NAME      VARCHAR2(250),
    MERCHANT_ADDRESS   VARCHAR2(250),
    TOTAL              VARCHAR2(250),
    FILENAME           VARCHAR2(250),
    SEQUENCE_ID        NUMBER
);
--
--
---Creating Passport Table---

CREATE TABLE XXMX_PASSPORT_DOCUMENT_EXTRACTION 
(
    DOCUMENT_TYPE   VARCHAR2(250),
    FIRST_NAME      VARCHAR2(20),
    LAST_NAME       VARCHAR2(20),
    COUNTRY         VARCHAR2(250),
    BIRTH_DATE      DATE,
    GENDER          VARCHAR2(20),
    PASSPORT_NO     VARCHAR2(250),
    EXPIRY_DATE     DATE,
    FILENAME        VARCHAR2(250),
    SEQUENCE_ID     NUMBER
);
--
--
-- Create Sequence for XXMX_INVOICE_DOCUMENT_EXTRACTION
CREATE SEQUENCE xxmx_invoice_seq
START WITH 1
INCREMENT BY 1
NOCACHE;
/

-- Create Trigger for XXMX_INVOICE_DOCUMENT_EXTRACTION
CREATE OR REPLACE TRIGGER xxmx_invoice_bir
BEFORE INSERT ON xxmx_invoice_document_extraction
FOR EACH ROW
BEGIN
    SELECT xxmx_invoice_seq.NEXTVAL
    INTO :NEW.sequence_id
    FROM dual;
END;
/
 
-- Create Sequence for XXMX_PASSPORT_DOCUMENT_EXTRACTION
CREATE SEQUENCE xxmx_passport_seq
START WITH 1
INCREMENT BY 1
NOCACHE;
/

-- Create Trigger for XXMX_PASSPORT_DOCUMENT_EXTRACTION
CREATE OR REPLACE TRIGGER xxmx_passport_bir
BEFORE INSERT ON xxmx_passport_document_extraction
FOR EACH ROW
BEGIN
    SELECT xxmx_passport_seq.NEXTVAL
    INTO :NEW.sequence_id
    FROM dual;
END;
/

-- Create Sequence for XXMX_RECEIPT_DOCUMENT_EXTRACTION
CREATE SEQUENCE xxmx_receipt_seq
START WITH 1
INCREMENT BY 1
NOCACHE;
/

-- Create Trigger for XXMX_RECEIPT_DOCUMENT_EXTRACTION
CREATE OR REPLACE TRIGGER xxmx_receipt_bir
BEFORE INSERT ON XXMX_RECEIPT_DOCUMENT_EXTRACTION
FOR EACH ROW
BEGIN
    SELECT xxmx_receipt_seq.NEXTVAL
    INTO :NEW.sequence_id
    FROM dual;
END;
/
