LOAD DATA
INFILE XXMX_HCM_BEN_PER_BEN_GROUP.dat
REPLACE 
INTO  TABLE XXMX_BEN_PBG_STG
FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"'  TRAILING NULLCOLS 
(MIGRATION_SET_NAME             ,
MIGRATION_STATUS               ,
BG_NAME                        ,
BENEFIT_GROUP_NAME             ,
EFFECTIVE_END_DATE             ,
EFFECTIVE_START_DATE           ,
LE_BENEFIT_GROUP_ID            ,
PERSON_NUMBER                  
)

