--------------------------------------------------------
--  Constraints for Table XXMX_PER_IMAGES_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM_ARCH" MODIFY ("IMAGENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM_ARCH" MODIFY ("IMAGE_REF" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM_ARCH" MODIFY ("IMAGETYPE" NOT NULL ENABLE);
