--------------------------------------------------------
--  Constraints for Table XXMX_PER_DISABILITY_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
