--------------------------------------------------------
--  Constraints for Table XXMX_PER_PAY_METHOD_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("PERSONAL_PAYMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("ORG_PAYMENT_METHOD_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("BANK_ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PAY_METHOD_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
