--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_REL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM" MODIFY ("CONTACTTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
