--------------------------------------------------------
--  Constraints for Table XXMX_LOC_ADDR_USG_F_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_LOC_ADDR_USG_F_XFM" MODIFY ("LOC_ADDRESS_USAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_LOC_ADDR_USG_F_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_LOC_ADDR_USG_F_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
