--------------------------------------------------------
--  DDL for Table XXMX_PER_ASG_WORK_SCH_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" NUMBER, 
	"MIGRATION_STATUS" NUMBER, 
	"BG_NAME" NUMBER, 
	"BG_ID" VARCHAR2(30 BYTE), 
	"RESOURCETYPE" VARCHAR2(30 BYTE), 
	"SCHEDULENAME" VARCHAR2(240 BYTE), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"ASSIGNMENT_NUMBER" NUMBER, 
	"ENTERPRISENAME" NUMBER, 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENT_NAME" VARCHAR2(60 BYTE), 
	"INTERNALLOCATIONCODE" VARCHAR2(240 BYTE), 
	"LOCATIONSETCODE" VARCHAR2(240 BYTE), 
	"JOB_CODE" VARCHAR2(240 BYTE), 
	"JOBSETCODE" VARCHAR2(240 BYTE), 
	"BUSINESS_UNIT_NAME" VARCHAR2(240 BYTE), 
	"POSITION_CODE" VARCHAR2(240 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(240 BYTE), 
	"PERSONNUMBER" VARCHAR2(240 BYTE), 
	"WORKTERMSASSIGNMENTNUMBER" VARCHAR2(240 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"OBJECTNAME" VARCHAR2(10 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PER_ASG_WORK_SCH_XFM" TO "XXMX_CORE";
