--------------------------------------------------------
--  DDL for Table XXMX_OLC_LEARN_RCD_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'LearningRecord', 
	"LEARNING_RECORD_ID" NUMBER, 
	"LEARN_RECORD_EFFECTIVE_START_DATE" DATE, 
	"LEARN_RECORD_EFFECTIVE_END_DATE" DATE, 
	"LEARNING_RECORD_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_ITEM_TYPE" VARCHAR2(30 BYTE), 
	"LEARNING_ITEM_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SUB_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_SOURCE_ID" NUMBER, 
	"ASSIGNMENT_SOURCE_INFO" VARCHAR2(240 BYTE), 
	"ASSIGNED_BY_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_TYPE" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_NUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_ATTRIBUTION_CODE" VARCHAR2(30 BYTE), 
	"LEARNER_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_STATUS" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_SOURCE_ID" NUMBER, 
	"LEARNING_RECORD_SOURCE_INFO" VARCHAR2(240 BYTE), 
	"LEARNING_RECORD_START_DATE" DATE, 
	"LEARNING_RECORD_DUE_DATE" DATE, 
	"LEARNING_RECORD_WITHDRAWN_DATE" DATE, 
	"LEARNING_RECORD_DELETED_DATE" DATE, 
	"LEARNING_RECORD_COMPLETION_DATE" DATE, 
	"LEARNING_RECORD_VALID_FROM_DATE" DATE, 
	"LEARNING_REC_EXPIRY_DATE" DATE, 
	"LEARNING_REC_TOT_ACT_EFFORT" NUMBER, 
	"LEARNING_REC_TOT_ACT_EFFORT_UOM" VARCHAR2(30 BYTE), 
	"REQUEST_DETAIL_START_DATE" DATE, 
	"REQUEST_DETAIL_COMPLETION_DATE" DATE, 
	"REQUEST_DETAIL_COMMENTS" VARCHAR2(4000 BYTE), 
	"REQUEST_DETAIL_PO_NUMBER" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_REASON_CODE" VARCHAR2(30 BYTE), 
	"LEARNING_RECORD_COMMENTS" VARCHAR2(4000 BYTE), 
	"LEARNING_RECORD_REQUEST_APPV_DATE" DATE, 
	"ACTUAL_SCORE" NUMBER, 
	"CPE_POINTS" NUMBER, 
	"CPE_TYPE" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_OLC_LEARN_RCD_XFM" TO "XXMX_CORE";
