--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_PAYEES_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"TEMP_EXT_PAYEE_ID" NUMBER, 
	"BUSINESS_UNIT" VARCHAR2(240 BYTE), 
	"VENDOR_CODE" VARCHAR2(30 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1 BYTE), 
	"DEFAULT_PAYMENT_METHOD_CODE" VARCHAR2(30 BYTE), 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(30 BYTE), 
	"SETTLEMENT_PRIORITY" VARCHAR2(30 BYTE), 
	"REMIT_ADVICE_DELIVERY_METHOD" VARCHAR2(30 BYTE), 
	"REMIT_ADVICE_EMAIL" VARCHAR2(255 BYTE), 
	"REMIT_ADVICE_FAX" VARCHAR2(100 BYTE), 
	"BANK_INSTRUCTION1_CODE" VARCHAR2(30 BYTE), 
	"BANK_INSTRUCTION2_CODE" VARCHAR2(30 BYTE), 
	"BANK_INSTRUCTION_DETAILS" VARCHAR2(255 BYTE), 
	"PAYMENT_REASON_CODE" VARCHAR2(30 BYTE), 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(240 BYTE), 
	"PAYMENT_TEXT_MESSAGE1" VARCHAR2(150 BYTE), 
	"PAYMENT_TEXT_MESSAGE2" VARCHAR2(150 BYTE), 
	"PAYMENT_TEXT_MESSAGE3" VARCHAR2(150 BYTE), 
	"BANK_CHARGE_BEARER" VARCHAR2(30 BYTE), 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_SITE_ID" NUMBER, 
	"SUPPLIER_SITE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_AP_SUPP_PAYEES_XFM_ARCH" TO "XXMX_CORE";
