--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_ACT_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_ACT_TL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_ACT_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_ACT_TL_XFM" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
