--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_PHONE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM_ARCH" MODIFY ("DATEFROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM_ARCH" MODIFY ("PHONETYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM_ARCH" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM_ARCH" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM_ARCH" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
