--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SELFPACE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM_ARCH" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
