--------------------------------------------------------
--  Constraints for Table XXMX_PER_SENIORITYDT_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM" MODIFY ("SENIORITYDATECODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM" MODIFY ("MANUALADJUSTMENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM" MODIFY ("DATESTART" NOT NULL ENABLE);
