--------------------------------------------------------
--  Constraints for Table XXMX_ASG_WORKMSURE_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ASG_WORKMSURE_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_WORKMSURE_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_WORKMSURE_XFM" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_WORKMSURE_XFM" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_WORKMSURE_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
