--------------------------------------------------------
--  Constraints for Table XXMX_ORG_UNIT_CLASS_F_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" MODIFY ("ORG_UNIT_CLASSIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
