--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_TL_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_TL_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_TL_XFM_ARCH" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_TL_XFM_ARCH" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
