--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_ACC_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("DEFAULT_ACCESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("SELF_VIEW_MODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("SELF_INITIAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("MGR_INITIAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_ACC_XFM_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
