--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RESV_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RESV_XFM" MODIFY ("CLASSROOM_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RESV_XFM" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RESV_XFM" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
