--------------------------------------------------------
--  DDL for Table XXMX_ORG_UNIT_CLASS_F_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"ORG_UNIT_CLASSIFICATION_ID" VARCHAR2(264 BYTE), 
	"MODULE_ID" VARCHAR2(32 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"ACTION_OCCURRENCE_ID" VARCHAR2(264 BYTE), 
	"ORGANIZATION_ID" VARCHAR2(264 BYTE), 
	"CLASSIFICATION_CODE" VARCHAR2(40 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"SET_CODE" VARCHAR2(264 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_ORG_UNIT_CLASS_F_XFM" TO "XXMX_CORE";
