--------------------------------------------------------
--  Constraints for Table XXMX_OLC_NONCAT_LEARN_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_XFM" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_XFM" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
