--------------------------------------------------------
--  Constraints for Table XXMX_ASG_PAYROLL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM" MODIFY ("PAYROLL_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
