--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_CONT_ADDRS_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"IMPORT_ACTION" VARCHAR2(10 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_SITE_ID" NUMBER, 
	"ADDRESS_NAME" VARCHAR2(240 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(320 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_AP_SUPP_CONT_ADDRS_XFM" TO "XXMX_CORE";
