--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_ACT_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_ACT_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_ACT_XFM" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_ACT_XFM" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_ACT_XFM" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
