--------------------------------------------------------
--  DDL for Table XXMX_ZX_TAX_REGISTRATION_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PARTY_TYPE_CODE" VARCHAR2(80 BYTE), 
	"PARTY_NUMBER" VARCHAR2(30 BYTE), 
	"PARTY_NAME" VARCHAR2(150 BYTE), 
	"TAX_REGIME_CODE" VARCHAR2(30 BYTE), 
	"TAX" VARCHAR2(30 BYTE), 
	"TAX_JURISDICTION_CODE" VARCHAR2(30 BYTE), 
	"REGISTRATION_TYPE_CODE" VARCHAR2(80 BYTE), 
	"REGISTRATION_NUMBER" VARCHAR2(50 BYTE), 
	"EFFECTIVE_FROM" DATE, 
	"EFFECTIVE_TO" DATE, 
	"DEFAULT_REGISTRATION_FLAG" VARCHAR2(3 BYTE), 
	"REGISTRATION_REASON_CODE" VARCHAR2(30 BYTE), 
	"REGISTRATION_STATUS_CODE" VARCHAR2(30 BYTE), 
	"REGISTRATION_SOURCE_CODE" VARCHAR2(30 BYTE), 
	"REP_PARTY_TAX_NAME" VARCHAR2(80 BYTE), 
	"ROUNDING_RULE_CODE" VARCHAR2(80 BYTE), 
	"ROUNDING_LEVEL_CODE" VARCHAR2(80 BYTE), 
	"SELF_ASSESS_FLAG" VARCHAR2(3 BYTE), 
	"INCLUSIVE_TAX_FLAG" VARCHAR2(3 BYTE), 
	"TAX_POINT_BASIS" VARCHAR2(80 BYTE), 
	"ISSUING_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"COLLECTING_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"REPORTING_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"VALIDATION_TYPE" VARCHAR2(30 BYTE), 
	"SELF_ASSESS_DIFF_TOL_LMT_FLAG" VARCHAR2(30 BYTE), 
	"MIN_SELF_ASSESS_DIFF_TOL_LIMIT" NUMBER, 
	"MAX_SELF_ASSESS_DIFF_TOL_LIMIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_ZX_TAX_REGISTRATION_XFM_ARCH" TO "XXMX_CORE";
