--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SELFPACE_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SELFPACE_XFM" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
