--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_LED_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("ACTIVITY_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("ACTIVITY_START_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("ACTIVITY_END_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("TIME_ZONE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_LED_XFM_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
