--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_ADDR_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("ADDRESSTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("ADDRESSLINE1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_ADDR_XFM" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
