--------------------------------------------------------
--  Constraints for Table XXMX_JOBS_F_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_JOBS_F_TL_XFM" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_JOBS_F_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_JOBS_F_TL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_JOBS_F_TL_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
