--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_ACC_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("DEFAULT_ACCESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("SELF_VIEW_MODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("SELF_INITIAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_ACC_XFM" MODIFY ("MGR_INITIAL_STATUS" NOT NULL ENABLE);
