--------------------------------------------------------
--  Constraints for Table XXMX_USER_DATA_ACCESS_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("SOURCE_SYSTEM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("NEW_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("SECURITY_CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_DATA_ACCESS_XFM" MODIFY ("SECURITY_CONTEXT_VALUE" NOT NULL ENABLE);
