--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_PHONE_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM" MODIFY ("DATEFROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM" MODIFY ("PHONETYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_PHONE_XFM" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
