--------------------------------------------------------
--  Constraints for Table XXMX_PER_SENIORITYDT_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM_ARCH" MODIFY ("SENIORITYDATECODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM_ARCH" MODIFY ("MANUALADJUSTMENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_SENIORITYDT_XFM_ARCH" MODIFY ("DATESTART" NOT NULL ENABLE);
