--------------------------------------------------------
--  Constraints for Table XXMX_OLC_GLOB_ACC_GRP_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM" MODIFY ("GLOBAL_ACCESS_GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM" MODIFY ("PRIORITY" NOT NULL ENABLE);
