--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM_ARCH" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM_ARCH" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM_ARCH" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
