--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_XFM" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_XFM" MODIFY ("SECTION_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_SXN_XFM" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
