--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_PRICE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_XFM_ARCH" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_XFM_ARCH" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_XFM_ARCH" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
