--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RES_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM_ARCH" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM_ARCH" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM_ARCH" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM_ARCH" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
