--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_RESV_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RESV_XFM" MODIFY ("INSTRUCTOR_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RESV_XFM" MODIFY ("INSTRUCTOR_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RESV_XFM" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
