--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SUP_F_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SUP_F_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SUP_F_XFM_ARCH" MODIFY ("MANAGER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SUP_F_XFM_ARCH" MODIFY ("MANAGER_ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SUP_F_XFM_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SUP_F_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
