--------------------------------------------------------
--  Constraints for Table XXMX_PER_ADDRESS_F_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM_ARCH" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM_ARCH" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM_ARCH" MODIFY ("ADDRESS_TYPE" NOT NULL ENABLE);
