--------------------------------------------------------
--  Constraints for Table XXMX_CITIZENSHIPS_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_CITIZENSHIPS_XFM_ARCH" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_CITIZENSHIPS_XFM_ARCH" MODIFY ("CITIZENSHIP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_CITIZENSHIPS_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
