--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_PRICE_COMP_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_COMP_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_COMP_XFM" MODIFY ("PRICING_COMPONENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_COMP_XFM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_PRICE_COMP_XFM" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
