--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RCPTS_RT6_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RCPTS_RT6_XFM" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RCPTS_RT6_XFM" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RCPTS_RT6_XFM" MODIFY ("TRANSFORM_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RCPTS_RT6_XFM" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RCPTS_RT6_XFM" MODIFY ("RECORD_SEQ" NOT NULL ENABLE);
