--------------------------------------------------------
--  DDL for Table XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'CandidateJobApplicationProfile', 
	"PROFILE_ITEM_ID" NUMBER(18,0), 
	"CONTENT_ITEM_ID" NUMBER(18,0), 
	"CONTENT_TYPE_ID" NUMBER(18,0), 
	"COUNTRY_ID" NUMBER(18,0), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"IMPORTANCE" NUMBER(18,0), 
	"INTEREST_LEVEL" VARCHAR2(30 BYTE), 
	"MANDATORY" VARCHAR2(30 BYTE), 
	"PARENT_PROFILE_ITEM_ID" NUMBER(18,0), 
	"PROFILE_ID" NUMBER(18,0), 
	"SOURCE_ID" NUMBER(18,0), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"STATE_PROVINCE_ID" NUMBER(18,0), 
	"STATE_GEOGRAPHY_CODE" VARCHAR2(360 BYTE), 
	"STATE_COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"COUNTRY_GEOGRAPHY_CODE" VARCHAR2(30 BYTE), 
	"COUNTRY_COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"CONTENT_TYPE" VARCHAR2(240 BYTE), 
	"CONTENT_ITEM" VARCHAR2(700 BYTE), 
	"SUBMISSION_ID" NUMBER(18,0), 
	"REQUISITION_NUMBER" VARCHAR2(240 BYTE), 
	"REQUISITION_ID" NUMBER(18,0), 
	"PERSON_ID" NUMBER(18,0), 
	"CANDIDATE_NUMBER" VARCHAR2(30 BYTE), 
	"SECTION_ID" NUMBER(18,0), 
	"SECTION_CONTEXT" VARCHAR2(300 BYTE), 
	"ITEM_DATE_1" DATE, 
	"ITEM_DATE_2" DATE, 
	"ITEM_DATE_3" DATE, 
	"ITEM_DATE_4" DATE, 
	"ITEM_DATE_5" DATE, 
	"ITEM_DATE_6" DATE, 
	"ITEM_DATE_7" DATE, 
	"ITEM_DATE_8" DATE, 
	"ITEM_DATE_9" DATE, 
	"ITEM_DATE_10" DATE, 
	"ITEM_DECIMAL_1" NUMBER(15,0), 
	"ITEM_DECIMAL_2" NUMBER(15,0), 
	"ITEM_DECIMAL_3" NUMBER(15,0), 
	"ITEM_DECIMAL_4" NUMBER(15,0), 
	"ITEM_DECIMAL_5" NUMBER(15,0), 
	"ITEM_NUMBER_1" NUMBER(18,0), 
	"ITEM_NUMBER_2" NUMBER(18,0), 
	"ITEM_NUMBER_3" NUMBER(18,0), 
	"ITEM_NUMBER_4" NUMBER(18,0), 
	"ITEM_NUMBER_5" NUMBER(18,0), 
	"ITEM_NUMBER_6" NUMBER(18,0), 
	"ITEM_NUMBER_7" NUMBER(18,0), 
	"ITEM_NUMBER_8" NUMBER(18,0), 
	"ITEM_NUMBER_9" NUMBER(18,0), 
	"ITEM_NUMBER_10" NUMBER(18,0), 
	"ITEM_TEXT_20001" VARCHAR2(2000 BYTE), 
	"ITEM_TEXT_20002" VARCHAR2(2000 BYTE), 
	"ITEM_TEXT_20003" VARCHAR2(2000 BYTE), 
	"ITEM_TEXT_20004" VARCHAR2(2000 BYTE), 
	"ITEM_TEXT_20005" VARCHAR2(2000 BYTE), 
	"ITEM_TEXT_2401" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2402" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2403" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2404" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2405" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2406" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2407" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2408" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_2409" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24010" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24011" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24012" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24013" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24014" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_24015" VARCHAR2(240 BYTE), 
	"ITEM_TEXT_301" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_302" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_303" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_304" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_305" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_306" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_307" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_308" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_309" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3010" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3011" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3012" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3013" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3014" VARCHAR2(30 BYTE), 
	"ITEM_TEXT_3015" VARCHAR2(30 BYTE), 
	"ITEM_CLOB_1" CLOB, 
	"ITEM_CLOB_2" CLOB, 
	"ITEM_CLOB_3" CLOB, 
	"ITEM_CLOB_4" CLOB, 
	"ITEM_CLOB_5" CLOB, 
	"QUALIFIER_ID_1" NUMBER(18,0), 
	"QUALIFIER_ID_2" NUMBER(18,0), 
	"QUALIFIER_CODE_1" VARCHAR2(30 BYTE), 
	"QUALIFIER_CODE_2" VARCHAR2(30 BYTE), 
	"QUALIFIER_SET_CODE_1" VARCHAR2(30 BYTE), 
	"QUALIFIER_SET_CODE_2" VARCHAR2(30 BYTE), 
	"RATING_LEVEL_ID_1" NUMBER(18,0), 
	"RATING_LEVEL_ID_2" NUMBER(18,0), 
	"RATING_LEVEL_ID_3" NUMBER(18,0), 
	"RATING_MODEL_ID_1" NUMBER(18,0), 
	"RATING_MODEL_ID_2" NUMBER(18,0), 
	"RATING_MODEL_ID_3" NUMBER(18,0), 
	"RATING_MODEL_CODE_1" VARCHAR2(30 BYTE), 
	"RATING_MODEL_CODE_2" VARCHAR2(30 BYTE), 
	"RATING_MODEL_CODE_3" VARCHAR2(30 BYTE), 
	"RATING_LEVEL_CODE_1" VARCHAR2(30 BYTE), 
	"RATING_LEVEL_CODE_2" VARCHAR2(30 BYTE), 
	"RATING_LEVEL_CODE_3" VARCHAR2(30 BYTE), 
	"SOURCE_KEY_1" NUMBER(18,0), 
	"SOURCE_KEY_2" NUMBER(18,0), 
	"SOURCE_KEY_3" NUMBER(18,0), 
	"GUID" VARCHAR2(32 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" 
 LOB ("ITEM_CLOB_1") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_CLOB_2") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_CLOB_3") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_CLOB_4") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_CLOB_5") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM" TO "XXMX_CORE";
