--------------------------------------------------------
--  DDL for Table XXMX_OLC_OFFER_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE), 
	"OBJECTNAME" VARCHAR2(150 BYTE), 
	"OFFERING_ID" NUMBER, 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"OFFERING_NUMBER" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(250 BYTE), 
	"DESCRIPTION" CLOB, 
	"DESCRIPTION_TEXT" VARCHAR2(4000 BYTE), 
	"OFFERING_TYPE" VARCHAR2(30 BYTE), 
	"PUBLISH_START_DATE" DATE, 
	"PUBLISH_END_DATE" DATE, 
	"OFFERING_START_DATE" DATE, 
	"OFFERING_END_DATE" DATE, 
	"PRIMARY_LOCATION_ID" NUMBER, 
	"PRIMARY_LOCATION_NUMBER" VARCHAR2(30 BYTE), 
	"LANGUAGE_CODE" VARCHAR2(30 BYTE), 
	"FACILITATOR_TYPE" VARCHAR2(30 BYTE), 
	"PRIMARY_INSTRUCTOR_ID" NUMBER, 
	"PRIMARY_INSTRUCTOR_NUMBER" VARCHAR2(30 BYTE), 
	"TRAINING_SUPPLIER_ID" NUMBER, 
	"TRAINING_SUPPLIER_NUMBER" VARCHAR2(30 BYTE), 
	"COORDINATOR_ID" NUMBER, 
	"COORDINATOR_NUMBER" VARCHAR2(30 BYTE), 
	"ENABLE_CAPACITY" VARCHAR2(1 BYTE), 
	"MINIMUM_CAPACITY" NUMBER, 
	"MAXIMUM_CAPACITY" NUMBER, 
	"ENABLE_WAITLIST" VARCHAR2(1 BYTE), 
	"QUESTIONNAIRE_CODE" VARCHAR2(240 BYTE), 
	"QSTNR_REQUIRED_FOR_COMPLETION" VARCHAR2(1 BYTE), 
	"COURSE_ID" NUMBER, 
	"COURSE_NUMBER" VARCHAR2(30 BYTE), 
	"OWNED_BY_PERSON_ID" NUMBER, 
	"OWNED_BY_PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"SOURCE_ID" NUMBER, 
	"SOURCE_INFO" VARCHAR2(240 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "XXMX_XFM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_OLC_OFFER_XFM_ARCH" TO "XXMX_CORE";
