--------------------------------------------------------
--  DDL for Table XXMX_PPM_PRJ_TEAM_MEM_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(240 BYTE), 
	"TEAM_MEMBER_NUMBER" VARCHAR2(30 BYTE), 
	"TEAM_MEMBER_NAME" VARCHAR2(240 BYTE), 
	"TEAM_MEMBER_EMAIL" VARCHAR2(240 BYTE), 
	"PROJECT_ROLE" VARCHAR2(240 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"ALLOCATION" NUMBER, 
	"LABOUR_EFFORT" NUMBER, 
	"COST_RATE" NUMBER, 
	"BILL_RATE" NUMBER, 
	"TRACK_TIME_FLAG" VARCHAR2(1 BYTE), 
	"ASSIGNMENT_TYPE_CODE" VARCHAR2(30 BYTE), 
	"BILLABLE_PERCENT" NUMBER, 
	"BILLABLE_PERCENT_REASON_CODE" VARCHAR2(30 BYTE), 
	"BATCH_ID" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
	"PROJECT_LONG_NAME" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PPM_PRJ_TEAM_MEM_XFM" TO "XXMX_CORE";
