--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASSIGNMENTS_M_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASSIGNMENTS_M_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASSIGNMENTS_M_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASSIGNMENTS_M_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASSIGNMENTS_M_XFM" MODIFY ("PRIMARY_WORK_TERMS_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASSIGNMENTS_M_XFM" MODIFY ("PRIMARY_ASSIGNMENT_FLAG" NOT NULL ENABLE);
