--------------------------------------------------------
--  Constraints for Table XXMX_BEN_PE_CO_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("BEN_PLAN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("BEN_OPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("ORIGINAL_ENROLLMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PE_CO_XFM" MODIFY ("ENROLLMENT_LINE_ID" NOT NULL ENABLE);
