--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COMM_RS_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM" MODIFY ("COMMUNITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
