--------------------------------------------------------
--  Constraints for Table XXMX_PER_ADDRESS_F_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ADDRESS_F_XFM" MODIFY ("ADDRESS_TYPE" NOT NULL ENABLE);
