--------------------------------------------------------
--  DDL for Table XXMX_PPM_RESOURCES_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" 
   (	"BATCH_ID" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"RBS_HEADER_NAME" VARCHAR2(240 BYTE), 
	"RES_FORMAT_NAME" VARCHAR2(240 BYTE), 
	"ALIAS" VARCHAR2(240 BYTE), 
	"LEVE1_RES_NAME" VARCHAR2(300 BYTE), 
	"LEVE2_RES_NAME" VARCHAR2(300 BYTE), 
	"LEVE3_RES_NAME" VARCHAR2(300 BYTE), 
	"RESOURCE_CLASS_NAME" VARCHAR2(240 BYTE), 
	"SPREAD_CURVE_NAME" VARCHAR2(240 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PPM_RESOURCES_XFM" TO "XXMX_CORE";
