--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RECEIPTS_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RECEIPTS_XFM_ARCH" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RECEIPTS_XFM_ARCH" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_AR_CASH_RECEIPTS_XFM_ARCH" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
