--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG_ARCH" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG_ARCH" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG_ARCH" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
