--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RECEIPTS_STG_17072023
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_17072023" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_17072023" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_AR_CASH_RECEIPTS_STG_17072023" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
