--------------------------------------------------------
--  DDL for Table XXMX_HZ_LOCATIONS_STG_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"LOCATION_ORIG_SYSTEM" VARCHAR2(30 BYTE), 
	"LOCATION_ORIG_SYSTEM_REFERENCE" VARCHAR2(240 BYTE), 
	"INSERT_UPDATE_FLAG" VARCHAR2(1 BYTE), 
	"COUNTRY" VARCHAR2(2 BYTE), 
	"ADDRESS1" VARCHAR2(240 BYTE), 
	"ADDRESS2" VARCHAR2(240 BYTE), 
	"ADDRESS3" VARCHAR2(240 BYTE), 
	"ADDRESS4" VARCHAR2(240 BYTE), 
	"CITY" VARCHAR2(60 BYTE), 
	"STATE" VARCHAR2(60 BYTE), 
	"PROVINCE" VARCHAR2(60 BYTE), 
	"COUNTY" VARCHAR2(60 BYTE), 
	"POSTAL_CODE" VARCHAR2(60 BYTE), 
	"POSTAL_PLUS4_CODE" VARCHAR2(10 BYTE), 
	"LOCATION_LANGUAGE" VARCHAR2(4 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"SHORT_DESCRIPTION" VARCHAR2(240 BYTE), 
	"SALES_TAX_GEOCODE" VARCHAR2(30 BYTE), 
	"SALES_TAX_INSIDE_CITY_LIMITS" VARCHAR2(1 BYTE), 
	"TIMEZONE_CODE" VARCHAR2(50 BYTE), 
	"ADDRESS1_STD" VARCHAR2(240 BYTE), 
	"ADAPTER_CONTENT_SOURCE" VARCHAR2(30 BYTE), 
	"ADDR_VALID_STATUS_CODE" VARCHAR2(30 BYTE), 
	"DATE_VALIDATED" DATE, 
	"ADDRESS_EFFECTIVE_DATE" DATE, 
	"ADDRESS_EXPIRATION_DATE" DATE, 
	"VALIDATED_FLAG" VARCHAR2(1 BYTE), 
	"DO_NOT_VALIDATE_FLAG" VARCHAR2(1 BYTE), 
	"INTERFACE_STATUS" VARCHAR2(30 BYTE), 
	"ERROR_ID" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"ATTRIBUTE16" VARCHAR2(150 BYTE), 
	"ATTRIBUTE17" VARCHAR2(150 BYTE), 
	"ATTRIBUTE18" VARCHAR2(150 BYTE), 
	"ATTRIBUTE19" VARCHAR2(150 BYTE), 
	"ATTRIBUTE20" VARCHAR2(150 BYTE), 
	"ATTRIBUTE21" VARCHAR2(150 BYTE), 
	"ATTRIBUTE22" VARCHAR2(150 BYTE), 
	"ATTRIBUTE23" VARCHAR2(150 BYTE), 
	"ATTRIBUTE24" VARCHAR2(150 BYTE), 
	"ATTRIBUTE25" VARCHAR2(150 BYTE), 
	"ATTRIBUTE26" VARCHAR2(150 BYTE), 
	"ATTRIBUTE27" VARCHAR2(150 BYTE), 
	"ATTRIBUTE28" VARCHAR2(150 BYTE), 
	"ATTRIBUTE29" VARCHAR2(150 BYTE), 
	"ATTRIBUTE30" VARCHAR2(255 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_NUMBER11" NUMBER, 
	"ATTRIBUTE_NUMBER12" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_DATE11" DATE, 
	"ATTRIBUTE_DATE12" DATE, 
	"GNR_STATUS" VARCHAR2(4 BYTE), 
	"LOAD_REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_HZ_LOCATIONS_STG_ARCH" TO "XXMX_READONLY";
