--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SELFPACE_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
