--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_STG" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_STG" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
