--------------------------------------------------------
--  DDL for Table XXMX_POSITIONS_F_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_POSITIONS_F_STG" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"POSITION_ID" VARCHAR2(264 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"BUSINESS_UNIT_NAME" VARCHAR2(264 BYTE), 
	"POSITION_CODE" VARCHAR2(60 BYTE), 
	"ORGANIZATION_ID" VARCHAR2(264 BYTE), 
	"JOB_ID" VARCHAR2(264 BYTE), 
	"LOCATION_ID" VARCHAR2(264 BYTE), 
	"ENTRY_GRADE_ID" VARCHAR2(264 BYTE), 
	"ENTRY_STEP_ID" VARCHAR2(264 BYTE), 
	"SUPERVISOR_ID" VARCHAR2(264 BYTE), 
	"SUPERVISOR_ASSIGNMENT_ID" VARCHAR2(264 BYTE), 
	"ACTION_OCCURRENCE_ID" VARCHAR2(264 BYTE), 
	"ACTIVE_STATUS" VARCHAR2(30 BYTE), 
	"HIRING_STATUS" VARCHAR2(30 BYTE), 
	"POSITION_TYPE" VARCHAR2(30 BYTE), 
	"PERMANENT_TEMPORARY_FLAG" VARCHAR2(30 BYTE), 
	"FULL_PART_TIME" VARCHAR2(30 BYTE), 
	"FTE" NUMBER(10,0), 
	"MAX_PERSONS" NUMBER(4,0), 
	"WORKING_HOURS" NUMBER(22,0), 
	"FREQUENCY" VARCHAR2(30 BYTE), 
	"TIME_NORMAL_START" VARCHAR2(5 BYTE), 
	"TIME_NORMAL_FINISH" VARCHAR2(5 BYTE), 
	"PROBATION_PERIOD" NUMBER(22,0), 
	"PROBATION_PERIOD_UNIT_CD" VARCHAR2(30 BYTE), 
	"BARGAINING_UNIT_CD" VARCHAR2(30 BYTE), 
	"POSITION_SYNCHRONIZATION_FLAG" VARCHAR2(30 BYTE), 
	"SECURITY_CLEARANCE" VARCHAR2(30 BYTE), 
	"OVERLAP_ALLOWED" VARCHAR2(30 BYTE), 
	"SEASONAL_FLAG" VARCHAR2(30 BYTE), 
	"SEASONAL_START_DATE" DATE, 
	"SEASONAL_END_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"ATTRIBUTE16" VARCHAR2(150 BYTE), 
	"ATTRIBUTE17" VARCHAR2(150 BYTE), 
	"ATTRIBUTE18" VARCHAR2(150 BYTE), 
	"ATTRIBUTE19" VARCHAR2(150 BYTE), 
	"ATTRIBUTE20" VARCHAR2(150 BYTE), 
	"ATTRIBUTE21" VARCHAR2(150 BYTE), 
	"ATTRIBUTE22" VARCHAR2(150 BYTE), 
	"ATTRIBUTE23" VARCHAR2(150 BYTE), 
	"ATTRIBUTE24" VARCHAR2(150 BYTE), 
	"ATTRIBUTE25" VARCHAR2(150 BYTE), 
	"ATTRIBUTE26" VARCHAR2(150 BYTE), 
	"ATTRIBUTE27" VARCHAR2(150 BYTE), 
	"ATTRIBUTE28" VARCHAR2(150 BYTE), 
	"ATTRIBUTE29" VARCHAR2(150 BYTE), 
	"ATTRIBUTE30" VARCHAR2(150 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_POSITIONS_F_STG" TO "XXMX_CORE";
