--------------------------------------------------------
--  DDL for Table XXMX_OLC_INSTR_LED_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'InstructorLedActivity', 
	"ACTIVITY_ID" NUMBER, 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"ACTIVITY_NUMBER" VARCHAR2(30 BYTE), 
	"ACTIVITY_POSITION" NUMBER, 
	"TITLE" VARCHAR2(250 BYTE), 
	"DESCRIPTION" CLOB, 
	"ACTIVITY_DATE" DATE, 
	"ACTIVITY_START_TIME" VARCHAR2(50 BYTE), 
	"ACTIVITY_END_TIME" VARCHAR2(50 BYTE), 
	"TIME_ZONE" VARCHAR2(30 BYTE), 
	"EXPECTED_EFFORT" NUMBER, 
	"SELF_COMPLETE_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"OFFERING_ID" NUMBER, 
	"OFFERING_NUMBER" VARCHAR2(30 BYTE), 
	"VIRTUAL_CLASSROOM_URL" VARCHAR2(500 BYTE), 
	"CLASSROOM_RESOURCE_ID" NUMBER, 
	"CLASSROOM_RESOURCE_NUMBER" VARCHAR2(30 BYTE), 
	"SOURCE_TYPE" VARCHAR2(30 BYTE), 
	"SOURCE_ID" NUMBER, 
	"SOURCE_INFO" VARCHAR2(240 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"DESCRIPTION_TEXT" VARCHAR2(4000 BYTE), 
	"VIRTUAL_PROVIDER_ID" NUMBER, 
	"VIRTUAL_PROVIDER_NUMBER" VARCHAR2(30 BYTE), 
	"VIRTUAL_PROVIDER_PRODUCT" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "XXMX_STG" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_OLC_INSTR_LED_STG" TO "XXMX_CORE";
