--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("OFFERING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("LANGUAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("COORDINATOR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
