--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_PMT_INSTRS_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"TEMP_EXT_PARTY_ID" NUMBER, 
	"TEMP_EXT_BANK_ACCT_ID" NUMBER, 
	"TEMP_PMT_INSTR_USE_ID" NUMBER, 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"ACCT_ASSIG_START_DATE" DATE, 
	"ACCT_ASSIG_END_DATE" DATE, 
	"OU_NAME" VARCHAR2(100 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_SITE_ID" NUMBER, 
	"SUPPLIER_SITE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_AP_SUPP_PMT_INSTRS_STG" TO "XXMX_CORE";
