--------------------------------------------------------
--  Constraints for Table XXMX_CITIZENSHIPS_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_CITIZENSHIPS_STG_ARCH" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_CITIZENSHIPS_STG_ARCH" MODIFY ("CITIZENSHIP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_CITIZENSHIPS_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
