--------------------------------------------------------
--  Constraints for Table XXMX_LOC_DETAILS_TL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_LOC_DETAILS_TL_STG" MODIFY ("LOCATION_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_LOC_DETAILS_TL_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_LOC_DETAILS_TL_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_LOC_DETAILS_TL_STG" MODIFY ("LANGUAGE" NOT NULL ENABLE);
