--------------------------------------------------------
--  DDL for Table XXMX_USER_DATA_ACCESS_STG_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(30 BYTE), 
	"ORIG_USER_NAME" VARCHAR2(240 BYTE), 
	"NEW_USER_NAME" VARCHAR2(240 BYTE), 
	"ROLE" VARCHAR2(100 BYTE), 
	"SECURITY_CONTEXT" VARCHAR2(100 BYTE), 
	"SECURITY_CONTEXT_VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" TO "XXMX_CORE";
