--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_PRICE_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_STG" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_STG" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_STG" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
