--------------------------------------------------------
--  DDL for Table XXMX_PPM_PRJ_CLASS_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BATCH_ID" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"PROJECT_NAME" VARCHAR2(240 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"CLASS_CATEGORY" VARCHAR2(240 BYTE), 
	"CLASS_CODE" VARCHAR2(240 BYTE), 
	"CODE_PERCENTAGE" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"PROJECT_LONG_NAME" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" TO "XXMX_CORE";
