--------------------------------------------------------
--  DDL for Table XXMX_SCM_PO_LINE_LOCATIONS_STD_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"INTERFACE_LINE_LOCATION_KEY" VARCHAR2(50 BYTE), 
	"INTERFACE_LINE_KEY" VARCHAR2(50 BYTE), 
	"SHIPMENT_NUM" NUMBER, 
	"SHIP_TO_LOCATION" VARCHAR2(60 BYTE), 
	"SHIP_TO_ORGANIZATION_CODE" VARCHAR2(18 BYTE), 
	"AMOUNT" NUMBER, 
	"QUANTITY" NUMBER, 
	"NEED_BY_DATE" DATE, 
	"PROMISED_DATE" DATE, 
	"SECONDARY_QUANTITY" NUMBER, 
	"SECONDARY_UNIT_OF_MEASURE" VARCHAR2(18 BYTE), 
	"DESTINATION_TYPE_CODE" VARCHAR2(25 BYTE), 
	"ACCRUE_ON_RECEIPT_FLAG" VARCHAR2(1 BYTE), 
	"ALLOW_SUBSTITUTE_RECEIPTS_FLAG" VARCHAR2(1 BYTE), 
	"ASSESSABLE_VALUE" NUMBER, 
	"DAYS_EARLY_RECEIPT_ALLOWED" NUMBER, 
	"DAYS_LATE_RECEIPT_ALLOWED" NUMBER, 
	"ENFORCE_SHIP_TO_LOCATION_CODE" VARCHAR2(25 BYTE), 
	"INSPECTION_REQUIRED_FLAG" VARCHAR2(1 BYTE), 
	"RECEIPT_REQUIRED_FLAG" VARCHAR2(1 BYTE), 
	"INVOICE_CLOSE_TOLERANCE" NUMBER, 
	"RECEIPT_CLOSE_TOLERANCE" NUMBER, 
	"QTY_RCV_TOLERANCE" NUMBER, 
	"QTY_RCV_EXCEPTION_CODE" VARCHAR2(25 BYTE), 
	"RECEIPT_DAYS_EXCEPTION_CODE" VARCHAR2(25 BYTE), 
	"RECEIVING_ROUTING" VARCHAR2(30 BYTE), 
	"NOTE_TO_RECEIVER" VARCHAR2(1000 BYTE), 
	"INPUT_TAX_CLASSIFICATION_CODE" VARCHAR2(30 BYTE), 
	"LINE_INTENDED_USE" VARCHAR2(240 BYTE), 
	"PRODUCT_CATEGORY" VARCHAR2(240 BYTE), 
	"PRODUCT_FISC_CLASSIFICATION" VARCHAR2(240 BYTE), 
	"PRODUCT_TYPE" VARCHAR2(240 BYTE), 
	"TRX_BUSINESS_CATEGORY_CODE" VARCHAR2(240 BYTE), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"ATTRIBUTE16" VARCHAR2(150 BYTE), 
	"ATTRIBUTE17" VARCHAR2(150 BYTE), 
	"ATTRIBUTE18" VARCHAR2(150 BYTE), 
	"ATTRIBUTE19" VARCHAR2(150 BYTE), 
	"ATTRIBUTE20" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_NUMBER1" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER2" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER3" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER4" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER5" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER6" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER7" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER8" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER9" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER10" NUMBER(18,0), 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP6" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP7" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP8" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP9" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP10" TIMESTAMP (6), 
	"FREIGHT_CARRIER" VARCHAR2(360 BYTE), 
	"MODE_OF_TRANSPORT" VARCHAR2(80 BYTE), 
	"SERVICE_LEVEL" VARCHAR2(80 BYTE), 
	"FINAL_DISCHARGE_LOCATION_CODE" VARCHAR2(60 BYTE), 
	"REQUESTED_SHIP_DATE" DATE, 
	"PROMISED_SHIP_DATE" DATE, 
	"REQUESTED_DELIVERY_DATE" DATE, 
	"PROMISED_DELIVERY_DATE" DATE, 
	"RETAINAGE_RATE" NUMBER, 
	"INVOICE_MATCH_OPTION" VARCHAR2(25 BYTE), 
	"PO_HEADER_ID" VARCHAR2(30 BYTE), 
	"PO_LINE_ID" VARCHAR2(30 BYTE), 
	"LINE_LOCATION_ID" VARCHAR2(30 BYTE), 
	"DOCUMENT_NUM" VARCHAR2(30 BYTE), 
	"LINE_NUM" NUMBER, 
	"ORIGINAL_AMOUNT" NUMBER, 
	"MIGRATED_AMOUNT" NUMBER, 
	"ORIGINAL_QUANTITY" NUMBER, 
	"MIGRATED_QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_SCM_PO_LINE_LOCATIONS_STD_STG" TO "XXMX_CORE";
