--------------------------------------------------------
--  DDL for Table XXMX_HZ_PERSON_LANGUAGE_STG_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PARTY_ORIG_SYSTEM" VARCHAR2(30 BYTE), 
	"PARTY_ORIG_SYSTEM_REFERENCE" VARCHAR2(240 BYTE), 
	"LANGUAGE_NAME" VARCHAR2(30 BYTE), 
	"NATIVE_LANGUAGE_FLAG" VARCHAR2(1 BYTE), 
	"PRIMARY_LANGUAGE_INDICATOR" VARCHAR2(1 BYTE), 
	"LOAD_REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_HZ_PERSON_LANGUAGE_STG_ARCH" TO "XXMX_READONLY";
