--------------------------------------------------------
--  Constraints for Table XXMX_JOBS_F_TL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_JOBS_F_TL_STG" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_JOBS_F_TL_STG" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_JOBS_F_TL_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_JOBS_F_TL_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
