--------------------------------------------------------
--  DDL for Index XXMX_JOBS_F_STG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_STG"."XXMX_JOBS_F_STG_PK" ON "XXMX_STG"."XXMX_JOBS_F_STG" ("JOB_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
