--------------------------------------------------------
--  Constraints for Table XXMX_PER_RELIGION_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_RELIGION_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_RELIGION_STG_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_RELIGION_STG_ARCH" MODIFY ("RELIGION" NOT NULL ENABLE);
