--------------------------------------------------------
--  Constraints for Table XXMX_ASG_WORKMSURE_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_ASG_WORKMSURE_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_WORKMSURE_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_WORKMSURE_STG" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_WORKMSURE_STG" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_WORKMSURE_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
