--------------------------------------------------------
--  Constraints for Table XXMX_USER_DATA_ACCESS_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("SOURCE_SYSTEM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("NEW_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("SECURITY_CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG_ARCH" MODIFY ("SECURITY_CONTEXT_VALUE" NOT NULL ENABLE);
