--------------------------------------------------------
--  Constraints for Table XXMX_OLC_GLOB_ACC_GRP_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG_ARCH" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG_ARCH" MODIFY ("GLOBAL_ACCESS_GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG_ARCH" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG_ARCH" MODIFY ("PRIORITY" NOT NULL ENABLE);
