--------------------------------------------------------
--  Constraints for Table XXMX_ASG_GRADESTEP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG" MODIFY ("GRADENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG" MODIFY ("GRADESTEPNAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_GRADESTEP_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
