--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("OFFERING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("LANGUAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("COORDINATOR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_STG_ARCH" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
