--------------------------------------------------------
--  Constraints for Table XXMX_ASG_PAYROLL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_ASG_PAYROLL_STG" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_PAYROLL_STG" MODIFY ("PAYROLL_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_PAYROLL_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_ASG_PAYROLL_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
