--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG_ARCH" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG_ARCH" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_ASG_SALARY_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
