--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_CUST_PRICE_COMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_COMP_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_COMP_STG" MODIFY ("PRICING_COMPONENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_COMP_STG" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_OFFER_CUST_PRICE_COMP_STG" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
