--------------------------------------------------------
--  Constraints for Table XXMX_PER_PERSONS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_PERSONS_STG" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PERSONS_STG" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PERSONS_STG" ADD CONSTRAINT "PK_PERSON_ID" PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG"  ENABLE;
