--------------------------------------------------------
--  Constraints for Table XXMX_PER_IMAGES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG" MODIFY ("IMAGENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG" MODIFY ("IMAGE_REF" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_IMAGES_STG" MODIFY ("IMAGETYPE" NOT NULL ENABLE);
