--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_REL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG" MODIFY ("CONTACTTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACT_REL_STG" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
