--------------------------------------------------------
--  Constraints for Table XXMX_BEN_BE_DB_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BEN_PLAN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BEN_OPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("ORIGINAL_ENROLLMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_BE_DB_STG" MODIFY ("BENEFICIARY_FIRST_NAME" NOT NULL ENABLE);
