--------------------------------------------------------
--  DDL for Table XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'MediaLinkLanguage', 
	"LANGUAGE_CODE" VARCHAR2(4 BYTE), 
	"MEDIA_LINK_ID" NUMBER(18,0), 
	"MEDIA_LINK_LANGUAGE_ID" NUMBER(18,0), 
	"SEQUENCE_NUMBER" NUMBER(9,0), 
	"CODE" VARCHAR2(240 BYTE), 
	"REQ_MEDIA_LINK_ID" NUMBER(18,0), 
	"GUID" VARCHAR2(32 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT SELECT ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_STG" TO "XXMX_CORE";
