--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_PHONES_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
