--------------------------------------------------------
--  Constraints for Table XXMX_BEN_DE_DD_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("BEN_PLAN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("BEN_OPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("ORIGINAL_ENROLLMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("DEPENDENT_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("DEPENDENT_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("DEPENDENT_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("DEPENDENT_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_BEN_DE_DD_STG_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
