--------------------------------------------------------
--  Constraints for Table XXMX_EXT_BANK_ACC_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("BANK_ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("BANK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("SORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_EXT_BANK_ACC_STG_ARCH" MODIFY ("EXT_BANK_ACC_OWNER" NOT NULL ENABLE);
