--------------------------------------------------------
--  Constraints for Table XXMX_PER_SENIORITYDT_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG" MODIFY ("SENIORITYDATECODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG" MODIFY ("MANUALADJUSTMENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG" MODIFY ("DATESTART" NOT NULL ENABLE);
