--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_TL_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_TL_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_TL_STG" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_TL_STG" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
