--------------------------------------------------------
--  Constraints for Table XXMX_OLC_GLOB_ACC_GRP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG" MODIFY ("GLOBAL_ACCESS_GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_GLOB_ACC_GRP_STG" MODIFY ("PRIORITY" NOT NULL ENABLE);
