--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"IMPORT_ACTION" VARCHAR2(10 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_SITE_ID" NUMBER, 
	"SUPPLIER_SITE" VARCHAR2(15 BYTE), 
	"PROCUREMENT_BU" VARCHAR2(240 BYTE), 
	"CLIENT_BU" VARCHAR2(240 BYTE), 
	"BILL_TO_BU" VARCHAR2(240 BYTE), 
	"SHIP_TO_LOCATION" VARCHAR2(60 BYTE), 
	"BILL_TO_LOCATION" VARCHAR2(60 BYTE), 
	"USE_WITHHOLDING_TAX" VARCHAR2(1 BYTE), 
	"WITHHOLDING_TAX_GROUP" VARCHAR2(25 BYTE), 
	"LIABILITY_DISTRIBUTION" VARCHAR2(800 BYTE), 
	"PREPAYMENT_DISTRIBUTION" VARCHAR2(800 BYTE), 
	"BILLS_PAYABLE_DISTRIBUTION" VARCHAR2(800 BYTE), 
	"DISTRIBUTION_SET" VARCHAR2(50 BYTE), 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
  GRANT FLASHBACK ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT ALTER ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_STG"."XXMX_AP_SUPP_SITE_ASSIGNS_STG_ARCH" TO "XXMX_READONLY";
