--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RES_STG" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RES_STG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RES_STG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RES_STG" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RES_STG" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
