--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACTS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_CONTACTS_STG" MODIFY ("CNTPERSONNUMBER" NOT NULL ENABLE);
