--------------------------------------------------------
--  Constraints for Table XXMX_PER_NID_F_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG" MODIFY ("NATIONAL_IDENTIFIER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG" MODIFY ("NATIONAL_IDENTIFIER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
