--------------------------------------------------------
--  Constraints for Table XXMX_USER_DATA_ACCESS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("SOURCE_SYSTEM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("NEW_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("SECURITY_CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_USER_DATA_ACCESS_STG" MODIFY ("SECURITY_CONTEXT_VALUE" NOT NULL ENABLE);
