--------------------------------------------------------
--  Constraints for Table XXMX_PER_NID_F_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG_ARCH" MODIFY ("NATIONAL_IDENTIFIER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG_ARCH" MODIFY ("NATIONAL_IDENTIFIER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_NID_F_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
