--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SELFPACE_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG_ARCH" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SELFPACE_STG_ARCH" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
