--------------------------------------------------------
--  Constraints for Table XXMX_PER_SENIORITYDT_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG_ARCH" MODIFY ("SENIORITYDATECODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG_ARCH" MODIFY ("MANUALADJUSTMENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_PER_SENIORITYDT_STG_ARCH" MODIFY ("DATESTART" NOT NULL ENABLE);
