--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COMM_RS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_COMM_RS_STG" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COMM_RS_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COMM_RS_STG" MODIFY ("COMMUNITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COMM_RS_STG" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
