--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH" MODIFY ("PRICING_COMPONENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_COURSE_PRICE_COMP_STG_ARCH" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
