--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_SXN_ACT_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_ACT_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_ACT_STG" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_ACT_STG" MODIFY ("SPECIALIZATION_SECTION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_SPEC_SXN_ACT_STG" MODIFY ("ACTIVITY_POSITION" NOT NULL ENABLE);
