--------------------------------------------------------
--  Constraints for Table XXMX_OLC_ADHOC_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_ADHOC_STG_ARCH" MODIFY ("ADHOC_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_ADHOC_STG_ARCH" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_ADHOC_STG_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
