--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RESV_STG_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG_ARCH" MODIFY ("CLASSROOM_RESERVATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG_ARCH" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_OLC_CLASS_RESV_STG_ARCH" MODIFY ("ACTIVITY_NUMBER" NOT NULL ENABLE);
