--------------------------------------------------------
--  DDL for Index XXMX_OLC_SPEC_DEF_ACC_STG_PK
--------------------------------------------------------

  CREATE INDEX "XXMX_STG"."XXMX_OLC_SPEC_DEF_ACC_STG_PK" ON "XXMX_STG"."XXMX_OLC_SPEC_DEF_ACC_STG" ("DEFAULT_ACCESS_NUMBER", "SPECIALIZATION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_STG" ;
