--------------------------------------------------------
--  Constraints for Table XXMX_RESP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("EBS_RESPONSIBILITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("EBS_RESPONSIBILITY_KEY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("EBS_APPLICATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_STG"."XXMX_RESP_STG" MODIFY ("ADD_REMOVE_ROLE" NOT NULL ENABLE);
