         xxmx_migration_metadata_ids_s.NEXTVAL
		,'FIN'
		,'AP'
		,:vn_BusinessEntitySeq
		,'SUPPLIERS'
		,:vn_SubEntitySeq
		,'SUPPLIERS'
		,'xxmx_supplier_pkg'
		,'ap_suppliers_stg'
		,'XXMX_AP_SUPPLIERS_STG'
		,NULL
		,'XXMX_AP_SUPPLIERS_XFM'
		,'xxmx_supplier_validations_pkg'
		,'validate_supplier_profiles'
		,'XXMX_AP_SUPPLIERS_VAL'
		,NULL
		,NULL
		,NULL
		,'PozSuppliersInt'
		,'csv'
		,1
		,'Y'
		,'Y'
		,NULL
		,NULL
		,NULL