INSERT INTO XXMX_OLC_SPEC_STG(
MIGRATION_SET_ID,
MIGRATION_SET_NAME,
MIGRATION_STATUS,
BG_NAME,
METADATA,
OBJECTNAME,
EFFECTIVE_START_DATE,
SPECIALIZATION_NUMBER,
TITLE,
SHORT_DESCRIPTION,
PUBLISH_START_DATE,
OWNED_BY_PERSON_NUMBER,
MINIMUM_EXPECTED_EFFORT,
MAXIMUM_EXPECTED_EFFORT,
SOURCE_SYSTEM_OWNER,
SOURCE_SYSTEM_ID)

VALUES(
2025,
'TEST_MIGRATION_SPEC',
'EXTRACTED',
'TEST_BG',
'MERGE',
'Specialization',
DATE '2021-08-15',
'SPL111222',
'Next Simple Specialization',
'Next Simple Specialization Short Description',
DATE '2021-08-15',
'1000005',
1,
9,
'DATAMIGRATION',
'SPLN1112221'
)
/

VALUES(
2025,
'TEST_MIGRATION_SPEC',
'EXTRACTED',
'TEST_BG',
'MERGE',
'Specialization',
DATE '2021-08-15',
'SPL111223',
'Next Typical Specialization',
'Next Typical Specialization Short Description',
DATE '2021-08-15',
'1000005',
1,
9,
'DATAMIGRATION',
'SPLN1112231'
)
/