INSERT INTO XXMX_OLC_SPEC_SXN_STG(
MIGRATION_SET_ID,
MIGRATION_SET_NAME,
MIGRATION_STATUS,
BG_NAME,
METADATA,
OBJECTNAME,
EFFECTIVE_START_DATE,
SPECIALIZATION_SECTION_NUMBER,
TITLE,
NUM_OF_ACTIVITIES_TO_COMPLETE,
INIT_ASSIGN_STATUS_ACTIVITIES,
SECTION_POSITION,
SPECIALIZATION_NUMBER,
SOURCE_SYSTEM_OWNER,
SOURCE_SYSTEM_ID)

VALUES(
2026,
'TEST_MIGRATION_SPEC_SXN',
'EXTRACTED',
'TEST_BG',
'MERGE',
'SpecializationSection',
DATE '2021-08-15',
'SSN111111',
'Next Simple Specialization Section',
1,
0,
'Active',
'SPL111222',
'DATAMIGRATION',
'SSNO1111111')
/

VALUES(
2026,
'TEST_MIGRATION_SPEC_SXN',
'EXTRACTED',
'TEST_BG',
'MERGE',
'SpecializationSection',
DATE '2021-08-15',
'SSN111112',
'Next Typical Specialization Section One',
1,
0,
'Active',
'SPL111223',
'DATAMIGRATION',
'SSNO1111121')
/

VALUES(
2026,
'TEST_MIGRATION_SPEC_SXN',
'EXTRACTED',
'TEST_BG',
'MERGE',
'SpecializationSection',
DATE '2021-08-15',
'SSN111113',
'Next Typical Specialization Section Two',
2,
0,
'Active',
'SPL111223',
'DATAMIGRATION',
'SSNO1111131')
/