--
/***************************************
** HCM Metadata (TM) - Talent Management
***************************************/
--
/*
** Performance Document
*/
--
EXECUTE :vn_BusinessEntitySeq := :vn_BusinessEntitySeq + 1;
EXECUTE :vn_SubEntitySeq := 0;
--
EXECUTE :vn_SubEntitySeq := :vn_SubEntitySeq + 1;
--
INSERT
INTO   xxmx_core.xxmx_migration_metadata
         (
         metadata_id
		,application_suite
		,application
		,business_entity_seq
		,business_entity
		,sub_entity_seq
		,sub_entity
		,entity_package_name
		,sql_load_name
		,stg_procedure_name
		,stg_table
		,xfm_procedure_name
		,xfm_table
		,file_gen_procedure_name
		,data_file_name
		,data_file_extension
		,file_group_number
		,enabled_flag
		,simple_xfm_performed_by
		,file_gen_performed_by
		,file_gen_package
		,batch_load
		,seq_in_fbdi_data
		 )
VALUES
         (
          xxmx_migration_metadata_ids_s.NEXTVAL
         ,'HCM'
         ,'TM'
         ,:vn_BusinessEntitySeq
         ,'PERFORMANCE_DOCUMENT'
         ,:vn_SubEntitySeq
         ,'PERFORMANCE_DOCUMENT'
         ,'xxmx_hcm_perf_doc_pkg'
         ,NULL
         ,'hcm_performance_doc_stg'
         ,'XXMX_HCM_PERFORMANCE_DOC_STG'
         ,NULL
         ,'XXMX_HCM_PERFORMANCE_DOC_XFM'
         ,NULL
         ,'PerfDocComplete'
         ,'dat'
         ,1
         ,'Y'
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
         );

---
---
---
EXECUTE :vn_SubEntitySeq := :vn_SubEntitySeq + 1;
--
INSERT
INTO   xxmx_core.xxmx_migration_metadata
         (
         metadata_id
		,application_suite
		,application
		,business_entity_seq
		,business_entity
		,sub_entity_seq
		,sub_entity
		,entity_package_name
		,sql_load_name
		,stg_procedure_name
		,stg_table
		,xfm_procedure_name
		,xfm_table
		,file_gen_procedure_name
		,data_file_name
		,data_file_extension
		,file_group_number
		,enabled_flag
		,simple_xfm_performed_by
		,file_gen_performed_by
		,file_gen_package
		,batch_load
		,seq_in_fbdi_data
		 )
VALUES
         (
          xxmx_migration_metadata_ids_s.NEXTVAL
         ,'HCM'
         ,'TM'
         ,:vn_BusinessEntitySeq
         ,'PERFORMANCE_DOCUMENT'
         ,:vn_SubEntitySeq
         ,'ATTACHMENT'
         ,'xxmx_hcm_perf_doc_pkg'
         ,NULL
         ,'hcm_attachment_stg'
         ,'XXMX_HCM_ATTACHMENT_STG'
         ,NULL
         ,'XXMX_HCM_ATTACHMENT_XFM'
         ,NULL
         ,'PerfDocComplete'
         ,'dat'
         ,1
         ,'Y'
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
         );
		 ---
---
---
EXECUTE :vn_SubEntitySeq := :vn_SubEntitySeq + 1;
--
INSERT
INTO   xxmx_core.xxmx_migration_metadata
         (
         metadata_id
		,application_suite
		,application
		,business_entity_seq
		,business_entity
		,sub_entity_seq
		,sub_entity
		,entity_package_name
		,sql_load_name
		,stg_procedure_name
		,stg_table
		,xfm_procedure_name
		,xfm_table
		,file_gen_procedure_name
		,data_file_name
		,data_file_extension
		,file_group_number
		,enabled_flag
		,simple_xfm_performed_by
		,file_gen_performed_by
		,file_gen_package
		,batch_load
		,seq_in_fbdi_data
		 )
VALUES
         (
          xxmx_migration_metadata_ids_s.NEXTVAL
         ,'HCM'
         ,'TM'
         ,:vn_BusinessEntitySeq
         ,'PERFORMANCE_DOCUMENT'
         ,:vn_SubEntitySeq
         ,'PARTICIPANT'
         ,'xxmx_hcm_perf_doc_pkg'
         ,NULL
         ,'hcm_participant_stg'
         ,'XXMX_HCM_PARTICIPANT_STG'
         ,NULL
         ,'XXMX_HCM_PARTICIPANT_XFM'
         ,NULL
         ,'PerfDocComplete'
         ,'dat'
         ,1
         ,'Y'
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
         );
		 ---
---
---
EXECUTE :vn_SubEntitySeq := :vn_SubEntitySeq + 1;
--
INSERT
INTO   xxmx_core.xxmx_migration_metadata
         (
         metadata_id
		,application_suite
		,application
		,business_entity_seq
		,business_entity
		,sub_entity_seq
		,sub_entity
		,entity_package_name
		,sql_load_name
		,stg_procedure_name
		,stg_table
		,xfm_procedure_name
		,xfm_table
		,file_gen_procedure_name
		,data_file_name
		,data_file_extension
		,file_group_number
		,enabled_flag
		,simple_xfm_performed_by
		,file_gen_performed_by
		,file_gen_package
		,batch_load
		,seq_in_fbdi_data
		 )
VALUES
         (
          xxmx_migration_metadata_ids_s.NEXTVAL
         ,'HCM'
         ,'TM'
         ,:vn_BusinessEntitySeq
         ,'PERFORMANCE_DOCUMENT'
         ,:vn_SubEntitySeq
         ,'RATINGS_COMMENTS'
         ,'xxmx_hcm_perf_doc_pkg'
         ,NULL
         ,'hcm_ratings_comments_stg'
         ,'XXMX_HCM_RATINGS_COMMENTS_STG'
         ,NULL
         ,'XXMX_HCM_RATINGS_COMMENTS_XFM'
         ,NULL
         ,'PerfDocComplete'
         ,'dat'
         ,1
         ,'Y'
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
		 ,NULL
         );