--*****************************************************************************
--**
--**                 Copyright (c) 2020 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  xxmx_hcm_ben_xfm_dbi.sql
--**
--** FILEPATH  :  $XXV1_TOP/install/sql
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :   XXMX_XFM
--**
--** AUTHORS   :  Shaik Latheef
--**
--** PURPOSE   :  This script installs the staging tables for the HCM 
--**              common Procedures and Functions packages.
--**
--** NOTES     :
--**
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--******************************************************************************

DROP TABLE XXMX_XFM.XXMX_BEN_PE_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_PE_CO_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_DE_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_DE_DD_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_BE_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_BE_DB_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_PBG_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_PBB_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_PH_XFM;
DROP TABLE XXMX_XFM.XXMX_BEN_PBO_XFM;


-- ***********************************************
-- Participant Enrollment Table
-- XXMX_BEN_PE_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PE_XFM
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_ID				NUMBER(18) NOT NULL,
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	EFFECTIVE_DATE			DATE NOT NULL,
	LEGAL_EMPLOYER			VARCHAR2(240),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );

-- ***********************************************
-- Participant Compensation Table
-- XXMX_BEN_PE_CO_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PE_CO_XFM
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID 					NUMBER(18) NOT NULL,
	PLAN						VARCHAR2(240) NOT NULL,
	PROGRAM						VARCHAR2(240),
	OPTION						VARCHAR2(240) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	RATE						NUMBER(18),
	COVERAGE					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	DENROLL_PROGRAM				VARCHAR2(240),
	DENROLL_PLAN				VARCHAR2(240),
	DENROLL_OPTION				VARCHAR2(240),
	LINE_NUMBER					NUMBER(18) NOT NULL,
	ENROLLMENT_LINE_ID			NUMBER(18) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
-- ***********************************************
-- Dependent Enrollment Table
-- XXMX_BEN_DE_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_DE_XFM
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	EFFECTIVE_DATE			DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	PERSON_ID				NUMBER(18) NOT NULL,
	LEGAL_EMPLOYER			VARCHAR2(240),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
-- ***********************************************
-- Dependent Designation Table
-- XXMX_BEN_DE_DD_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_DE_DD_XFM
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID					NUMBER(18) NOT NULL,
	PLAN						VARCHAR2(240) NOT NULL,
	PROGRAM						VARCHAR2(240),
	OPTION						VARCHAR2(240) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	DEPENDENT_PERSON_NUMBER		VARCHAR2(30) NOT NULL,
	DEPENDENT_PERSON_ID			NUMBER(18) NOT NULL,
	LINE_NUMBER					NUMBER(18) NOT NULL,
	DEPENDENT_LINE_ID			NUMBER(18) NOT NULL,
	DEPENDENT_FIRST_NAME		VARCHAR2(150),
	DEPENDENT_LAST_NAME			VARCHAR2(150),
	DEPENDENT_DATE_OF_BIRTH		DATE,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );    
   
   
-- ***********************************************
-- Beneficiary Enrollment Table
-- XXMX_BEN_BE_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_BE_XFM
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	EFFECTIVE_DATE			DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	PERSON_ID				NUMBER(18) NOT NULL,
	LEGAL_EMPLOYER			VARCHAR2(240),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   ); 
   
-- ***********************************************
-- Beneficiary Designation Table
-- XXMX_BEN_BE_DB_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_BE_DB_XFM
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID					NUMBER(18) NOT NULL,
	PLAN						VARCHAR2(240) NOT NULL,
	PROGRAM						VARCHAR2(240),
	OPTION						VARCHAR2(240) NOT NULL,
	BENEFICIARY_PERCENTAGE		NUMBER(18) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	BENEFICIARY_PERSON_NUMBER	VARCHAR2(30) NOT NULL,
	BENEFICIARY_PERSON_ID		NUMBER(18) NOT NULL,
	BENEFICIARY_TYPE			VARCHAR2(30) NOT NULL,
	LINE_NUMBER					NUMBER(18) NOT NULL,
	BENEFICIARY_LINE_ID			NUMBER(18) NOT NULL,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	BENEFICIARY_LAST_NAME		VARCHAR2(150),
	BENEFICIARY_FIRST_NAME		VARCHAR2(150),
	BENEFICIARY_DATE_OF_BIRTH	DATE,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   ); 
   
-- ***********************************************
-- Person Benefit Group Table
-- XXMX_BEN_PBG_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PBG_XFM
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	BENEFIT_GROUP_NAME		VARCHAR2(240),
	EFFECTIVE_END_DATE		DATE,
	EFFECTIVE_START_DATE	DATE NOT NULL,
	GUID					VARCHAR2(32),
	LE_BENEFIT_GROUP_ID		NUMBER(18) NOT NULL,
	PERSON_ID				NUMBER(18) NOT NULL,
	SOURCE_SYSTEM_ID		NUMBER(2000),
	SOURCE_SYSTEM_OWNER		VARCHAR2(256),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );

-- ***********************************************
-- Person Benefit Balance Table
-- XXMX_BEN_PBB_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PBB_XFM
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	BENEFIT_BALANCE_NAME	VARCHAR2(240),
	BENEFIT_RELATION_NAME	VARCHAR2(240),
	ASSIGNMENT_NUMBER		VARCHAR2(50),
	LEGAL_EMPLOYER			VARCHAR2(240),
	EFFECTIVE_END_DATE		DATE,
	EFFECTIVE_START_DATE	DATE NOT NULL,
	LEGAL_ENTITY_ID			NUMBER(18),
	PER_BNFTS_BAL_ID		NUMBER(18) NOT NULL,
	PERSON_ID				NUMBER(18) NOT NULL,
	UOM						VARCHAR2(30),
	VAL						NUMBER,
	SOURCE_SYSTEM_ID		NUMBER(2000),
	SOURCE_SYSTEM_OWNER		VARCHAR2(256),
	GUID					VARCHAR2(32),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   ); 

-- ***********************************************
-- Person Habits Table
-- XXMX_BEN_PH_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PH_XFM
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),		
	LEGAL_EMPLOYER				VARCHAR2(240) NOT NULL,
	COORD_MED_PL_NAME			VARCHAR2(240),
	CVRD_IN_ANTHR_PL			VARCHAR2(30) DEFAULT 'NO',
	DISABILITY_STATUS			VARCHAR2(30),
	EFFECTIVE_END_DATE			DATE,	
	EFFECTIVE_START_DATE		DATE NOT NULL,
	GUID						VARCHAR2(32),
	LE_HABITS_COV_ID			NUMBER(18) NOT NULL,
	PERSON_ID					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30),
	REGISTERED_DISABLED_FLAG	VARCHAR2(30) DEFAULT 'NO',
	SOURCE_SYSTEM_ID			NUMBER(2000),
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	STUDENT_STATUS				VARCHAR2(30),
	TOBACCO_TYPE_USAGE			VARCHAR2(30) DEFAULT 'NO',
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );   
   
-- ***********************************************
-- Person Beneficiary Organization Table
-- XXMX_BEN_PBO_XFM
CREATE TABLE XXMX_XFM.XXMX_BEN_PBO_XFM
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),			
	PER_BNF_ORG_ID				NUMBER(22) NOT NULL,
	START_DATE					DATE NOT NULL,
	END_DATE					DATE,
	PERSON_ID					NUMBER(18) NOT NULL,
	BNF_TYP_CD					VARCHAR2(30) DEFAULT 'ORG',
	BNF_ORGANIZATION_ID			NUMBER(22),
	TRUSTEE_ORG_NAME			VARCHAR2(240),
	TRUSTEE_ORG_REG_CD			VARCHAR2(240),
	TRUSTEE_ORG_DESCRIPTION		VARCHAR2(600),
	TRUSTEE_ADDL_DETAILS		VARCHAR2(600),
	TRUSTEE_EXECUTOR_NAME		VARCHAR2(240), 
	ORGANIZATION_NAME			VARCHAR2(240), 
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	GUID						VARCHAR2(32),
	SOURCE_SYSTEM_ID			NUMBER(2000),	
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
	--------------------------
	---SYNONYMS AND GRANTS
	--------------------------

	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PE_XFM FOR XXMX_XFM.XXMX_BEN_PE_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PE_CO_XFM FOR XXMX_XFM.XXMX_BEN_PE_CO_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_DE_XFM FOR XXMX_XFM.XXMX_BEN_DE_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_DE_DD_XFM FOR XXMX_XFM.XXMX_BEN_DE_DD_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_BE_XFM FOR XXMX_XFM.XXMX_BEN_BE_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_BE_DB_XFM FOR XXMX_XFM.XXMX_BEN_BE_DB_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBG_XFM FOR XXMX_XFM.XXMX_BEN_PBG_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBB_XFM FOR XXMX_XFM.XXMX_BEN_PBB_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PH_XFM FOR XXMX_XFM.XXMX_BEN_PH_XFM;
	CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBO_XFM FOR XXMX_XFM.XXMX_BEN_PBO_XFM;
	
  
    GRANT ALL ON XXMX_XFM.XXMX_BEN_PE_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_PE_CO_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_DE_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_DE_DD_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_BE_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_BE_DB_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_PBG_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_PBB_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_PH_XFM TO XXMX_CORE;
	GRANT ALL ON XXMX_XFM.XXMX_BEN_PBO_XFM TO XXMX_CORE;

/