--ALTER SESSION SET CONTAINER = MXDM_PDB1;
--
--
--*****************************************************************************
--**
--**                 Copyright (c) 2020 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  xmxx_ppm_proj_stg_dbi.sql
--**
--** FILEPATH  :  $XXV1_TOP/install/sql
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  APPS
--**
--** AUTHORS   :  Pallavi Kanajar
--**
--** PURPOSE   :  This script installs the package specification for the Patech
--**              common Procedures and Functions package.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    Run the installation script to create all necessary database objects
--**       and Concurrent definitions:
--**
--**            $XXV1_TOP/install/sql/xxv1_mxdm_utilities_1_dbi.sql
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** CALLED INSTALLATION SCRIPTS
--** ---------------------------
--**
--** The following installation scripts are called by this script:
--**
--** File Path                                    File Name
--** -------------------------------------------  ------------------------------
--** N/A                                          N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--** [ 1.0  DD-Mon-YYYY  Change Author       Created.                          ]
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--**   1.0  09-DEC-2020  Pallavi Kanajar    Created from original V1 Solutions
--**                                         Limited version.
--**
--******************************************************************************
--
--
PROMPT
PROMPT
PROMPT *********************************************************************
PROMPT **
PROMPT ** Installing Extract Database Objects for Maximise PPM Data Migration
PROMPT **
PROMPT *********************************************************************
PROMPT
PROMPT
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Dropping Tables
PROMPT ******************
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PLANRBS_HEADER_STG
PROMPT
--
DROP TABLE XXMX_STG.XXMX_PPM_PLANRBS_HEADER_STG;
--
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Creating Tables
PROMPT ******************
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PLANRBS_HEADER_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_PLANRBS_HEADER_STG" 
(	
   "MIGRATION_SET_ID" NUMBER, 
   "MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
   "MIGRATION_STATUS" VARCHAR2(50 BYTE), 
   "RBS_HEADER_NAME" VARCHAR2(240 BYTE), 
   "DESCRIPTION" VARCHAR2(2000 BYTE), 
   "PROJECT_UNIT_NAME" VARCHAR2(240 BYTE), 
   "JOB_SET_NAME" VARCHAR2(80 BYTE), 
   "ALLOW_CHANGE_IN_PROJECT_FLAG" VARCHAR2(1 BYTE), 
   "START_DATE_ACTIVE" DATE, 
   "END_DATE_ACTIVE" DATE, 
   "BATCH_NAME" VARCHAR2(240 BYTE), 
   "BATCH_ID" VARCHAR2(80 BYTE), 
   "LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
   "CREATED_BY" VARCHAR2(64 BYTE), 
   "LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
   "LAST_UPDATE_DATE" TIMESTAMP (6), 
   "CREATION_DATE" TIMESTAMP (6)
);
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_BILLEVENT_STG
PROMPT
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_BILLEVENT_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_BILLEVENT_STG
PROMPT
--
CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_BILLEVENT_STG" 
(	
   "BATCH_ID" VARCHAR2(80), 
   "BATCH_NAME" VARCHAR2(240 ), 
   "MIGRATION_SET_ID" NUMBER, 
   "MIGRATION_SET_NAME" VARCHAR2(100 ), 
   "MIGRATION_STATUS" VARCHAR2(50 ), 
   "INT_REC_ID" NUMBER, 
   "LOAD_REQUEST_ID" NUMBER, 
   "SOURCENAME" VARCHAR2(80 ), 
   "SOURCEREF" VARCHAR2(80 ), 
   "ORGANIZATION_NAME" VARCHAR2(240 ), 
   "CONTRACT_TYPE_NAME" VARCHAR2(150 ), 
   "CONTRACT_NUMBER" VARCHAR2(120 ), 
   "CONTRACT_LINE_NUMBER" VARCHAR2(150 ), 
   "EVENT_TYPE_NAME" VARCHAR2(240 ), 
   "EVENT_DESC" VARCHAR2(240 ), 
   "COMPLETION_DATE" VARCHAR2(240 ), 
   "BILL_TRNS_CURRENCY_CODE" VARCHAR2(15 ), 
   "BILL_TRNS_AMOUNT" NUMBER, 
   "PROJECT_NUMBER" VARCHAR2(25 ), 
   "TASK_NUMBER" VARCHAR2(100 ), 
   "BILL_HOLD_FLAG" VARCHAR2(1 ), 
   "REVENUE_HOLD_FLAG" VARCHAR2(1 ), 
   "ATTRIBUTE_CATEGORY" VARCHAR2(30 ), 
   "ATTRIBUTE1" VARCHAR2(150 ), 
   "ATTRIBUTE2" VARCHAR2(150 ), 
   "ATTRIBUTE3" VARCHAR2(150 ), 
   "ATTRIBUTE4" VARCHAR2(150 ), 
   "ATTRIBUTE5" VARCHAR2(150 ), 
   "ATTRIBUTE6" VARCHAR2(150 ), 
   "ATTRIBUTE7" VARCHAR2(150 ), 
   "ATTRIBUTE8" VARCHAR2(150 ), 
   "ATTRIBUTE9" VARCHAR2(150 ), 
   "ATTRIBUTE10" VARCHAR2(150 ), 
   "ATTRIBUTE_CHAR11" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR12" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR13" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR14" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR15" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR16" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR17" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR18" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR19" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR20" VARCHAR2(240 ), 
   "ATTRIBUTE_CHAR21" CHAR(1000 ), 
   "ATTRIBUTE_CHAR22" CHAR(1000 ), 
   "ATTRIBUTE_CHAR23" CHAR(1000 ), 
   "ATTRIBUTE_CHAR24" CHAR(1000 ), 
   "ATTRIBUTE_CHAR25" CHAR(1000 ), 
   "ATTRIBUTE_CHAR26" CHAR(1000 ), 
   "ATTRIBUTE_CHAR27" CHAR(1000 ), 
   "ATTRIBUTE_CHAR28" CHAR(1000 ), 
   "ATTRIBUTE_CHAR29" CHAR(1000 ), 
   "ATTRIBUTE_CHAR30" CHAR(1000 ), 
   "ATTRIBUTE_NUMBER1" NUMBER, 
   "ATTRIBUTE_NUMBER2" NUMBER, 
   "ATTRIBUTE_NUMBER3" NUMBER, 
   "ATTRIBUTE_NUMBER4" NUMBER, 
   "ATTRIBUTE_NUMBER5" NUMBER, 
   "ATTRIBUTE_NUMBER6" NUMBER, 
   "ATTRIBUTE_NUMBER7" NUMBER, 
   "ATTRIBUTE_NUMBER8" NUMBER, 
   "ATTRIBUTE_NUMBER9" NUMBER, 
   "ATTRIBUTE_NUMBER10" NUMBER, 
   "ATTRIBUTE_DATE1" DATE, 
   "ATTRIBUTE_DATE2" DATE, 
   "ATTRIBUTE_DATE3" DATE, 
   "ATTRIBUTE_DATE4" DATE, 
   "ATTRIBUTE_DATE5" DATE, 
   "ATTRIBUTE_DATE6" DATE, 
   "ATTRIBUTE_DATE7" DATE, 
   "ATTRIBUTE_DATE8" DATE, 
   "ATTRIBUTE_DATE9" DATE, 
   "ATTRIBUTE_DATE10" DATE, 
   "ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
   "ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
   "ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
   "ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
   "ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
   "REVERSE_ACCRUAL_FLAG" VARCHAR2(1 ), 
   "ITEM_EVENT_FLAG" VARCHAR2(1 ), 
   "QUANTITY" NUMBER, 
   "ITEM_NUMBER" VARCHAR2(300 ), 
   "UNIT_OF_MEASURE" VARCHAR2(25 ), 
   "UNIT_PRICE" NUMBER, 
   "LOAD_STATUS" VARCHAR2(10 ), 
   "CREATION_DATE" TIMESTAMP (6), 
   "LAST_UPDATE_DATE" TIMESTAMP (6), 
   "CREATED_BY" VARCHAR2(64 ), 
   "LAST_UPDATED_BY" VARCHAR2(64 ), 
   "LAST_UPDATE_LOGIN" VARCHAR2(32 )
) ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_CLASS_STG
PROMPT
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_CLASS_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_CLASS_STG
PROMPT
--


CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_CLASS_STG" 
(
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"CLASS_CATEGORY" VARCHAR2(240 ), 
	"CLASS_CODE" VARCHAR2(240 ), 
	"CODE_PERCENTAGE" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 )
)  ;
--
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_LBRCOST_STG
PROMPT
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_LBRCOST_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_LBRCOST_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_LBRCOST_STG" 
(	
   "MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 ), 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"TRANSACTION_TYPE" VARCHAR2(20 ) DEFAULT 'LABOR', 
	"BUSINESS_UNIT" VARCHAR2(240 ), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240 ), 
	"TRANSACTION_SOURCE_ID" VARCHAR2(200 ), 
	"DOCUMENT_NAME" VARCHAR2(240 ), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240 ), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 ), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(250 ), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30 ), 
	"PERSON_NAME" VARCHAR2(2000 ), 
	"PERSON_ID" NUMBER, 
	"HCM_ASSIGNMENT_NAME" VARCHAR2(80 ), 
	"HCM_ASSIGNMENT_ID" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240 ), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"ORGANIZATION_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(80 ), 
	"UNIT_OF_MEASURE" VARCHAR2(30 ), 
	"WORK_TYPE" VARCHAR2(240 ), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"ACCRUAL_FLAG" VARCHAR2(1 ), 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(120 ), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 ), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(120 ), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 ), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(50 ), 
	"DENOM_CURRENCY" VARCHAR2(80 ), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 ), 
	"ACCT_CURRENCY" VARCHAR2(80 ), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30 ), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(4 ), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1 ), 
	"CONTEXT_CATEGORY" VARCHAR2(40 ), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(150 ), 
	"FUNDING_SOURCE_ID" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ), 
	"CONTRACT_NUMBER" VARCHAR2(120 ), 
	"CONTRACT_NAME" VARCHAR2(240 ), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240 ), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240 )
)  ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_MISCCOST_STG
PROMPT
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_MISCCOST_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_MISCCOST_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_MISCCOST_STG" 
(	
   "MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"TRANSACTION_TYPE" VARCHAR2(20 ), 
	"BUSINESS_UNIT" VARCHAR2(240 ), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240 ), 
	"TRANSACTION_SOURCE_ID" VARCHAR2(200 ), 
	"DOCUMENT_NAME" VARCHAR2(240 ), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240 ), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 ), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(250 ), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30 ), 
	"PERSON_NAME" VARCHAR2(2000 ), 
	"PERSON_ID" NUMBER, 
	"HCM_ASSIGNMENT_NAME" VARCHAR2(80 ), 
	"HCM_ASSIGNMENT_ID" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240 ), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"ORGANIZATION_ID" NUMBER,  
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(80 ), 
	"UNIT_OF_MEASURE" VARCHAR2(30 ), 
	"WORK_TYPE" VARCHAR2(240 ), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"ACCRUAL_FLAG" VARCHAR2(1 ), 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(120 ), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 ), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(120 ), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 ), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(50 ), 
	"DENOM_CURRENCY" VARCHAR2(80 ), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 ), 
	"ACCT_CURRENCY" VARCHAR2(80 ), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30 ), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(4 ), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1 ), 
	"CONTEXT_CATEGORY" VARCHAR2(40 ), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(150 ), 
	"FUNDING_SOURCE_ID" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ),
   "CONTRACT_NUMBER" VARCHAR2(120 ), 
	"CONTRACT_NAME" VARCHAR2(240 ), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240 ), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240 )
)  ;

--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_NONLABCOST_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_NONLABCOST_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_NONLABCOST_STG
PROMPT
--


CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_NONLABCOST_STG" 
(	
   "FILE_SET_ID" VARCHAR2(30 ), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"TRANSACTION_TYPE" VARCHAR2(30 ), 
	"BUSINESS_UNIT" VARCHAR2(240 ), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240 ), 
	"TRANSACTION_SOURCE_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(240 ), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240 ), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(250 ), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30 ), 
	"PERSON_NAME" VARCHAR2(2000 ), 
	"PERSON_ID" NUMBER, 
	"HCM_ASSIGNMENT_NAME" VARCHAR2(80 ), 
	"HCM_ASSIGNMENT_ID" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240 ), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"ORGANIZATION_ID" NUMBER, 
	"NON_LABOR_RESOURCE" VARCHAR2(240 ), 
	"NON_LABOR_RESOURCE_ID" NUMBER, 
	"NON_LABOR_RESOURCE_ORG" VARCHAR2(240 ), 
	"NON_LABOR_RESOURCE_ORG_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(80 ), 
	"UNIT_OF_MEASURE" VARCHAR2(30 ), 
	"WORK_TYPE" VARCHAR2(240 ), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(120 ), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 ), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(120 ), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 ), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(15 ), 
	"DENOM_CURRENCY" VARCHAR2(80 ), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 ), 
	"ACCT_CURRENCY" VARCHAR2(80 ), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30 ), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(4 ), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1 ), 
	"CONTEXT_CATEGORY" VARCHAR2(40 ), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(64 ), 
	"CREATED_BY" VARCHAR2(64 ), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"FUNDING_SOURCE_ID" VARCHAR2(150 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ),
   "CONTRACT_NUMBER" VARCHAR2(120 ), 
	"CONTRACT_NAME" VARCHAR2(300 ), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240 ), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240 ) 
) ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_SUPCOST_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_SUPCOST_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_SUPCOST_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_SUPCOST_STG" 
(	
   "MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 ), 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"TRANSACTION_TYPE" VARCHAR2(20 ), 
	"BUSINESS_UNIT" VARCHAR2(240 ), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240 ), 
	"TRANSACTION_SOURCE_ID" VARCHAR2(200 ), 
	"DOCUMENT_NAME" VARCHAR2(240 ), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240 ), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 ), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(250 ), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240 ), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"ORGANIZATION_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(80 ), 
	"UNIT_OF_MEASURE" VARCHAR2(30 ), 
	"WORK_TYPE" VARCHAR2(240 ), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"ACCRUAL_FLAG" VARCHAR2(1 ), 
	"SUPPLIER_NUMBER" VARCHAR2(30 ), 
	"SUPPLIER_NAME" VARCHAR2(360 ), 
	"VENDOR_ID" NUMBER, 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(120 ), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1 ), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(120 ), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 ), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(50 ), 
	"DENOM_CURRENCY" VARCHAR2(80 ), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000 ), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000 ), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 ), 
	"ACCT_CURRENCY" VARCHAR2(80 ), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30 ), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(4 ), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1 ), 
	"CONTEXT_CATEGORY" VARCHAR2(40 ), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(150 ), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(150 ), 
	"FUNDING_SOURCE_ID" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(150 ), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ), 
	"CONTRACT_NUMBER" VARCHAR2(120 ), 
	"CONTRACT_NAME" VARCHAR2(240 ), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240 ), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240 )
) ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_TASKS_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_TASKS_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_TASKS_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_TASKS_STG" 
(	
   "MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"OPERATING_UNIT" VARCHAR2(240 ), 
	"LEDGER_NAME" VARCHAR2(30 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"PROJECT_NUMBER" VARCHAR2(100 ), 
	"SOURCE_TASK_REFERENCE" VARCHAR2(25 ), 
	"FINANCIAL_TASK" VARCHAR2(1 ), 
	"TASK_DESCRIPTION" VARCHAR2(2000 ), 
	"PARENT_TASK_NUMBER" VARCHAR2(100 ), 
	"PLANNING_START_DATE" DATE, 
	"PLANNING_END_DATE" DATE, 
	"PLANNED_EFFORT" NUMBER, 
	"PLANNED_DURATION" NUMBER, 
	"MILESTONE_FLAG" VARCHAR2(1 ), 
	"CRITICAL_FLAG" VARCHAR2(1 ), 
	"CHARGEABLE_FLAG" VARCHAR2(1 ), 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"LIMIT_TO_TXN_CONTROLS_FLAG" VARCHAR2(1 ), 
	"SERVICE_TYPE_CODE" VARCHAR2(30 ), 
	"WORK_TYPE_ID" NUMBER(18,0), 
	"MANAGER_PERSON_ID" VARCHAR2(30 ), 
	"ALLOW_CROSS_CHARGE_FLAG" VARCHAR2(1 ), 
	"CC_PROCESS_LABOR_FLAG" VARCHAR2(1 ), 
	"CC_PROCESS_NL_FLAG" VARCHAR2(1 ), 
	"RECEIVE_PROJECT_INVOICE_FLAG" VARCHAR2(1 ), 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"REQMNT_CODE" VARCHAR2(30 ), 
	"SPRINT" VARCHAR2(30 ), 
	"PRIORITY" NUMBER(18,0), 
	"SCHEDULE_MODE" VARCHAR2(240 ), 
	"BASELINE_START_DATE" DATE, 
	"BASELINE_FINISH_DATE" DATE, 
	"BASELINE_EFFORT" NUMBER, 
	"BASELINE_DURATION" NUMBER, 
	"BASELINE_ALLOCATION" NUMBER, 
	"BASELINE_LABOR_COST_AMOUNT" NUMBER, 
	"BASELINE_LABOR_BILLED_AMOUNT" NUMBER, 
	"BASELINE_EXPENSE_COST_AMOUNT" NUMBER, 
	"CONSTRAINT_TYPE_CODE" VARCHAR2(240 ), 
	"CONSTRAINT_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE11" VARCHAR2(150 ), 
	"ATTRIBUTE12" VARCHAR2(150 ), 
	"ATTRIBUTE13" VARCHAR2(150 ), 
	"ATTRIBUTE14" VARCHAR2(150 ), 
	"ATTRIBUTE15" VARCHAR2(150 ), 
	"ATTRIBUTE16" VARCHAR2(150 ), 
	"ATTRIBUTE17" VARCHAR2(150 ), 
	"ATTRIBUTE18" VARCHAR2(150 ), 
	"ATTRIBUTE19" VARCHAR2(150 ), 
	"ATTRIBUTE20" VARCHAR2(150 ), 
	"ATTRIBUTE21" VARCHAR2(150 ), 
	"ATTRIBUTE22" VARCHAR2(150 ), 
	"ATTRIBUTE23" VARCHAR2(150 ), 
	"ATTRIBUTE24" VARCHAR2(150 ), 
	"ATTRIBUTE25" VARCHAR2(150 ), 
	"ATTRIBUTE26" VARCHAR2(150 ), 
	"ATTRIBUTE27" VARCHAR2(150 ), 
	"ATTRIBUTE28" VARCHAR2(150 ), 
	"ATTRIBUTE29" VARCHAR2(150 ), 
	"ATTRIBUTE30" VARCHAR2(150 ), 
	"ATTRIBUTE31" VARCHAR2(150 ), 
	"ATTRIBUTE32" VARCHAR2(150 ), 
	"ATTRIBUTE33" VARCHAR2(150 ), 
	"ATTRIBUTE34" VARCHAR2(150 ), 
	"ATTRIBUTE35" VARCHAR2(150 ), 
	"ATTRIBUTE36" VARCHAR2(150 ), 
	"ATTRIBUTE37" VARCHAR2(150 ), 
	"ATTRIBUTE38" VARCHAR2(150 ), 
	"ATTRIBUTE39" VARCHAR2(150 ), 
	"ATTRIBUTE40" VARCHAR2(150 ), 
	"ATTRIBUTE41" VARCHAR2(150 ), 
	"ATTRIBUTE42" VARCHAR2(150 ), 
	"ATTRIBUTE43" VARCHAR2(150 ), 
	"ATTRIBUTE44" VARCHAR2(150 ), 
	"ATTRIBUTE45" VARCHAR2(150 ), 
	"ATTRIBUTE46" VARCHAR2(150 ), 
	"ATTRIBUTE47" VARCHAR2(150 ), 
	"ATTRIBUTE48" VARCHAR2(150 ), 
	"ATTRIBUTE49" VARCHAR2(150 ), 
	"ATTRIBUTE50" VARCHAR2(150 ), 
	"ATTRIBUTE1_NUMBER" NUMBER, 
	"ATTRIBUTE2_NUMBER" NUMBER, 
	"ATTRIBUTE3_NUMBER" NUMBER, 
	"ATTRIBUTE4_NUMBER" NUMBER, 
	"ATTRIBUTE5_NUMBER" NUMBER, 
	"ATTRIBUTE6_NUMBER" NUMBER, 
	"ATTRIBUTE7_NUMBER" NUMBER, 
	"ATTRIBUTE8_NUMBER" NUMBER, 
	"ATTRIBUTE9_NUMBER" NUMBER, 
	"ATTRIBUTE10_NUMBER" NUMBER, 
	"ATTRIBUTE11_NUMBER" NUMBER, 
	"ATTRIBUTE12_NUMBER" NUMBER, 
	"ATTRIBUTE13_NUMBER" NUMBER, 
	"ATTRIBUTE14_NUMBER" NUMBER, 
	"ATTRIBUTE15_NUMBER" NUMBER, 
	"ATTRIBUTE1_DATE" DATE, 
	"ATTRIBUTE2_DATE" DATE, 
	"ATTRIBUTE3_DATE" DATE, 
	"ATTRIBUTE4_DATE" DATE, 
	"ATTRIBUTE5_DATE" DATE, 
	"ATTRIBUTE6_DATE" DATE, 
	"ATTRIBUTE7_DATE" DATE, 
	"ATTRIBUTE8_DATE" DATE, 
	"ATTRIBUTE9_DATE" DATE, 
	"ATTRIBUTE10_DATE" DATE, 
	"ATTRIBUTE11_DATE" DATE, 
	"ATTRIBUTE12_DATE" DATE, 
	"ATTRIBUTE13_DATE" DATE, 
	"ATTRIBUTE14_DATE" DATE, 
	"ATTRIBUTE15_DATE" DATE, 
	"LOAD_STATUS" VARCHAR2(10 ), 
	"IMPORT_STATUS" VARCHAR2(10 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"LAST_UPDATE_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"SOURCE_APPLICATION_CODE" VARCHAR2(30 )
) ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_TEAM_MEM_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_TEAM_MEM_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_TEAM_MEM_STG
PROMPT
--


CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_TEAM_MEM_STG" 
(
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"TEAM_MEMBER_NUMBER" VARCHAR2(30 ), 
	"TEAM_MEMBER_NAME" VARCHAR2(240 ), 
	"TEAM_MEMBER_EMAIL" VARCHAR2(240 ), 
	"PROJECT_ROLE" VARCHAR2(240 ), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"ALLOCATION" NUMBER, 
	"LABOUR_EFFORT" NUMBER, 
	"COST_RATE" NUMBER, 
	"BILL_RATE" NUMBER, 
	"TRACK_TIME_FLAG" VARCHAR2(1 ), 
	"ASSIGNMENT_TYPE_CODE" VARCHAR2(30 ), 
	"BILLABLE_PERCENT" NUMBER, 
	"BILLABLE_PERCENT_REASON_CODE" VARCHAR2(30 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6), 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"ORGANIZATION_NAME" VARCHAR2(240 )
) ;
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PRJ_TRX_CONTROL_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PRJ_TRX_CONTROL_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PRJ_TRX_CONTROL_STG
PROMPT
--


CREATE TABLE "XXMX_STG"."XXMX_PPM_PRJ_TRX_CONTROL_STG" 
(
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ), 
	"TXN_CTRL_REFERENCE" VARCHAR2(240 ), 
	"PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"TASK_NUMBER" VARCHAR2(100 ), 
	"TASK_NAME" VARCHAR2(255 ), 
	"EXPENDITURE_CATEGORY_NAME" VARCHAR2(240 ), 
	"EXPENDITURE_TYPE" VARCHAR2(240 ), 
	"NON_LABOR_RESOURCE" VARCHAR2(240 ), 
	"PERSON_NUMBER" VARCHAR2(30 ), 
	"PERSON_NAME" VARCHAR2(2000 ), 
	"PERSON_EMAIL" VARCHAR2(360 ), 
	"PERSON_TYPE" VARCHAR2(20 ), 
	"JOB_NAME" VARCHAR2(240 ), 
	"ORGANIZATION_NAME" VARCHAR2(240 ), 
	"CHARGEABLE_FLAG" VARCHAR2(1 ), 
	"BILLABLE_FLAG" VARCHAR2(1 ), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 ), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20 ), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(20 )
);

--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_PROJECTS_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_PROJECTS_STG;
--
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_PROJECTS_STG
PROMPT
--
--

  CREATE TABLE "XXMX_STG"."XXMX_PPM_PROJECTS_STG" 
   (	
   "MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"XFACE_REC_ID" NUMBER(18,0), 
   "PROJECT_NAME" VARCHAR2(240 ), 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
   "SOURCE_TEMPLATE_NUMBER" VARCHAR2(25 ),
   "SOURCE_TEMPLATE_NAME" VARCHAR2(240 ), 
   "SOURCE_APPLICATION_CODE" VARCHAR2(30 ),
   "SOURCE_PROJECT_REFERENCE" VARCHAR2(25 ),    
   "SCHEDULE_NAME" VARCHAR2(200 ), 
   "EPS_NAME" VARCHAR2(200 ), 
   "PROJECT_PLAN_VIEW_ACCESS" VARCHAR2(30 ), 
   "SCHEDULE_TYPE" VARCHAR2(30 ),
   "ORGANIZATION_NAME" VARCHAR2(240 ), 
   "LEGAL_ENTITY_NAME" VARCHAR2(240 ), 
   "DESCRIPTION" VARCHAR2(2000 ), 
   "PROJECT_MANAGER_NUMBER" VARCHAR2(30 ), 
   "PROJECT_MANAGER_NAME" VARCHAR2(360 ), 
   "PROJECT_MANAGER_EMAIL" VARCHAR2(360 ), 
   "PROJECT_START_DATE" DATE, 
	"PROJECT_FINISH_DATE" DATE, 
   "CLOSED_DATE" DATE, 
   "PRJ_PLAN_BASELINE_NAME" VARCHAR2(100 ), 
	"PRJ_PLAN_BASELINE_DESC" VARCHAR2(1000 ), 
	"PRJ_PLAN_BASELINE_DATE" DATE,
   "PROJECT_STATUS_NAME" VARCHAR2(80 ), 
	"PROJECT_PRIORITY_CODE" VARCHAR2(30 ),
   "OUTLINE_DISPLAY_LEVEL" NUMBER(18,0),  
	"PLANNING_PROJECT_FLAG" VARCHAR2(1 ), 
   "SERVICE_TYPE_CODE" VARCHAR2(30 ), 
   "WORK_TYPE_NAME" VARCHAR2(240 ),
   "LIMIT_TO_TXN_CONTROLS_CODE" VARCHAR2(30 ),
   "BUDGETARY_CONTROL_FLAG" VARCHAR2(1 ), 
   "PROJECT_CURRENCY_CODE" VARCHAR2(15 ),    
   "CURRENCY_CONV_RATE_TYPE" VARCHAR2(15 ), 
   "CURRENCY_CONV_DATE_TYPE_CODE" VARCHAR2(30 ), 
   "CURRENCY_CONV_DATE" DATE, 
   "CINT_ELIGIBLE_FLAG" VARCHAR2(1 ), 
   "CINT_RATE_SCH_NAME" VARCHAR2(30 ), 
   "CINT_STOP_DATE" DATE, 
   "ASSET_ALLOCATION_METHOD_CODE" VARCHAR2(30 ),
	"CAPITAL_EVENT_PROCESSING_CODE" VARCHAR2(30 ), 
	"ALLOW_CROSS_CHARGE_FLAG" VARCHAR2(1 ), 
	"CC_PROCESS_LABOR_FLAG" VARCHAR2(1 ),
   "LABOR_TP_SCHEDULE_NAME" VARCHAR2(50 ),    
   "LABOR_TP_FIXED_DATE" DATE,
   "CC_PROCESS_NL_FLAG" VARCHAR2(1 ),
   "NL_TP_SCHEDULE_NAME" VARCHAR2(50 ), 
   "NL_TP_FIXED_DATE" DATE, 
   "BURDEN_SCHEDULE_NAME" VARCHAR2(30 ), 
   "BURDEN_SCH_FIXED_DATED" DATE,    
   "KPI_NOTIFICATION_ENABLED" VARCHAR2(5 ), 
	"KPI_NOTIFICATION_RECIPIENTS" VARCHAR2(30 ), 
   "KPI_NOTIFICATION_INCLUDE_NOTES" VARCHAR2(5 ),
   "COPY_TEAM_MEMBERS_FLAG" VARCHAR2(1 ), 
   "COPY_CLASSIFICATIONS_FLAG" VARCHAR2(1),
   "COPY_ATTACHMENTS_FLAG" VARCHAR2(1 ), 
	"COPY_DFF_FLAG" VARCHAR2(1 ), 
   "COPY_TASKS_FLAG" VARCHAR2(1 ), 
	"COPY_TASK_ATTACHMENTS_FLAG" VARCHAR2(1 ), 
	"COPY_TASK_DFF_FLAG" VARCHAR2(1 ), 
	"COPY_TASK_ASSIGNMENTS_FLAG" VARCHAR2(1 ), 
	"COPY_TRANSACTION_CONTROLS_FLAG" VARCHAR2(1 ), 
   "COPY_ASSETS_FLAG" VARCHAR2(1 ), 
	"COPY_ASSET_ASSIGNMENTS_FLAG" VARCHAR2(1 ), 
	"COPY_COST_OVERRIDES_FLAG" VARCHAR2(1 ), 
   "OPPORTUNITY_ID" NUMBER(18,0), 
   "OPPORTUNITY_NUMBER" VARCHAR2(240 ), 
	"OPPORTUNITY_CUSTOMER_NUMBER" VARCHAR2(240 ), 
	"OPPORTUNITY_CUSTOMER_ID" NUMBER(18,0),
   "OPPORTUNITY_AMT" NUMBER, 
   "OPPORTUNITY_CURRCODE" VARCHAR2(15 ),
   "OPPORTUNITY_WIN_CONF_PERCENT" NUMBER, 
   "OPPORTUNITY_NAME" VARCHAR2(240 ), 
	"OPPORTUNITY_DESC" VARCHAR2(1000 ), 
	"OPPORTUNITY_CUSTOMER_NAME" VARCHAR2(900 ), 
	"OPPORTUNITY_STATUS" VARCHAR2(240 ), 
   "ATTRIBUTE_CATEGORY" VARCHAR2(30 ), 
	"ATTRIBUTE1" VARCHAR2(150 ), 
	"ATTRIBUTE2" VARCHAR2(150 ), 
	"ATTRIBUTE3" VARCHAR2(150 ), 
	"ATTRIBUTE4" VARCHAR2(150 ), 
	"ATTRIBUTE5" VARCHAR2(150 ), 
	"ATTRIBUTE6" VARCHAR2(150 ), 
	"ATTRIBUTE7" VARCHAR2(150 ), 
	"ATTRIBUTE8" VARCHAR2(150 ), 
	"ATTRIBUTE9" VARCHAR2(150 ), 
	"ATTRIBUTE10" VARCHAR2(150 ), 
	"ATTRIBUTE11" VARCHAR2(150 ), 
	"ATTRIBUTE12" VARCHAR2(150 ), 
	"ATTRIBUTE13" VARCHAR2(150 ), 
	"ATTRIBUTE14" VARCHAR2(150 ), 
	"ATTRIBUTE15" VARCHAR2(150 ), 
	"ATTRIBUTE16" VARCHAR2(150 ), 
	"ATTRIBUTE17" VARCHAR2(150 ), 
	"ATTRIBUTE18" VARCHAR2(150 ), 
	"ATTRIBUTE19" VARCHAR2(150 ), 
	"ATTRIBUTE20" VARCHAR2(150 ), 
	"ATTRIBUTE21" VARCHAR2(150 ), 
	"ATTRIBUTE22" VARCHAR2(150 ), 
	"ATTRIBUTE23" VARCHAR2(150 ), 
	"ATTRIBUTE24" VARCHAR2(150 ), 
	"ATTRIBUTE25" VARCHAR2(150 ), 
	"ATTRIBUTE26" VARCHAR2(150 ), 
	"ATTRIBUTE27" VARCHAR2(150 ), 
	"ATTRIBUTE28" VARCHAR2(150 ), 
	"ATTRIBUTE29" VARCHAR2(150 ), 
	"ATTRIBUTE30" VARCHAR2(150 ), 
	"ATTRIBUTE31" VARCHAR2(150 ), 
	"ATTRIBUTE32" VARCHAR2(150 ), 
	"ATTRIBUTE33" VARCHAR2(150 ), 
	"ATTRIBUTE34" VARCHAR2(150 ), 
	"ATTRIBUTE35" VARCHAR2(150 ), 
	"ATTRIBUTE36" VARCHAR2(150 ), 
	"ATTRIBUTE37" VARCHAR2(150 ), 
	"ATTRIBUTE38" VARCHAR2(150 ), 
	"ATTRIBUTE39" VARCHAR2(150 ), 
	"ATTRIBUTE40" VARCHAR2(150 ), 
	"ATTRIBUTE41" VARCHAR2(150 ), 
	"ATTRIBUTE42" VARCHAR2(150 ), 
	"ATTRIBUTE43" VARCHAR2(150 ), 
	"ATTRIBUTE44" VARCHAR2(150 ), 
	"ATTRIBUTE45" VARCHAR2(150 ), 
	"ATTRIBUTE46" VARCHAR2(150 ), 
	"ATTRIBUTE47" VARCHAR2(150 ), 
	"ATTRIBUTE48" VARCHAR2(150 ), 
	"ATTRIBUTE49" VARCHAR2(150 ), 
	"ATTRIBUTE50" VARCHAR2(150 ), 
	"ATTRIBUTE1_NUMBER" NUMBER, 
	"ATTRIBUTE2_NUMBER" NUMBER, 
	"ATTRIBUTE3_NUMBER" NUMBER, 
	"ATTRIBUTE4_NUMBER" NUMBER, 
	"ATTRIBUTE5_NUMBER" NUMBER, 
	"ATTRIBUTE6_NUMBER" NUMBER, 
	"ATTRIBUTE7_NUMBER" NUMBER, 
	"ATTRIBUTE8_NUMBER" NUMBER, 
	"ATTRIBUTE9_NUMBER" NUMBER, 
	"ATTRIBUTE10_NUMBER" NUMBER, 
	"ATTRIBUTE11_NUMBER" NUMBER, 
	"ATTRIBUTE12_NUMBER" NUMBER, 
	"ATTRIBUTE13_NUMBER" NUMBER, 
	"ATTRIBUTE14_NUMBER" NUMBER, 
	"ATTRIBUTE15_NUMBER" NUMBER, 
	"ATTRIBUTE1_DATE" DATE, 
	"ATTRIBUTE2_DATE" DATE, 
	"ATTRIBUTE3_DATE" DATE, 
	"ATTRIBUTE4_DATE" DATE, 
	"ATTRIBUTE5_DATE" DATE, 
	"ATTRIBUTE6_DATE" DATE, 
	"ATTRIBUTE7_DATE" DATE, 
	"ATTRIBUTE8_DATE" DATE, 
	"ATTRIBUTE9_DATE" DATE, 
	"ATTRIBUTE10_DATE" DATE, 
	"ATTRIBUTE11_DATE" DATE, 
	"ATTRIBUTE12_DATE" DATE, 
	"ATTRIBUTE13_DATE" DATE, 
	"ATTRIBUTE14_DATE" DATE, 
	"ATTRIBUTE15_DATE" DATE, 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"LOAD_REQUEST_ID" NUMBER(18,0), 
	"REQUEST_ID" NUMBER(18,0), 
	"ORG_ID" NUMBER(18,0), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6), 
	"COPY_PROJECT_CLASSES_FLAG" VARCHAR2(1 ), 
	"COPY_GROUP_SPACE_FLAG" VARCHAR2(1 ), 
	"LOAD_STATUS" VARCHAR2(10 ), 
	"IMPORT_STATUS" VARCHAR2(10 ), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 ), 
	"PROJECT_ID" VARCHAR2(30 ), 
	"PROJ_OWNING_ORG" VARCHAR2(240 ), 
	"BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 )
   )  ;
--
--
--
PROMPT
PROMPT Dropping Table XXMX_PPM_RESOURCES_STG
PROMPT
--
--
DROP TABLE XXMX_STG.XXMX_PPM_RESOURCES_STG;
--
--
PROMPT
PROMPT Creating Table XXMX_PPM_RESOURCES_STG
PROMPT
--

CREATE TABLE "XXMX_STG"."XXMX_PPM_RESOURCES_STG" 
(	
   "BATCH_ID" VARCHAR2(80 ), 
	"BATCH_NAME" VARCHAR2(240 ), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 ), 
	"MIGRATION_STATUS" VARCHAR2(50 ), 
	"RBS_HEADER_NAME" VARCHAR2(240 ), 
	"RES_FORMAT_NAME" VARCHAR2(240 ), 
	"ALIAS" VARCHAR2(240 ), 
	"LEVE1_RES_NAME" VARCHAR2(300 ), 
	"LEVE2_RES_NAME" VARCHAR2(300 ), 
	"LEVE3_RES_NAME" VARCHAR2(300 ), 
	"RESOURCE_CLASS_NAME" VARCHAR2(240 ), 
	"SPREAD_CURVE_NAME" VARCHAR2(240 ), 
	"PROJECT_NUMBER" VARCHAR2(25 ), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 ), 
	"CREATED_BY" VARCHAR2(64 ), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 )
)  ;

--
PROMPT ***********************
PROMPT **Provide Grants
PROMPT ***********************
--

GRANT ALL ON  XXMX_STG.XXMX_PPM_PROJECTS_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_TASKS_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_TRX_CONTROL_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_LBRCOST_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_SUPCOST_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_MISCCOST_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_NONLABCOST_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_BILLEVENT_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_RESOURCES_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PLANRBS_HEADER_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_TEAM_MEM_STG TO xxmx_core;
GRANT ALL ON  XXMX_STG.XXMX_PPM_PRJ_CLASS_STG TO xxmx_core;
--
--
PROMPT ***********************
PROMPT **Synonym Creations
PROMPT *********************** 
--

Create or replace synonym xxmx_CORE.XXMX_PPM_PROJECTS_STG FOR XXMX_STG.XXMX_PPM_PROJECTS_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_TASKS_STG FOR XXMX_STG.XXMX_PPM_PRJ_TASKS_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_TRX_CONTROL_STG FOR XXMX_STG.XXMX_PPM_PRJ_TRX_CONTROL_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_LBRCOST_STG FOR XXMX_STG.XXMX_PPM_PRJ_LBRCOST_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_SUPCOST_STG FOR XXMX_STG.XXMX_PPM_PRJ_SUPCOST_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_MISCCOST_STG FOR XXMX_STG.XXMX_PPM_PRJ_MISCCOST_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_NONLABCOST_STG FOR XXMX_STG.XXMX_PPM_PRJ_NONLABCOST_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_BILLEVENT_STG FOR XXMX_STG.XXMX_PPM_PRJ_BILLEVENT_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_RESOURCES_STG FOR XXMX_STG.XXMX_PPM_RESOURCES_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PLANRBS_HEADER_STG FOR XXMX_STG.XXMX_PPM_PLANRBS_HEADER_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_TEAM_MEM_STG FOR XXMX_STG.XXMX_PPM_PRJ_TEAM_MEM_STG;
Create or replace synonym xxmx_CORE.XXMX_PPM_PRJ_CLASS_STG FOR XXMX_STG.XXMX_PPM_PRJ_CLASS_STG;

--
--
PROMPT
PROMPT
PROMPT **********************************
PROMPT **                                
PROMPT ** End of Database Object Creation
PROMPT **                                
PROMPT **********************************
PROMPT
PROMPT
--
--
