--
--
--*****************************************************************************
--**
--**                 Copyright (c) 2021 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  xxmx_fa_massadd_xfm_dbi.sql
--**
--** FILEPATH  :  ????
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  APPS
--**
--** AUTHORS   :  Ian S. Vickerstaff
--**
--** PURPOSE   :  This script installs the XXMX_XFM DB Objects for the Maximise
--**              Fixed Assets Data Migration.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    None
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--** [ 1.0  DD-Mon-YYYY  Change Author       Created.                          ]
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--**   1.0  08-JAN-2021  Ian S. Vickerstaff  Created for Maximise.
--**
--**   1.1  20-JAN-2021  Ian S. Vickerstaff  Grants added.
--**
--**   1.2  14-JUL-2021  Ian S. Vickerstaff  Header comment updates.
--**
--******************************************************************************
--
--
PROMPT
PROMPT
PROMPT *************************************************************
PROMPT **
PROMPT ** Installing Database Objects for Maximise FA Data Migration
PROMPT **
PROMPT *************************************************************
PROMPT
PROMPT
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Dropping Tables
PROMPT ******************
--
--
PROMPT
PROMPT Dropping Table xxmx_fa_mass_additions_xfm
PROMPT
--
DROP TABLE xxmx_fa_mass_additions_xfm;
--
PROMPT
PROMPT Dropping Table xxmx_fa_mass_addition_dist_xfm
PROMPT
--
DROP TABLE xxmx_fa_mass_addition_dist_xfm;
--
--
PROMPT
PROMPT Dropping Table xxmx_fa_mass_rates_xfm
PROMPT
--
DROP TABLE xxmx_fa_mass_rates_xfm;
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Creating Tables
PROMPT ******************
--
--
PROMPT
PROMPT Creating Table xxmx_fa_mass_additions_xfm
PROMPT
--
/*
** CREATE TABLE: xxmx_fa_mass_additions_xfm
*/
--Migration_set_id is generated in the maximise Code
--File_set_id is mandatory for Data File (non-Ebs Source)
--
CREATE TABLE xxmx_xfm.xxmx_fa_mass_additions_xfm 
   (	
   MIGRATION_SET_ID NUMBER, 
   FILE_SET_ID   VARCHAR2(20),
	MIGRATION_SET_NAME VARCHAR2(100), 
	MIGRATION_STATUS VARCHAR2(50), 
	OPERATING_UNIT VARCHAR2(240), 
	LEDGER_NAME VARCHAR2(30), 
	MASS_ADDITION_ID NUMBER(18,0), 
	ASSET_CATEGORY_ID NUMBER(18,0), 
	PREPARER_ID NUMBER(18,0), 
	PAYABLES_CODE_COMBINATION_ID NUMBER(18,0), 
	CREATE_BATCH_ID NUMBER(18,0), 
	CASH_GENERATING_UNIT_ID NUMBER(18,0), 
	PO_VENDOR_ID NUMBER(18,0), 
	INVOICE_ID NUMBER(18,0), 
	PARENT_MASS_ADDITION_ID NUMBER(18,0), 
	PARENT_ASSET_ID NUMBER(18,0), 
	AP_DISTRIBUTION_LINE_NUMBER NUMBER(18,0), 
	POST_BATCH_ID NUMBER(18,0), 
	ADD_TO_ASSET_ID NUMBER(18,0), 
	ASSET_KEY_CCID NUMBER(18,0), 
	LOAD_REQUEST_ID NUMBER(18,0), 
	MERGE_PARENT_MASS_ADDITIONS_ID NUMBER(18,0), 
	SPLIT_PARENT_MASS_ADDITIONS_ID NUMBER(18,0), 
	PROJECT_ASSET_LINE_ID NUMBER(18,0), 
	PROJECT_ID NUMBER(18,0), 
	TASK_ID NUMBER(18,0), 
	UNITS_TO_ADJUST NUMBER(18,0), 
	ASSET_ID NUMBER(18,0), 
	INVOICE_DISTRIBUTION_ID NUMBER(18,0), 
	PO_DISTRIBUTION_ID NUMBER(18,0), 
	REQUEST_ID NUMBER(18,0), 
	WORKER_ID NUMBER(18,0), 
	PROCESS_ORDER NUMBER(18,0), 
	INVOICE_PAYMENT_ID NUMBER(18,0), 
	OBJECT_VERSION_NUMBER NUMBER(9,0), 
	METHOD_ID NUMBER(18,0), 
	FLAT_RATE_ID NUMBER(18,0), 
	CONVENTION_TYPE_ID NUMBER(18,0), 
	BONUS_RULE_ID NUMBER(18,0), 
	CEILING_TYPE_ID NUMBER(18,0), 
	PRIOR_METHOD_ID NUMBER(18,0), 
	PRIOR_FLAT_RATE_ID NUMBER(18,0), 
	WARRANTY_ID NUMBER(18,0), 
	ITC_AMOUNT_ID NUMBER(18,0), 
	LEASE_ID NUMBER(18,0), 
	LESSOR_ID NUMBER(18,0), 
	LIFE_IN_MONTHS NUMBER(4,0), 
	PERIOD_COUNTER_FULLY_RESERVED NUMBER(18,0), 
	PERIOD_COUNTER_EXTENDED NUMBER(18,0), 
	PRIOR_LIFE_IN_MONTHS NUMBER(18,0), 
	PROJECT_ORGANIZATION_ID NUMBER(18,0), 
	TASK_ORGANIZATION_ID NUMBER(18,0), 
	EXPENDITURE_ORGANIZATION_ID NUMBER(18,0), 
	PROJECT_TXN_DOC_ENTRY_ID NUMBER(18,0), 
	EXPENDITURE_TYPE_ID NUMBER(18,0), 
	LEASE_SCHEDULE_ID NUMBER(18,0), 
	ASSET_SCHEDULE_NUM NUMBER(18,0), 
	INVOICE_PAYMENT_NUMBER NUMBER(18,0), 
	SHIP_TO_CUST_LOCATION_ID NUMBER(18,0), 
	SHIP_TO_LOCATION_ID NUMBER(18,0), 
	ASSET_NUMBER VARCHAR2(30), 
	TAG_NUMBER VARCHAR2(15), 
	DESCRIPTION VARCHAR2(80), 
	MANUFACTURER_NAME VARCHAR2(360), 
	SERIAL_NUMBER VARCHAR2(35), 
	MODEL_NUMBER VARCHAR2(40), 
	BOOK_TYPE_CODE VARCHAR2(30), 
	FEEDER_SYSTEM_NAME VARCHAR2(40), 
	LAST_UPDATED_BY VARCHAR2(64), 
	REVIEWER_COMMENTS VARCHAR2(60), 
	INVOICE_NUMBER VARCHAR2(50), 
	VENDOR_NUMBER VARCHAR2(30), 
	PO_NUMBER VARCHAR2(30), 
	POSTING_STATUS VARCHAR2(15), 
	QUEUE_NAME VARCHAR2(30), 
	INVOICE_CREATED_BY VARCHAR2(64), 
	INVOICE_UPDATED_BY VARCHAR2(64), 
	PAYABLES_BATCH_NAME VARCHAR2(50), 
	DEPRECIATE_FLAG VARCHAR2(3), 
	SPLIT_MERGED_CODE VARCHAR2(3), 
	AMORTIZE_FLAG VARCHAR2(3), 
	NEW_MASTER_FLAG VARCHAR2(3), 
	ASSET_TYPE VARCHAR2(11), 
	MERGED_CODE VARCHAR2(3), 
	SPLIT_CODE VARCHAR2(3), 
	SUM_UNITS VARCHAR2(3), 
	INVENTORIAL VARCHAR2(3), 
	DIST_NAME VARCHAR2(25), 
	CONTEXT VARCHAR2(250), 
	SHORT_FISCAL_YEAR_FLAG VARCHAR2(3), 
	PROPERTY_TYPE_CODE VARCHAR2(30), 
	PROPERTY_1245_1250_CODE VARCHAR2(4), 
	IN_USE_FLAG VARCHAR2(3), 
	OWNED_LEASED VARCHAR2(15), 
	NEW_USED VARCHAR2(4), 
	MATERIAL_INDICATOR_FLAG VARCHAR2(1), 
	SALVAGE_TYPE VARCHAR2(30), 
	DEPRN_LIMIT_TYPE VARCHAR2(30), 
	MASS_PROPERTY_FLAG VARCHAR2(1), 
	COMMITMENT VARCHAR2(30), 
	INVESTMENT_LAW VARCHAR2(30), 
	TRANSACTION_NAME VARCHAR2(240), 
	CREATED_BY VARCHAR2(64), 
	LAST_UPDATE_LOGIN VARCHAR2(32), 
	ATTRIBUTE1 VARCHAR2(150), 
	ATTRIBUTE2 VARCHAR2(150), 
	ATTRIBUTE3 VARCHAR2(150), 
	ATTRIBUTE4 VARCHAR2(150), 
	ATTRIBUTE5 VARCHAR2(150), 
	ATTRIBUTE6 VARCHAR2(150), 
	ATTRIBUTE7 VARCHAR2(150), 
	ATTRIBUTE8 VARCHAR2(150), 
	ATTRIBUTE9 VARCHAR2(150), 
	ATTRIBUTE10 VARCHAR2(150), 
	ATTRIBUTE11 VARCHAR2(150), 
	ATTRIBUTE12 VARCHAR2(150), 
	ATTRIBUTE13 VARCHAR2(150), 
	ATTRIBUTE14 VARCHAR2(150), 
	ATTRIBUTE15 VARCHAR2(150), 
	ATTRIBUTE_CATEGORY_CODE VARCHAR2(30), 
	MERGE_INVOICE_NUMBER VARCHAR2(50), 
	MERGE_VENDOR_NUMBER VARCHAR2(30), 
	ATTRIBUTE16 VARCHAR2(150), 
	ATTRIBUTE17 VARCHAR2(150), 
	ATTRIBUTE18 VARCHAR2(150), 
	ATTRIBUTE19 VARCHAR2(150), 
	ATTRIBUTE20 VARCHAR2(150), 
	ATTRIBUTE21 VARCHAR2(150), 
	ATTRIBUTE22 VARCHAR2(150), 
	ATTRIBUTE23 VARCHAR2(150), 
	ATTRIBUTE24 VARCHAR2(150), 
	ATTRIBUTE25 VARCHAR2(150), 
	ATTRIBUTE26 VARCHAR2(150), 
	ATTRIBUTE27 VARCHAR2(150), 
	ATTRIBUTE28 VARCHAR2(150), 
	ATTRIBUTE29 VARCHAR2(150), 
	ATTRIBUTE30 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(30), 
	GLOBAL_ATTRIBUTE1 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE2 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE3 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE4 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE5 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE6 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE7 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE8 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE9 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE10 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE11 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE12 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE13 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE14 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE15 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE16 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE17 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE18 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE19 VARCHAR2(150), 
	GLOBAL_ATTRIBUTE20 VARCHAR2(150), 
	TH_ATTRIBUTE1 VARCHAR2(150), 
	TH_ATTRIBUTE2 VARCHAR2(150), 
	TH_ATTRIBUTE3 VARCHAR2(150), 
	TH_ATTRIBUTE4 VARCHAR2(150), 
	TH_ATTRIBUTE5 VARCHAR2(150), 
	TH_ATTRIBUTE6 VARCHAR2(150), 
	TH_ATTRIBUTE7 VARCHAR2(150), 
	TH_ATTRIBUTE8 VARCHAR2(150), 
	TH_ATTRIBUTE9 VARCHAR2(150), 
	TH_ATTRIBUTE10 VARCHAR2(150), 
	TH_ATTRIBUTE11 VARCHAR2(150), 
	TH_ATTRIBUTE12 VARCHAR2(150), 
	TH_ATTRIBUTE13 VARCHAR2(150), 
	TH_ATTRIBUTE14 VARCHAR2(150), 
	TH_ATTRIBUTE15 VARCHAR2(150), 
	TH_ATTRIBUTE_CATEGORY_CODE VARCHAR2(30), 
	TH2_ATTRIBUTE1 VARCHAR2(150), 
	TH2_ATTRIBUTE2 VARCHAR2(150), 
	TH2_ATTRIBUTE3 VARCHAR2(150), 
	TH2_ATTRIBUTE4 VARCHAR2(150), 
	TH2_ATTRIBUTE5 VARCHAR2(150), 
	TH2_ATTRIBUTE6 VARCHAR2(150), 
	TH2_ATTRIBUTE7 VARCHAR2(150), 
	TH2_ATTRIBUTE8 VARCHAR2(150), 
	TH2_ATTRIBUTE9 VARCHAR2(150), 
	TH2_ATTRIBUTE10 VARCHAR2(150), 
	TH2_ATTRIBUTE11 VARCHAR2(150), 
	TH2_ATTRIBUTE12 VARCHAR2(150), 
	TH2_ATTRIBUTE13 VARCHAR2(150), 
	TH2_ATTRIBUTE14 VARCHAR2(150), 
	TH2_ATTRIBUTE15 VARCHAR2(150), 
	TH2_ATTRIBUTE_CATEGORY_CODE VARCHAR2(30), 
	AI_ATTRIBUTE1 VARCHAR2(150), 
	AI_ATTRIBUTE2 VARCHAR2(150), 
	AI_ATTRIBUTE3 VARCHAR2(150), 
	AI_ATTRIBUTE4 VARCHAR2(150), 
	AI_ATTRIBUTE5 VARCHAR2(150), 
	AI_ATTRIBUTE6 VARCHAR2(150), 
	AI_ATTRIBUTE7 VARCHAR2(150), 
	AI_ATTRIBUTE8 VARCHAR2(150), 
	AI_ATTRIBUTE9 VARCHAR2(150), 
	AI_ATTRIBUTE10 VARCHAR2(150), 
	AI_ATTRIBUTE11 VARCHAR2(150), 
	AI_ATTRIBUTE12 VARCHAR2(150), 
	AI_ATTRIBUTE13 VARCHAR2(150), 
	AI_ATTRIBUTE14 VARCHAR2(150), 
	AI_ATTRIBUTE15 VARCHAR2(150), 
	AI_ATTRIBUTE_CATEGORY_CODE VARCHAR2(30), 
	ASSET_KEY_SEGMENT1 VARCHAR2(30), 
	ASSET_KEY_SEGMENT2 VARCHAR2(30), 
	ASSET_KEY_SEGMENT3 VARCHAR2(30), 
	ASSET_KEY_SEGMENT4 VARCHAR2(30), 
	ASSET_KEY_SEGMENT5 VARCHAR2(30), 
	ASSET_KEY_SEGMENT6 VARCHAR2(30), 
	ASSET_KEY_SEGMENT7 VARCHAR2(30), 
	ASSET_KEY_SEGMENT8 VARCHAR2(30), 
	ASSET_KEY_SEGMENT9 VARCHAR2(30), 
	ASSET_KEY_SEGMENT10 VARCHAR2(30), 
	ADD_TO_ASSET_NUMBER VARCHAR2(30), 
	PARENT_ASSET_NUMBER VARCHAR2(30), 
	GROUP_ASSET_NUMBER VARCHAR2(30), 
	BONUS_RULE VARCHAR2(30), 
	CASH_GENERATING_UNIT VARCHAR2(30), 
	CEILING_NAME VARCHAR2(30), 
	PRORATE_CONVENTION_CODE VARCHAR2(10), 
	METHOD_CODE VARCHAR2(12), 
	CATEGORY_SEGMENT1 VARCHAR2(30), 
	CATEGORY_SEGMENT2 VARCHAR2(30), 
	CATEGORY_SEGMENT3 VARCHAR2(30), 
	CATEGORY_SEGMENT4 VARCHAR2(30), 
	CATEGORY_SEGMENT5 VARCHAR2(30), 
	CATEGORY_SEGMENT6 VARCHAR2(30), 
	CATEGORY_SEGMENT7 VARCHAR2(30), 
	CLEARING_ACCT_SEGMENT1 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT2 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT3 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT4 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT5 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT6 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT7 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT8 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT9 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT10 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT11 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT12 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT13 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT14 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT15 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT16 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT17 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT18 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT19 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT20 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT21 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT22 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT23 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT24 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT25 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT26 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT27 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT28 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT29 VARCHAR2(25), 
	CLEARING_ACCT_SEGMENT30 VARCHAR2(25), 
	PREPARER_EMAIL_ADDRESS VARCHAR2(240), 
	PERIOD_NAME_FULLY_RESERVED VARCHAR2(15), 
	PERIOD_NAME_EXTENDED VARCHAR2(15), 
	PRIOR_METHOD_CODE VARCHAR2(12), 
	PREPARER_NAME VARCHAR2(240), 
	PREPARER_NUMBER VARCHAR2(30), 
	BK_GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(30), 
	BK_GLOBAL_ATTRIBUTE1 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE2 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE3 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE4 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE5 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE6 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE7 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE8 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE9 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE10 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE11 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE12 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE13 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE14 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE15 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE16 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE17 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE18 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE19 VARCHAR2(150), 
	BK_GLOBAL_ATTRIBUTE20 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(30), 
	TH_GLOBAL_ATTRIBUTE1 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE2 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE3 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE4 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE5 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE6 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE7 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE8 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE9 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE10 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE11 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE12 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE13 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE14 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE15 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE16 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE17 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE18 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE19 VARCHAR2(150), 
	TH_GLOBAL_ATTRIBUTE20 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE_CATEGORY VARCHAR2(30), 
	AI_GLOBAL_ATTRIBUTE1 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE2 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE3 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE4 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE5 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE6 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE7 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE8 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE9 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE10 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE11 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE12 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE13 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE14 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE15 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE16 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE17 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE18 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE19 VARCHAR2(150), 
	AI_GLOBAL_ATTRIBUTE20 VARCHAR2(150), 
	REDUCE_ADDITION_FLAG VARCHAR2(1), 
	REDUCE_ADJUSTMENT_FLAG VARCHAR2(1), 
	REDUCE_RETIREMENT_FLAG VARCHAR2(1), 
	RECOGNIZE_GAIN_LOSS VARCHAR2(30), 
	RECAPTURE_RESERVE_FLAG VARCHAR2(1), 
	LIMIT_PROCEEDS_FLAG VARCHAR2(1), 
	TERMINAL_GAIN_LOSS VARCHAR2(30), 
	TRACKING_METHOD VARCHAR2(30), 
	EXCESS_ALLOCATION_OPTION VARCHAR2(30), 
	DEPRECIATION_OPTION VARCHAR2(30), 
	MEMBER_ROLLUP_FLAG VARCHAR2(1), 
	ALLOCATE_TO_FULLY_RSV_FLAG VARCHAR2(1), 
	OVER_DEPRECIATE_OPTION VARCHAR2(30), 
	PERIOD_FULL_RESERVE VARCHAR2(30), 
	PERIOD_EXTD_DEPRN VARCHAR2(30), 
	PRIOR_DEPRN_LIMIT_TYPE VARCHAR2(30), 
	WARRANTY_NUMBER VARCHAR2(15), 
	UNIT_OF_MEASURE VARCHAR2(25), 
	ATTACHMENT_FLAG VARCHAR2(1), 
	ERROR_MSG VARCHAR2(2000), 
	LOW_VALUE_ASSET_FLAG VARCHAR2(1), 
	CREATE_EXPENSED_ASSET_FLAG VARCHAR2(1), 
	CAP_THRESHOLD_CHECK_FLAG VARCHAR2(1), 
	INVOICE_LINE_TYPE VARCHAR2(30), 
	LINE_TYPE_LOOKUP_CODE VARCHAR2(25), 
	INVOICE_LINE_DESCRIPTION VARCHAR2(240), 
	INTANGIBLE_ASSET_FLAG VARCHAR2(1), 
	LEASE_NUMBER VARCHAR2(30), 
	VENDOR_NAME VARCHAR2(360), 
	INVOICE_VOUCHER_NUMBER VARCHAR2(50), 
	PROJECT_NUMBER VARCHAR2(25), 
	PROJECT_TASK_NUMBER VARCHAR2(100), 
	FULLY_RESERVE_ON_ADD_FLAG VARCHAR2(1), 
	DATE_PLACED_IN_SERVICE DATE, 
	FIXED_ASSETS_COST NUMBER, 
	PAYABLES_UNITS NUMBER, 
	FIXED_ASSETS_UNITS NUMBER, 
	CREATE_BATCH_DATE DATE, 
	YTD_IMPAIRMENT NUMBER, 
	IMPAIRMENT_RESERVE NUMBER, 
	LAST_UPDATE_DATE TIMESTAMP (6), 
	INVOICE_DATE DATE, 
	PAYABLES_COST NUMBER, 
	DEPRN_RESERVE NUMBER, 
	YTD_DEPRN NUMBER, 
	CREATION_DATE TIMESTAMP (6), 
	SALVAGE_VALUE NUMBER, 
	ACCOUNTING_DATE DATE, 
	ATTRIBUTE_NUMBER1 NUMBER, 
	ATTRIBUTE_NUMBER2 NUMBER, 
	ATTRIBUTE_NUMBER3 NUMBER, 
	ATTRIBUTE_NUMBER4 NUMBER, 
	ATTRIBUTE_NUMBER5 NUMBER, 
	ATTRIBUTE_DATE1 DATE, 
	ATTRIBUTE_DATE2 DATE, 
	ATTRIBUTE_DATE3 DATE, 
	ATTRIBUTE_DATE4 DATE, 
	ATTRIBUTE_DATE5 DATE, 
	GLOBAL_ATTRIBUTE_NUMBER1 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER2 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER3 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER4 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER5 NUMBER, 
	GLOBAL_ATTRIBUTE_DATE1 DATE, 
	GLOBAL_ATTRIBUTE_DATE2 DATE, 
	GLOBAL_ATTRIBUTE_DATE3 DATE, 
	GLOBAL_ATTRIBUTE_DATE4 DATE, 
	GLOBAL_ATTRIBUTE_DATE5 DATE, 
	CONVERSION_DATE DATE, 
	ORIGINAL_DEPRN_START_DATE DATE, 
	GROUP_ASSET_ID NUMBER, 
	BONUS_YTD_DEPRN NUMBER, 
	BONUS_DEPRN_RESERVE NUMBER, 
	AMORTIZATION_START_DATE DATE, 
	PERCENT_SALVAGE_VALUE NUMBER, 
	ALLOWED_DEPRN_LIMIT NUMBER, 
	ALLOWED_DEPRN_LIMIT_AMOUNT NUMBER, 
	INVOICE_LINE_NUMBER NUMBER, 
	TH_ATTRIBUTE_NUMBER1 NUMBER, 
	TH_ATTRIBUTE_NUMBER2 NUMBER, 
	TH_ATTRIBUTE_NUMBER3 NUMBER, 
	TH_ATTRIBUTE_NUMBER4 NUMBER, 
	TH_ATTRIBUTE_NUMBER5 NUMBER, 
	TH_ATTRIBUTE_DATE1 DATE, 
	TH_ATTRIBUTE_DATE2 DATE, 
	TH_ATTRIBUTE_DATE3 DATE, 
	TH_ATTRIBUTE_DATE4 DATE, 
	TH_ATTRIBUTE_DATE5 DATE, 
	TH2_ATTRIBUTE_NUMBER1 NUMBER, 
	TH2_ATTRIBUTE_NUMBER2 NUMBER, 
	TH2_ATTRIBUTE_NUMBER3 NUMBER, 
	TH2_ATTRIBUTE_NUMBER4 NUMBER, 
	TH2_ATTRIBUTE_NUMBER5 NUMBER, 
	TH2_ATTRIBUTE_DATE1 DATE, 
	TH2_ATTRIBUTE_DATE2 DATE, 
	TH2_ATTRIBUTE_DATE3 DATE, 
	TH2_ATTRIBUTE_DATE4 DATE, 
	TH2_ATTRIBUTE_DATE5 DATE, 
	AI_ATTRIBUTE_NUMBER1 NUMBER, 
	AI_ATTRIBUTE_NUMBER2 NUMBER, 
	AI_ATTRIBUTE_NUMBER3 NUMBER, 
	AI_ATTRIBUTE_NUMBER4 NUMBER, 
	AI_ATTRIBUTE_NUMBER5 NUMBER, 
	AI_ATTRIBUTE_DATE1 DATE, 
	AI_ATTRIBUTE_DATE2 DATE, 
	AI_ATTRIBUTE_DATE3 DATE, 
	AI_ATTRIBUTE_DATE4 DATE, 
	AI_ATTRIBUTE_DATE5 DATE, 
	REDUCTION_RATE NUMBER, 
	NBV_AT_SWITCH NUMBER, 
	PRIOR_DEPRN_LIMIT_AMOUNT NUMBER, 
	PRIOR_DEPRN_LIMIT NUMBER, 
	YTD_REVAL_DEPRN_EXPENSE NUMBER, 
	PRODUCTION_CAPACITY NUMBER, 
	REVAL_AMORTIZATION_BASIS NUMBER, 
	REVAL_CEILING NUMBER, 
	REVAL_RESERVE NUMBER, 
	UNREVALUED_COST NUMBER, 
	FULLY_RSVD_REVALS_COUNTER NUMBER, 
	BASIC_RATE NUMBER, 
	ADJUSTED_RATE NUMBER, 
	ADJUSTED_COST NUMBER, 
	FAIR_MARKET_VALUE NUMBER, 
	IMPAIR_LOSS_BALANCE NUMBER, 
	LAST_PRICE_INDEX_VALUE NUMBER, 
	REVAL_LOSS_BALANCE NUMBER, 
	PRIOR_BASIC_RATE NUMBER, 
	PRIOR_ADJUSTED_RATE NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER6 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER7 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER8 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER9 NUMBER, 
	GLOBAL_ATTRIBUTE_NUMBER10 NUMBER, 
	GLOBAL_ATTRIBUTE_DATE6 DATE, 
	GLOBAL_ATTRIBUTE_DATE7 DATE, 
	GLOBAL_ATTRIBUTE_DATE8 DATE, 
	GLOBAL_ATTRIBUTE_DATE9 DATE, 
	GLOBAL_ATTRIBUTE_DATE10 DATE, 
	BK_GLOBAL_ATTRIBUTE_NUMBER1 NUMBER, 
	BK_GLOBAL_ATTRIBUTE_NUMBER2 NUMBER, 
	BK_GLOBAL_ATTRIBUTE_NUMBER3 NUMBER, 
	BK_GLOBAL_ATTRIBUTE_NUMBER4 NUMBER, 
	BK_GLOBAL_ATTRIBUTE_NUMBER5 NUMBER, 
	BK_GLOBAL_ATTRIBUTE_DATE1 DATE, 
	BK_GLOBAL_ATTRIBUTE_DATE2 DATE, 
	BK_GLOBAL_ATTRIBUTE_DATE3 DATE, 
	BK_GLOBAL_ATTRIBUTE_DATE4 DATE, 
	BK_GLOBAL_ATTRIBUTE_DATE5 DATE, 
	TH_GLOBAL_ATTRIBUTE_NUMBER1 NUMBER, 
	TH_GLOBAL_ATTRIBUTE_NUMBER2 NUMBER, 
	TH_GLOBAL_ATTRIBUTE_NUMBER3 NUMBER, 
	TH_GLOBAL_ATTRIBUTE_NUMBER4 NUMBER, 
	TH_GLOBAL_ATTRIBUTE_NUMBER5 NUMBER, 
	TH_GLOBAL_ATTRIBUTE_DATE1 DATE, 
	TH_GLOBAL_ATTRIBUTE_DATE2 DATE, 
	TH_GLOBAL_ATTRIBUTE_DATE3 DATE, 
	TH_GLOBAL_ATTRIBUTE_DATE4 DATE, 
	TH_GLOBAL_ATTRIBUTE_DATE5 DATE, 
	AI_GLOBAL_ATTRIBUTE_NUMBER1 NUMBER, 
	AI_GLOBAL_ATTRIBUTE_NUMBER2 NUMBER, 
	AI_GLOBAL_ATTRIBUTE_NUMBER3 NUMBER, 
	AI_GLOBAL_ATTRIBUTE_NUMBER4 NUMBER, 
	AI_GLOBAL_ATTRIBUTE_NUMBER5 NUMBER, 
	AI_GLOBAL_ATTRIBUTE_DATE1 DATE, 
	AI_GLOBAL_ATTRIBUTE_DATE2 DATE, 
	AI_GLOBAL_ATTRIBUTE_DATE3 DATE, 
	AI_GLOBAL_ATTRIBUTE_DATE4 DATE, 
	AI_GLOBAL_ATTRIBUTE_DATE5 DATE, 
	DEPRN_ADJUSTMENT_FACTOR NUMBER, 
	REVAL_AMORT_BALANCE NUMBER, 
	YTD_REVAL_AMORTIZATION NUMBER, 
	REVALUED_COST NUMBER, 
	BACKLOG_DEPRN_RESERVE NUMBER, 
	YTD_BACKLOG_DEPRN NUMBER, 
	DEPRN_EXPENSE_SEGMENT6 VARCHAR2(25)
   ) ;
--
PROMPT
PROMPT Creating Table xxmx_fa_mass_addition_dist_xfm
PROMPT
--
/*
** CREATE TABLE: xxmx_ap_invoice_lines_xfm
*/
--
CREATE TABLE  xxmx_xfm.xxmx_fa_mass_addition_dist_xfm 
   (	
   MIGRATION_SET_ID NUMBER, 
   FILE_SET_ID   VARCHAR2(20),
	MIGRATION_SET_NAME VARCHAR2(100), 
	MIGRATION_STATUS VARCHAR2(50), 
	OPERATING_UNIT VARCHAR2(240), 
	LEDGER_NAME VARCHAR2(30), 
	MASSADD_DIST_ID NUMBER, 
	MASS_ADDITION_ID NUMBER, 
	UNITS NUMBER, 
	DEPRN_EXPENSE_CCID NUMBER, 
	LOCATION_ID NUMBER, 
	EMPLOYEE_ID NUMBER, 
	LOAD_REQUEST_ID NUMBER(18,0), 
	CREATION_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(64), 
	LAST_UPDATE_DATE TIMESTAMP (6), 
	LAST_UPDATED_BY VARCHAR2(64), 
	LAST_UPDATE_LOGIN VARCHAR2(32), 
	OBJECT_VERSION_NUMBER NUMBER(9,0), 
	DEPRN_EXPENSE_SEGMENT1 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT2 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT3 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT4 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT5 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT6 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT7 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT8 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT9 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT10 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT11 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT12 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT13 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT14 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT15 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT16 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT17 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT18 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT19 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT20 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT21 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT22 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT23 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT24 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT25 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT26 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT27 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT28 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT29 VARCHAR2(25), 
	DEPRN_EXPENSE_SEGMENT30 VARCHAR2(25), 
	LOCATION_SEGMENT1 VARCHAR2(30), 
	LOCATION_SEGMENT2 VARCHAR2(30), 
	LOCATION_SEGMENT3 VARCHAR2(30), 
	LOCATION_SEGMENT4 VARCHAR2(30), 
	LOCATION_SEGMENT5 VARCHAR2(30), 
	LOCATION_SEGMENT6 VARCHAR2(30), 
	LOCATION_SEGMENT7 VARCHAR2(30), 
	EMPLOYEE_EMAIL_ADDRESS VARCHAR2(240), 
	DEPRN_SOURCE_CODE VARCHAR2(300)
   );
--
PROMPT
PROMPT Creating Table xxmx_fa_mass_rates_xfm
PROMPT
--
/*
** CREATE TABLE: xxmx_ap_invoice_lines_xfm
*/
--
CREATE TABLE  xxmx_xfm.xxmx_fa_mass_rates_xfm 
    (	
   MIGRATION_SET_ID NUMBER,
   FILE_SET_ID   VARCHAR2(20),
	MIGRATION_SET_NAME VARCHAR2(100), 
	MIGRATION_STATUS VARCHAR2(50), 
	OPERATING_UNIT VARCHAR2(240), 
	LEDGER_NAME VARCHAR2(30), 
	SET_OF_BOOKS_ID NUMBER(18,0), 
	MASS_ADDITION_ID NUMBER(18,0), 
	PARENT_MASS_ADDITION_ID NUMBER(18,0), 
	FIXED_ASSETS_COST NUMBER, 
	EXCHANGE_RATE NUMBER, 
	LOAD_REQUEST_ID NUMBER(18,0), 
	CREATED_BY VARCHAR2(64), 
	CREATION_DATE TIMESTAMP (6), 
	LAST_UPDATED_BY VARCHAR2(64), 
	LAST_UPDATE_DATE TIMESTAMP (6), 
	LAST_UPDATE_LOGIN VARCHAR2(32), 
	OBJECT_VERSION_NUMBER NUMBER(9,0), 
	CURRENCY_CODE VARCHAR2(15)
   );

--
PROMPT ***********************
PROMPT **Provide Grants
PROMPT ***********************
--
GRANT ALL ON xxmx_fa_mass_additions_xfm TO xxmx_core;
--
GRANT ALL ON xxmx_fa_mass_addition_dist_xfm TO xxmx_core;
--
GRANT ALL ON xxmx_fa_mass_rates_xfm TO xxmx_core;
--
--
PROMPT ***********************
PROMPT **Synonym Creations
PROMPT *********************** 
--

Create or replace synonym xxmx_core.xxmx_fa_mass_rates_xfm FOR xxmx_xfm.xxmx_fa_mass_rates_xfm;
Create or replace synonym xxmx_core.xxmx_fa_mass_addition_dist_xfm FOR xxmx_xfm.xxmx_fa_mass_addition_dist_xfm;
Create or replace synonym xxmx_core.xxmx_fa_mass_additions_xfm FOR xxmx_xfm.xxmx_fa_mass_additions_xfm;
--
--
PROMPT
PROMPT ***********************************************************************
PROMPT **
PROMPT Completed ** Installing Database Objects for Maximise FA Data Migration
PROMPT **
PROMPT ***********************************************************************
PROMPT 