--*****************************************************************************
--**
--**                 Copyright (c) 2020 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  xxmx_hcm_ben_stg_dbi.sql
--**
--** FILEPATH  :  $XXV1_TOP/install/sql
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  XXMX_STG
--**
--** AUTHORS   :  Shaik Latheef
--**
--** PURPOSE   :  This script installs the staging tables for the HCM 
--**              common Procedures and Functions packages.
--**
--** NOTES     :
--**
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--** [ 1.0  DD-Mon-YYYY  Shaik Latheef       Initial staging table setup        ]
--******************************************************************************


DROP INDEX XXMX_STG.XXMX_BEN_PE_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_PE_CO_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_DE_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_DE_DD_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_BE_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_BE_DB_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_PBG_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_PBB_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_PH_STG_PK;
DROP INDEX XXMX_STG.XXMX_BEN_PBO_STG_PK;

DROP TABLE XXMX_STG.XXMX_BEN_PE_STG;		-- Participant Enrollment Table
DROP TABLE XXMX_STG.XXMX_BEN_PE_CO_STG;		-- Participant Compensation Table
DROP TABLE XXMX_STG.XXMX_BEN_DE_STG;		-- Dependent Enrollment Table
DROP TABLE XXMX_STG.XXMX_BEN_DE_DD_STG;		-- Dependent Designation Table
DROP TABLE XXMX_STG.XXMX_BEN_BE_STG;		-- Beneficiary Enrollment Table
DROP TABLE XXMX_STG.XXMX_BEN_BE_DB_STG;		-- Beneficiary Designation Table
DROP TABLE XXMX_STG.XXMX_BEN_PBG_STG;		-- Person Benefit Group Table
DROP TABLE XXMX_STG.XXMX_BEN_PBB_STG;		-- Person Benefit Balance Table
DROP TABLE XXMX_STG.XXMX_BEN_PH_STG;		-- Person Habits Table
DROP TABLE XXMX_STG.XXMX_BEN_PBO_STG;		-- Person Beneficiary Organization Table


-- ***********************************************
-- Participant Enrollment Table
-- XXMX_BEN_PE_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PE_STG
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_ID				NUMBER(18),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	EFFECTIVE_DATE			DATE NOT NULL,
	LEGAL_EMPLOYER			VARCHAR2(240) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PE_STG_PK  
             ON XXMX_STG.XXMX_BEN_PE_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PE_STG FOR XXMX_STG.XXMX_BEN_PE_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PE_STG TO XXMX_CORE;

-- ***********************************************
-- Participant Compensation Table
-- XXMX_BEN_PE_CO_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PE_CO_STG
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	RATE						NUMBER(18),
	COVERAGE					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	DENROLL_BEN_PROGRAM			VARCHAR2(240),
	DENROLL_BEN_PLAN			VARCHAR2(240),
	DENROLL_BEN_OPTION			VARCHAR2(240),
	LINE_NUMBER					NUMBER(18) NOT NULL,
	ENROLLMENT_LINE_ID			NUMBER(18) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PE_CO_STG_PK  
             ON XXMX_STG.XXMX_BEN_PE_CO_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PE_CO_STG FOR XXMX_STG.XXMX_BEN_PE_CO_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PE_CO_STG TO XXMX_CORE;
   
-- ***********************************************
-- Dependent Enrollment Table
-- XXMX_BEN_DE_STG
CREATE TABLE XXMX_STG.XXMX_BEN_DE_STG
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	EFFECTIVE_DATE			DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	PERSON_ID				NUMBER(18),
	LEGAL_EMPLOYER			VARCHAR2(240) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_DE_STG_PK  
             ON XXMX_STG.XXMX_BEN_DE_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_DE_STG FOR XXMX_STG.XXMX_BEN_DE_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_DE_STG TO XXMX_CORE; 
   
-- ***********************************************
-- Dependent Designation Table
-- XXMX_BEN_DE_DD_STG
CREATE TABLE XXMX_STG.XXMX_BEN_DE_DD_STG
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	DEPENDENT_PERSON_NUMBER		VARCHAR2(30) NOT NULL,
	DEPENDENT_PERSON_ID			NUMBER(18),
	LINE_NUMBER					NUMBER(18) NOT NULL,
	DEPENDENT_LINE_ID			NUMBER(18) NOT NULL,
	DEPENDENT_FIRST_NAME		VARCHAR2(150),
	DEPENDENT_LAST_NAME			VARCHAR2(150),
	DEPENDENT_DATE_OF_BIRTH		DATE,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_DE_DD_STG_PK  
             ON XXMX_STG.XXMX_BEN_DE_DD_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_DE_DD_STG FOR XXMX_STG.XXMX_BEN_DE_DD_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_DE_DD_STG TO XXMX_CORE;     
   
   
-- ***********************************************
-- Beneficiary Enrollment Table
-- XXMX_BEN_BE_STG
CREATE TABLE XXMX_STG.XXMX_BEN_BE_STG
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	PARTICIPANT_LAST_NAME	VARCHAR2(150),
	PARTICIPANT_FIRST_NAME	VARCHAR2(150),
	BENEFIT_RELATIONSHIP	VARCHAR2(240) NOT NULL,
	EFFECTIVE_DATE			DATE NOT NULL,
	CLOSE_LIFE_EVENT		VARCHAR2(30) DEFAULT 'NO',
	CLOSE_LIFE_EVENT_DATE	DATE,
	LIFE_EVENT				VARCHAR2(240) NOT NULL,
	LIFE_EVENT_OCCURED_DATE	DATE NOT NULL,
	PERSON_ID				NUMBER(18),
	LEGAL_EMPLOYER			VARCHAR2(240) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_BE_STG_PK  
             ON XXMX_STG.XXMX_BEN_BE_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_BE_STG FOR XXMX_STG.XXMX_BEN_BE_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_BE_STG TO XXMX_CORE;   
   
-- ***********************************************
-- Beneficiary Designation Table
-- XXMX_BEN_BE_DB_STG
CREATE TABLE XXMX_STG.XXMX_BEN_BE_DB_STG
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240),
	BG_ID            			NUMBER(15),
	PERSON_ID					NUMBER(18),
	BEN_PLAN					VARCHAR2(240) NOT NULL,
	BEN_PROGRAM					VARCHAR2(240),
	BEN_OPTION					VARCHAR2(240) NOT NULL,
	BENEFICIARY_PERCENTAGE		NUMBER(18) NOT NULL,
	ORIGINAL_ENROLLMENT_DATE	DATE,
	BENEFICIARY_PERSON_NUMBER	VARCHAR2(30) NOT NULL,
	BENEFICIARY_PERSON_ID		NUMBER(18),
	BENEFICIARY_TYPE			VARCHAR2(30) NOT NULL,
	LINE_NUMBER					NUMBER(18) NOT NULL,
	BENEFICIARY_LINE_ID			NUMBER(18) NOT NULL,
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	BENEFICIARY_LAST_NAME		VARCHAR2(150),
	BENEFICIARY_FIRST_NAME		VARCHAR2(150),
	BENEFICIARY_DATE_OF_BIRTH	DATE,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_BE_DB_STG_PK  
             ON XXMX_STG.XXMX_BEN_BE_DB_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_BE_DB_STG FOR XXMX_STG.XXMX_BEN_BE_DB_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_BE_DB_STG TO XXMX_CORE;   
   
-- ***********************************************
-- Person Benefit Group Table
-- XXMX_BEN_PBG_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PBG_STG
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	BENEFIT_GROUP_NAME		VARCHAR2(240),
	EFFECTIVE_END_DATE		DATE,
	EFFECTIVE_START_DATE	DATE NOT NULL,
	GUID					VARCHAR2(32),
	LE_BENEFIT_GROUP_ID		VARCHAR2(30) NOT NULL,
	PERSON_ID				NUMBER(18),
	SOURCE_SYSTEM_ID		VARCHAR2(100),
	SOURCE_SYSTEM_OWNER		VARCHAR2(256),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PBG_STG_PK  
             ON XXMX_STG.XXMX_BEN_PBG_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBG_STG FOR XXMX_STG.XXMX_BEN_PBG_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PBG_STG TO XXMX_CORE; 

-- ***********************************************
-- Person Benefit Balance Table
-- XXMX_BEN_PBB_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PBB_STG
   (	
	MIGRATION_SET_ID 		NUMBER,
	MIGRATION_SET_NAME 		VARCHAR2(150),
	MIGRATION_STATUS		VARCHAR2(50),
	BG_NAME   				VARCHAR2(240),
	BG_ID            		NUMBER(15),
	PERSON_NUMBER			VARCHAR2(30) NOT NULL,
	BENEFIT_BALANCE_NAME	VARCHAR2(240),
	BENEFIT_RELATION_NAME	VARCHAR2(240),
	ASSIGNMENT_NUMBER		VARCHAR2(50),
	LEGAL_EMPLOYER			VARCHAR2(240) NOT NULL,
	EFFECTIVE_END_DATE		DATE,
	EFFECTIVE_START_DATE	DATE NOT NULL,
	LEGAL_ENTITY_ID			NUMBER(18),
	PER_BNFTS_BAL_ID		NUMBER(18) NOT NULL,
	PERSON_ID				NUMBER(18),
	UOM						VARCHAR2(30),
	VAL						NUMBER,
	SOURCE_SYSTEM_ID		VARCHAR2(100),
	SOURCE_SYSTEM_OWNER		VARCHAR2(256),
	GUID					VARCHAR2(32),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PBB_STG_PK  
             ON XXMX_STG.XXMX_BEN_PBB_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBB_STG FOR XXMX_STG.XXMX_BEN_PBB_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PBB_STG TO XXMX_CORE;  

-- ***********************************************
-- Person Habits Table
-- XXMX_BEN_PH_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PH_STG
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),		
	LEGAL_EMPLOYER				VARCHAR2(240) NOT NULL,
	COORD_MED_PL_NAME			VARCHAR2(240),
	CVRD_IN_ANTHR_PL			VARCHAR2(30) DEFAULT 'NO',
	DISABILITY_STATUS			VARCHAR2(30),
	EFFECTIVE_END_DATE			DATE,	
	EFFECTIVE_START_DATE		DATE NOT NULL,
	GUID						VARCHAR2(32),
	LE_HABITS_COV_ID			VARCHAR2(30) NOT NULL,	
	PERSON_ID					NUMBER(18),
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	REGISTERED_DISABLED_FLAG	VARCHAR2(30) DEFAULT 'NO',
	SOURCE_SYSTEM_ID			VARCHAR2(100),		
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	STUDENT_STATUS				VARCHAR2(30),
	TOBACCO_TYPE_USAGE			VARCHAR2(30) DEFAULT 'NO',
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PH_STG_PK  
             ON XXMX_STG.XXMX_BEN_PH_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PH_STG FOR XXMX_STG.XXMX_BEN_PH_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PH_STG TO XXMX_CORE;     
   
-- ***********************************************
-- Person Beneficiary Organization Table
-- XXMX_BEN_PBO_STG
CREATE TABLE XXMX_STG.XXMX_BEN_PBO_STG
   (	
	MIGRATION_SET_ID 			NUMBER,
	MIGRATION_SET_NAME 			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BG_NAME   					VARCHAR2(240), 
	BG_ID            			NUMBER(15),			
	PER_BNF_ORG_ID				NUMBER(22) NOT NULL,
	START_DATE					DATE NOT NULL,
	END_DATE					DATE,
	PERSON_ID					NUMBER(18),
	BNF_TYP_CD					VARCHAR2(30) DEFAULT 'ORG',
	BNF_ORGANIZATION_ID			NUMBER(22),
	TRUSTEE_ORG_NAME			VARCHAR2(240),
	TRUSTEE_ORG_REG_CD			VARCHAR2(240),
	TRUSTEE_ORG_DESCRIPTION		VARCHAR2(600),
	TRUSTEE_ADDL_DETAILS		VARCHAR2(600),
	TRUSTEE_EXECUTOR_NAME		VARCHAR2(240), 
	ORGANIZATION_NAME			VARCHAR2(240), 
	PERSON_NUMBER				VARCHAR2(30) NOT NULL,
	GUID						VARCHAR2(32),
	SOURCE_SYSTEM_ID			VARCHAR2(100),	
	SOURCE_SYSTEM_OWNER			VARCHAR2(256),
	ATTRIBUTE_CATEGORY VARCHAR2(30),
	ATTRIBUTE1 VARCHAR2(150),
	ATTRIBUTE2 VARCHAR2(150),
	ATTRIBUTE3 VARCHAR2(150),
	ATTRIBUTE4 VARCHAR2(150),
	ATTRIBUTE5 VARCHAR2(150),
	ATTRIBUTE6 VARCHAR2(150),
	ATTRIBUTE7 VARCHAR2(150),
	ATTRIBUTE8 VARCHAR2(150),
	ATTRIBUTE9 VARCHAR2(150),
	ATTRIBUTE10 VARCHAR2(150)
   );
   
   CREATE INDEX XXMX_STG.XXMX_BEN_PBO_STG_PK  
             ON XXMX_STG.XXMX_BEN_PBO_STG (PERSON_NUMBER);

   CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_BEN_PBO_STG FOR XXMX_STG.XXMX_BEN_PBO_STG ;
   GRANT ALL ON XXMX_STG.XXMX_BEN_PBO_STG TO XXMX_CORE;     

/
