-- ***************
-- **Persons Table
-- ***************
CREATE TABLE XXMX_PER_PERSONS_STG
   (
    FILE_SET_ID							VARCHAR2(30),
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'Person',
	--
    PERSON_ID      						NUMBER,
	EFFECTIVE_START_DATE        		DATE NOT NULL,
	EFFECTIVE_END_DATE          		DATE,
	PERSON_NUMBER  						VARCHAR2(30) NOT NULL,
	BLOOD_TYPE     						VARCHAR2(30),
	CORRESPONDENCE_LANGUAGE     		VARCHAR2(30),
	START_DATE     						DATE NOT NULL,
	DATE_OF_BIRTH  						DATE,
	DATE_OF_DEATH  						DATE,
	COUNTRY_OF_BIRTH            		VARCHAR2(240),
	REGION_OF_BIRTH						VARCHAR2(240),
	TOWN_OF_BIRTH  						VARCHAR2(240),
	SOURCE_SYSTEM_OWNER         		VARCHAR2(256),
	SOURCE_SYSTEM_ID            		VARCHAR2(2000),
	ACTION_CODE    						VARCHAR2(150),
	REASON_CODE    						VARCHAR2(150),
	PERSON_DUPLICATE_CHECK      		VARCHAR2(30),
	USER_GUID      						VARCHAR2(64),
	--
	PARTY_ID                         	VARCHAR2(264),
	PERSON_TYPE                      	VARCHAR2(30),
	ATTRIBUTE_CATEGORY               	VARCHAR2(30),
	ATTRIBUTE1                       	VARCHAR2(150),
	ATTRIBUTE2                       	VARCHAR2(150),
	ATTRIBUTE3                       	VARCHAR2(150),
	ATTRIBUTE4                       	VARCHAR2(150),
	ATTRIBUTE5                       	VARCHAR2(150),
	ATTRIBUTE6                       	VARCHAR2(150),
	ATTRIBUTE7                       	VARCHAR2(150),
	ATTRIBUTE8                       	VARCHAR2(150),
	ATTRIBUTE9                       	VARCHAR2(150),
	ATTRIBUTE10                      	VARCHAR2(150),
	ATTRIBUTE11                      	VARCHAR2(150),
	ATTRIBUTE12                      	VARCHAR2(150),
	ATTRIBUTE13                      	VARCHAR2(150),
	ATTRIBUTE14                      	VARCHAR2(150),
	ATTRIBUTE15                      	VARCHAR2(150),
	ATTRIBUTE16                      	VARCHAR2(150),
	ATTRIBUTE17                      	VARCHAR2(150),
	ATTRIBUTE18                      	VARCHAR2(150),
	ATTRIBUTE19                      	VARCHAR2(150),
	ATTRIBUTE20                      	VARCHAR2(150),
	ATTRIBUTE21                      	VARCHAR2(150),
	ATTRIBUTE22                      	VARCHAR2(150),
	ATTRIBUTE23                      	VARCHAR2(150),
	ATTRIBUTE24                      	VARCHAR2(150),
	ATTRIBUTE25                      	VARCHAR2(150),
	ATTRIBUTE26                      	VARCHAR2(150),
	ATTRIBUTE27                      	VARCHAR2(150),
	ATTRIBUTE28                      	VARCHAR2(150),
	ATTRIBUTE29                      	VARCHAR2(150),
	ATTRIBUTE30                      	VARCHAR2(150),
	OBJECT_VERSION_NUMBER   			NUMBER(9),
	CREATED_BY                       	VARCHAR2(64),
	CREATION_DATE         				DATE,
	LAST_UPDATED_BY                  	VARCHAR2(64),
	LAST_UPDATE_LOGIN                	VARCHAR2(32),
	LAST_UPDATE_DATE      				DATE,
	ATTRIBUTE_NUMBER1                	NUMBER,
	ATTRIBUTE_NUMBER2                	NUMBER,
	ATTRIBUTE_NUMBER3                	NUMBER,
	ATTRIBUTE_NUMBER4                	NUMBER,
	ATTRIBUTE_NUMBER5                	NUMBER,
	ATTRIBUTE_NUMBER6                	NUMBER,
	ATTRIBUTE_NUMBER7                	NUMBER,
	ATTRIBUTE_NUMBER8                	NUMBER,
	ATTRIBUTE_NUMBER9                	NUMBER,
	ATTRIBUTE_NUMBER10               	NUMBER,
	ATTRIBUTE_NUMBER11               	NUMBER,
	ATTRIBUTE_NUMBER12               	NUMBER,
	ATTRIBUTE_NUMBER13               	NUMBER,
	ATTRIBUTE_NUMBER14               	NUMBER,
	ATTRIBUTE_NUMBER15               	NUMBER,
	ATTRIBUTE_NUMBER16               	NUMBER,
	ATTRIBUTE_NUMBER17               	NUMBER,
	ATTRIBUTE_NUMBER18               	NUMBER,
	ATTRIBUTE_NUMBER19               	NUMBER,
	ATTRIBUTE_NUMBER20               	NUMBER,
	ATTRIBUTE_DATE1                  	DATE,
	ATTRIBUTE_DATE2                  	DATE,
	ATTRIBUTE_DATE3                  	DATE,
	ATTRIBUTE_DATE4                  	DATE,
	ATTRIBUTE_DATE5                  	DATE,
	ATTRIBUTE_DATE6                  	DATE,
	ATTRIBUTE_DATE7                  	DATE,
	ATTRIBUTE_DATE8                  	DATE,
	ATTRIBUTE_DATE9                  	DATE,
	ATTRIBUTE_DATE10                 	DATE,
	ATTRIBUTE_DATE11                 	DATE,
	ATTRIBUTE_DATE12                 	DATE,
	ATTRIBUTE_DATE13                 	DATE,
	ATTRIBUTE_DATE14                 	DATE,
	ATTRIBUTE_DATE15                 	DATE
); 