--
--
--*****************************************************************************
--**
--**                 Copyright (c) 2021 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  XXMX_SCM_PO_STG_DBI.sql
--**
--** FILEPATH  :  ????
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  XXMX_STG
--**
--** AUTHORS   :  Shaik Latheef
--**
--** PURPOSE   :  This script installs the XXMX_STG DB Objects for the Maximise
--**              Purchase Orders Data Migration.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    None
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--** [ 1.0  DD-Mon-YYYY  Change Author       Created.                          ]
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  ------------------------------------------------------------
--**   1.0  07-OCT-2021  Shaik Latheef  	 Created Purchase Orders STG tables for Maximise.
--**   1.1  08-NOV-2021  Shaik Latheef  	 Renamed Purchase Orders STG tables and added few attributes.
--**   1.2  12-NOV-2021  Shaik Latheef  	 Renamed Purchase Orders Filename and added few attributes.
--**   1.3  16-NOV-2021  Shaik Latheef  	 Added BPA and CPA tables.
--**
--*******************************************************************************************************
--
--
PROMPT
PROMPT
PROMPT *************************************************************
PROMPT **
PROMPT ** Installing Database Objects for Maximise PO Data Migration
PROMPT **
PROMPT *************************************************************
PROMPT
PROMPT
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Dropping Tables
PROMPT ******************
--
--
DROP TABLE XXMX_SCM_PO_HEADERS_STD_STG;
DROP TABLE XXMX_SCM_PO_LINES_STD_STG;
DROP TABLE XXMX_SCM_PO_LINE_LOCATIONS_STD_STG;
DROP TABLE XXMX_SCM_PO_DISTRIBUTIONS_STD_STG;
DROP TABLE XXMX_SCM_PO_HEADERS_BPA_STG;
DROP TABLE XXMX_SCM_PO_LINES_BPA_STG;
DROP TABLE XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG;
DROP TABLE XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG;
DROP TABLE XXMX_SCM_PO_ATTR_VALUES_BPA_STG;
DROP TABLE XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG;
DROP TABLE XXMX_SCM_PO_HEADERS_CPA_STG;
DROP TABLE XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG;
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Creating Tables
PROMPT ******************
--
--
-- **********************
-- **STD PO Headers Table
-- **********************
CREATE TABLE XXMX_SCM_PO_HEADERS_STD_STG
	(
	FILE_SET_ID								VARCHAR2(30),
	MIGRATION_SET_ID                		NUMBER,
	MIGRATION_SET_NAME              		VARCHAR2(100),
	MIGRATION_STATUS               			VARCHAR2(50),
	INTERFACE_HEADER_KEY					VARCHAR2(50),
	ACTION									VARCHAR2(25),
	BATCH_ID								NUMBER,
	INTERFACE_SOURCE_CODE					VARCHAR2(25),
	APPROVAL_ACTION							VARCHAR2(25),
	DOCUMENT_NUM							VARCHAR2(30),
	DOCUMENT_TYPE_CODE						VARCHAR2(25),
	STYLE_DISPLAY_NAME						VARCHAR2(240),
	PRC_BU_NAME								VARCHAR2(240),
	REQ_BU_NAME								VARCHAR2(240),
	SOLDTO_LE_NAME							VARCHAR2(240),
	BILLTO_BU_NAME							VARCHAR2(240),
	AGENT_NAME								VARCHAR2(2000),
	CURRENCY_CODE							VARCHAR2(15),
	RATE									NUMBER,
	RATE_TYPE								VARCHAR2(30),
	RATE_DATE								DATE,
	COMMENTS								VARCHAR2(240),
	BILL_TO_LOCATION						VARCHAR2(60),
	SHIP_TO_LOCATION						VARCHAR2(60),
	VENDOR_NAME								VARCHAR2(360),
	VENDOR_NUM								VARCHAR2(30),
	VENDOR_SITE_CODE						VARCHAR2(15),
	VENDOR_CONTACT							VARCHAR2(360),
	VENDOR_DOC_NUM							VARCHAR2(25),
	FOB										VARCHAR2(30),
	FREIGHT_CARRIER							VARCHAR2(360),
	FREIGHT_TERMS							VARCHAR2(30),
	PAY_ON_CODE								VARCHAR2(25),
	PAYMENT_TERMS							VARCHAR2(50),
	ORIGINATOR_ROLE							VARCHAR2(25),
	CHANGE_ORDER_DESC						VARCHAR2(2000),
	ACCEPTANCE_REQUIRED_FLAG				VARCHAR2(1),
	ACCEPTANCE_WITHIN_DAYS					NUMBER,
	SUPPLIER_NOTIF_METHOD					VARCHAR2(25),
	FAX										VARCHAR2(60),
	EMAIL_ADDRESS							VARCHAR2(2000),
	CONFIRMING_ORDER_FLAG					VARCHAR2(1),
	NOTE_TO_VENDOR							VARCHAR2(1000),
	NOTE_TO_RECEIVER						VARCHAR2(1000),
	DEFAULT_TAXATION_COUNTRY				VARCHAR2(2),
	TAX_DOCUMENT_SUBTYPE					VARCHAR2(240),
	ATTRIBUTE_CATEGORY						VARCHAR2(30),
	ATTRIBUTE1								VARCHAR2(150),
	ATTRIBUTE2								VARCHAR2(150),
	ATTRIBUTE3								VARCHAR2(150),
	ATTRIBUTE4								VARCHAR2(150),
	ATTRIBUTE5								VARCHAR2(150),
	ATTRIBUTE6								VARCHAR2(150),
	ATTRIBUTE7								VARCHAR2(150),
	ATTRIBUTE8								VARCHAR2(150),
	ATTRIBUTE9								VARCHAR2(150),
	ATTRIBUTE10								VARCHAR2(150),
	ATTRIBUTE11								VARCHAR2(150),
	ATTRIBUTE12								VARCHAR2(150),
	ATTRIBUTE13								VARCHAR2(150),
	ATTRIBUTE14								VARCHAR2(150),
	ATTRIBUTE15								VARCHAR2(150),
	ATTRIBUTE16								VARCHAR2(150),
	ATTRIBUTE17								VARCHAR2(150),
	ATTRIBUTE18								VARCHAR2(150),
	ATTRIBUTE19								VARCHAR2(150),
	ATTRIBUTE20								VARCHAR2(150),
	ATTRIBUTE_DATE1							DATE,
	ATTRIBUTE_DATE2							DATE,
	ATTRIBUTE_DATE3							DATE,
	ATTRIBUTE_DATE4							DATE,
	ATTRIBUTE_DATE5							DATE,
	ATTRIBUTE_DATE6							DATE,
	ATTRIBUTE_DATE7							DATE,
	ATTRIBUTE_DATE8							DATE,
	ATTRIBUTE_DATE9							DATE,
	ATTRIBUTE_DATE10						DATE,
	ATTRIBUTE_NUMBER1						NUMBER(18),
	ATTRIBUTE_NUMBER2						NUMBER(18),
	ATTRIBUTE_NUMBER3						NUMBER(18),
	ATTRIBUTE_NUMBER4						NUMBER(18),
	ATTRIBUTE_NUMBER5						NUMBER(18),
	ATTRIBUTE_NUMBER6						NUMBER(18),
	ATTRIBUTE_NUMBER7						NUMBER(18),
	ATTRIBUTE_NUMBER8						NUMBER(18),
	ATTRIBUTE_NUMBER9						NUMBER(18),
	ATTRIBUTE_NUMBER10						NUMBER(18),
	ATTRIBUTE_TIMESTAMP1					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10					TIMESTAMP(6),
	AGENT_EMAIL_ADDRESS						VARCHAR2(240),
	MODE_OF_TRANSPORT						VARCHAR2(30),
	SERVICE_LEVEL							VARCHAR2(80),
	FIRST_PTY_REG_NUM						VARCHAR2(50),
	THIRD_PTY_REG_NUM						VARCHAR2(50),
	BUYER_MANAGED_TRANSPORT_FLAG			VARCHAR2(1),
	MASTER_CONTRACT_NUMBER					VARCHAR2(120),
	MASTER_CONTRACT_TYPE					VARCHAR2(150),
	CC_EMAIL_ADDRESS						VARCHAR2(2000),
	BCC_EMAIL_ADDRESS						VARCHAR2(2000),
	PO_HEADER_ID							VARCHAR2(30)
    );

-- ********************
-- **STD PO Lines Table
-- ********************
CREATE TABLE  XXMX_SCM_PO_LINES_STD_STG
    (
	FILE_SET_ID								VARCHAR2(30),	
	MIGRATION_SET_ID                		NUMBER,
	MIGRATION_SET_NAME              		VARCHAR2(100),
	MIGRATION_STATUS               			VARCHAR2(50),
    INTERFACE_LINE_KEY						VARCHAR2(50),
	INTERFACE_HEADER_KEY					VARCHAR2(50),
	ACTION									VARCHAR2(25),
	LINE_NUM								NUMBER,
	LINE_TYPE								VARCHAR2(30),
	ITEM									VARCHAR2(300),
	ITEM_DESCRIPTION						VARCHAR2(240),
	ITEM_REVISION							VARCHAR2(18),
	CATEGORY								VARCHAR2(2000),
	AMOUNT									NUMBER,
	QUANTITY								NUMBER,
	UNIT_OF_MEASURE							VARCHAR2(25),
	UNIT_PRICE								NUMBER,
	SECONDARY_QUANTITY						NUMBER,
	SECONDARY_UNIT_OF_MEASURE				VARCHAR2(18),
	VENDOR_PRODUCT_NUM						VARCHAR2(25),
	NEGOTIATED_BY_PREPARER_FLAG				VARCHAR2(1),
	HAZARD_CLASS							VARCHAR2(40),
	UN_NUMBER								VARCHAR2(25),
	NOTE_TO_VENDOR							VARCHAR2(1000),
	NOTE_TO_RECEIVER						VARCHAR2(1000),
	LINE_ATTRIBUTE_CATEGORY_LINES			VARCHAR2(30),
	LINE_ATTRIBUTE1							VARCHAR2(150),
	LINE_ATTRIBUTE2							VARCHAR2(150),
	LINE_ATTRIBUTE3							VARCHAR2(150),
	LINE_ATTRIBUTE4							VARCHAR2(150),
	LINE_ATTRIBUTE5							VARCHAR2(150),
	LINE_ATTRIBUTE6							VARCHAR2(150),
	LINE_ATTRIBUTE7							VARCHAR2(150),
	LINE_ATTRIBUTE8							VARCHAR2(150),
	LINE_ATTRIBUTE9							VARCHAR2(150),
	LINE_ATTRIBUTE10						VARCHAR2(150),
	LINE_ATTRIBUTE11						VARCHAR2(150),
	LINE_ATTRIBUTE12						VARCHAR2(150),
	LINE_ATTRIBUTE13						VARCHAR2(150),
	LINE_ATTRIBUTE14						VARCHAR2(150),
	LINE_ATTRIBUTE15						VARCHAR2(150),
	LINE_ATTRIBUTE16						VARCHAR2(150),
	LINE_ATTRIBUTE17						VARCHAR2(150),
	LINE_ATTRIBUTE18						VARCHAR2(150),
	LINE_ATTRIBUTE19						VARCHAR2(150),
	LINE_ATTRIBUTE20						VARCHAR2(150),
	ATTRIBUTE_DATE1							DATE,
	ATTRIBUTE_DATE2							DATE,
	ATTRIBUTE_DATE3							DATE,
	ATTRIBUTE_DATE4							DATE,
	ATTRIBUTE_DATE5							DATE,
	ATTRIBUTE_DATE6							DATE,
	ATTRIBUTE_DATE7							DATE,
	ATTRIBUTE_DATE8							DATE,
	ATTRIBUTE_DATE9							DATE,
	ATTRIBUTE_DATE10						DATE,
	ATTRIBUTE_NUMBER1						NUMBER(18),
	ATTRIBUTE_NUMBER2						NUMBER(18),
	ATTRIBUTE_NUMBER3						NUMBER(18),
	ATTRIBUTE_NUMBER4						NUMBER(18),
	ATTRIBUTE_NUMBER5						NUMBER(18),
	ATTRIBUTE_NUMBER6						NUMBER(18),
	ATTRIBUTE_NUMBER7						NUMBER(18),
	ATTRIBUTE_NUMBER8						NUMBER(18),
	ATTRIBUTE_NUMBER9						NUMBER(18),
	ATTRIBUTE_NUMBER10						NUMBER(18),
	ATTRIBUTE_TIMESTAMP1					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10					TIMESTAMP(6),
	UNIT_WEIGHT								NUMBER,
	WEIGHT_UOM_CODE							VARCHAR2(3),
	WEIGHT_UNIT_OF_MEASURE					VARCHAR2(25),
	UNIT_VOLUME								NUMBER,
	VOLUME_UOM_CODE							VARCHAR2(3),
	VOLUME_UNIT_OF_MEASURE					VARCHAR2(25),
	TEMPLATE_NAME							VARCHAR2(30),
	ITEM_ATTRIBUTE_CATEGORY					VARCHAR2(30),
	ITEM_ATTRIBUTE1							VARCHAR2(150),
	ITEM_ATTRIBUTE2							VARCHAR2(150),
	ITEM_ATTRIBUTE3							VARCHAR2(150),
	ITEM_ATTRIBUTE4							VARCHAR2(150),
	ITEM_ATTRIBUTE5							VARCHAR2(150),
	ITEM_ATTRIBUTE6							VARCHAR2(150),
	ITEM_ATTRIBUTE7							VARCHAR2(150),
	ITEM_ATTRIBUTE8							VARCHAR2(150),
	ITEM_ATTRIBUTE9							VARCHAR2(150),
	ITEM_ATTRIBUTE10						VARCHAR2(150),
	ITEM_ATTRIBUTE11						VARCHAR2(150),
	ITEM_ATTRIBUTE12						VARCHAR2(150),
	ITEM_ATTRIBUTE13						VARCHAR2(150),
	ITEM_ATTRIBUTE14						VARCHAR2(150),
	ITEM_ATTRIBUTE15						VARCHAR2(150),
	SOURCE_AGREEMENT_PRC_BU_NAME			VARCHAR2(240),
	SOURCE_AGREEMENT						VARCHAR2(30),
	SOURCE_AGREEMENT_LINE					NUMBER,
	DISCOUNT_TYPE							VARCHAR2(25),
	DISCOUNT								NUMBER,
	DISCOUNT_REASON							VARCHAR2(240),
	MAX_RETAINAGE_AMOUNT					NUMBER,
	PO_HEADER_ID							VARCHAR2(30),
	PO_LINE_ID								VARCHAR2(30)
    );
	 
-- *****************************
-- **STD PO Line Locations Table
-- *****************************
CREATE TABLE  XXMX_SCM_PO_LINE_LOCATIONS_STD_STG
    (
	FILE_SET_ID								VARCHAR2(30),	
	MIGRATION_SET_ID                		NUMBER,
	MIGRATION_SET_NAME              		VARCHAR2(100),
	MIGRATION_STATUS               			VARCHAR2(50),
	INTERFACE_LINE_LOCATION_KEY				VARCHAR2(50),
	INTERFACE_LINE_KEY						VARCHAR2(50),
	SHIPMENT_NUM							NUMBER,
	SHIP_TO_LOCATION						VARCHAR2(60),
	SHIP_TO_ORGANIZATION_CODE				VARCHAR2(18),
	AMOUNT									NUMBER,
	QUANTITY								NUMBER,
	NEED_BY_DATE							DATE,
	PROMISED_DATE							DATE,
	SECONDARY_QUANTITY						NUMBER,
	SECONDARY_UNIT_OF_MEASURE				VARCHAR2(18),
	DESTINATION_TYPE_CODE					VARCHAR2(25),
	ACCRUE_ON_RECEIPT_FLAG					VARCHAR2(1),
	ALLOW_SUBSTITUTE_RECEIPTS_FLAG			VARCHAR2(1),
	ASSESSABLE_VALUE						NUMBER,
	DAYS_EARLY_RECEIPT_ALLOWED				NUMBER,
	DAYS_LATE_RECEIPT_ALLOWED				NUMBER,
	ENFORCE_SHIP_TO_LOCATION_CODE			VARCHAR2(25),
	INSPECTION_REQUIRED_FLAG				VARCHAR2(1),
	RECEIPT_REQUIRED_FLAG					VARCHAR2(1),
	INVOICE_CLOSE_TOLERANCE					NUMBER,
	RECEIPT_CLOSE_TOLERANCE					NUMBER,
	QTY_RCV_TOLERANCE						NUMBER,
	QTY_RCV_EXCEPTION_CODE					VARCHAR2(25),
	RECEIPT_DAYS_EXCEPTION_CODE				VARCHAR2(25),
	RECEIVING_ROUTING						VARCHAR2(30),
	NOTE_TO_RECEIVER						VARCHAR2(1000),
	INPUT_TAX_CLASSIFICATION_CODE			VARCHAR2(30),
	LINE_INTENDED_USE						VARCHAR2(240),
	PRODUCT_CATEGORY						VARCHAR2(240),
	PRODUCT_FISC_CLASSIFICATION 			VARCHAR2(240),
	PRODUCT_TYPE							VARCHAR2(240),
	TRX_BUSINESS_CATEGORY_CODE				VARCHAR2(240),
	USER_DEFINED_FISC_CLASS					VARCHAR2(30),
	ATTRIBUTE_CATEGORY						VARCHAR2(30),
	ATTRIBUTE1								VARCHAR2(150),
	ATTRIBUTE2								VARCHAR2(150),
	ATTRIBUTE3								VARCHAR2(150),
	ATTRIBUTE4								VARCHAR2(150),
	ATTRIBUTE5								VARCHAR2(150),
	ATTRIBUTE6								VARCHAR2(150),
	ATTRIBUTE7								VARCHAR2(150),
	ATTRIBUTE8								VARCHAR2(150),
	ATTRIBUTE9								VARCHAR2(150),
	ATTRIBUTE10								VARCHAR2(150),
	ATTRIBUTE11								VARCHAR2(150),
	ATTRIBUTE12								VARCHAR2(150),
	ATTRIBUTE13								VARCHAR2(150),
	ATTRIBUTE14								VARCHAR2(150),
	ATTRIBUTE15								VARCHAR2(150),
	ATTRIBUTE16								VARCHAR2(150),
	ATTRIBUTE17								VARCHAR2(150),
	ATTRIBUTE18								VARCHAR2(150),
	ATTRIBUTE19								VARCHAR2(150),
	ATTRIBUTE20								VARCHAR2(150),
	ATTRIBUTE_DATE1							DATE,
	ATTRIBUTE_DATE2							DATE,
	ATTRIBUTE_DATE3							DATE,
	ATTRIBUTE_DATE4							DATE,
	ATTRIBUTE_DATE5							DATE,
	ATTRIBUTE_DATE6							DATE,
	ATTRIBUTE_DATE7							DATE,
	ATTRIBUTE_DATE8							DATE,
	ATTRIBUTE_DATE9							DATE,
	ATTRIBUTE_DATE10						DATE,
	ATTRIBUTE_NUMBER1						NUMBER(18),
	ATTRIBUTE_NUMBER2						NUMBER(18),
	ATTRIBUTE_NUMBER3						NUMBER(18),
	ATTRIBUTE_NUMBER4						NUMBER(18),
	ATTRIBUTE_NUMBER5						NUMBER(18),
	ATTRIBUTE_NUMBER6						NUMBER(18),
	ATTRIBUTE_NUMBER7						NUMBER(18),
	ATTRIBUTE_NUMBER8						NUMBER(18),
	ATTRIBUTE_NUMBER9						NUMBER(18),
	ATTRIBUTE_NUMBER10						NUMBER(18),
	ATTRIBUTE_TIMESTAMP1					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10					TIMESTAMP(6),
	FREIGHT_CARRIER							VARCHAR2(360),
	MODE_OF_TRANSPORT						VARCHAR2(80),
	SERVICE_LEVEL							VARCHAR2(80),
	FINAL_DISCHARGE_LOCATION_CODE			VARCHAR2(60),
	REQUESTED_SHIP_DATE						DATE,
	PROMISED_SHIP_DATE						DATE,
	REQUESTED_DELIVERY_DATE					DATE,
	PROMISED_DELIVERY_DATE					DATE,
	RETAINAGE_RATE							NUMBER,
	INVOICE_MATCH_OPTION					VARCHAR2(25),
	PO_HEADER_ID							VARCHAR2(30),
	PO_LINE_ID								VARCHAR2(30),
	LINE_LOCATION_ID						VARCHAR2(30)
    );
	 
-- ****************************
-- **STD PO Distributions Table
-- ****************************
CREATE TABLE  XXMX_SCM_PO_DISTRIBUTIONS_STD_STG
    (
	FILE_SET_ID								VARCHAR2(30),	
	MIGRATION_SET_ID                		NUMBER,
	MIGRATION_SET_NAME              		VARCHAR2(100),
	MIGRATION_STATUS               			VARCHAR2(50),
   	INTERFACE_DISTRIBUTION_KEY				VARCHAR2(50),
	INTERFACE_LINE_LOCATION_KEY				VARCHAR2(50),
	DISTRIBUTION_NUM						NUMBER,
	DELIVER_TO_LOCATION						VARCHAR2(60),
	DELIVER_TO_PERSON_FULL_NAME				VARCHAR2(2000),
	DESTINATION_SUBINVENTORY				VARCHAR2(10),
	AMOUNT_ORDERED							NUMBER,
	QUANTITY_ORDERED						NUMBER,
	CHARGE_ACCOUNT_SEGMENT1					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT2					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT3					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT4					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT5					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT6					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT7					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT8					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT9					VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT10				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT11				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT12				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT13				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT14				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT15				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT16				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT17				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT18				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT19				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT20				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT21				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT22				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT23				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT24				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT25				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT26				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT27				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT28				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT29				VARCHAR2(25),
	CHARGE_ACCOUNT_SEGMENT30				VARCHAR2(25),
	DESTINATION_CONTEXT						VARCHAR2(30),
	PROJECT									VARCHAR2(240),
	TASK									VARCHAR2(100),
	PJC_EXPENDITURE_ITEM_DATE				DATE,
	EXPENDITURE_TYPE						VARCHAR2(240),
	EXPENDITURE_ORGANIZATION				VARCHAR2(240),
	PJC_BILLABLE_FLAG						VARCHAR2(1),
	PJC_CAPITALIZABLE_FLAG					VARCHAR2(1),
	PJC_WORK_TYPE							VARCHAR2(240),
	PJC_RESERVED_ATTRIBUTE1					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE2					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE3					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE4					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE5					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE6					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE7					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE8					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE9					VARCHAR2(150),
	PJC_RESERVED_ATTRIBUTE10				VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE1					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE2					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE3					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE4					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE5					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE6					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE7					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE8					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE9					VARCHAR2(150),
	PJC_USER_DEF_ATTRIBUTE10				VARCHAR2(150),
	RATE									NUMBER,
	RATE_DATE								DATE,
	ATTRIBUTE_CATEGORY						VARCHAR2(30),
	ATTRIBUTE1								VARCHAR2(150),
	ATTRIBUTE2								VARCHAR2(150),
	ATTRIBUTE3								VARCHAR2(150),
	ATTRIBUTE4								VARCHAR2(150),
	ATTRIBUTE5								VARCHAR2(150),
	ATTRIBUTE6								VARCHAR2(150),
	ATTRIBUTE7								VARCHAR2(150),
	ATTRIBUTE8								VARCHAR2(150),
	ATTRIBUTE9								VARCHAR2(150),
	ATTRIBUTE10								VARCHAR2(150),
	ATTRIBUTE11								VARCHAR2(150),
	ATTRIBUTE12								VARCHAR2(150),
	ATTRIBUTE13								VARCHAR2(150),
	ATTRIBUTE14								VARCHAR2(150),
	ATTRIBUTE15								VARCHAR2(150),
	ATTRIBUTE16								VARCHAR2(150),
	ATTRIBUTE17								VARCHAR2(150),
	ATTRIBUTE18								VARCHAR2(150),
	ATTRIBUTE19								VARCHAR2(150),
	ATTRIBUTE20								VARCHAR2(150),
	ATTRIBUTE_DATE1							DATE,
	ATTRIBUTE_DATE2							DATE,
	ATTRIBUTE_DATE3							DATE,
	ATTRIBUTE_DATE4							DATE,
	ATTRIBUTE_DATE5							DATE,
	ATTRIBUTE_DATE6							DATE,
	ATTRIBUTE_DATE7							DATE,
	ATTRIBUTE_DATE8							DATE,
	ATTRIBUTE_DATE9							DATE,
	ATTRIBUTE_DATE10						DATE,
	ATTRIBUTE_NUMBER1						NUMBER(18),
	ATTRIBUTE_NUMBER2						NUMBER(18),
	ATTRIBUTE_NUMBER3						NUMBER(18),
	ATTRIBUTE_NUMBER4						NUMBER(18),
	ATTRIBUTE_NUMBER5						NUMBER(18),
	ATTRIBUTE_NUMBER6						NUMBER(18),
	ATTRIBUTE_NUMBER7						NUMBER(18),
	ATTRIBUTE_NUMBER8						NUMBER(18),
	ATTRIBUTE_NUMBER9						NUMBER(18),
	ATTRIBUTE_NUMBER10						NUMBER(18),
	ATTRIBUTE_TIMESTAMP1					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9					TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10					TIMESTAMP(6),
	DELIVER_TO_PERSON_EMAIL_ADDR			VARCHAR2(240),
	BUDGET_DATE								DATE,
	PJC_CONTRACT_NUMBER						VARCHAR2(120),
	PJC_FUNDING_SOURCE						VARCHAR2(360),
	PO_HEADER_ID							VARCHAR2(30),
	PO_LINE_ID								VARCHAR2(30),
	LINE_LOCATION_ID						VARCHAR2(30),
	PO_DISTRIBUTION_ID						VARCHAR2(30)
    );
	
-- **********************
-- **BPA PO Headers Table
-- **********************
CREATE TABLE XXMX_SCM_PO_HEADERS_BPA_STG
	(
	FILE_SET_ID										VARCHAR2(30),
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_HEADER_KEY							VARCHAR2(50),
	ACTION											VARCHAR2(25),
	BATCH_ID										NUMBER,
	INTERFACE_SOURCE_CODE							VARCHAR2(25),
	APPROVAL_ACTION									VARCHAR2(25),
	DOCUMENT_NUM									VARCHAR2(30),
	DOCUMENT_TYPE_CODE								VARCHAR2(25),
	STYLE_DISPLAY_NAME								VARCHAR2(240),
	PRC_BU_NAME										VARCHAR2(240),
	AGENT_NAME										VARCHAR2(2000),
	CURRENCY_CODE									VARCHAR2(15),
	COMMENTS 										VARCHAR2(240),
	VENDOR_NAME										VARCHAR2(360),
	VENDOR_NUM										VARCHAR2(30),
	VENDOR_SITE_CODE								VARCHAR2(15),
	VENDOR_CONTACT									VARCHAR2(360),
	VENDOR_DOC_NUM									VARCHAR2(25),
	FOB												VARCHAR2(30),
	FREIGHT_CARRIER									VARCHAR2(360),
	FREIGHT_TERMS									VARCHAR2(30),
	PAY_ON_CODE										VARCHAR2(25),
	PAYMENT_TERMS									VARCHAR2(50),
	ORIGINATOR_ROLE									VARCHAR2(25),
	CHANGE_ORDER_DESC								VARCHAR2(2000),
	ACCEPTANCE_REQUIRED_FLAG						VARCHAR2(1),
	ACCEPTANCE_WITHIN_DAYS							NUMBER,
	SUPPLIER_NOTIF_METHOD							VARCHAR2(25),
	FAX												VARCHAR2(60),
	EMAIL_ADDRESS									VARCHAR2(2000),
	CONFIRMING_ORDER_FLAG							VARCHAR2(1),
	AMOUNT_AGREED 									NUMBER,
	AMOUNT_LIMIT 									NUMBER,
	MIN_RELEASE_AMOUNT 								NUMBER,
	EFFECTIVE_DATE									DATE,
	EXPIRATION_DATE 								DATE,
	NOTE_TO_VENDOR 									VARCHAR2(1000),
	NOTE_TO_RECEIVER 								VARCHAR2(1000),
	GENERATE_ORDERS_AUTOMATIC 						VARCHAR2(1),
	SUBMIT_APPROVAL_AUTOMATIC						VARCHAR2(1),
	GROUP_REQUISITIONS								VARCHAR2(1),
	GROUP_REQUISITION_LINES							VARCHAR2(1),
	USE_SHIP_TO										VARCHAR2(1),
	USE_NEED_BY_DATE								VARCHAR2(1),
	CAT_ADMIN_AUTH_ENABLED_FLAG						VARCHAR2(1),
	RETRO_PRICE_APPLY_UPDATES_FLAG					VARCHAR2(1),
	RETRO_PRICE_COMM_UPDATES_FLAG					VARCHAR2(1),
	ATTRIBUTE_CATEGORY								VARCHAR2(30),
	ATTRIBUTE1										VARCHAR2(150),
	ATTRIBUTE2										VARCHAR2(150),
	ATTRIBUTE3										VARCHAR2(150),
	ATTRIBUTE4										VARCHAR2(150),
	ATTRIBUTE5										VARCHAR2(150),
	ATTRIBUTE6										VARCHAR2(150),
	ATTRIBUTE7										VARCHAR2(150),
	ATTRIBUTE8										VARCHAR2(150),
	ATTRIBUTE9										VARCHAR2(150),
	ATTRIBUTE10										VARCHAR2(150),
	ATTRIBUTE11										VARCHAR2(150),
	ATTRIBUTE12										VARCHAR2(150),
	ATTRIBUTE13										VARCHAR2(150),
	ATTRIBUTE14										VARCHAR2(150),
	ATTRIBUTE15										VARCHAR2(150),
	ATTRIBUTE16										VARCHAR2(150),
	ATTRIBUTE17										VARCHAR2(150),
	ATTRIBUTE18										VARCHAR2(150),
	ATTRIBUTE19										VARCHAR2(150),
	ATTRIBUTE20										VARCHAR2(150),
	ATTRIBUTE_DATE1									DATE,
	ATTRIBUTE_DATE2									DATE,
	ATTRIBUTE_DATE3									DATE,
	ATTRIBUTE_DATE4									DATE,
	ATTRIBUTE_DATE5									DATE,
	ATTRIBUTE_DATE6									DATE,
	ATTRIBUTE_DATE7									DATE,
	ATTRIBUTE_DATE8									DATE,
	ATTRIBUTE_DATE9									DATE,
	ATTRIBUTE_DATE10								DATE,
	ATTRIBUTE_NUMBER1								NUMBER(18),
	ATTRIBUTE_NUMBER2								NUMBER(18),
	ATTRIBUTE_NUMBER3								NUMBER(18),
	ATTRIBUTE_NUMBER4								NUMBER(18),
	ATTRIBUTE_NUMBER5								NUMBER(18),
	ATTRIBUTE_NUMBER6								NUMBER(18),
	ATTRIBUTE_NUMBER7								NUMBER(18),
	ATTRIBUTE_NUMBER8								NUMBER(18),
	ATTRIBUTE_NUMBER9								NUMBER(18),
	ATTRIBUTE_NUMBER10								NUMBER(18),
	ATTRIBUTE_TIMESTAMP1							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10							TIMESTAMP(6),	
	AGENT_EMAIL_ADDRESS								VARCHAR2(240),
	MODE_OF_TRANSPORT								VARCHAR2(80),
	SERVICE_LEVEL									VARCHAR2(80),
	AGING_PERIOD_DAYS								NUMBER(5),
	AGING_ONSET_POINT								VARCHAR2(30),
	CONSUMPTION_ADVICE_FREQUENCY					VARCHAR2(30),
	CONSUMPTION_ADVICE_SUMMARY						VARCHAR2(30),
	DEFAULT_CONSIGNMENT_LINE_FLAG					VARCHAR2(1),
	PAY_ON_USE_FLAG 								VARCHAR2(1),
	BILLING_CYCLE_CLOSING_DATE						DATE,
	CONFIGURED_ITEM_FLAG							VARCHAR2(1),
	USE_SALES_ORDER_NUMBER_FLAG						VARCHAR2(1),
	BUYER_MANAGED_TRANSPORT_FLAG					VARCHAR2(1),
	ALLOW_ORDERING_FROM_UNASSIGNED_SITES			VARCHAR2(1),
	OUTSIDE_PROCESS_ENABLED_FLAG					VARCHAR2(1),
	MASTER_CONTRACT_NUMBER							VARCHAR2(120),
	MASTER_CONTRACT_TYPE							VARCHAR2(150),	
	PO_HEADER_ID									NUMBER	
    );

-- ********************
-- **BPA PO Lines Table
-- ********************
CREATE TABLE  XXMX_SCM_PO_LINES_BPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_LINE_KEY								VARCHAR2(50),
	INTERFACE_HEADER_KEY							VARCHAR2(50),	
	ACTION											VARCHAR2(25),	
	LINE_NUM										NUMBER,
	LINE_TYPE										VARCHAR2(30),
	ITEM											VARCHAR2(300),
	ITEM_DESCRIPTION								VARCHAR2(240),	
	ITEM_REVISION									VARCHAR2(18),	
	CATEGORY										VARCHAR2(2000),	
	COMMITTED_AMOUNT								NUMBER,	
	UNIT_OF_MEASURE									VARCHAR2(25),
	UNIT_PRICE										NUMBER,
	ALLOW_PRICE_OVERRIDE_FLAG						VARCHAR2(1),
	NOT_TO_EXCEED_PRICE								NUMBER,
	VENDOR_PRODUCT_NUM								VARCHAR2(25),
	NEGOTIATED_BY_PREPARER_FLAG						VARCHAR2(1),
	NOTE_TO_VENDOR									VARCHAR2(1000),
	NOTE_TO_RECEIVER								VARCHAR2(1000),
	MIN_RELEASE_AMOUNT								NUMBER,	
	EXPIRATION_DATE									DATE,
	SUPPLIER_PART_AUXID 							VARCHAR2(255),
	SUPPLIER_REF_NUMBER								VARCHAR2(150),
	ATTRIBUTE_CATEGORY								VARCHAR2(30),
	ATTRIBUTE1										VARCHAR2(150),
	ATTRIBUTE2										VARCHAR2(150),
	ATTRIBUTE3										VARCHAR2(150),
	ATTRIBUTE4										VARCHAR2(150),
	ATTRIBUTE5										VARCHAR2(150),
	ATTRIBUTE6										VARCHAR2(150),
	ATTRIBUTE7										VARCHAR2(150),
	ATTRIBUTE8										VARCHAR2(150),
	ATTRIBUTE9										VARCHAR2(150),
	ATTRIBUTE10										VARCHAR2(150),
	ATTRIBUTE11										VARCHAR2(150),
	ATTRIBUTE12										VARCHAR2(150),
	ATTRIBUTE13										VARCHAR2(150),
	ATTRIBUTE14										VARCHAR2(150),
	ATTRIBUTE15										VARCHAR2(150),
	ATTRIBUTE16										VARCHAR2(150),
	ATTRIBUTE17										VARCHAR2(150),
	ATTRIBUTE18										VARCHAR2(150),
	ATTRIBUTE19										VARCHAR2(150),
	ATTRIBUTE20										VARCHAR2(150),
	ATTRIBUTE_DATE1									DATE,
	ATTRIBUTE_DATE2									DATE,
	ATTRIBUTE_DATE3									DATE,
	ATTRIBUTE_DATE4									DATE,
	ATTRIBUTE_DATE5									DATE,
	ATTRIBUTE_DATE6									DATE,
	ATTRIBUTE_DATE7									DATE,
	ATTRIBUTE_DATE8									DATE,
	ATTRIBUTE_DATE9									DATE,
	ATTRIBUTE_DATE10								DATE,
	ATTRIBUTE_NUMBER1								NUMBER(18),
	ATTRIBUTE_NUMBER2								NUMBER(18),
	ATTRIBUTE_NUMBER3								NUMBER(18),
	ATTRIBUTE_NUMBER4								NUMBER(18),
	ATTRIBUTE_NUMBER5								NUMBER(18),
	ATTRIBUTE_NUMBER6								NUMBER(18),
	ATTRIBUTE_NUMBER7								NUMBER(18),
	ATTRIBUTE_NUMBER8								NUMBER(18),
	ATTRIBUTE_NUMBER9								NUMBER(18),
	ATTRIBUTE_NUMBER10								NUMBER(18),
	ATTRIBUTE_TIMESTAMP1							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10							TIMESTAMP(6),		
	AGING_PERIOD_DAYS								NUMBER(5),
	CONSIGNMENT_LINE_FLAG							VARCHAR2(1),	
	UNIT_WEIGHT										NUMBER,
	WEIGHT_UOM_CODE									VARCHAR2(3),
	WEIGHT_UNIT_OF_MEASURE 							VARCHAR2(25),
	UNIT_VOLUME										NUMBER,
	VOLUME_UOM_CODE									VARCHAR2(3),
	VOLUME_UNIT_OF_MEASURE 							VARCHAR2(25),
	TEMPLATE_NAME									VARCHAR2(30),
	ITEM_ATTRIBUTE_CATEGORY							VARCHAR2(30),
	ITEM_ATTRIBUTE1									VARCHAR2(150),								
	ITEM_ATTRIBUTE2									VARCHAR2(150),
	ITEM_ATTRIBUTE3									VARCHAR2(150),
	ITEM_ATTRIBUTE4									VARCHAR2(150),
	ITEM_ATTRIBUTE5									VARCHAR2(150),
	ITEM_ATTRIBUTE6									VARCHAR2(150),
	ITEM_ATTRIBUTE7									VARCHAR2(150),
	ITEM_ATTRIBUTE8									VARCHAR2(150),
	ITEM_ATTRIBUTE9									VARCHAR2(150),
	ITEM_ATTRIBUTE10								VARCHAR2(150),
	ITEM_ATTRIBUTE11								VARCHAR2(150),
	ITEM_ATTRIBUTE12								VARCHAR2(150),
	ITEM_ATTRIBUTE13								VARCHAR2(150),
	ITEM_ATTRIBUTE14								VARCHAR2(150),
	ITEM_ATTRIBUTE15								VARCHAR2(150),
	PARENT_ITEM										VARCHAR2(300),
	TOP_MODEL										VARCHAR2(300),
	SUPPLIER_PARENT_ITEM							VARCHAR2(300),
	SUPPLIER_TOP_MODEL								VARCHAR2(300),
	AMOUNT											NUMBER,
	PRICE_BREAK_LOOKUP_CODE							VARCHAR2(25),
	QUANTITY_COMMITTED								NUMBER,
	ALLOW_DESCRIPTION_UPDATE_FLAG					VARCHAR2(1),	
	PO_HEADER_ID									VARCHAR2(30),
	PO_LINE_ID										VARCHAR2(30)	
    );
	 
-- *****************************
-- **BPA PO Line Locations Table
-- *****************************
CREATE TABLE  XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_LINE_LOCATION_KEY						VARCHAR2(50),
	INTERFACE_LINE_KEY								VARCHAR2(50),
	SHIPMENT_NUM									NUMBER,
	SHIP_TO_LOCATION								VARCHAR2(60),
	SHIP_TO_ORGANIZATION_CODE						VARCHAR2(18),
	QUANTITY										NUMBER,
	PRICE_OVERRIDE 									NUMBER,
	PRICE_DISCOUNT									NUMBER,
	START_DATE										DATE,
	END_DATE										DATE,
	ATTRIBUTE_CATEGORY								VARCHAR2(30),
	ATTRIBUTE1										VARCHAR2(150),
	ATTRIBUTE2										VARCHAR2(150),
	ATTRIBUTE3										VARCHAR2(150),
	ATTRIBUTE4										VARCHAR2(150),
	ATTRIBUTE5										VARCHAR2(150),
	ATTRIBUTE6										VARCHAR2(150),
	ATTRIBUTE7										VARCHAR2(150),
	ATTRIBUTE8										VARCHAR2(150),
	ATTRIBUTE9										VARCHAR2(150),
	ATTRIBUTE10										VARCHAR2(150),
	ATTRIBUTE11										VARCHAR2(150),
	ATTRIBUTE12										VARCHAR2(150),
	ATTRIBUTE13										VARCHAR2(150),
	ATTRIBUTE14										VARCHAR2(150),
	ATTRIBUTE15										VARCHAR2(150),
	ATTRIBUTE16										VARCHAR2(150),
	ATTRIBUTE17										VARCHAR2(150),
	ATTRIBUTE18										VARCHAR2(150),
	ATTRIBUTE19										VARCHAR2(150),
	ATTRIBUTE20										VARCHAR2(150),
	ATTRIBUTE_DATE1									DATE,
	ATTRIBUTE_DATE2									DATE,
	ATTRIBUTE_DATE3									DATE,
	ATTRIBUTE_DATE4									DATE,
	ATTRIBUTE_DATE5									DATE,
	ATTRIBUTE_DATE6									DATE,
	ATTRIBUTE_DATE7									DATE,
	ATTRIBUTE_DATE8									DATE,
	ATTRIBUTE_DATE9									DATE,
	ATTRIBUTE_DATE10								DATE,
	ATTRIBUTE_NUMBER1								NUMBER(18),
	ATTRIBUTE_NUMBER2								NUMBER(18),
	ATTRIBUTE_NUMBER3								NUMBER(18),
	ATTRIBUTE_NUMBER4								NUMBER(18),
	ATTRIBUTE_NUMBER5								NUMBER(18),
	ATTRIBUTE_NUMBER6								NUMBER(18),
	ATTRIBUTE_NUMBER7								NUMBER(18),
	ATTRIBUTE_NUMBER8								NUMBER(18),
	ATTRIBUTE_NUMBER9								NUMBER(18),
	ATTRIBUTE_NUMBER10								NUMBER(18),
	ATTRIBUTE_TIMESTAMP1							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10							TIMESTAMP(6),
	PO_HEADER_ID									VARCHAR2(30),
	PO_LINE_ID										VARCHAR2(30),
	LINE_LOCATION_ID								VARCHAR2(30)
    );	
	
-- ***************************
-- **BPA Org Assignments Table
-- ***************************
CREATE TABLE  XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_BU_ASSIGNMENT_KEY						VARCHAR2(50),
	INTERFACE_HEADER_KEY							VARCHAR2(50),
	REQ_BU_NAME 									VARCHAR2(240),
	ORDERED_LOCALLY_FLAG							VARCHAR2(1),
	VENDOR_SITE_CODE 								VARCHAR2(15),
	SHIP_TO_LOCATION								VARCHAR2(60),
	BILL_TO_BU_NAME									VARCHAR2(240),
	BILL_TO_LOCATION								VARCHAR2(60),
	ENABLED											VARCHAR2(1)
    );

-- ****************************
-- **BPA Attribute Values Table
-- ****************************
CREATE TABLE  XXMX_SCM_PO_ATTR_VALUES_BPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_ATTRIBUTE_KEY							VARCHAR2(50),										
	INTERFACE_LINE_KEY								VARCHAR2(50),
	THUMBNAIL_IMAGE									VARCHAR2(700),
	PICTURE											VARCHAR2(700),
	MANUFACTURER_PART_NUM							VARCHAR2(700),
	ROUNDING_FACTOR									NUMBER,
	AVAILABILITY									VARCHAR2(700),
	LEAD_TIME										NUMBER,
	UNSPSC											VARCHAR2(700),
	ATTACHMENT_URL									VARCHAR2(700),
	SUPPLIER_URL									VARCHAR2(700),
	MANUFACTURER_URL								VARCHAR2(700),
	ATTRIBUTE_CATEGORY								VARCHAR2(30),
	ATTRIBUTE1										VARCHAR2(150),
	ATTRIBUTE2										VARCHAR2(150),
	ATTRIBUTE3										VARCHAR2(150),
	ATTRIBUTE4										VARCHAR2(150),
	ATTRIBUTE5										VARCHAR2(150),
	ATTRIBUTE6										VARCHAR2(150),
	ATTRIBUTE7										VARCHAR2(150),
	ATTRIBUTE8										VARCHAR2(150),
	ATTRIBUTE9										VARCHAR2(150),
	ATTRIBUTE10										VARCHAR2(150),
	ATTRIBUTE11										VARCHAR2(150),
	ATTRIBUTE12										VARCHAR2(150),
	ATTRIBUTE13										VARCHAR2(150),
	ATTRIBUTE14										VARCHAR2(150),
	ATTRIBUTE15										VARCHAR2(150),
	ATTRIBUTE16										VARCHAR2(150),
	ATTRIBUTE17										VARCHAR2(150),
	ATTRIBUTE18										VARCHAR2(150),
	ATTRIBUTE19										VARCHAR2(150),
	ATTRIBUTE20										VARCHAR2(150),
	ATTRIBUTE_DATE1									DATE,
	ATTRIBUTE_DATE2									DATE,
	ATTRIBUTE_DATE3									DATE,
	ATTRIBUTE_DATE4									DATE,
	ATTRIBUTE_DATE5									DATE,
	ATTRIBUTE_DATE6									DATE,
	ATTRIBUTE_DATE7									DATE,
	ATTRIBUTE_DATE8									DATE,
	ATTRIBUTE_DATE9									DATE,
	ATTRIBUTE_DATE10								DATE,
	ATTRIBUTE_NUMBER1								NUMBER(18),
	ATTRIBUTE_NUMBER2								NUMBER(18),
	ATTRIBUTE_NUMBER3								NUMBER(18),
	ATTRIBUTE_NUMBER4								NUMBER(18),
	ATTRIBUTE_NUMBER5								NUMBER(18),
	ATTRIBUTE_NUMBER6								NUMBER(18),
	ATTRIBUTE_NUMBER7								NUMBER(18),
	ATTRIBUTE_NUMBER8								NUMBER(18),
	ATTRIBUTE_NUMBER9								NUMBER(18),
	ATTRIBUTE_NUMBER10								NUMBER(18),
	ATTRIBUTE_TIMESTAMP1							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10							TIMESTAMP(6),
	PACKAGING_STRING								VARCHAR2(240)
    );

-- ***************************************
-- **BPA Translated Attribute Values Table
-- ***************************************
CREATE TABLE  XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_ATTRIBUTE_KEY							VARCHAR2(50),
	INTERFACE_LINE_KEY								VARCHAR2(50),
	DESCRIPTION										VARCHAR2(240),
	MANUFACTURER									VARCHAR2(700),
	ALIAS											VARCHAR2(700),
	COMMENTS										VARCHAR2(700),
	LONG_DESCRIPTION								VARCHAR2(4000),
	LANGUAGE										VARCHAR2(4)
    );	
	 
-- **********************
-- **CPA PO Headers Table
-- **********************
CREATE TABLE XXMX_SCM_PO_HEADERS_CPA_STG
	(
	FILE_SET_ID										VARCHAR2(30),
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_HEADER_KEY							VARCHAR2(50),	
	ACTION											VARCHAR2(25),
	BATCH_ID										NUMBER,
	INTERFACE_SOURCE_CODE 							VARCHAR2(25),
	APPROVAL_ACTION									VARCHAR2(25),
	DOCUMENT_NUM									VARCHAR2(30),
	DOCUMENT_TYPE_CODE								VARCHAR2(25),
	STYLE_DISPLAY_NAME								VARCHAR2(240),
	PRC_BU_NAME										VARCHAR2(240),
	AGENT_NAME 										VARCHAR2(2000),
	CURRENCY_CODE									VARCHAR2(15),
	COMMENTS										VARCHAR2(240),
	VENDOR_NAME										VARCHAR2(360),
	VENDOR_NUM 										VARCHAR2(30),
	VENDOR_SITE_CODE								VARCHAR2(15),
	VENDOR_CONTACT									VARCHAR2(360),
	VENDOR_DOC_NUM									VARCHAR2(25),
	FOB												VARCHAR2(30),
	FREIGHT_CARRIER									VARCHAR2(360),
	FREIGHT_TERMS									VARCHAR2(30),
	PAY_ON_CODE										VARCHAR2(25),
	PAYMENT_TERMS									VARCHAR2(50),
	ORIGINATOR_ROLE									VARCHAR2(25),
	CHANGE_ORDER_DESC								VARCHAR2(2000),
	ACCEPTANCE_REQUIRED_FLAG						VARCHAR2(1),
	ACCEPTANCE_WITHIN_DAYS							NUMBER,
	SUPPLIER_NOTIF_METHOD 							VARCHAR2(25),
	FAX												VARCHAR2(60),
	EMAIL_ADDRESS									VARCHAR2(2000),
	CONFIRMING_ORDER_FLAG							VARCHAR2(1),
	AMOUNT_AGREED									NUMBER,
	AMOUNT_LIMIT									NUMBER,
	MIN_RELEASE_AMOUNT								NUMBER,
	EFFECTIVE_DATE									DATE,
	EXPIRATION_DATE									DATE,
	NOTE_TO_VENDOR									VARCHAR2(1000),
	NOTE_TO_RECEIVER								VARCHAR2(1000),
	GENERATE_ORDERS_AUTOMATIC						VARCHAR2(1),
	SUBMIT_APPROVAL_AUTOMATIC						VARCHAR2(1),
	GROUP_REQUISITIONS								VARCHAR2(1),
	GROUP_REQUISITION_LINES							VARCHAR2(1),
	USE_SHIP_TO										VARCHAR2(1),
	USE_NEED_BY_DATE								DATE,
	ATTRIBUTE_CATEGORY								VARCHAR2(30),
	ATTRIBUTE1										VARCHAR2(150),
	ATTRIBUTE2										VARCHAR2(150),
	ATTRIBUTE3										VARCHAR2(150),
	ATTRIBUTE4										VARCHAR2(150),
	ATTRIBUTE5										VARCHAR2(150),
	ATTRIBUTE6										VARCHAR2(150),
	ATTRIBUTE7										VARCHAR2(150),
	ATTRIBUTE8										VARCHAR2(150),
	ATTRIBUTE9										VARCHAR2(150),
	ATTRIBUTE10										VARCHAR2(150),
	ATTRIBUTE11										VARCHAR2(150),
	ATTRIBUTE12										VARCHAR2(150),
	ATTRIBUTE13										VARCHAR2(150),
	ATTRIBUTE14										VARCHAR2(150),
	ATTRIBUTE15										VARCHAR2(150),
	ATTRIBUTE16										VARCHAR2(150),
	ATTRIBUTE17										VARCHAR2(150),
	ATTRIBUTE18										VARCHAR2(150),
	ATTRIBUTE19										VARCHAR2(150),
	ATTRIBUTE20										VARCHAR2(150),
	ATTRIBUTE_DATE1									DATE,
	ATTRIBUTE_DATE2									DATE,
	ATTRIBUTE_DATE3									DATE,
	ATTRIBUTE_DATE4									DATE,
	ATTRIBUTE_DATE5									DATE,
	ATTRIBUTE_DATE6									DATE,
	ATTRIBUTE_DATE7									DATE,
	ATTRIBUTE_DATE8									DATE,
	ATTRIBUTE_DATE9									DATE,
	ATTRIBUTE_DATE10								DATE,
	ATTRIBUTE_NUMBER1								NUMBER(18),
	ATTRIBUTE_NUMBER2								NUMBER(18),
	ATTRIBUTE_NUMBER3								NUMBER(18),
	ATTRIBUTE_NUMBER4								NUMBER(18),
	ATTRIBUTE_NUMBER5								NUMBER(18),
	ATTRIBUTE_NUMBER6								NUMBER(18),
	ATTRIBUTE_NUMBER7								NUMBER(18),
	ATTRIBUTE_NUMBER8								NUMBER(18),
	ATTRIBUTE_NUMBER9								NUMBER(18),
	ATTRIBUTE_NUMBER10								NUMBER(18),
	ATTRIBUTE_TIMESTAMP1							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP2							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP3							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP4							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP5							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP6							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP7							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP8							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP9							TIMESTAMP(6),
	ATTRIBUTE_TIMESTAMP10							TIMESTAMP(6),
	AGENT_EMAIL_ADDR								VARCHAR2(240),
	MODE_OF_TRANSPORT								VARCHAR2(80),
	SERVICE_LEVEL									VARCHAR2(80),
	USE_SALES_ORDER_NUMBER_FLAG						VARCHAR2(1),
	BUYER_MANAGED_TRANSPORT_FLAG					VARCHAR2(1),
	CONFIGURED_ITEM_FLAG							VARCHAR2(1),
	ALLOW_ORDERING_FROM_UNASSIGNED_SITES			VARCHAR2(1),
	OUTSIDE_PROCESS_ENABLED_FLAG					VARCHAR2(1),
	DISABLE_AUTOSOURCING_FLAG						VARCHAR2(1),
	MASTER_CONTRACT_NUMBER							VARCHAR2(120),
	MASTER_CONTRACT_TYPE							VARCHAR2(150),
	PO_HEADER_ID									VARCHAR2(30)
    );
	
-- ***************************
-- **CPA Org Assignments Table
-- ***************************
CREATE TABLE  XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG
    (
	FILE_SET_ID										VARCHAR2(30),	
	MIGRATION_SET_ID                				NUMBER,
	MIGRATION_SET_NAME              				VARCHAR2(100),
	MIGRATION_STATUS               					VARCHAR2(50),
	INTERFACE_BU_ASSIGNMENT_KEY						VARCHAR2(50),
	INTERFACE_HEADER_KEY							VARCHAR2(50),
	REQ_BU_NAME										VARCHAR2(240),
	ORDERED_LOCALLY_FLAG							VARCHAR2(1),
	VENDOR_SITE_CODE								VARCHAR2(15),
	SHIP_TO_LOCATION								VARCHAR2(60),
	BILL_TO_BU_NAME									VARCHAR2(240),
	BILL_TO_LOCATION								VARCHAR2(60),
	ENABLED											VARCHAR2(1)
    );
	
--
--
PROMPT
PROMPT
PROMPT ****************************
PROMPT ** CREATE OR REPLACE SYNONYM
PROMPT ****************************
--
--

--
--
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_HEADERS_STD_STG FOR XXMX_STG.XXMX_SCM_PO_HEADERS_STD_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_LINES_STD_STG FOR XXMX_STG.XXMX_SCM_PO_LINES_STD_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_LINE_LOCATIONS_STD_STG FOR XXMX_STG.XXMX_SCM_PO_LINE_LOCATIONS_STD_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_DISTRIBUTIONS_STD_STG FOR XXMX_STG.XXMX_SCM_PO_DISTRIBUTIONS_STD_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_HEADERS_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_HEADERS_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_LINES_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_LINES_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_ATTR_VALUES_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_ATTR_VALUES_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG FOR XXMX_STG.XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_HEADERS_CPA_STG FOR XXMX_STG.XXMX_SCM_PO_HEADERS_CPA_STG;
CREATE OR REPLACE SYNONYM XXMX_CORE.XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG FOR XXMX_STG.XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG;
--
--

--
--
PROMPT
PROMPT
PROMPT ***********************
PROMPT ** Granting permissions
PROMPT ***********************
--
--
	 
--
--
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_HEADERS_STD_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_LINES_STD_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_LINE_LOCATIONS_STD_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_DISTRIBUTIONS_STD_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_HEADERS_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_LINES_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_LINE_LOCATIONS_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_ATTR_VALUES_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_HEADERS_CPA_STG TO XXMX_CORE;
GRANT ALL ON XXMX_STG.XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_STG TO XXMX_CORE;
--
--

--
--
PROMPT
PROMPT
PROMPT **********************************
PROMPT **                                
PROMPT ** End of Database Object Creation
PROMPT **                                
PROMPT **********************************
PROMPT
PROMPT
--
--