-- ********************************
-- **MIGRATION_STATUS_TRACKER Table
-- ********************************
CREATE TABLE xxmx_migration_status_tracker
(
RECORD_ID					NUMBER NOT NULL,
LOAD_FILE_ID				NUMBER NOT NULL,
MIGRATION_SET_ID			NUMBER,
APPLICATION_SUITE			VARCHAR2(5),
APPLICATION					VARCHAR2(5),
BUSINESS_ENTITY				VARCHAR2(100),
SUB_ENTITY					VARCHAR2(100),
ITERATION					VARCHAR2(10),
BATCH_ENABLED				VARCHAR2(5),
HCM_FILE_NAME				VARCHAR2(200),
FILE_LOCATION				VARCHAR2(4000),
CURRENT_STATUS				VARCHAR2(100),
LOAD_DATA_READY				VARCHAR2(5),
LOAD_FILE_GEN_DBSERVER		VARCHAR2(5),
LOAD_FILE_MOVED_FTP			VARCHAR2(5),
ERROR_ID					NUMBER,
ERROR_MESSAGE				VARCHAR2(4000),
CREATION_DATE				TIMESTAMP(3),
CREATED_BY					VARCHAR2(250),
LAST_UPDATE_DATE			TIMESTAMP(3),
LAST_UPDATED_BY				VARCHAR2(250),
USER_NAME					VARCHAR2(250)
);