--------------------------------------------------------
--  DDL for Table XX_CLOUD_COUNTRY_CODES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_CLOUD_COUNTRY_CODES" 
   (	"NAME" VARCHAR2(120 BYTE), 
	"CODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
