--------------------------------------------------------
--  DDL for Table XX_ORG_CODE
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_ORG_CODE" 
   (	"DEPT_ID" VARCHAR2(100 BYTE), 
	"ORG_CODE" VARCHAR2(1000 BYTE), 
	"DEPT_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
