--------------------------------------------------------
--  DDL for Table XX_POSITION_MAP_TEMP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_POSITION_MAP_TEMP" 
   (	"GEN1" VARCHAR2(20 BYTE), 
	"GEN2" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"POSITION_CODE" VARCHAR2(250 BYTE), 
	"LOCATION_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XX_POSITION_MAP_TEMP" TO "XXMX_READONLY";
