--------------------------------------------------------
--  DDL for Table XX_PER_SAL_HIST_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XX_PER_SAL_HIST_STG" 
   (	"EMPLOYEE_NUMBER" VARCHAR2(30 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"LOCATION" VARCHAR2(60 BYTE), 
	"GRADE" VARCHAR2(240 BYTE), 
	"JOB" VARCHAR2(700 BYTE), 
	"COMPANY" VARCHAR2(240 BYTE), 
	"DEPARTMENT" VARCHAR2(240 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"POSITION_CODE" VARCHAR2(50 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(150 BYTE), 
	"END_DATE" VARCHAR2(50 BYTE), 
	"START_DATE" VARCHAR2(50 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(10 BYTE), 
	"BG_NAME" VARCHAR2(10 BYTE), 
	"LOCATION_CODE" VARCHAR2(10 BYTE), 
	"ORIGINAL_DATE_OF_HIRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
