--------------------------------------------------------
--  Constraints for Table XXMX_PA_CUST_REV_DIST_LINES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("EXPENDITURE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("LINE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("DRAFT_REVENUE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("DRAFT_REVENUE_ITEM_LINE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_CUST_REV_DIST_LINES_ALL" MODIFY ("BILL_TRANS_CURRENCY_CODE" NOT NULL ENABLE);
