--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RECEIPTS_XFM_BKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_XFM_BKUP" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_XFM_BKUP" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_XFM_BKUP" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
