--------------------------------------------------------
--  DDL for Table XXMX_PPM_CLOUD_CONT_BILLPLANS_BKP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CLOUD_CONT_BILLPLANS_BKP" 
   (	"CONTRACT_ID" NUMBER, 
	"ID" NUMBER, 
	"CONTRACT_NUMBER" VARCHAR2(100 BYTE), 
	"CONT_MAJOR_VERSION" NUMBER, 
	"BILL_PLAN_ID" NUMBER, 
	"BP_MAJOR_VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
