--------------------------------------------------------
--  Constraints for Table XXMX_MAPPING_DEFINITIONS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" MODIFY ("MAPPING_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" MODIFY ("APPL_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" MODIFY ("MAPPING_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" MODIFY ("ENABLED_FLAG" NOT NULL ENABLE);
