--------------------------------------------------------
--  DDL for Table XXMX_FA_MASS_RATES_STG_BKP_241123
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FA_MASS_RATES_STG_BKP_241123" 
   (	"FILE_SET_ID" VARCHAR2(20 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"OPERATING_UNIT" VARCHAR2(240 BYTE), 
	"LEDGER_NAME" VARCHAR2(30 BYTE), 
	"SET_OF_BOOKS_ID" NUMBER(18,0), 
	"INTERFACE_LINE_NUM" NUMBER, 
	"MASS_ADDITION_ID" NUMBER(18,0), 
	"PARENT_MASS_ADDITION_ID" NUMBER(18,0), 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"FIXED_ASSETS_COST" NUMBER, 
	"EXCHANGE_RATE" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER(18,0), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
