--------------------------------------------------------
--  DDL for Table XXMX_MIGRATION_METADATA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MIGRATION_METADATA" 
   (	"METADATA_ID" NUMBER, 
	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"BUSINESS_ENTITY_SEQ" NUMBER(3,0), 
	"BUSINESS_ENTITY" VARCHAR2(100 BYTE), 
	"SUB_ENTITY_SEQ" NUMBER(3,0), 
	"SUB_ENTITY" VARCHAR2(100 BYTE), 
	"ENTITY_PACKAGE_NAME" VARCHAR2(30 BYTE), 
	"SQL_LOAD_NAME" VARCHAR2(100 BYTE), 
	"STG_PROCEDURE_NAME" VARCHAR2(30 BYTE), 
	"STG_TABLE" VARCHAR2(1000 BYTE), 
	"SIMPLE_XFM_PERFORMED_BY" VARCHAR2(10 BYTE), 
	"XFM_PROCEDURE_NAME" VARCHAR2(30 BYTE), 
	"XFM_TABLE" VARCHAR2(1000 BYTE), 
	"FILE_GEN_PERFORMED_BY" VARCHAR2(10 BYTE), 
	"FILE_GEN_PACKAGE" VARCHAR2(30 BYTE), 
	"FILE_GEN_PROCEDURE_NAME" VARCHAR2(30 BYTE), 
	"DATA_FILE_NAME" VARCHAR2(1000 BYTE), 
	"DATA_FILE_EXTENSION" VARCHAR2(3 BYTE), 
	"FILE_GROUP_NUMBER" NUMBER(3,0), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_READONLY";
  GRANT ALTER ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT READ ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT SELECT ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT INSERT ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT INDEX ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT DELETE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT ALTER ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_STG";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT READ ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT SELECT ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT INSERT ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT INDEX ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
  GRANT DELETE ON "XXMX_CORE"."XXMX_MIGRATION_METADATA" TO "XXMX_XFM";
