--------------------------------------------------------
--  Constraints for Table XXMX_STG_TABLE_COLUMNS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" MODIFY ("STG_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" MODIFY ("STG_TABLE_COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" MODIFY ("STG_COLUMN_SEQ" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_STG_TABLE_COLUMNS" MODIFY ("DATA_TYPE" NOT NULL ENABLE);
