--------------------------------------------------------
--  DDL for Table XXMX_PA0032_PROD
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA0032_PROD" 
   (	"DATA_SOURCE" VARCHAR2(4000 BYTE), 
	"COLUMN_KEY" VARCHAR2(4000 BYTE), 
	"OU_NAME" VARCHAR2(4000 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(4000 BYTE), 
	"TASK_NUMBER" VARCHAR2(4000 BYTE), 
	"BILL_TRANS_CURRENCY_CODE" VARCHAR2(4000 BYTE), 
	"ACCRUED_INCOME_TRANS" NUMBER, 
	"DEFERRED_INCOME_TRANS" NUMBER, 
	"ACCRUED_INCOME_LEDGER" NUMBER, 
	"DEFERRED_INCOME_LEDGER" NUMBER, 
	"REVAL_ACCRUED_INCOME_LEDGER" NUMBER, 
	"REVAL_DEFERRED_INCOME_LEDGER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
