--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_BANK_ACCTS_XFM_BKP_28623
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_AP_SUPP_BANK_ACCTS_XFM_BKP_28623" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"TEMP_EXT_PARTY_ID" NUMBER, 
	"TEMP_EXT_BANK_ACCT_ID" NUMBER, 
	"BANK_NAME" VARCHAR2(360 BYTE), 
	"BRANCH_NAME" VARCHAR2(360 BYTE), 
	"XXMX_BRANCH_NUMBER" VARCHAR2(30 BYTE), 
	"COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"BANK_ACCOUNT_NAME" VARCHAR2(80 BYTE), 
	"BANK_ACCOUNT_NUM" VARCHAR2(100 BYTE), 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"FOREIGN_PAYMENT_USE_FLAG" VARCHAR2(1 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IBAN" VARCHAR2(50 BYTE), 
	"CHECK_DIGITS" VARCHAR2(30 BYTE), 
	"BANK_ACCOUNT_NAME_ALT" VARCHAR2(320 BYTE), 
	"BANK_ACCOUNT_TYPE" VARCHAR2(25 BYTE), 
	"ACCOUNT_SUFFIX" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"AGENCY_LOCATION_CODE" VARCHAR2(30 BYTE), 
	"EXCHANGE_RATE_AGREEMENT_NUM" VARCHAR2(80 BYTE), 
	"EXCHANGE_RATE_AGREEMENT_TYPE" VARCHAR2(80 BYTE), 
	"EXCHANGE_RATE" NUMBER, 
	"SECONDARY_ACCOUNT_REFERENCE" VARCHAR2(30 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_SITE_ID" NUMBER, 
	"SUPPLIER_SITE" VARCHAR2(15 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"OU_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
