--------------------------------------------------------
--  Constraints for Table XXMX_GL_FUSION_SEG_DEFAULTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_SEG_DEFAULTS" MODIFY ("FUSION_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_SEG_DEFAULTS" MODIFY ("FUSION_SEGMENT_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_FUSION_SEG_DEFAULTS" MODIFY ("FUSION_SEGMENT_DEFAULT_VALUE" NOT NULL ENABLE);
