--------------------------------------------------------
--  Constraints for Table XXMX_PPM_TEMPLATE_TASK_FLAGS_SIT
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_SIT" MODIFY ("PROJECT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_SIT" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_SIT" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
