--------------------------------------------------------
--  Constraints for Table XXMX_GL_ACCT_SEG_TRANSFORMS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" MODIFY ("DATA_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" MODIFY ("SOURCE_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" MODIFY ("SOURCE_SEGMENT_COLUMN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" MODIFY ("SOURCE_SEGMENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCT_SEG_TRANSFORMS" MODIFY ("FROZEN_FLAG" NOT NULL ENABLE);
