--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_PRJ_TASK_IDS_ROWNUM_BKUP_291123_D1
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_PRJ_TASK_IDS_ROWNUM_BKUP_291123_D1" 
   (	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"PROJECT_TASK_NUMBER" VARCHAR2(25 BYTE), 
	"CREATE_UPDATE" CHAR(6 BYTE), 
	"PROJECT_CHARGEABLE_FLAG" VARCHAR2(5 BYTE), 
	"PROJECT_BILLABLE_FLAG" VARCHAR2(5 BYTE), 
	"PROJECT_ID" NUMBER, 
	"PROJECT_ELEMENT_ID" NUMBER, 
	"ROWN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
