--------------------------------------------------------
--  DDL for Table XXMX_HCM_PPM_JOB_MAPPING_SIT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_PPM_JOB_MAPPING_SIT" 
   (	"PERSON_NUMBER" NUMBER, 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"JOB_NAME" VARCHAR2(240 BYTE), 
	"POSITION_NAME" VARCHAR2(240 BYTE), 
	"POSITION_CODE" VARCHAR2(240 BYTE), 
	"FROM_SET_NAME" VARCHAR2(240 BYTE), 
	"MAP_SET_NAME" VARCHAR2(240 BYTE), 
	"TO_SET_NAME" VARCHAR2(240 BYTE), 
	"FROM_JOB_NAME" VARCHAR2(240 BYTE), 
	"MAP_JOB_NAME" VARCHAR2(240 BYTE), 
	"TO_JOB_NAME" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
