--------------------------------------------------------
--  DDL for Index XXMX_SEEDED_SUB_EXTENSIONS_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_SEEDED_SUB_EXTENSIONS_U1" ON "XXMX_CORE"."XXMX_SEEDED_SUB_EXTENSIONS" ("APPLICATION_SUITE", "APPLICATION", "BUSINESS_ENTITY", "SUB_ENTITY", "PHASE", "EXECUTION_SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
