--------------------------------------------------------
--  DDL for Table XXMX_LEDGERS_IN_SCOPE
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_LEDGERS_IN_SCOPE" 
   (	"LEDGER_NAME" VARCHAR2(150 BYTE), 
	"CURRENCY" VARCHAR2(50 BYTE), 
	"LEDGER_ID" VARCHAR2(100 BYTE), 
	"TRANSLATED" VARCHAR2(1 BYTE), 
	"ACCESS_SET_ID" NUMBER, 
	"CHART_OF_ACCOUNT_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"PERIOD_SET_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
