--------------------------------------------------------
--  Constraints for Table XXMX_HR_ALL_ORGANIZATION_UNITS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HR_ALL_ORGANIZATION_UNITS" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HR_ALL_ORGANIZATION_UNITS" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HR_ALL_ORGANIZATION_UNITS" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HR_ALL_ORGANIZATION_UNITS" MODIFY ("NAME" NOT NULL ENABLE);
