--------------------------------------------------------
--  DDL for Index XXMX_DATA_FILE_PROPERTIES_U3
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES_U3" ON "XXMX_CORE"."XXMX_DATA_FILE_PROPERTIES" ("XFM_TABLE_ID", "GENERATION_SEQUENCE", "DATA_FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
