--------------------------------------------------------
--  DDL for Table XXMX_SUPPLIER_SCOPE_BKP_300523
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_BKP_300523" 
   (	"VENDOR_ID" NUMBER, 
	"VENDOR_NUMBER" VARCHAR2(30 BYTE), 
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_TYPE" VARCHAR2(30 BYTE), 
	"PARTY_ID" NUMBER, 
	"ORG_ID" NUMBER, 
	"OPERATING_UNIT_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_ID" NUMBER, 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"PARTY_SITE_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
