--------------------------------------------------------
--  Constraints for Table XXMX_HCM_EXWORKERS_SCOPE
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("SYSTEM_PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("USER_PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HCM_EXWORKERS_SCOPE" MODIFY ("PERSON_TYPE_ID" NOT NULL ENABLE);
