--------------------------------------------------------
--  Constraints for Table XXMX_PROJ_TASK_BILL_CHARG_TBL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PROJ_TASK_BILL_CHARG_TBL" ADD PRIMARY KEY ("S_NO", "INTEGRATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE"  ENABLE;
