--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_STG24
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG24" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG24" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG24" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
