--------------------------------------------------------
--  DDL for Table XXMX_DM_PREVAL_SUMMARY
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DM_PREVAL_SUMMARY" 
   (	"LOAD_NAME" VARCHAR2(100 BYTE), 
	"OBJECT_NAME" VARCHAR2(100 BYTE), 
	"PARAM_COLUMN" VARCHAR2(100 BYTE), 
	"RECORD_COUNT" NUMBER, 
	"VAL_RESULT" VARCHAR2(100 BYTE), 
	"VAL_MESSAGE" VARCHAR2(100 BYTE), 
	"BATCH_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
