--------------------------------------------------------
--  Constraints for Table XXMX_CITIZENSHIPS_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_UATBKUP" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_UATBKUP" MODIFY ("CITIZENSHIP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
