--------------------------------------------------------
--  DDL for Table XXMX_PPM_PRJ_TASK_UPDATES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_PRJ_TASK_UPDATES" 
   (	"PROJECT_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"BILLABLE_FLAG" VARCHAR2(100 BYTE), 
	"CHARGEABLE_FLAG" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
