--------------------------------------------------------
--  DDL for Materialized View XXMX_PAY_ELE_VALS_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXMX_CORE"."XXMX_PAY_ELE_VALS_MV" ("EMPLOYEE_NUMBER", "ASSIGNMENT_NUMBER", "ELEMENT_NAME", "IV_NAME", "DISPLAY_SEQUENCE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "SCREEN_ENTRY_VALUE")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select * from XXMX_PAY_ELE_VALS_TAB;

   COMMENT ON MATERIALIZED VIEW "XXMX_CORE"."XXMX_PAY_ELE_VALS_MV"  IS 'snapshot table for snapshot XXMX_CORE.XXMX_PAY_ELE_VALS_MV';
