--------------------------------------------------------
--  Constraints for Table XXMX_PPM_TEMPLATE_TASK_FLAGS_TST
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_TST" MODIFY ("PROJECT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_TST" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_TST" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
