--------------------------------------------------------
--  DDL for Table XXMX_ABSENCE_TYPES_CLOUD
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_ABSENCE_TYPES_CLOUD" 
   (	"LEGISLATION_CODE" VARCHAR2(1000 BYTE), 
	"REASON_START_DATE" VARCHAR2(1000 BYTE), 
	"NAME" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
