--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_UATBKUP" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_UATBKUP" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_UATBKUP" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_PHONES_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
