--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_STG_24OCT23" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_STG_24OCT23" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_STG_24OCT23" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_STG_24OCT23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
