--------------------------------------------------------
--  Constraints for Table XXMX_MIGRATION_USERS_AND_ROLES
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES" MODIFY ("CLOUD_ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES" MODIFY ("EMPLOYEE_NUMBER" NOT NULL ENABLE);
