--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_PRJ_TASK_IDS_ROWNUM_BKUP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_PRJ_TASK_IDS_ROWNUM_BKUP" 
   (	"PROJECT_NUMBER" VARCHAR2(100 BYTE), 
	"ELEMENT_NUMBER" VARCHAR2(100 BYTE), 
	"CREATE_UPDATE" CHAR(6 BYTE), 
	"PROJECT_CHARGEABLE_FLAG" CHAR(4 BYTE), 
	"PROJECT_BILLABLE_FLAG" CHAR(4 BYTE), 
	"PROJECT_ID" NUMBER, 
	"PROJECT_ELEMENT_ID" NUMBER, 
	"ROWN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
