--------------------------------------------------------
--  Constraints for Table XXMX_FUSION_ADDRESS_FORMAT
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" MODIFY ("TERRITORY_SHORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" MODIFY ("ATTRIBUTE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" MODIFY ("STYLE_FORMAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" MODIFY ("TERRITORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" MODIFY ("MANDATORY_FLAG" NOT NULL ENABLE);
