--------------------------------------------------------
--  DDL for View XXMX_MAP_TCA_STG_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_MAP_TCA_STG_V" ("TABLE_NAME", "MIGRATION_SET_ID", "STG_TABLE_COUNT") AS 
  SELECT 'XXMX_HZ_PARTIES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_PARTIES_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_PARTY_SITES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_PARTY_SITES_STG  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_PARTY_SITE_USES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_PARTY_SITE_USES_STG  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCOUNTS_STG'  TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CUST_ACCOUNTS_STG  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCT_SITES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CUST_ACCT_SITES_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_SITE_USES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CUST_SITE_USES_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_LOCATIONS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_LOCATIONS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_PROFILES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CUST_PROFILES_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CONTACT_POINTS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CONTACT_POINTS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCT_CONTACTS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_CUST_ACCT_CONTACTS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ORG_CONTACTS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_ORG_CONTACTS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ORG_CONTACT_ROLES_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_ORG_CONTACT_ROLES_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_RELATIONSHIPS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_RELATIONSHIPS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ROLE_RESPS_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_HZ_ROLE_RESPS_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_TAX_PROFILE_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_ZX_TAX_PROFILE_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_PARTY_CLASSIFIC_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_ZX_PARTY_CLASSIFIC_STG GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_TAX_REGISTRATION_STG' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) STG_TABLE_COUNT FROM XXMX_ZX_TAX_REGISTRATION_STG GROUP BY MIGRATION_SET_ID
;
