--------------------------------------------------------
--  DDL for Table XXMX_MIGRATION_ROLE_GROUPS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MIGRATION_ROLE_GROUPS" 
   (	"APPLICATION" VARCHAR2(30 BYTE), 
	"SECURITY_CONTEXT" VARCHAR2(30 BYTE), 
	"GROUP_NAME" VARCHAR2(60 BYTE), 
	"SECURITY_CONTEXT_VALUE" VARCHAR2(60 BYTE), 
	"NOTES" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
