--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_PMT_INSTRS_STG_171123
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_AP_SUPP_PMT_INSTRS_STG_171123" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"TEMP_EXT_PARTY_ID" NUMBER, 
	"TEMP_EXT_BANK_ACCT_ID" NUMBER, 
	"TEMP_PMT_INSTR_USE_ID" NUMBER, 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"ACCT_ASSIG_START_DATE" DATE, 
	"ACCT_ASSIG_END_DATE" DATE, 
	"OU_NAME" VARCHAR2(100 BYTE), 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_SITE_ID" NUMBER, 
	"SUPPLIER_SITE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
