--------------------------------------------------------
--  Constraints for Table XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("CONTACT_POINT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("CONTACT_POINT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("OWNER_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("OWNER_TABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("CONTENT_SOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_HZ_CONTACT_POINTS_BKP_220124_NEW" MODIFY ("ACTUAL_CONTENT_SOURCE" NOT NULL ENABLE);
