--------------------------------------------------------
--  Constraints for Table XXMX_ASG_WORKMSURE_STG_22NOV23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_STG_22NOV23" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_STG_22NOV23" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_STG_22NOV23" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_STG_22NOV23" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_ASG_WORKMSURE_STG_22NOV23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
