--------------------------------------------------------
--  DDL for Table XXMX_MIGRATION_USERS_AND_ROLES
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES" 
   (	"USER_NAME" VARCHAR2(30 BYTE), 
	"CLOUD_ROLE" VARCHAR2(240 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(10 BYTE), 
	"FIRST_NAME" VARCHAR2(120 BYTE), 
	"LAST_NAME" VARCHAR2(120 BYTE), 
	"ROLE_GROUP_NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
