--------------------------------------------------------
--  Constraints for Table XXMX_PER_DISABILITY_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_UATBKUP" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_UATBKUP" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_UATBKUP" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
