--------------------------------------------------------
--  Constraints for Table XXMX_PRJ_UNBILLED_EVENTS_00
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS_00" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS_00" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS_00" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PRJ_UNBILLED_EVENTS_00" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
