--------------------------------------------------------
--  DDL for Table XXMX_OPEN_AR_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_OPEN_AR_TRANSACTIONS" 
   (	"CUSTOMER_TRX_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(240 BYTE), 
	"STATUS_TRX" VARCHAR2(240 BYTE), 
	"TRX_CLASS" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
