--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_STG_2408231257
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_2408231257" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_2408231257" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_2408231257" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
