--------------------------------------------------------
--  Constraints for Table XXMX_GL_SOURCE_STRUCT_SEGMENTS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGMENTS" MODIFY ("SOURCE_LEDGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGMENTS" MODIFY ("SOURCE_SEGMENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGMENTS" MODIFY ("SOURCE_SEGMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGMENTS" MODIFY ("SOURCE_SEGMENT_COLUMN" NOT NULL ENABLE);
