--------------------------------------------------------
--  DDL for Table XXMX_FUSION_ADDRESS_FORMAT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FUSION_ADDRESS_FORMAT" 
   (	"TERRITORY_SHORT_NAME" VARCHAR2(100 BYTE), 
	"ATTRIBUTE_CODE" VARCHAR2(30 BYTE), 
	"STYLE_FORMAT_CODE" VARCHAR2(100 BYTE), 
	"TERRITORY_CODE" VARCHAR2(30 BYTE), 
	"MANDATORY_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
