--------------------------------------------------------
--  Constraints for Table XXMX_MIGRATION_USERS_AND_ROLES_SIT2_21_07_2023
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES_SIT2_21_07_2023" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES_SIT2_21_07_2023" MODIFY ("CLOUD_ROLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_MIGRATION_USERS_AND_ROLES_SIT2_21_07_2023" MODIFY ("EMPLOYEE_NUMBER" NOT NULL ENABLE);
