--------------------------------------------------------
--  DDL for Table XXMX_PA_DRAFT_REVENUE_ITEMS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA_DRAFT_REVENUE_ITEMS" 
   (	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NAME" VARCHAR2(255 BYTE), 
	"PROJECT_ID" NUMBER(15,0), 
	"DRAFT_REVENUE_NUM" NUMBER(15,0), 
	"LINE_NUM" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"AMOUNT" NUMBER(22,5), 
	"REVENUE_SOURCE" VARCHAR2(30 BYTE), 
	"REVENUE_CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"REQUEST_ID" NUMBER(15,0), 
	"PROGRAM_APPLICATION_ID" NUMBER(15,0), 
	"PROGRAM_ID" NUMBER(15,0), 
	"PROGRAM_UPDATE_DATE" DATE, 
	"REVPROC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"PROJFUNC_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"PROJFUNC_REVENUE_AMOUNT" NUMBER, 
	"PROJECT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"PROJECT_REVENUE_AMOUNT" NUMBER, 
	"FUNDING_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"FUNDING_REVENUE_AMOUNT" NUMBER, 
	"REVTRANS_AMOUNT" NUMBER, 
	"REVTRANS_CURRENCY_CODE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
