--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASSIGNMENTS_M_STG_14NOV23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_STG_14NOV23" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_STG_14NOV23" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_STG_14NOV23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_STG_14NOV23" MODIFY ("PRIMARY_WORK_TERMS_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_STG_14NOV23" MODIFY ("PRIMARY_ASSIGNMENT_FLAG" NOT NULL ENABLE);
