--------------------------------------------------------
--  DDL for Table XXMX_PA_COSTS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PA_COSTS" 
   (	"BUSINESS_UNIT" VARCHAR2(240 BYTE), 
	"PROJECT_ID" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"EXPENDITURE_COMMENT" VARCHAR2(240 BYTE), 
	"EXP_BATCH_NAME" VARCHAR2(240 BYTE), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(250 BYTE), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NAME" VARCHAR2(255 BYTE), 
	"EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
	"OVERRIDE_TO_ORGANIZATION_ID" NUMBER(15,0), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE" VARCHAR2(30 BYTE), 
	"WORK_TYPE" VARCHAR2(80 BYTE), 
	"BILLABLE_FLAG" VARCHAR2(1 BYTE), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"ACCT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30 BYTE), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1 BYTE), 
	"CC_CROSS_CHARGE_TYPE" VARCHAR2(2 BYTE), 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(155 BYTE), 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(155 BYTE), 
	"ORIG_TRANSACTION_REFERENCE" NUMBER(15,0), 
	"NET_ZERO_ADJUSTMENT_FLAG" VARCHAR2(1 BYTE), 
	"INVOICE_ID" CHAR(1 BYTE), 
	"BILL_GROUP" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
