--------------------------------------------------------
--  Constraints for Table XXMX_GL_ACCOUNT_TRANSFORMS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_TRANSFORMS" MODIFY ("APPLICATION_SUITE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_TRANSFORMS" MODIFY ("APPLICATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_TRANSFORMS" MODIFY ("BUSINESS_ENTITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_TRANSFORMS" MODIFY ("SUB_ENTITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_TRANSFORMS" MODIFY ("SOURCE_LEDGER_NAME" NOT NULL ENABLE);
