--------------------------------------------------------
--  DDL for Table XXMX_PPM_LICFEE_UNPAID_INV
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" 
   (	"INVOICE_NUM" VARCHAR2(50 BYTE), 
	"INVOICE_ID" NUMBER(15,0), 
	"INVOICE_DATE" DATE, 
	"INVOICE_AMOUNT" NUMBER, 
	"SUPPLIER" VARCHAR2(30 BYTE), 
	"SUPPLIER_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"PROJECT_NUM" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(25 BYTE), 
	"AMOUNT_REMAINING" NUMBER, 
	"ORG_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT ALTER ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT DELETE ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT INDEX ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT INSERT ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT UPDATE ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT REFERENCES ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT READ ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT ON COMMIT REFRESH ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT QUERY REWRITE ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT DEBUG ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
  GRANT FLASHBACK ON "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" TO "XXMX_READONLY";
