--------------------------------------------------------
--  Constraints for Table XXMX_PA_EXP_SCOPE_ALL_01JAN20
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("EXPENDITURE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("EXPENDITURE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("EXPENDITURE_ITEM_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("EXPENDITURE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("COST_DISTRIBUTED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("REVENUE_DISTRIBUTED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("BILLABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("BILL_HOLD_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("SYSTEM_LINKAGE_FUNCTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("CC_CROSS_CHARGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("CC_BL_DISTRIBUTED_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EXP_SCOPE_ALL_01JAN20" MODIFY ("CC_IC_PROCESSED_CODE" NOT NULL ENABLE);
