--------------------------------------------------------
--  Constraints for Table XXMX_COSTS_PA_DRAFT_INVOICES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("DRAFT_INVOICE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("TRANSFER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("GENERATION_ERROR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_COSTS_PA_DRAFT_INVOICES_ALL" MODIFY ("AGREEMENT_ID" NOT NULL ENABLE);
