--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_CONTACTS_VALIDATION
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_AP_SUPP_CONTACTS_VALIDATION" 
   (	"VALIDATION_ERROR_MESSAGE" VARCHAR2(3000 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"IMPORT_ACTION" VARCHAR2(10 BYTE), 
	"SUPPLIER_CONTACT_ID" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"PREFIX" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"FIRST_NAME_NEW" VARCHAR2(150 BYTE), 
	"MIDDLE_NAME" VARCHAR2(60 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME_NEW" VARCHAR2(150 BYTE), 
	"JOB_TITLE" VARCHAR2(100 BYTE), 
	"PRIMARY_ADMIN_CONTACT" VARCHAR2(1 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(360 BYTE), 
	"EMAIL_ADDRESS_NEW" VARCHAR2(360 BYTE), 
	"PHONE_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"AREA_CODE" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(40 BYTE), 
	"PHONE_EXTENSION" VARCHAR2(40 BYTE), 
	"FAX_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"FAX_AREA_CODE" VARCHAR2(10 BYTE), 
	"FAX" VARCHAR2(40 BYTE), 
	"MOBILE_COUNTRY_CODE" VARCHAR2(10 BYTE), 
	"MOBILE_AREA_CODE" VARCHAR2(10 BYTE), 
	"MOBILE" VARCHAR2(40 BYTE), 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
