--------------------------------------------------------
--  DDL for Table XXMX_HCM_PPM_WORKERS_LIST
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HCM_PPM_WORKERS_LIST" 
   (	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"EX_MIN_DATE" DATE, 
	"EX_MAX_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
