--------------------------------------------------------
--  DDL for Table XXMX_DM_FUSION_DAS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DM_FUSION_DAS" 
   (	"ACCESS_SET_ID" VARCHAR2(100 BYTE), 
	"DAS_NAME" VARCHAR2(100 BYTE), 
	"ACCESS_PRIVILEGE_CODE" VARCHAR2(100 BYTE), 
	"LEDGER_ID" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(100 BYTE), 
	"BU_NAME" VARCHAR2(100 BYTE), 
	"BU_ID" VARCHAR2(100 BYTE), 
	"CURRENCY_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_DM_FUSION_DAS" TO "XXMX_READONLY";
