--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_ADDR_STG_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("ADDRESSTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("ADDRESSLINE1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACT_ADDR_STG_24JUL23" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
