--------------------------------------------------------
--  DDL for Index XXMX_SIMPLE_TRANSFORMS_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_SIMPLE_TRANSFORMS_U1" ON "XXMX_CORE"."XXMX_SIMPLE_TRANSFORMS" ("APPLICATION_SUITE", "APPLICATION", "CATEGORY_CODE", "SOURCE_VALUE", "FUSION_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 163 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
