--------------------------------------------------------
--  DDL for Table XXMX_MIGRATION_DETAILS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MIGRATION_DETAILS" 
   (	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"BUSINESS_ENTITY_SEQ" NUMBER(3,0), 
	"BUSINESS_ENTITY" VARCHAR2(100 BYTE), 
	"SUB_ENTITY_SEQ" NUMBER(3,0), 
	"SUB_ENTITY" VARCHAR2(100 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"BUSINESS_UNIT_NAME" VARCHAR2(240 BYTE), 
	"PHASE" VARCHAR2(20 BYTE), 
	"STAGING_TABLE" VARCHAR2(30 BYTE), 
	"EXTRACT_START_DATETIME" DATE, 
	"EXTRACT_COMPLETION_DATETIME" DATE, 
	"EXTRACT_ROW_COUNT" NUMBER, 
	"TRANSFORM_TABLE" VARCHAR2(30 BYTE), 
	"TRANSFORM_START_DATETIME" DATE, 
	"TRANSFORM_COMPLETION_DATETIME" DATE, 
	"EXPORT_FILE_NAME" VARCHAR2(2000 BYTE), 
	"EXPORT_START_DATETIME" DATE, 
	"EXPORT_COMPLETION_DATETIME" DATE, 
	"EXPORT_ROW_COUNT" NUMBER, 
	"MIGRATION_STATUS" VARCHAR2(20 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"EXPORT_START_TIMESTAMP" TIMESTAMP (3), 
	"EXTRACT_START_TIMESTAMP" TIMESTAMP (3), 
	"EXPORT_SECONDS" NUMBER(2,0), 
	"EXPORT_MINUTES" NUMBER(2,0), 
	"EXPORT_HOURS" NUMBER(2,0), 
	"EXPORT_END_TIMESTAMP" TIMESTAMP (3), 
	"VALIDATE_START_TIMESTAMP" TIMESTAMP (3), 
	"VALIDATE_END_TIMESTAMP" TIMESTAMP (3), 
	"VALIDATE_HOURS" NUMBER(2,0), 
	"VALIDATE_MINUTES" NUMBER(2,0), 
	"VALIDATE_SECONDS" NUMBER(2,0), 
	"VALIDATE_ROW_COUNT" NUMBER, 
	"EXTRACT_END_TIMESTAMP" TIMESTAMP (3), 
	"EXTRACT_HOURS" NUMBER(2,0), 
	"EXTRACT_MINUTES" NUMBER(2,0), 
	"EXTRACT_SECONDS" NUMBER(2,0), 
	"TRANSFORM_END_TIMESTAMP" TIMESTAMP (3), 
	"TRANSFORM_HOURS" NUMBER(2,0), 
	"TRANSFORM_MINUTES" NUMBER(2,0), 
	"TRANSFORM_SECONDS" NUMBER(2,0), 
	"TRANSFORM_START_TIMESTAMP" TIMESTAMP (3), 
	"ERROR_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_MIGRATION_DETAILS" TO "XXMX_READONLY";
