--------------------------------------------------------
--  Constraints for Table XXMX_SUPPLIER_SCOPE
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE" MODIFY ("VENDOR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE" MODIFY ("VENDOR_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
