--------------------------------------------------------
--  DDL for Table XXMX_FA_DEPRN_METHODS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FA_DEPRN_METHODS" 
   (	"METHOD_CODE" VARCHAR2(360 BYTE), 
	"LIFE_IN_MONTHS" VARCHAR2(360 BYTE), 
	"RATE_SOURCE_RULE" VARCHAR2(360 BYTE), 
	"DEPRN_BASIS_RULE" VARCHAR2(360 BYTE), 
	"NAME" VARCHAR2(360 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
