--------------------------------------------------------
--  Constraints for Table XXMX_CLOSED_AR_PRJ_DI_EVT
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_CLOSED_AR_PRJ_DI_EVT" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CLOSED_AR_PRJ_DI_EVT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CLOSED_AR_PRJ_DI_EVT" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CLOSED_AR_PRJ_DI_EVT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CLOSED_AR_PRJ_DI_EVT" MODIFY ("LINE_NUM" NOT NULL ENABLE);
