--------------------------------------------------------
--  DDL for Table XXMX_SIMPLE_TRANSFORMS_LEDGERBKP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_SIMPLE_TRANSFORMS_LEDGERBKP" 
   (	"APPLICATION_SUITE" VARCHAR2(5 BYTE), 
	"APPLICATION" VARCHAR2(5 BYTE), 
	"CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"SOURCE_VALUE" VARCHAR2(2000 BYTE), 
	"FUSION_VALUE" VARCHAR2(2000 BYTE), 
	"SOURCE_OPERATING_UNIT_NAME" VARCHAR2(240 BYTE), 
	"TRANSFORM_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
