--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_XFM_DRYRUN
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFM_DRYRUN" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFM_DRYRUN" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFM_DRYRUN" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFM_DRYRUN" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFM_DRYRUN" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
