--------------------------------------------------------
--  DDL for Table XXMX_GL_OPENING_BALANCE_V_BKP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_GL_OPENING_BALANCE_V_BKP" 
   (	"LEDGER_ID" NUMBER(15,0), 
	"PERIOD_NAME" VARCHAR2(15 BYTE), 
	"CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"CODE_COMBINATION_ID" NUMBER(15,0), 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
