--------------------------------------------------------
--  DDL for Table XXMX_HDL_FILE_TEMP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_HDL_FILE_TEMP" 
   (	"ID" NUMBER(10,0), 
	"FILE_NAME" VARCHAR2(40 BYTE), 
	"LINE_TYPE" VARCHAR2(40 BYTE), 
	"LINE_CONTENT" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_HDL_FILE_TEMP" TO "XXMX_READONLY";
