--------------------------------------------------------
--  DDL for Materialized View XXMX_HCM_EXPERSON_ASG_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG_MV" ("ASSIGNMENT_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "BUSINESS_GROUP_ID", "RECRUITER_ID", "GRADE_ID", "POSITION_ID", "JOB_ID", "ASSIGNMENT_STATUS_TYPE_ID", "PAYROLL_ID", "LOCATION_ID", "PERSON_REFERRED_BY_ID", "SUPERVISOR_ID", "SPECIAL_CEILING_STEP_ID", "PERSON_ID", "RECRUITMENT_ACTIVITY_ID", "SOURCE_ORGANIZATION_ID", "ORGANIZATION_ID", "PEOPLE_GROUP_ID", "SOFT_CODING_KEYFLEX_ID", "VACANCY_ID", "PAY_BASIS_ID", "ASSIGNMENT_SEQUENCE", "ASSIGNMENT_TYPE", "PRIMARY_FLAG", "APPLICATION_ID", "ASSIGNMENT_NUMBER", "CHANGE_REASON", "COMMENT_ID", "DATE_PROBATION_END", "DEFAULT_CODE_COMB_ID", "EMPLOYMENT_CATEGORY", "FREQUENCY", "INTERNAL_ADDRESS_LINE", "MANAGER_FLAG", "NORMAL_HOURS", "PERF_REVIEW_PERIOD", "PERF_REVIEW_PERIOD_FREQUENCY", "PERIOD_OF_SERVICE_ID", "PROBATION_PERIOD", "PROBATION_UNIT", "SAL_REVIEW_PERIOD", "SAL_REVIEW_PERIOD_FREQUENCY", "SET_OF_BOOKS_ID", "SOURCE_TYPE", "TIME_NORMAL_FINISH", "TIME_NORMAL_START", "BARGAINING_UNIT_CODE", "LABOUR_UNION_MEMBER_FLAG", "HOURLY_SALARIED_CODE", "CONTRACT_ID", "COLLECTIVE_AGREEMENT_ID", "CAGR_ID_FLEX_NUM", "CAGR_GRADE_DEF_ID", "ESTABLISHMENT_ID", "REQUEST_ID", "PROGRAM_APPLICATION_ID", "PROGRAM_ID", "PROGRAM_UPDATE_DATE", "ASS_ATTRIBUTE_CATEGORY", "ASS_ATTRIBUTE1", "ASS_ATTRIBUTE2", "ASS_ATTRIBUTE3", "ASS_ATTRIBUTE4", "ASS_ATTRIBUTE5", "ASS_ATTRIBUTE6", "ASS_ATTRIBUTE7", "ASS_ATTRIBUTE8", "ASS_ATTRIBUTE9", "ASS_ATTRIBUTE10", "ASS_ATTRIBUTE11", "ASS_ATTRIBUTE12", "ASS_ATTRIBUTE13", "ASS_ATTRIBUTE14", "ASS_ATTRIBUTE15", "ASS_ATTRIBUTE16", "ASS_ATTRIBUTE17", "ASS_ATTRIBUTE18", "ASS_ATTRIBUTE19", "ASS_ATTRIBUTE20", "ASS_ATTRIBUTE21", "ASS_ATTRIBUTE22", "ASS_ATTRIBUTE23", "ASS_ATTRIBUTE24", "ASS_ATTRIBUTE25", "ASS_ATTRIBUTE26", "ASS_ATTRIBUTE27", "ASS_ATTRIBUTE28", "ASS_ATTRIBUTE29", "ASS_ATTRIBUTE30", "LAST_UPDATE_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_LOGIN", "CREATED_BY", "CREATION_DATE", "TITLE", "OBJECT_VERSION_NUMBER", "NOTICE_PERIOD", "NOTICE_PERIOD_UOM", "EMPLOYEE_CATEGORY", "WORK_AT_HOME", "JOB_POST_SOURCE_NAME", "POSTING_CONTENT_ID", "PERIOD_OF_PLACEMENT_DATE_START", "VENDOR_ID", "VENDOR_EMPLOYEE_NUMBER", "VENDOR_ASSIGNMENT_NUMBER", "ASSIGNMENT_CATEGORY", "PROJECT_TITLE", "APPLICANT_RANK", "VENDOR_SITE_ID", "PO_HEADER_ID", "PO_LINE_ID", "PROJECTED_ASSIGNMENT_END", "GRADE_LADDER_PGM_ID", "SUPERVISOR_ASSIGNMENT_ID", "EMPLOYEE_NUMBER", "EXPENSE_CHECK_SEND_TO_ADDRESS", "NPW_NUMBER", "PERSON_TYPE_ID", "SYSTEM_PERSON_TYPE", "USER_PERSON_TYPE", "LAST_NAME", "FIRST_NAME", "INTERNAL_LOCATION", "PROJECTED_START_DATE", "CURRENT_EMPLOYEE_FLAG", "DATE_START", "FINAL_PROCESS_DATE", "PPOS_ID", "PAY_SYSTEM_STATUS", "PER_SYSTEM_STATUS")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS select * from xxmx_core.xxmx_hcm_experson_asg;

   COMMENT ON MATERIALIZED VIEW "XXMX_CORE"."XXMX_HCM_EXPERSON_ASG_MV"  IS 'snapshot table for snapshot XXMX_CORE.XXMX_HCM_EXPERSON_ASG_MV';
