--------------------------------------------------------
--  DDL for Sequence XXMX_STG_TABLE_IDS_S
--------------------------------------------------------

   CREATE SEQUENCE  "XXMX_CORE"."XXMX_STG_TABLE_IDS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 180 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "XXMX_CORE"."XXMX_STG_TABLE_IDS_S" TO "XXMX_STG";
  GRANT SELECT ON "XXMX_CORE"."XXMX_STG_TABLE_IDS_S" TO "XXMX_STG";
