--------------------------------------------------------
--  Constraints for Table XXMX_GL_OPENING_BALANCE_V
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_GL_OPENING_BALANCE_V" MODIFY ("LEDGER_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_OPENING_BALANCE_V" MODIFY ("PERIOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_OPENING_BALANCE_V" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_GL_OPENING_BALANCE_V" MODIFY ("CODE_COMBINATION_ID" NOT NULL ENABLE);
