--------------------------------------------------------
--  Constraints for Table XXMX_CITIZENSHIPS_XFM_13JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_13JUL23" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_13JUL23" MODIFY ("CITIZENSHIP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_CITIZENSHIPS_XFM_13JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
