--------------------------------------------------------
--  DDL for Table XXMX_MISSING_PROJ_TASKS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MISSING_PROJ_TASKS" 
   (	"PROJ_TASK" VARCHAR2(200 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(140 BYTE), 
	"TASK_NUMBER" VARCHAR2(140 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
