--------------------------------------------------------
--  Constraints for Table XXMX_PER_DISABILITY_XFM_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_24JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_24JUL23" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_24JUL23" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_DISABILITY_XFM_24JUL23" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
