--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_PRJ_TASK_IDS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_PRJ_TASK_IDS" 
   (	"PROJECT_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"SEGMENT1" VARCHAR2(100 BYTE), 
	"ELEMENT_NUMBER" VARCHAR2(100 BYTE), 
	"PROJECT_ID" NUMBER, 
	"PROJECT_ELEMENT_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1 BYTE), 
	"CHARGEABLE_FLAG" VARCHAR2(100 BYTE), 
	"TOP_TASK_ID" NUMBER, 
	"WBS_LEVEL" NUMBER, 
	"PARENT_TASK_ID" NUMBER, 
	"STANDALONE_FLAG" VARCHAR2(100 BYTE), 
	"PARENT_FLAG" VARCHAR2(100 BYTE), 
	"CHILD_FLAG" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
