--------------------------------------------------------
--  Constraints for Table XXMX_AP_INVOICES_ALL_TEMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("INVOICE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("SET_OF_BOOKS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("INVOICE_CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("PAYMENT_CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("PAYMENT_CROSS_RATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("GL_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("APPROVAL_READY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICES_ALL_TEMP_STG" MODIFY ("WFAPPROVAL_STATUS" NOT NULL ENABLE);
