--------------------------------------------------------
--  DDL for Table XXMX_MAPPING_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" 
   (	"MAPPING_ID" NUMBER, 
	"APPL_NAME" VARCHAR2(30 BYTE), 
	"MAPPING_NAME" VARCHAR2(150 BYTE), 
	"SEQ_NO" NUMBER, 
	"SOURCE_ORG_ID" NUMBER, 
	"SOURCE_OBJECT_ID" NUMBER, 
	"SOURCE_OBJECT_NAME" VARCHAR2(150 BYTE), 
	"SOURCE_COLUMN_NAME" VARCHAR2(150 BYTE), 
	"SOURCE_VALUE" VARCHAR2(250 BYTE), 
	"SOURCE_ID" VARCHAR2(30 BYTE), 
	"TARGET_ORG_ID" NUMBER, 
	"TARGET_OBJECT_ID" NUMBER, 
	"TARGET_OBJECT_NAME" VARCHAR2(150 BYTE), 
	"TARGET_COLUMN_NAME" VARCHAR2(150 BYTE), 
	"TARGET_OBJECT_WHERE_CLAUSE" VARCHAR2(1000 BYTE), 
	"MAPPING_TYPE" VARCHAR2(30 BYTE), 
	"MAPPING_DEFINATION" VARCHAR2(1000 BYTE), 
	"TARGET_VALUE" VARCHAR2(250 BYTE), 
	"TARGET_ID" VARCHAR2(30 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_MAPPING_DEFINITIONS" TO "XXMX_READONLY";
