--------------------------------------------------------
--  DDL for Table XXMX_DATA_FILE_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DATA_FILE_PARAMETERS" 
   (	"BUSINESS_ENTITY" VARCHAR2(200 BYTE), 
	"SUB_ENTITY" VARCHAR2(200 BYTE), 
	"FUSION_DATA_FILE" VARCHAR2(200 BYTE), 
	"PARAMETER_COUNT" NUMBER, 
	"PARAMETER_COL1" VARCHAR2(500 BYTE), 
	"PARAMETER_VAL1" VARCHAR2(500 BYTE), 
	"PARAMETER_COL2" VARCHAR2(500 BYTE), 
	"PARAMETER_VAL2" VARCHAR2(500 BYTE), 
	"PARAMETER_COL3" VARCHAR2(500 BYTE), 
	"PARAMETER_VAL3" VARCHAR2(500 BYTE), 
	"PARAMETER_COL4" VARCHAR2(500 BYTE), 
	"PARAMETER_VAL4" VARCHAR2(500 BYTE), 
	"PARAMETER_COL5" VARCHAR2(500 BYTE), 
	"PARAMETER_VAL5" VARCHAR2(500 BYTE), 
	"ENABLED_FLAG" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_DATA_FILE_PARAMETERS" TO "XXMX_READONLY";
