--------------------------------------------------------
--  DDL for Table XXMX_ZX_PARTY_CLASSIFIC_RPT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_ZX_PARTY_CLASSIFIC_RPT" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PARTY_TYPE_CODE" VARCHAR2(80 BYTE), 
	"PARTY_NUMBER" VARCHAR2(30 BYTE), 
	"PARTY_NAME" VARCHAR2(150 BYTE), 
	"CLASS_CATEGORY" VARCHAR2(30 BYTE), 
	"CLASSIFICATION_TYPE_CODE" VARCHAR2(30 BYTE), 
	"CLASSIFICATION_TYPE_NAME" VARCHAR2(150 BYTE), 
	"TAX_REGIME_CODE" VARCHAR2(30 BYTE), 
	"FISCAL_CLASSIFICATION_CODE" VARCHAR2(30 BYTE), 
	"CLASS_CODE" VARCHAR2(80 BYTE), 
	"CLASS_NAME" VARCHAR2(80 BYTE), 
	"EFFECTIVE_FROM" DATE, 
	"EFFECTIVE_TO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
