--------------------------------------------------------
--  Constraints for Table XXMX_RA_CUSTOMER_TRX_LINES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("CUSTOMER_TRX_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("CUSTOMER_TRX_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("SET_OF_BOOKS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("LINE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_LINES_ALL" MODIFY ("EXTENDED_AMOUNT" NOT NULL ENABLE);
