--------------------------------------------------------
--  DDL for Sequence XXMX_STG_TABLE_COLUMN_IDS_S
--------------------------------------------------------

   CREATE SEQUENCE  "XXMX_CORE"."XXMX_STG_TABLE_COLUMN_IDS_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15174 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMN_IDS_S" TO "XXMX_STG";
  GRANT ALTER ON "XXMX_CORE"."XXMX_STG_TABLE_COLUMN_IDS_S" TO "XXMX_STG";
