--------------------------------------------------------
--  Constraints for Table XXMX_PPM_TEMPLATE_TASK_FLAGS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS" MODIFY ("PROJECT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
