--------------------------------------------------------
--  DDL for Table XXMX_FUSION_LOCKBOX_DETAILS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_FUSION_LOCKBOX_DETAILS" 
   (	"BU_NAME" VARCHAR2(30 BYTE), 
	"ORG_ID" NUMBER, 
	"RECEIPT_METHOD" VARCHAR2(30 BYTE), 
	"BANK_ORIGINATION_NUMBER" VARCHAR2(100 BYTE), 
	"LOCKBOX_NUMBER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
