--------------------------------------------------------
--  Constraints for Table XXMX_RA_CUSTOMER_TRX_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("CUSTOMER_TRX_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("TRX_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("CUST_TRX_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("TRX_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("SET_OF_BOOKS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("COMPLETE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_RA_CUSTOMER_TRX_ALL" MODIFY ("CREATED_FROM" NOT NULL ENABLE);
