--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASSIGNMENTS_M_XFMA
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_XFMA" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_XFMA" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_XFMA" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_XFMA" MODIFY ("PRIMARY_WORK_TERMS_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASSIGNMENTS_M_XFMA" MODIFY ("PRIMARY_ASSIGNMENT_FLAG" NOT NULL ENABLE);
