--------------------------------------------------------
--  Constraints for Table XXMX_PA_TASKS
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("TOP_TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("WBS_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("READY_TO_BILL_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("READY_TO_DISTRIBUTE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("CARRYING_OUT_ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("ALLOW_CROSS_CHARGE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("CC_PROCESS_LABOR_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_TASKS" MODIFY ("CC_PROCESS_NL_FLAG" NOT NULL ENABLE);
