--------------------------------------------------------
--  Constraints for Table XXMX_PA_COST_DISTRIBUTION_LINES_ALL
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("EXPENDITURE_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("LINE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("TRANSFER_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("BILLABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_COST_DISTRIBUTION_LINES_ALL" MODIFY ("LINE_TYPE" NOT NULL ENABLE);
