--------------------------------------------------------
--  DDL for Table XXMX_LICENSE_FEE_TEMP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_LICENSE_FEE_TEMP" 
   (	"INVOICE_ID" NUMBER(38,0), 
	"INVOICE_NUM" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
