--------------------------------------------------------
--  Constraints for Table XXMX_OPEN_AR_PRJ_EVT
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_OPEN_AR_PRJ_EVT" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_OPEN_AR_PRJ_EVT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_OPEN_AR_PRJ_EVT" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_OPEN_AR_PRJ_EVT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_OPEN_AR_PRJ_EVT" MODIFY ("LINE_NUM" NOT NULL ENABLE);
