--------------------------------------------------------
--  DDL for Table XXMX_RECURRING_ELEMTS_XL_DATA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_RECURRING_ELEMTS_XL_DATA" 
   (	"ELEM_ENTRY_ID_CNT" NUMBER, 
	"ELEMENT_NAME" VARCHAR2(120 BYTE), 
	"MIGRATE" VARCHAR2(5 BYTE), 
	"COMMENTS" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_RECURRING_ELEMTS_XL_DATA" TO "XXMX_READONLY";
