--------------------------------------------------------
--  DDL for Table XXMX_CANDIDATE_NAME_MAP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CANDIDATE_NAME_MAP" 
   (	"CAND_FIRST_NAME" VARCHAR2(3000 BYTE), 
	"CAND_LAST_NAME" VARCHAR2(3000 BYTE), 
	"CAND_EMAIL" VARCHAR2(3000 BYTE), 
	"CAND_ENCRYPTEDID" VARCHAR2(3000 BYTE), 
	"CAND_ADDRESS" VARCHAR2(3000 BYTE), 
	"CAND_POSTALCODE" VARCHAR2(3000 BYTE), 
	"CAND_CITY" VARCHAR2(3000 BYTE), 
	"CAND_SUBMITTEDDATE" VARCHAR2(1000 BYTE), 
	"REQUISITIONID" VARCHAR2(3000 BYTE), 
	"CAND_COUNTRY" VARCHAR2(3000 BYTE), 
	"APPL_SOURCE_TYPE" VARCHAR2(3000 BYTE), 
	"APPL_SOURCE" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
