--------------------------------------------------------
--  DDL for Table XXMX_TALENT_CORRECT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_TALENT_CORRECT" 
   (	"EMPLOYEE_NUMBER" VARCHAR2(100 BYTE), 
	"DATEFROM" VARCHAR2(200 BYTE), 
	"DATETO" VARCHAR2(100 BYTE), 
	"OVERALL_RATING" VARCHAR2(100 BYTE), 
	"YEAR_VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
