--------------------------------------------------------
--  Constraints for Table XXMX_AR_CASH_RECEIPTS_OLD
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_OLD" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_OLD" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AR_CASH_RECEIPTS_OLD" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
