--------------------------------------------------------
--  DDL for Table XXMX_OBJECT_SUMMARY
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_OBJECT_SUMMARY" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"GATE" NUMBER, 
	"TABLE_NAME" VARCHAR2(60 BYTE), 
	"BUSINESS_ENTITY" VARCHAR2(30 BYTE), 
	"SUB_ENTITY" VARCHAR2(30 BYTE), 
	"RECORD_COUNT" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
