--------------------------------------------------------
--  Constraints for Table XXMX_PA_EVENTS_01JAN2017
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("TASK_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("EVENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("BILL_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("REVENUE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("REVENUE_DISTRIBUTED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PA_EVENTS_01JAN2017" MODIFY ("EVENT_ID" NOT NULL ENABLE);
