--------------------------------------------------------
--  Constraints for Table XXMX_EXPENDITURE_ORG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_EXPENDITURE_ORG" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_EXPENDITURE_ORG" ADD CONSTRAINT "XXMX_EXPENDITURE_ORG_PK" PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
