--------------------------------------------------------
--  DDL for Table XXMX_ESS_REQUEST_TEMP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_ESS_REQUEST_TEMP" 
   (	"REQUESTID" NUMBER(38,0), 
	"USERNAME" VARCHAR2(26 BYTE), 
	"JOBID" NUMBER(38,0), 
	"JOBNAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
