--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_STG_SIT
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_SIT" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_SIT" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_STG_SIT" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
