--------------------------------------------------------
--  Constraints for Table XXMX_AP_INVOICE_LINES_ALL_TEMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("LINE_TYPE_LOOKUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("ACCOUNTING_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("SET_OF_BOOKS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("WFAPPROVAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_LINES_ALL_TEMP_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
