--------------------------------------------------------
--  DDL for Table XXMX_IREC_HCM_CITY_GEOGRAPHY_ID
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_IREC_HCM_CITY_GEOGRAPHY_ID" 
   (	"COUNTRY" VARCHAR2(100 BYTE), 
	"REGION1" VARCHAR2(100 BYTE), 
	"REGION2" VARCHAR2(100 BYTE), 
	"REGION3" VARCHAR2(100 BYTE), 
	"GEOGRAPHY_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
