--------------------------------------------------------
--  Constraints for Table XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("ACCOUNTING_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("ASSETS_ADDITION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("ASSETS_TRACKING_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("DISTRIBUTION_LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("DIST_CODE_COMBINATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("LINE_TYPE_LOOKUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("PERIOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("SET_OF_BOOKS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_INVOICE_DISTRIBUTIONS_ALL_TEMP_STG" MODIFY ("INVOICE_DISTRIBUTION_ID" NOT NULL ENABLE);
