--------------------------------------------------------
--  DDL for Table XXMX_EBS_EVT_MAY_FIX
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_EBS_EVT_MAY_FIX" 
   (	"PROJECT" VARCHAR2(10 BYTE), 
	"TASK" VARCHAR2(30 BYTE), 
	"EVENT_NUMBER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
