--------------------------------------------------------
--  DDL for Table XXMX_LICENSE_FEE_APINV
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_LICENSE_FEE_APINV" 
   (	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"VENDOR_NAME" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"INVOICE_AMOUNT" NUMBER, 
	"AMOUNT_PAID" NUMBER, 
	"PAYMENT_STATUS_FLAG" VARCHAR2(1 BYTE), 
	"COST_TYPE" VARCHAR2(8 BYTE), 
	"AR_INVOICE_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_LICENSE_FEE_APINV" TO "XXMX_READONLY";
