--------------------------------------------------------
--  DDL for View XXMX_MAP_TCA_XFM_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_MAP_TCA_XFM_V" ("TABLE_NAME", "MIGRATION_SET_ID", "XFM_TABLE_COUNT") AS 
  SELECT 'XXMX_HZ_PARTIES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_PARTIES_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_PARTY_SITES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_PARTY_SITES_XFM  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_PARTY_SITE_USES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_PARTY_SITE_USES_XFM  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCOUNTS_XFM'  TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_CUST_ACCOUNTS_XFM  GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCT_SITES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_CUST_ACCT_SITES_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_SITE_USES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_CUST_SITE_USES_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_LOCATIONS_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_LOCATIONS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_PROFILES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_CUST_PROFILES_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CONTACT_POINTS_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_CONTACT_POINTS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_CUST_ACCT_CONTACTS_XFM' TABLE_NAME,MIGRATION_SET_ID,NVL(COUNT(*),0) XFM_TABLE_COUNT FROM XXMX_HZ_CUST_ACCT_CONTACTS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ORG_CONTACTS_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_ORG_CONTACTS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ORG_CONTACT_ROLES_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_ORG_CONTACT_ROLES_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_RELATIONSHIPS_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_RELATIONSHIPS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_HZ_ROLE_RESPS_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_HZ_ROLE_RESPS_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_TAX_PROFILE_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_ZX_TAX_PROFILE_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_PARTY_CLASSIFIC_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_ZX_PARTY_CLASSIFIC_XFM GROUP BY MIGRATION_SET_ID
UNION ALL
SELECT 'XXMX_ZX_TAX_REGISTRATION_XFM' TABLE_NAME,MIGRATION_SET_ID,COUNT(*) XFM_TABLE_COUNT FROM XXMX_ZX_TAX_REGISTRATION_XFM GROUP BY MIGRATION_SET_ID
;
