--------------------------------------------------------
--  Constraints for Table XXMX_PPM_CLOUD_INVOICES
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_CLOUD_INVOICES" ADD PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE"  ENABLE;
