--------------------------------------------------------
--  DDL for Table XXMX_GL_ACCOUNT_CODE_COMBINATIONSBKP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_GL_ACCOUNT_CODE_COMBINATIONSBKP" 
   (	"S_NO" NUMBER, 
	"XFM_TABLE" VARCHAR2(100 BYTE), 
	"GL_ACCCOUNT_DESC" VARCHAR2(100 BYTE), 
	"SEGMENT1" VARCHAR2(100 BYTE), 
	"SEGMENT2" VARCHAR2(100 BYTE), 
	"SEGMENT3" VARCHAR2(100 BYTE), 
	"SEGMENT4" VARCHAR2(100 BYTE), 
	"SEGMENT5" VARCHAR2(100 BYTE), 
	"SEGMENT6" VARCHAR2(100 BYTE), 
	"SEGMENT7" VARCHAR2(100 BYTE), 
	"SEGMENT8" VARCHAR2(100 BYTE), 
	"SEGMENT9" VARCHAR2(100 BYTE), 
	"SEGMENT10" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"ERROR_CODE" VARCHAR2(100 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"FUTURE1" VARCHAR2(100 BYTE), 
	"FUTURE2" VARCHAR2(100 BYTE), 
	"FUTURE3" VARCHAR2(100 BYTE), 
	"LEDGER_NAME" VARCHAR2(100 BYTE), 
	"XFM_TABLE_COLUMN" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
