--------------------------------------------------------
--  Constraints for Table XXMX_PER_RELIGION_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_UATBKUP" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_RELIGION_XFM_UATBKUP" MODIFY ("RELIGION" NOT NULL ENABLE);
