--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_XFMA
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFMA" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFMA" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFMA" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFMA" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_XFMA" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
