--------------------------------------------------------
--  DDL for View XXMX_STG_COUNTS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_STG_COUNTS_V" ("MIGRATION_SET_ID", "STG_ROW_COUNT", "STG_TABLE_NAME") AS 
  (
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_LOCATIONS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_LOCATIONS_STG LOCATIONS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ORG_UNITS_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ORG_UNITS_F_STG ORG_UNITS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ORG_UNITS_F_TL_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ORG_UNITS_F_TL_STG ORG_UNITS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ADDR_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ADDR_F_STG ADDR_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_LOC_ADDR_USG_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_LOC_ADDR_USG_F_STG ADDR_USG_F_ group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_LOC_DETAILS_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_LOC_DETAILS_F_STG LOC_DETAILS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_LOC_DETAILS_TL_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_LOC_DETAILS_TL_STG LOC_DETAILS_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_GRADES_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_GRADES_F_STG GRADES_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_GRADES_F_TL_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_GRADES_F_TL_STG GRADES_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_POSITIONS_F_TL_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_POSITIONS_F_TL_STG POSITIONS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_POSITIONS_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_POSITIONS_F_STG POSITIONS_F group by migration_set_id
UNION ALL
--SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_MAP_LOOKUPS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_MAP_LOOKUPS_STG MAP_LOOKUPS group by migration_set_id
--UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_JOBS_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_JOBS_F_STG JOBS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_JOBS_F_TL_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_JOBS_F_TL_STG JOBS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_NID_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_NID_F_STG PER_NID_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_RELIGION_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_RELIGION_STG PER_RELIGION group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_SENIORITYDT_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_SENIORITYDT_STG PER_SENIORITYDT group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PERSONS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_PERSONS_STG PER_PERSONS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_CONTACTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_CONTACTS_STG PER_CONTACTS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ADDR_USG_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_ADDR_USG_F_STG PER_ADDR_USG_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_NAMES_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_NAMES_F_STG PER_NAMES_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_LEG_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_LEG_F_STG PER_LEG_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ETHNICITIES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_ETHNICITIES_STG PER_ETHNICITIES group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PHONES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_PHONES_STG PER_PHONES group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_CITIZENSHIPS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_CITIZENSHIPS_STG CITIZENSHIPS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_EMAIL_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_EMAIL_F_STG PER_EMAIL_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PEOPLE_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_PEOPLE_F_STG PER_PEOPLE_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_POS_WR_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_POS_WR_STG PER_POS_WR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ASSIGNMENTS_M_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_ASSIGNMENTS_M_STG PER_ASSIGNMENTS_M group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ORG_UNIT_CLASS_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ORG_UNIT_CLASS_F_STG ORG_UNIT_CLASS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ORG_INFO_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ORG_INFO_F_STG ORG_INFO_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ASG_SUP_F_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PER_ASG_SUP_F_STG PER_ASG_SUP_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ASG_PAYROLL_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_ASG_PAYROLL_STG  ASG_PAYROLL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ADDRESS_F_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_ADDRESS_F_STG  PER_ADDRESS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PASSPORT_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_PASSPORT_STG  PER_PASSPORT group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PAY_METHOD_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_PAY_METHOD_STG  PER_PAY_METHOD group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ASG_SALARY_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_ASG_SALARY_STG  PER_ASG_SALARY group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ASG_WORKMSURE_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_ASG_WORKMSURE_STG  ASG_WORKMSURE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ASG_GRADESTEP_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_ASG_GRADESTEP_STG  ASG_GRADESTEP group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_THIRD_ORG_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_THIRD_ORG_STG  THIRD_ORG group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_THIRD_ADDR_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_THIRD_ADDR_STG  THIRD_ADDR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_THIRD_PAYMTHD_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_THIRD_PAYMTHD_STG  THIRD_PAYMTHD group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_CONTACT_REL_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_CONTACT_REL_STG PER_CONTACT_REL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_CONTACT_ADDR_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_CONTACT_ADDR_STG PER_CONTACT_ADDR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_CONTACT_PHONE_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_CONTACT_PHONE_STG PER_CONTACT_PHONE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_EXT_BANK_ACC_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_EXT_BANK_ACC_STG EXT_BANK_ACC group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_ABSENCE_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_ABSENCE_STG PERSON_ABSENCE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_DISABILITY_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_DISABILITY_STG PERSON_DISABILITY group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_CARRY_OVER_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_CARRY_OVER_STG CARRY_OVER group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PAY_ELE_ENTRY_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PAY_ELE_ENTRY_STG ELEMENT_ENTRIES group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_TALENT_PROFILE_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_TALENT_PROFILE_STG TALENT_PROFILE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PER_PROFILE_ITEM_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_PER_PROFILE_ITEM_STG PROFILE_ITEM group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_OLM_CLASS_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_OLM_CLASS_STG OLC_OFFERING_CLASS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_OLM_COURSE_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_OLM_COURSE_STG OLC_COURSE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_OLM_CERTIFICATION_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_OLM_CERTIFICATION_STG OLC_CERTIFICATION group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_LEARNER_RECORDS_STG' STG_TABLE_NAME FROM  XXMX_STG.XXMX_LEARNER_RECORDS_STG OLC_LEARNER_RECORDS group by migration_set_id
union all
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_ACCOUNTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_ACCOUNTS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_ROLE_RESPS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_ROLE_RESPS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_SITES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_ACCT_SITES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_PROFILES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_PROFILES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_PARTIES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_PARTIES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_ORG_CONTACT_ROLES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_ORG_CONTACT_ROLES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_LOCATIONS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_LOCATIONS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_ORG_CONTACTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_ORG_CONTACTS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_SITE_USES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_SITE_USES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_PARTY_CLASSIFS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_PARTY_CLASSIFS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_PARTY_SITES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_PARTY_SITES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_RELATIONSHIPS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_RELATIONSHIPS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_RELATE_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_ACCT_RELATE_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CONTACT_POINTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CONTACT_POINTS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_PARTY_SITE_USES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_PARTY_SITE_USES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_CONTACTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_CUST_ACCT_CONTACTS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_HZ_PERSON_LANGUAGE_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_HZ_PERSON_LANGUAGE_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ZX_PARTY_CLASSIFIC_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ZX_PARTY_CLASSIFIC_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ZX_TAX_PROFILE_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ZX_TAX_PROFILE_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_ZX_TAX_REGISTRATION_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_ZX_TAX_REGISTRATION_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PROJECTS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PROJECTS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_CLASS_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PRJ_CLASS_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_TEAM_MEM_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PRJ_TEAM_MEM_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_RATE_OVERRIDES_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_RATE_OVERRIDES_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_LBRCOST_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PRJ_LBRCOST_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_MISCCOST_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PRJ_MISCCOST_STG group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_BILLEVENT_STG' STG_TABLE_NAME FROM XXMX_STG.XXMX_PPM_PRJ_BILLEVENT_STG group by migration_set_id
)
;
