--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_STG_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_STG_24JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_STG_24JUL23" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_STG_24JUL23" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_STG_24JUL23" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ABSENCE_STG_24JUL23" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
