--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_XFM_250120
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_250120" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_250120" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_250120" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
