--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACTS_STG_24OCT23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACTS_STG_24OCT23" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACTS_STG_24OCT23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_CONTACTS_STG_24OCT23" MODIFY ("CNTPERSONNUMBER" NOT NULL ENABLE);
