--------------------------------------------------------
--  Constraints for Table XXMX_BUSINESS_RELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_BUSINESS_RELATIONSHIP" MODIFY ("LOOKUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_BUSINESS_RELATIONSHIP" ADD CONSTRAINT "XXMX_BUSINESS_RELATIONSHIP_PK" PRIMARY KEY ("LOOKUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
