--------------------------------------------------------
--  Constraints for Table XXMX_PER_SENIORITYDT_STG_24JUL23
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_STG_24JUL23" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_STG_24JUL23" MODIFY ("SENIORITYDATECODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_STG_24JUL23" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_STG_24JUL23" MODIFY ("MANUALADJUSTMENTDAYS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_SENIORITYDT_STG_24JUL23" MODIFY ("DATESTART" NOT NULL ENABLE);
