--------------------------------------------------------
--  Constraints for Table XXMX_PPM_LICFEE_UNPAID_INV
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("INVOICE_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("SUPPLIER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("PROJECT_NUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_LICFEE_UNPAID_INV" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
