--------------------------------------------------------
--  DDL for View XXMX_XFM_COUNTS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMX_CORE"."XXMX_XFM_COUNTS_V" ("MIGRATION_SET_ID", "XFM_ROW_COUNT", "XFM_TABLE_NAME") AS 
  (
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_LOCATIONS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_LOCATIONS_XFM LOCATIONS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ORG_UNITS_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ORG_UNITS_F_XFM ORG_UNITS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ORG_UNITS_F_TL_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ORG_UNITS_F_TL_XFM ORG_UNITS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ADDR_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ADDR_F_XFM ADDR_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_LOC_ADDR_USG_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_LOC_ADDR_USG_F_XFM ADDR_USG_F_ group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_LOC_DETAILS_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_LOC_DETAILS_F_XFM LOC_DETAILS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_LOC_DETAILS_TL_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_LOC_DETAILS_TL_XFM LOC_DETAILS_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_GRADES_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_GRADES_F_XFM GRADES_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_GRADES_F_TL_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_GRADES_F_TL_XFM GRADES_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_POSITIONS_F_TL_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_POSITIONS_F_TL_XFM POSITIONS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_POSITIONS_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_POSITIONS_F_XFM POSITIONS_F group by migration_set_id
UNION ALL
--SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_MAP_LOOKUPS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_MAP_LOOKUPS_XFM MAP_LOOKUPS group by migration_set_id
--UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_JOBS_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_JOBS_F_XFM JOBS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_JOBS_F_TL_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_JOBS_F_TL_XFM JOBS_F_TL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_NID_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_NID_F_XFM PER_NID_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_RELIGION_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_RELIGION_XFM PER_RELIGION group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_SENIORITYDT_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_SENIORITYDT_XFM PER_SENIORITYDT group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PERSONS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_PERSONS_XFM PER_PERSONS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_CONTACTS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_CONTACTS_XFM PER_CONTACTS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ADDR_USG_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_ADDR_USG_F_XFM PER_ADDR_USG_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_NAMES_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_NAMES_F_XFM PER_NAMES_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_LEG_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_LEG_F_XFM PER_LEG_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ETHNICITIES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_ETHNICITIES_XFM PER_ETHNICITIES group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PHONES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_PHONES_XFM PER_PHONES group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_CITIZENSHIPS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_CITIZENSHIPS_XFM CITIZENSHIPS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_EMAIL_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_EMAIL_F_XFM PER_EMAIL_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PEOPLE_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_PEOPLE_F_XFM PER_PEOPLE_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_POS_WR_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_POS_WR_XFM PER_POS_WR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ASSIGNMENTS_M_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_ASSIGNMENTS_M_XFM PER_ASSIGNMENTS_M group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ORG_UNIT_CLASS_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ORG_UNIT_CLASS_F_XFM ORG_UNIT_CLASS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ORG_INFO_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ORG_INFO_F_XFM ORG_INFO_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ASG_SUP_F_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_PER_ASG_SUP_F_XFM PER_ASG_SUP_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ASG_PAYROLL_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_ASG_PAYROLL_XFM  ASG_PAYROLL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ADDRESS_F_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_ADDRESS_F_XFM  PER_ADDRESS_F group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PASSPORT_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_PASSPORT_XFM  PER_PASSPORT group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PAY_METHOD_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_PAY_METHOD_XFM  PER_PAY_METHOD group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ASG_SALARY_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_ASG_SALARY_XFM  PER_ASG_SALARY group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ASG_WORKMSURE_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_ASG_WORKMSURE_XFM  ASG_WORKMSURE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ASG_GRADESTEP_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_ASG_GRADESTEP_XFM  ASG_GRADESTEP group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_THIRD_ORG_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_THIRD_ORG_XFM  THIRD_ORG group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_THIRD_ADDR_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_THIRD_ADDR_XFM  THIRD_ADDR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_THIRD_PAYMTHD_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_THIRD_PAYMTHD_XFM  THIRD_PAYMTHD group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_CONTACT_REL_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_CONTACT_REL_XFM PER_CONTACT_REL group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_CONTACT_ADDR_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_CONTACT_ADDR_XFM PER_CONTACT_ADDR group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_CONTACT_PHONE_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_CONTACT_PHONE_XFM PER_CONTACT_PHONE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_EXT_BANK_ACC_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_EXT_BANK_ACC_XFM EXT_BANK_ACC group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_ABSENCE_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_ABSENCE_XFM PERSON_ABSENCE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_DISABILITY_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_DISABILITY_XFM PERSON_DISABILITY group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_CARRY_OVER_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_CARRY_OVER_XFM CARRY_OVER group by migration_set_id
UNION ALL
--SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PAY_ELE_ENTRY_XFM' XFM_TABLE_NAME FROM  XXMX_PAY_ELE_ENTRY_XFM ELEMENT_ENTRIES group by migration_set_id
--UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_TALENT_PROFILE_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_TALENT_PROFILE_XFM TALENT_PROFILE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_PER_PROFILE_ITEM_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_PER_PROFILE_ITEM_XFM PROFILE_ITEM group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_OLM_CLASS_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_OLM_CLASS_XFM OLC_OFFERING_CLASS group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_OLM_COURSE_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_OLM_COURSE_XFM OLC_COURSE group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_OLM_CERTIFICATION_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_OLM_CERTIFICATION_XFM OLC_CERTIFICATION group by migration_set_id
UNION ALL
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_LEARNER_RECORDS_XFM' XFM_TABLE_NAME FROM  XXMX_XFM.XXMX_LEARNER_RECORDS_XFM OLC_LEARNER_RECORDS group by migration_set_id
union all
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_ACCOUNTS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_ACCOUNTS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_ROLE_RESPS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_ROLE_RESPS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_SITES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_ACCT_SITES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_PROFILES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_PROFILES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_PARTIES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_PARTIES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_ORG_CONTACT_ROLES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_ORG_CONTACT_ROLES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_LOCATIONS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_LOCATIONS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_ORG_CONTACTS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_ORG_CONTACTS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_SITE_USES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_SITE_USES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_PARTY_CLASSIFS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_PARTY_CLASSIFS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_PARTY_SITES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_PARTY_SITES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_RELATIONSHIPS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_RELATIONSHIPS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_RELATE_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_ACCT_RELATE_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CONTACT_POINTS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CONTACT_POINTS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_PARTY_SITE_USES_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_PARTY_SITE_USES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_CUST_ACCT_CONTACTS_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_CUST_ACCT_CONTACTS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_HZ_PERSON_LANGUAGE_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_HZ_PERSON_LANGUAGE_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ZX_PARTY_CLASSIFIC_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ZX_PARTY_CLASSIFIC_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ZX_TAX_PROFILE_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ZX_TAX_PROFILE_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) XFM_ROW_COUNT, 'XXMX_ZX_TAX_REGISTRATION_XFM' XFM_TABLE_NAME FROM XXMX_XFM.XXMX_ZX_TAX_REGISTRATION_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PROJECTS_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PROJECTS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_CLASS_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PRJ_CLASS_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_TEAM_MEM_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PRJ_TEAM_MEM_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_RATE_OVERRIDES_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_RATE_OVERRIDES_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_LBRCOST_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PRJ_LBRCOST_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_MISCCOST_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PRJ_MISCCOST_XFM group by migration_set_id
union
SELECT migration_set_id  MIGRATION_SET_ID , count(*) STG_ROW_COUNT, 'XXMX_PPM_PRJ_BILLEVENT_XFM' STG_TABLE_NAME FROM XXMX_XFM.XXMX_PPM_PRJ_BILLEVENT_XFM group by migration_set_id
)
;
