--------------------------------------------------------
--  DDL for Table XXMX_JOBVITE_DEPT_ORG_CODES_BKUP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_JOBVITE_DEPT_ORG_CODES_BKUP" 
   (	"JOBVITE_DEPT_NAME" VARCHAR2(250 BYTE), 
	"FUSION_DEPT_NAME" VARCHAR2(250 BYTE), 
	"FUSION_DEPT_ID" VARCHAR2(80 BYTE), 
	"FUSION_ORG_CODE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
