--------------------------------------------------------
--  Constraints for Table XXMX_PPM_TEMPLATE_TASK_FLAGS_BKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_BKUP" MODIFY ("PROJECT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_BKUP" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PPM_TEMPLATE_TASK_FLAGS_BKUP" MODIFY ("TASK_NUMBER" NOT NULL ENABLE);
