--------------------------------------------------------
--  Constraints for Table XXMX_SUPPLIER_SCOPE_310723_BKP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_310723_BKP" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_310723_BKP" MODIFY ("VENDOR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_310723_BKP" MODIFY ("OPERATING_UNIT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_310723_BKP" MODIFY ("VENDOR_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_SUPPLIER_SCOPE_310723_BKP" MODIFY ("VENDOR_SITE_CODE" NOT NULL ENABLE);
