--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_LOADED_PERSON_DATA
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_LOADED_PERSON_DATA" 
   (	"PERSON_NUMBER" VARCHAR2(240 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(240 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(240 BYTE), 
	"LEGISLATION_CODE" VARCHAR2(240 BYTE), 
	"NAME_TYPE" VARCHAR2(240 BYTE), 
	"FIRST_NAME" VARCHAR2(240 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(240 BYTE), 
	"LAST_NAME" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
