--------------------------------------------------------
--  DDL for Index XXMX_GL_SOURCE_STRUCT_SEGS_U2
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGS_U2" ON "XXMX_CORE"."XXMX_GL_SOURCE_STRUCT_SEGMENTS" ("SOURCE_LEDGER_NAME", "SOURCE_SEGMENT_COLUMN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
