--------------------------------------------------------
--  DDL for Table XXMX_CLOUD_POSITIONS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_CLOUD_POSITIONS" 
   (	"PERSON_NUMBER" VARCHAR2(250 BYTE), 
	"EFFECTIVE_START_DATE" VARCHAR2(250 BYTE), 
	"EFFECTIVE_END_DATE" VARCHAR2(250 BYTE), 
	"JOB_NAME" VARCHAR2(250 BYTE), 
	"POSITION_NAME" VARCHAR2(250 BYTE), 
	"POSITION_CODE" VARCHAR2(250 BYTE), 
	"FROM_SET_NAME" VARCHAR2(250 BYTE), 
	"MAP_SET_NAME" VARCHAR2(250 BYTE), 
	"TO_SET_NAME" VARCHAR2(250 BYTE), 
	"FROM_JOB_NAME" VARCHAR2(250 BYTE), 
	"MAP_JOB_NAME" VARCHAR2(250 BYTE), 
	"TO_JOB_NAME" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
