--------------------------------------------------------
--  DDL for Materialized View XXMX_CITCO_OPEN_AR_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXMX_CORE"."XXMX_CITCO_OPEN_AR_MV" ("CUSTOMER_TRX_ID", "INVOICE_ID", "DRAFT_NUMBER", "BILL_THROUGH_DATE", "INVOICE_DATE", "INVOICE_CLASS", "INVOICE_CURRENCY", "APPROVED_DATE", "APPROVED_BY_PERSON", "CREATION_DATE", "CREATED_BY_USER", "CREATED_BY_PERSON", "RELEASED_DATE", "RELEASED_BY_PERSON", "INVOICE_AR_NUMBER", "CREDITED_DRAFT_INVOICE", "CREDITED_AR_NUMBER", "STATUS", "GL_DATE_CLOSED", "COLLECTION_DAYS", "DUE_DATE", "PRINTED")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT 
         * 
    FROM XXMX_CITCO_OPEN_AR_V;

   COMMENT ON MATERIALIZED VIEW "XXMX_CORE"."XXMX_CITCO_OPEN_AR_MV"  IS 'snapshot table for snapshot XXMX_CORE.XXMX_CITCO_OPEN_AR_MV';
