--------------------------------------------------------
--  DDL for Table XXMX_PPM_CONT_PROJ_INT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CONT_PROJ_INT" 
   (	"PROJECT_ID" VARCHAR2(250 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(250 BYTE), 
	"PROJECT_NAME" VARCHAR2(250 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"START_DATE" VARCHAR2(250 BYTE), 
	"COMPLETION_DATE" VARCHAR2(250 BYTE), 
	"PROJECT_LONG_NAME" VARCHAR2(250 BYTE), 
	"PROJECT_TYPE" VARCHAR2(250 BYTE), 
	"PROJECT_STATUS_CODE" VARCHAR2(250 BYTE), 
	"PROJECT_CURRENCY_CODE" VARCHAR2(250 BYTE), 
	"PROJFUNC_CURRENCY_CODE" VARCHAR2(250 BYTE), 
	"MANAGER" VARCHAR2(250 BYTE), 
	"ORG_NAME" VARCHAR2(250 BYTE), 
	"UNIT_NAME" VARCHAR2(250 BYTE), 
	"LEGAL_ENTITY_NAME" VARCHAR2(250 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(250 BYTE), 
	"CUST_ACCT_NUM" VARCHAR2(30 BYTE), 
	"PAYMENT_TERM_NAME" VARCHAR2(50 BYTE), 
	"LEGAL_ENTITY_ID" VARCHAR2(250 BYTE), 
	"UNIT_ID" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
