--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_XFMA
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFMA" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFMA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFMA" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_ASG_SALARY_XFMA" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
