--------------------------------------------------------
--  DDL for Table XXMX_PER_GOAL_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PER_GOAL_STG" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"SOURCESYSTEMOWNER" VARCHAR2(50 BYTE), 
	"METADATA" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(500 BYTE), 
	"DETAIL" VARCHAR2(4000 BYTE), 
	"START_DATE" DATE, 
	"TARGET_DATE" DATE, 
	"PERSONNUMBER" VARCHAR2(30 BYTE), 
	"ASSIGNMENT_NUMBER" VARCHAR2(30 BYTE), 
	"SCORECARD_ID" NUMBER, 
	"ASSIGNED_BY_PERSON_NUM" VARCHAR2(30 BYTE), 
	"PRIVATE_FLAG" VARCHAR2(5 BYTE), 
	"GOAL_SOURCE_CODE" VARCHAR2(5 BYTE), 
	"STATUS_CODE" VARCHAR2(20 BYTE), 
	"PRIORITY_CODE" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"WEIGHTING_PERCENT" NUMBER, 
	"SUCCESS_CRITERIA" VARCHAR2(4000 BYTE), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE), 
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
