--------------------------------------------------------
--  Constraints for Table XXMX_AP_SUPPLIERS_TEMP_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("VENDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("SEGMENT1" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("SUMMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("ENABLED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_AP_SUPPLIERS_TEMP_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
