--------------------------------------------------------
--  DDL for Table XXMX_DM_OIC_READ_LOG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_DM_OIC_READ_LOG" 
   (	"INSTANCE_ID" NUMBER, 
	"USER_NAME" VARCHAR2(250 BYTE), 
	"INTEGRATION_NAME" VARCHAR2(250 BYTE), 
	"INTEGRATION_IDENTIFIER" VARCHAR2(250 BYTE), 
	"INTEGRATION_VERSION" VARCHAR2(250 BYTE), 
	"START_TIME" VARCHAR2(250 BYTE), 
	"END_TIME" VARCHAR2(250 BYTE), 
	"DURATION_MINS" NUMBER(10,2), 
	"PARAMETER1" VARCHAR2(250 BYTE), 
	"PARAMETER2" VARCHAR2(250 BYTE), 
	"PARAMETER3" VARCHAR2(250 BYTE), 
	"PARAMETER4" VARCHAR2(250 BYTE), 
	"PARAMETER5" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
  GRANT SELECT ON "XXMX_CORE"."XXMX_DM_OIC_READ_LOG" TO "XXMX_READONLY";
