--------------------------------------------------------
--  DDL for Table XXMX_PER_APL_LE_DTL_UATBKUP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PER_APL_LE_DTL_UATBKUP" 
   (	"APPLICANT_NUMBER" VARCHAR2(1000 BYTE), 
	"FULL_NAME" VARCHAR2(1000 BYTE), 
	"BU_CODE" VARCHAR2(1000 BYTE), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
