--------------------------------------------------------
--  DDL for Table XXMX_PPM_LIC_UNPAID_V_TEMP
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_LIC_UNPAID_V_TEMP" 
   (	"INVOICE_ID" NUMBER(15,0), 
	"INVOICE_NUM" VARCHAR2(50 BYTE), 
	"AR_INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"AR_INVOICE_DATE" DATE, 
	"COST_TYPE" VARCHAR2(9 BYTE), 
	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"SYSTEM_REFERENCE2" VARCHAR2(30 BYTE), 
	"SYSTEM_REFERENCE3" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
