--------------------------------------------------------
--  Constraints for Table XXMX_PER_NID_F_XFM_UATBKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_PER_NID_F_XFM_UATBKUP" MODIFY ("NATIONAL_IDENTIFIER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_NID_F_XFM_UATBKUP" MODIFY ("NATIONAL_IDENTIFIER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_PER_NID_F_XFM_UATBKUP" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
