--------------------------------------------------------
--  DDL for Table XXMX_PPM_CONT_PARTY_CONTACTS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CONT_PARTY_CONTACTS" 
   (	"ACTION_CODE" VARCHAR2(250 BYTE), 
	"EXT_SOURCE" VARCHAR2(250 BYTE), 
	"EXT_KEY" VARCHAR2(250 BYTE), 
	"HEADER_EXT_SOURCE" VARCHAR2(250 BYTE), 
	"HEADER_EXT_KEY" VARCHAR2(250 BYTE), 
	"PARTY_EXT_SOURCE" VARCHAR2(250 BYTE), 
	"PARTY_EXT_KEY" VARCHAR2(250 BYTE), 
	"CONTACT_ROLE_CODE" VARCHAR2(250 BYTE), 
	"CONTACT_ID" VARCHAR2(250 BYTE), 
	"CONTACT_NAME" VARCHAR2(250 BYTE), 
	"OWNER_FLAG" VARCHAR2(250 BYTE), 
	"ACCESS_LEVEL" VARCHAR2(250 BYTE), 
	"START_DATE" VARCHAR2(250 BYTE), 
	"END_DATE" VARCHAR2(250 BYTE), 
	"BATCH_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
