--------------------------------------------------------
--  DDL for Materialized View XXMX_PPM_OPEN_AR_EVTS_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "XXMX_CORE"."XXMX_PPM_OPEN_AR_EVTS_MV" ("SOURCEREF", "ORGANIZATION_NAME", "EVENT_TYPE_NAME", "EVENT_DESC", "COMPLETION_DATE", "BILL_TRNS_CURRENCY_CODE", "BILL_TRNS_AMOUNT", "PROJECT_NUMBER", "TASK_NUMBER", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "PROJECT_CURRENCY_CODE", "PROJECT_BILL_AMOUNT", "PROJFUNC_CURRENCY_CODE", "PROJFUNC_BILL_AMOUNT")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT
  --        SOURCENAME,
        SOURCEREF,
        ORGANIZATION_NAME,
--        CONTRACT_TYPE_NAME,
--        CONTRACT_NUMBER,
--        CONTRACT_LINE_NUMBER,
        EVENT_TYPE_NAME,
        EVENT_DESC,
        COMPLETION_DATE,   --TBD
        BILL_TRNS_CURRENCY_CODE,
        BILL_TRNS_AMOUNT,
        PROJECT_NUMBER,
        TASK_NUMBER,
--        BILL_HOLD_FLAG,  --a
--        REVENUE_HOLD_FLAG, --a
--        ATTRIBUTE_CATEGORY, --a
        ATTRIBUTE1,
        ATTRIBUTE2,
        ATTRIBUTE3, --a
        ATTRIBUTE4,
        ATTRIBUTE5, --a
        ATTRIBUTE6,
        ATTRIBUTE7,
        ATTRIBUTE8,
        ATTRIBUTE9,
        ATTRIBUTE10,
        PROJECT_CURRENCY_CODE,
        PROJECT_BILL_AMOUNT,
        PROJFUNC_CURRENCY_CODE,
        PROJFUNC_BILL_AMOUNT 
FROM xxmx_ppm_open_ar_evts_v;

   COMMENT ON MATERIALIZED VIEW "XXMX_CORE"."XXMX_PPM_OPEN_AR_EVTS_MV"  IS 'snapshot table for snapshot XXMX_CORE.XXMX_PPM_OPEN_AR_EVTS_MV';
