--------------------------------------------------------
--  DDL for Table XXMX_PPM_CONT_TASK_INT
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PPM_CONT_TASK_INT" 
   (	"PROJECT_ID" VARCHAR2(250 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(250 BYTE), 
	"TASK_ID" VARCHAR2(250 BYTE), 
	"TASK_NUMBER" VARCHAR2(250 BYTE), 
	"TASK_NAME" VARCHAR2(250 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"START_DATE" VARCHAR2(250 BYTE), 
	"COMPLETION_DATE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
