--------------------------------------------------------
--  Constraints for Table XXMX_TASKS_FLAG_XFM_UAT_BKUP
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_UAT_BKUP" MODIFY ("TEMPLATE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_UAT_BKUP" MODIFY ("PROJECT_TASK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXMX_TASKS_FLAG_XFM_UAT_BKUP" MODIFY ("TEMPLATE_TASK_NUMBER" NOT NULL ENABLE);
