--------------------------------------------------------
--  DDL for Table XXMX_UNBILLED_PA_COSTS
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_UNBILLED_PA_COSTS" 
   (	"PROJECT_ID" NUMBER(15,0), 
	"SEGMENT1" VARCHAR2(25 BYTE), 
	"EXPENDITURE_ITEM_ID" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
	"ORG_ID" NUMBER(15,0), 
	"RECVR_ORG_ID" NUMBER, 
	"NET_ZERO_ADJUSTMENT_FLAG" VARCHAR2(1 BYTE), 
	"CONNECTION_ID" VARCHAR2(46 BYTE), 
	"AGEING_ID" NUMBER, 
	"DAYS" NUMBER, 
	"QUANTITY" NUMBER, 
	"BILL_TRANS_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"PROJECT_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"AMOUNT" NUMBER, 
	"AMOUNT_PROJ_CUR" NUMBER, 
	"AMOUNT_PROJ_FUNC_CUR" NUMBER, 
	"AMOUNT_PROJ_EUR" NUMBER, 
	"AMOUNT_PROJ_USD" NUMBER, 
	"ITEM_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	"INVOICE_ID" VARCHAR2(81 BYTE), 
	"PERIOD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
