--------------------------------------------------------
--  Constraints for Table XXPA_JOB_RELATIONSHIPS_V_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("ROW_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("JOB_RELATIONSHIP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("FROM_JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("TO_JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("FROM_JOB_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("TO_JOB_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
