--------------------------------------------------------
--  DDL for Table XXPA_JOB_RELATIONSHIPS_V_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXPA_JOB_RELATIONSHIPS_V_STG" 
   (	"ROW_ID" ROWID, 
	"JOB_RELATIONSHIP_ID" NUMBER(15,0), 
	"FROM_JOB_NAME" VARCHAR2(700 BYTE), 
	"FROM_JOB_ID" NUMBER(15,0), 
	"TO_JOB_NAME" VARCHAR2(700 BYTE), 
	"TO_JOB_ID" NUMBER(15,0), 
	"FROM_JOB_GROUP_ID" NUMBER(15,0), 
	"TO_JOB_GROUP_ID" NUMBER(15,0), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
