--------------------------------------------------------
--  DDL for Table XXPA_PROJ_STATUSES_V_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXPA_PROJ_STATUSES_V_STG" 
   (	"PROJECT_STATUS_CODE" VARCHAR2(30 BYTE), 
	"PROJECT_STATUS_NAME" VARCHAR2(80 BYTE), 
	"PROJECT_SYSTEM_STATUS_CODE" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"PREDEFINED_FLAG" VARCHAR2(150 BYTE), 
	"STARTING_STATUS_FLAG" VARCHAR2(1 BYTE), 
	"ENABLE_WF_FLAG" VARCHAR2(1 BYTE), 
	"WORKFLOW_ITEM_TYPE" VARCHAR2(30 BYTE), 
	"WORKFLOW_PROCESS" VARCHAR2(30 BYTE), 
	"WF_SUCCESS_STATUS_CODE" VARCHAR2(30 BYTE), 
	"WF_FAILURE_STATUS_CODE" VARCHAR2(30 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"STATUS_TYPE" VARCHAR2(30 BYTE), 
	"NEXT_ALLOWABLE_STATUS_FLAG" VARCHAR2(1 BYTE), 
	"STATUS_ICON_IND" VARCHAR2(80 BYTE), 
	"STATUS_ICON_ACTIVE_IND" VARCHAR2(80 BYTE), 
	"PROJECT_STATUS_WEIGHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
