--------------------------------------------------------
--  DDL for Table XXPA_TRANSACTION_CONTROLS_STG
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" 
   (	"PROJECT_ID" NUMBER(15,0), 
	"START_DATE_ACTIVE" DATE, 
	"CHARGEABLE_FLAG" VARCHAR2(1 BYTE), 
	"BILLABLE_INDICATOR" VARCHAR2(1 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"PERSON_ID" NUMBER(9,0), 
	"EXPENDITURE_CATEGORY" VARCHAR2(30 BYTE), 
	"EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
	"NON_LABOR_RESOURCE" VARCHAR2(20 BYTE), 
	"END_DATE_ACTIVE" DATE, 
	"SCHEDULED_EXP_ONLY" VARCHAR2(1 BYTE), 
	"EMPLOYEES_ONLY_FLAG" VARCHAR2(1 BYTE), 
	"WORKPLAN_RES_ONLY_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_CORE" ;
