--------------------------------------------------------
--  Constraints for Table XXPA_PROJECT_CLASSES_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("CLASS_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_PROJECT_CLASSES_STG" MODIFY ("OBJECT_TYPE" NOT NULL ENABLE);
