--------------------------------------------------------
--  Constraints for Table XXPA_TRANSACTION_CONTROLS_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("START_DATE_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("CHARGEABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("BILLABLE_INDICATOR" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPA_TRANSACTION_CONTROLS_STG" MODIFY ("LAST_UPDATE_LOGIN" NOT NULL ENABLE);
