--------------------------------------------------------
--  Constraints for Table XXPER_ALL_ASSIGNMENTS_F_STG
--------------------------------------------------------

  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("BUSINESS_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("ASSIGNMENT_STATUS_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("ASSIGNMENT_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("ASSIGNMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_CORE"."XXPER_ALL_ASSIGNMENTS_F_STG" MODIFY ("PRIMARY_FLAG" NOT NULL ENABLE);
