--------------------------------------------------------
--  DDL for Table XXMX_PERSON
--------------------------------------------------------

  CREATE TABLE "XXMX_CORE"."XXMX_PERSON" 
   (	"PERSON_NUMBER" NUMBER, 
	"FIRST_NAME" VARCHAR2(300 BYTE), 
	"LAST_NAME" VARCHAR2(300 BYTE), 
	"MIDDLE_NAMES" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
