Select * from AP_INVOICE_LINES_ALL;


INVOICE_ID                     NOT NULL NUMBER(15)    
LINE_NUMBER                    NOT NULL NUMBER        
LINE_TYPE_LOOKUP_CODE          NOT NULL VARCHAR2(25)  
REQUESTER_ID                            NUMBER(15)    
DESCRIPTION                             VARCHAR2(240) 
LINE_SOURCE                             VARCHAR2(30)  
ORG_ID                                  NUMBER(15)    
LINE_GROUP_NUMBER                       NUMBER        
INVENTORY_ITEM_ID                       NUMBER        
ITEM_DESCRIPTION                        VARCHAR2(240) 
SERIAL_NUMBER                           VARCHAR2(35)  
MANUFACTURER                            VARCHAR2(30)  
MODEL_NUMBER                            VARCHAR2(40)  
WARRANTY_NUMBER                         VARCHAR2(15)  
GENERATE_DISTS                          VARCHAR2(1)   
MATCH_TYPE                              VARCHAR2(25)  
DISTRIBUTION_SET_ID                     NUMBER(15)    
ACCOUNT_SEGMENT                         VARCHAR2(25)  
BALANCING_SEGMENT                       VARCHAR2(25)  
COST_CENTER_SEGMENT                     VARCHAR2(25)  
OVERLAY_DIST_CODE_CONCAT                VARCHAR2(250) 
DEFAULT_DIST_CCID                       NUMBER(15)    
PRORATE_ACROSS_ALL_ITEMS                VARCHAR2(1)   
ACCOUNTING_DATE                NOT NULL DATE          
PERIOD_NAME                             VARCHAR2(15)  
DEFERRED_ACCTG_FLAG                     VARCHAR2(1)   
DEF_ACCTG_START_DATE                    DATE          
DEF_ACCTG_END_DATE                      DATE          
DEF_ACCTG_NUMBER_OF_PERIODS             NUMBER        
DEF_ACCTG_PERIOD_TYPE                   VARCHAR2(30)  
SET_OF_BOOKS_ID                NOT NULL NUMBER(15)    
AMOUNT                         NOT NULL NUMBER        
BASE_AMOUNT                             NUMBER        
ROUNDING_AMT                            NUMBER        
QUANTITY_INVOICED                       NUMBER        
UNIT_MEAS_LOOKUP_CODE                   VARCHAR2(25)  
UNIT_PRICE                              NUMBER        
WFAPPROVAL_STATUS              NOT NULL VARCHAR2(30)  
USSGL_TRANSACTION_CODE                  VARCHAR2(30)  
DISCARDED_FLAG                          VARCHAR2(1)   
ORIGINAL_AMOUNT                         NUMBER        
ORIGINAL_BASE_AMOUNT                    NUMBER        
ORIGINAL_ROUNDING_AMT                   NUMBER        
CANCELLED_FLAG                          VARCHAR2(1)   
INCOME_TAX_REGION                       VARCHAR2(10)  
TYPE_1099                               VARCHAR2(10)  
STAT_AMOUNT                             NUMBER        
PREPAY_INVOICE_ID                       NUMBER(15)    
PREPAY_LINE_NUMBER                      NUMBER        
INVOICE_INCLUDES_PREPAY_FLAG            VARCHAR2(1)   
CORRECTED_INV_ID                        NUMBER(15)    
CORRECTED_LINE_NUMBER                   NUMBER        
PO_HEADER_ID                            NUMBER        
PO_LINE_ID                              NUMBER        
PO_RELEASE_ID                           NUMBER        
PO_LINE_LOCATION_ID                     NUMBER        
PO_DISTRIBUTION_ID                      NUMBER        
RCV_TRANSACTION_ID                      NUMBER        
FINAL_MATCH_FLAG                        VARCHAR2(1)   
ASSETS_TRACKING_FLAG                    VARCHAR2(1)   
ASSET_BOOK_TYPE_CODE                    VARCHAR2(15)  
ASSET_CATEGORY_ID                       NUMBER(15)    
PROJECT_ID                              NUMBER(15)    
TASK_ID                                 NUMBER(15)    
EXPENDITURE_TYPE                        VARCHAR2(30)  
EXPENDITURE_ITEM_DATE                   DATE          
EXPENDITURE_ORGANIZATION_ID             NUMBER(15)    
PA_QUANTITY                             NUMBER        
PA_CC_AR_INVOICE_ID                     NUMBER(15)    
PA_CC_AR_INVOICE_LINE_NUM               NUMBER(15)    
PA_CC_PROCESSED_CODE                    VARCHAR2(1)   
AWARD_ID                                NUMBER(15)    
AWT_GROUP_ID                            NUMBER(15)    
REFERENCE_1                             VARCHAR2(30)  
REFERENCE_2                             VARCHAR2(30)  
RECEIPT_VERIFIED_FLAG                   VARCHAR2(1)   
RECEIPT_REQUIRED_FLAG                   VARCHAR2(1)   
RECEIPT_MISSING_FLAG                    VARCHAR2(1)   
JUSTIFICATION                           VARCHAR2(240) 
EXPENSE_GROUP                           VARCHAR2(80)  
START_EXPENSE_DATE                      DATE          
END_EXPENSE_DATE                        DATE          
RECEIPT_CURRENCY_CODE                   VARCHAR2(15)  
RECEIPT_CONVERSION_RATE                 NUMBER        
RECEIPT_CURRENCY_AMOUNT                 NUMBER        
DAILY_AMOUNT                            NUMBER        
WEB_PARAMETER_ID                        NUMBER        
ADJUSTMENT_REASON                       VARCHAR2(240) 
MERCHANT_DOCUMENT_NUMBER                VARCHAR2(80)  
MERCHANT_NAME                           VARCHAR2(240) 
MERCHANT_REFERENCE                      VARCHAR2(240) 
MERCHANT_TAX_REG_NUMBER                 VARCHAR2(80)  
MERCHANT_TAXPAYER_ID                    VARCHAR2(80)  
COUNTRY_OF_SUPPLY                       VARCHAR2(5)   
CREDIT_CARD_TRX_ID                      NUMBER(15)    
COMPANY_PREPAID_INVOICE_ID              NUMBER(15)    
CC_REVERSAL_FLAG                        VARCHAR2(1)   
CREATION_DATE                           DATE          
CREATED_BY                              NUMBER(15)    
LAST_UPDATED_BY                NOT NULL NUMBER(15)    
LAST_UPDATE_DATE               NOT NULL DATE          
LAST_UPDATE_LOGIN                       NUMBER(15)    
PROGRAM_APPLICATION_ID                  NUMBER(15)    
PROGRAM_ID                              NUMBER(15)    
PROGRAM_UPDATE_DATE                     DATE          
REQUEST_ID                              NUMBER(15)    
ATTRIBUTE_CATEGORY                      VARCHAR2(150) 
ATTRIBUTE1                              VARCHAR2(150) 
ATTRIBUTE2                              VARCHAR2(150) 
ATTRIBUTE3                              VARCHAR2(150) 
ATTRIBUTE4                              VARCHAR2(150) 
ATTRIBUTE5                              VARCHAR2(150) 
ATTRIBUTE6                              VARCHAR2(150) 
ATTRIBUTE7                              VARCHAR2(150) 
ATTRIBUTE8                              VARCHAR2(150) 
ATTRIBUTE9                              VARCHAR2(150) 
ATTRIBUTE10                             VARCHAR2(150) 
ATTRIBUTE11                             VARCHAR2(150) 
ATTRIBUTE12                             VARCHAR2(150) 
ATTRIBUTE13                             VARCHAR2(150) 
ATTRIBUTE14                             VARCHAR2(150) 
ATTRIBUTE15                             VARCHAR2(150) 
GLOBAL_ATTRIBUTE_CATEGORY               VARCHAR2(150) 
GLOBAL_ATTRIBUTE1                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE2                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE3                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE4                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE5                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE6                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE7                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE8                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE9                       VARCHAR2(150) 
GLOBAL_ATTRIBUTE10                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE11                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE12                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE13                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE14                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE15                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE16                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE17                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE18                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE19                      VARCHAR2(150) 
GLOBAL_ATTRIBUTE20                      VARCHAR2(150) 
LINE_SELECTED_FOR_APPL_FLAG             VARCHAR2(1)   
PREPAY_APPL_REQUEST_ID                  NUMBER(15)    
APPLICATION_ID                          NUMBER(15)    
PRODUCT_TABLE                           VARCHAR2(30)  
REFERENCE_KEY1                          VARCHAR2(150) 
REFERENCE_KEY2                          VARCHAR2(150) 
REFERENCE_KEY3                          VARCHAR2(150) 
REFERENCE_KEY4                          VARCHAR2(150) 
REFERENCE_KEY5                          VARCHAR2(150) 
PURCHASING_CATEGORY_ID                  NUMBER(15)    
COST_FACTOR_ID                          NUMBER(15)    
CONTROL_AMOUNT                          NUMBER        
ASSESSABLE_VALUE                        NUMBER        
TOTAL_REC_TAX_AMOUNT                    NUMBER        
TOTAL_NREC_TAX_AMOUNT                   NUMBER        
TOTAL_REC_TAX_AMT_FUNCL_CURR            NUMBER        
TOTAL_NREC_TAX_AMT_FUNCL_CURR           NUMBER        
INCLUDED_TAX_AMOUNT                     NUMBER        
PRIMARY_INTENDED_USE                    VARCHAR2(30)  
TAX_ALREADY_CALCULATED_FLAG             VARCHAR2(1)   
SHIP_TO_LOCATION_ID                     NUMBER(15)    
PRODUCT_TYPE                            VARCHAR2(240) 
PRODUCT_CATEGORY                        VARCHAR2(240) 
PRODUCT_FISC_CLASSIFICATION             VARCHAR2(240) 
USER_DEFINED_FISC_CLASS                 VARCHAR2(240) 
TRX_BUSINESS_CATEGORY                   VARCHAR2(240) 
SUMMARY_TAX_LINE_ID                     NUMBER        
TAX_REGIME_CODE                         VARCHAR2(30)  
TAX                                     VARCHAR2(30)  
TAX_JURISDICTION_CODE                   VARCHAR2(30)  
TAX_STATUS_CODE                         VARCHAR2(30)  
TAX_RATE_ID                             NUMBER(15)    
TAX_RATE_CODE                           VARCHAR2(150) 
TAX_RATE                                NUMBER        
TAX_CODE_ID                             NUMBER(15)    
HISTORICAL_FLAG                         VARCHAR2(1)   
TAX_CLASSIFICATION_CODE                 VARCHAR2(30)  
SOURCE_APPLICATION_ID                   NUMBER        
SOURCE_EVENT_CLASS_CODE                 VARCHAR2(30)  
SOURCE_ENTITY_CODE                      VARCHAR2(30)  
SOURCE_TRX_ID                           NUMBER        
SOURCE_LINE_ID                          NUMBER        
SOURCE_TRX_LEVEL_TYPE                   VARCHAR2(30)  
RETAINED_AMOUNT                         NUMBER        
RETAINED_AMOUNT_REMAINING               NUMBER        
RETAINED_INVOICE_ID                     NUMBER(15)    
RETAINED_LINE_NUMBER                    NUMBER        
LINE_SELECTED_FOR_RELEASE_FLAG          VARCHAR2(1)   
LINE_OWNER_ROLE                         VARCHAR2(320) 
DISPUTABLE_FLAG                         VARCHAR2(1)   
RCV_SHIPMENT_LINE_ID                    NUMBER(15)    
AIL_INVOICE_ID                          NUMBER(15)    
AIL_DISTRIBUTION_LINE_NUMBER            NUMBER(15)    
AIL_INVOICE_ID2                         NUMBER(15)    
AIL_DISTRIBUTION_LINE_NUMBER2           NUMBER(15)    
AIL_INVOICE_ID3                         NUMBER(15)    
AIL_DISTRIBUTION_LINE_NUMBER3           NUMBER(15)    
AIL_INVOICE_ID4                         NUMBER(15)    
PAY_AWT_GROUP_ID                        NUMBER(15)