--setup checks

select distinct customer_class_code
from XXMX_HZ_CUST_ACCOUNTS_XFM
order by 1;

select distinct STANDARD_TERM_NAME
from XXMX_HZ_CUST_PROFILES_XFM
WHERE STANDARD_TERM_NAME IS NOT NULL
order by 1;

select distinct STATEMENT_CYCLE_NAME
from XXMX_HZ_CUST_PROFILES_XFM
WHERE STATEMENT_CYCLE_NAME IS NOT NULL
order by 1;

select distinct TAX_REGIME_CODE --, tax, TAX_JURISDICTION_CODE, EFFECTIVE_FROM --REGISTRATION_TYPE_CODE
from XXMX_ZX_TAX_REGISTRATION_XFM
order by 1;

select distinct CLASS_CATEGORY, CLASSIFICATION_TYPE_CODE, CLASSIFICATION_TYPE_NAME--,CLASS_CODE
from XXMX_ZX_PARTY_CLASSIFIC_XFM
order by 1;

select distinct class_code --, tax, TAX_JURISDICTION_CODE, EFFECTIVE_FROM --REGISTRATION_TYPE_CODE
from XXMX_ZX_PARTY_CLASSIFIC_XFM
order by 1;