select distinct application_suite from xxmx_migration_metadata;									--5

select distinct application from xxmx_migration_metadata; where application_suite like 'PPM';	--13

HCM - 	TM
		BEN
		PAY
		HR
		IREC
		
OLC	-	LRN

SCM	-	PO

FIN	-	GL
		AR
		ZX
		AP
		FA

PPM	-	PRJ


select distinct business_entity from xxmx_migration_metadata; where application like 'HR';		--53


HR		-	LOCATION
			ORGANIZATION
			BANKS_AND_BRANCHES
			PERSON
			WORKER
			
IREC	-	GEOGRAPHY_HIERARCHY 90000
			JOB_REQUISITION
			CANDIDATE
			CANDIDATE_POOL
			JOB_REFERRAL
			PROSPECT

PAY		-	CALC_CARDS_PAE 103000
			CALC_CARDS_SD
			CALC_CARDS_SL
			CALC_CARDS_BP
			CALC_CARDS_NSD
			CALC_CARDS_PGL
			PAY_BALANCES
			ELEMENTS

LRN		-	LEGACY_LEARNING_ITEM 106000
			LEGACY_LEARNING_ITEM_TRANSLATION
			NON_CATALOG_LEARNING_ITEM
			NON_CATALOG_LEARNING_ITEM_TRASNLATION		--rename translation
			TRAINING_SUPPLIER_RESOURCE					--new
			TRAINING_SUPPLIER_RESOURCE_TRANSLATION		--new
			CLASSROOM_RESOURCE
			CLASSROOM_RESOURCE_TRANSLATION
			INSTRUCTOR_RESOURCE
			COURSE_V3
			COURSE
			COURSE_V3_TRANSLATION
			COURSE_TRANSLATION
			OFFERING_V3_TRANSLATION
			OFFERING_TRANSLATION
			OFFER_ACT_SEC_V3_TRNSLN
			INSTRUCTOR_LED_ACTIVITY_TRNSLN
			INSTR_LED_ACTIVITY_V3_TRNSLN
			SELFPACED_ACTIVITY_TRNSLN
			SELFPACED_ACTIVITY_V3_TRNSLN
			EVALUATION_ACTIVITY_V3_TRNSLN
			COURSE_OFFG_PRICING_DEFAULTS
			OFFERING_CUSTOM_PRICING
			SPECIALIZATION_V3
			SPECIALIZATION
			SPECIALIZATION_TRANSLATION
			SPECIALIZATION_V3_TRANSLATION
			SPECIALIZATION_V3_SXN_TRNSLN		--put sxn before v3
			SPECIALIZATION_SECTION_TRNSLN
			GLOBAL_ACCESS_GROUP_RELATION
			COMMUNITY_RELATION
			LEARNING_RECORD
			LEARNING_RECORD_ACTIVITY_ATTEMPT
			LEARNING_RECORD_ACT_ATTEMPT_V3
			
BEN		-	BENEFITS 160100
		
TM		-	GOAL 126000
			GOAL_PLAN
			GOAL_PLAN_SET
			PERFORMANCE_DOCUMENT 200100





AP		-	SUPPLIERS
			SUPPLIER_ADDRESSES
			SUPPLIER_SITES
			SUPPLIER_CONTACT
			SUPPLIER_SITE_ASSIGNS
			SUPPLIER_BANK_ACCOUNTS
			INVOICES
			SUPPLIER_TAX
			
AR		-	CUSTOMERS
			TRANSACTIONS
			CASH_RECEIPTS
			
ZX		-	CUSTOMER_TAX

GL		-	OPEN_BAL
			SUMM_BAL
			DETAIL_BAL
			JOURNAL
			DAILY_RATES
			HISTORICAL_RATES
			
FA		-	FIXED_ASSETS

PO		-	PURCHASE_ORDERS
			PURCHASE_ORDERS_BPA
			PURCHASE_ORDERS_CPA
			PURCHASE_ORDER_RECEIPT

PRJ		-	PRJ_FOUNDATION
			PRJ_RBS
			PRJ_EVENTS
			PRJ_COST
			
select distinct sub_entity from xxmx_migration_metadata;										--261

