--------------------------------------------------------
--  File created - Thursday-February-01-2024   
--------------------------------------------------------
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ADDR_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_INVOICES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_INVOICES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_INVOICE_LINES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_INVOICE_LINES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPPLIERS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPPLIERS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPPLIER_SITES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPPLIER_SITES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_3RD_PTY_RELS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_3RD_PTY_RELS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_ADDRS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_ADDRS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_BANK_ACCTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_BANK_ACCTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_CONTACTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_CONTACTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_CONT_ADDRS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_CONT_ADDRS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_PAYEES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_PAYEES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_PMT_INSTRS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_PMT_INSTRS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_SITE_ASSIGNS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_SITE_ASSIGNS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_TAX_PROF_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_TAX_PROF_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_TAX_REG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AP_SUPP_TAX_REG_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT5_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT6_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT8_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RECEIPTS_OUT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RECEIPTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RECEIPTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CUST_BANKS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CUST_BANKS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_DISTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_DISTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_LINES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_LINES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_SALESCREDITS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_TRX_SALESCREDITS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_GRADESTEP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_GRADESTEP_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_PAYROLL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_PAYROLL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_WORKMSURE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_WORKMSURE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BANKS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BANKS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BANK_BRANCHES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BANK_BRANCHES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_DB_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_DB_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_DD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_DD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBB_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBB_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBG_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBO_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBO_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_CO_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_CO_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PH_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PH_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CARRY_OVER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CARRY_OVER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CITIZENSHIPS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CITIZENSHIPS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_EXT_BANK_ACC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_EXT_BANK_ACC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_LOCATION_TEST.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_ADDITIONS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_ADDITIONS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_ADDITION_DIST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_ADDITION_DIST_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_RATES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_FA_MASS_RATES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_BALANCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_BALANCES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_DAILYRATES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_DAILYRATES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_DETAIL_BALANCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_DETAIL_BALANCES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_HISTORICALRATES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_HISTORICALRATES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_JOURNAL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_JOURNAL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_OPENING_BALANCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_OPENING_BALANCES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_SUMMARY_BALANCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_SUMMARY_BALANCES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GL_TEST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_ADDRESS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_ADDRESS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_ATTMT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_EMAIL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_EMAIL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_EXTRA_INFO_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_INTERACT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_JOBAPPL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_EXTRA_INFO_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_PROFL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_JOB_APPL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_NAME_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_NAME_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_NAT_IDENFR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PHONE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PHONE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_INTERACT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_INTERACT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_MEMBR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_MEMBR_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_OWNER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_OWNER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_POOL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PREFD_JOB_FAM_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PREFD_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PREFD_ORG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PREF_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_PROFL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CAN_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_CAN_INTERACT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_CAN_PER_INFO_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_CAN_PREFD_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_QSTNR_PARTCPNT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_QSTNR_RESP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CJA_QSTN_RESP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CL_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CL_POST_DESC_CNTXT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CON_LIB_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CON_LIB_VER_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CON_LIB_VER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CON_LIB_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CP_TAL_COMM_DET_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_CP_TAL_COMM_DET_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_GEO_HIER_NODE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_GEO_HIER_NODE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_GEO_HIER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_GEO_HIER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_SEC_PROFL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_TEMPL_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_TEMPL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JOB_REQ_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_APPL_SPEC_QSTN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_ASSMT_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_ASSMT_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_SCRN_PKG_V2_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_BKG_CHECK_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_HIRE_TEAM_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_INTRVW_QSTNR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_JOB_PROFL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_LANG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_MEDIA_LINK_LANG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_OTHER_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_OTHER_WORK_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_TAX_CRED_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_TAX_CRED_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JRT_TEMPL_MEDIA_LINK_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_APPL_SPEC_QSTN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_ASSMT_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_ASSMT_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_SCRN_PKG_V2_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_BKG_CHECK_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_HIRE_TEAM_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_HIRE_TEAM_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_INTRVW_QSTNR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_JOB_PROFL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_LANG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_MEDIA_LINK_LANG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_MEDIA_LINK_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_OTHER_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_OTHER_WORK_LOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_POST_DET_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_POST_DET_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_TAX_CRED_CONFIG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_JR_TAX_CRED_SCRN_PKG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_MEDIA_LINK_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_PROSPECT_INTERACT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_PROSPECT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_PROSPECT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_REFERRAL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_REFERRAL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_REF_ATTMT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HCM_IREC_TEMPL_MEDIA_LINK_TRNSLN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_CNT_ITEMS_B_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_CNT_ITEMS_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_ESTB_B_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_ESTB_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PFL_ITEMS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_B_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_REL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_LVL_B_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_LVL_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_MDL_B_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_MDL_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CONTACT_POINTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CONTACT_POINTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCOUNTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCOUNTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_CONTACTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_CONTACTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_RELATE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_RELATE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_SITES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_ACCT_SITES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_PROFILES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_PROFILES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_SITE_USES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_CUST_SITE_USES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_LOCATIONS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_LOCATIONS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ORG_CONTACTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ORG_CONTACTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ORG_CONTACT_ROLES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ORG_CONTACT_ROLES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTIES_RPT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTIES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTIES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_CLASSIFS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_CLASSIFS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITES_RPT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITE_USES_RPT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITE_USES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PARTY_SITE_USES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PERSON_LANGUAGE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_PERSON_LANGUAGE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_RELATIONSHIPS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_RELATIONSHIPS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ROLE_RESPS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HZ_ROLE_RESPS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_IBY_CUST_BANK_ACCTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LEARNER_RECORDS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LEARNER_RECORDS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOCATIONS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_ADDR_USG_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_DETAILS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_DETAILS_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_MAP_LOOKUPS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_ADHOC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_ADHOC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RESV_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RESV_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COMM_RS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COMM_RS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_ACC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_ACC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_COMP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_COMP_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_GLOB_ACC_GRP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_ACT_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_ACT_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_LED_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_LED_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RESV_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RESV_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_ACC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_ACC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_DEF_ACC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_DEF_ACC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_ACT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_ACT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_TL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_CERTIFICATION_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_CERTIFICATION_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_CLASS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_CLASS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_COURSE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLM_COURSE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_INFO_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNITS_F_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNITS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNIT_CLASS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ABSENCE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ABSENCE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDRESS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDRESS_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDR_USG_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDR_USG_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_AOR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SALARY_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SALARY_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SUP_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SUP_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_WORKSCH_EXP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_WORK_SCH_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASSIGNMENTS_M_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASSIGNMENTS_M_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_ADDR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_ADDR_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_PHONE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_PHONE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_REL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_REL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DISABILITY_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DISABILITY_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DOCUMENTATION_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_EMAIL_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_EMAIL_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ETHNICITIES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ETHNICITIES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_IMAGES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_IMAGES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_LEG_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_LEG_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_MAT_ABSENCE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_MAT_ABSENCE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NAMES_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NAMES_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NID_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NID_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PASSPORT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PASSPORT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PAY_METHOD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PAY_METHOD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PEOPLE_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PEOPLE_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PERSONS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PERSONS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PHONES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PHONES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_POS_WR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_POS_WR_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PROFILE_ITEM_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PROFILE_ITEM_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_RELIGION_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_RELIGION_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_SENIORITYDT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_SENIORITYDT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_TALENT_PROFILE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_TALENT_PROFILE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_VISA_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_VISA_F_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_POSITIONS_F_TL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_POSITIONS_F_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_LIC_UNPAID_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PLANRBS_HEADER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PLANRBS_HEADER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_BILLEVENT_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_CLASS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_CLASS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_LBRCOST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_LBRCOST_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_MISCCOST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_MISCCOST_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_NONLABCOST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_NONLABCOST_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_SUPCOST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_SUPCOST_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TASKS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TASKS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TEAM_MEM_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TEAM_MEM_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TRX_CONTROL_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PROJECTS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PROJECTS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_PROJECTS_XFM_BCK_12_12_2022.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_RATE_OVERRIDES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_RATE_OVERRIDES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_RESOURCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PPM_RESOURCES_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RA_CUST_RCPT_METHODS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RA_CUST_RCPT_METHODS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RESP_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RESP_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_ATTR_VALUES_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_ATTR_VALUES_TLP_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_DISTRIBUTIONS_STD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_DISTRIBUTIONS_STD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_GA_ORG_ASSIGN_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_GA_ORG_ASSIGN_CPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_BPA_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_CPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_CPA_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_STD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_HEADERS_STD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINES_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINES_BPA_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINES_STD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINES_STD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_STD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SCM_PO_LINE_LOCATIONS_STD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SUPP_TEST_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_SUP_TEST_GL_COMBO.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_TEST_OPENING_BALANCES_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_ADDR_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_ADDR_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_ORG_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_ORG_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_PAYMTHD_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_THIRD_PAYMTHD_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_DATA_ACCESS_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_DATA_ACCESS_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_PARTY_CLASSIFIC_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_PARTY_CLASSIFIC_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_TAX_PROFILE_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_TAX_PROFILE_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_TAX_REGISTRATION_XFM.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ZX_TAX_REGISTRATION_XFM_ARCH.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RESV_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_GLOB_ACC_GRP_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_MAP_LOOKUPS_XFM_N1.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_XTRT_HRT_CNT_ITEMS_B_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_TL_XFM_UK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RES_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBB_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_ADHOC_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_COMP_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBG_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_ACC_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX5.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX2.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RESV_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_DEF_ACC_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBO_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_LED_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_CO_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_ACT_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_DD_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_ACC_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX7.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_MAP_LOOKUPS_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX1.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_ACT_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COMM_RS_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX3.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_CNT_ITEMS_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX6.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\INDEX4.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_TL_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PH_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_DB_XFM_PK.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_ESTB_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PASSPORT_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_CO_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACTS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_WORKMSURE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_ADDR_USG_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_ACC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_ADDR_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PEOPLE_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_MAP_LOOKUPS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_REL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_ACC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PAY_METHOD_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASSIGNMENTS_M_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RESP_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDR_USG_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PASSPORT_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_LEG_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NID_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CITIZENSHIPS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_WORKMSURE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_EMAIL_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_EXT_BANK_ACC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_RELIGION_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DISABILITY_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PH_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SUP_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_GRADESTEP_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_ACT_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT6_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_DEF_ACC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_COMP_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_DD_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_LEG_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_LED_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RES_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_DD_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_GLOB_ACC_GRP_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_POSITIONS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_SENIORITYDT_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_COMP_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_ADDR_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_ACT_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBG_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_MAT_ABSENCE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NID_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PHONES_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_ACC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_VISA_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBO_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PERSONS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_POSITIONS_F_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_EXT_BANK_ACC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ABSENCE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_MDL_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PH_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_LVL_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNIT_CLASS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACTS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RES_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_PAYROLL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NAMES_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ETHNICITIES_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_DEF_ACC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DISABILITY_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_ACT_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SALARY_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_ACT_ATT_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBO_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PERSONS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_B_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBG_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_ADHOC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEG_LEARN_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASSIGNMENTS_M_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PROFILE_REL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_ACT_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_CUST_PRICE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ABSENCE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ETHNICITIES_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SALARY_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_PFL_ITEMS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PAY_METHOD_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_GRADESTEP_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBB_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNITS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDR_USG_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PHONES_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_CNT_ITEMS_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_REL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COMM_RS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_MAT_ABSENCE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_LVL_B_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_CO_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDRESS_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_JOBS_F_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_EMAIL_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RECEIPTS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_ACC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_DE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOCATIONS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_LED_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_PHONE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_INFO_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_CNT_ITEMS_B_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_PBB_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_GRADES_F_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT8_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COMM_RS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RESV_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_NAMES_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_INSTR_RESV_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_IMAGES_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RCPTS_RT5_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_ADHOC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_DETAILS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_RELIGION_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ORG_UNITS_F_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ADDR_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_TL_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_VISA_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ADDRESS_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_CONTACT_PHONE_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_SENIORITYDT_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_SXN_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_ESTB_B_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_DB_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_LOC_DETAILS_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_NONCAT_LEARN_TL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_DOCUMENTATION_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_IMAGES_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RES_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_ASG_SUP_F_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_AR_CASH_RECEIPTS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_ASG_PAYROLL_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RESV_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SELFPACE_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_PER_PEOPLE_F_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_COURSE_PRICE_COMP_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_HRT_RATING_MDL_B_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_SPEC_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_OFFER_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_DATA_ACCESS_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_LEARN_RCD_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_RESP_XFM_ARCH_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_DATA_ACCESS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_OLC_CLASS_RESV_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_CITIZENSHIPS_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_USER_XFM_CONSTRAINT.sql
@C:\Users\KSUSHMA\Desktop\All xfm bkp latest\XXMX_BEN_BE_DB_XFM_CONSTRAINT.sql
