--------------------------------------------------------
--  Constraints for Table XXMX_OLC_NONCAT_LEARN_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_TL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_NONCAT_LEARN_TL_XFM" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
