--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_CUST_PRICE_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_CUST_PRICE_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_CUST_PRICE_XFM" MODIFY ("PRICING_RULE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_CUST_PRICE_XFM" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_CUST_PRICE_XFM" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
