--------------------------------------------------------
--  Constraints for Table XXMX_PER_IMAGES_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM" MODIFY ("IMAGENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM" MODIFY ("IMAGE_REF" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_IMAGES_XFM" MODIFY ("IMAGETYPE" NOT NULL ENABLE);
