--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
