--------------------------------------------------------
--  DDL for Table XXMX_ZX_PARTY_CLASSIFIC_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PARTY_TYPE_CODE" VARCHAR2(80 BYTE), 
	"PARTY_NUMBER" VARCHAR2(30 BYTE), 
	"PARTY_NAME" VARCHAR2(150 BYTE), 
	"CLASS_CATEGORY" VARCHAR2(30 BYTE), 
	"CLASSIFICATION_TYPE_CODE" VARCHAR2(30 BYTE), 
	"CLASSIFICATION_TYPE_NAME" VARCHAR2(150 BYTE), 
	"TAX_REGIME_CODE" VARCHAR2(30 BYTE), 
	"FISCAL_CLASSIFICATION_CODE" VARCHAR2(30 BYTE), 
	"CLASS_CODE" VARCHAR2(80 BYTE), 
	"CLASS_NAME" VARCHAR2(80 BYTE), 
	"EFFECTIVE_FROM" DATE, 
	"EFFECTIVE_TO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_TCA_READONLY";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_ZX_PARTY_CLASSIFIC_XFM" TO "XXMX_CORE";
