--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
