--------------------------------------------------------
--  DDL for Index XXMX_OLC_INSTR_RESV_XFM_PK
--------------------------------------------------------

  CREATE INDEX "XXMX_XFM"."XXMX_OLC_INSTR_RESV_XFM_PK" ON "XXMX_XFM"."XXMX_OLC_INSTR_RESV_XFM" ("INSTRUCTOR_RESERVATION_NUMBER", "ACTIVITY_NUMBER", "INSTRUCTOR_RESOURCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
