--------------------------------------------------------
--  DDL for Table XXMX_PER_VISA_F_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PER_VISA_F_XFM" 
   (	"MIGRATION_SET_ID" NUMBER, 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"EFFECTIVESTARTDATE" DATE, 
	"EFFECTIVEENDDATE" DATE, 
	"PERSONNUMBER" VARCHAR2(100 BYTE), 
	"PERSON_ID" VARCHAR2(264 BYTE), 
	"LEGISLATIONCODE" VARCHAR2(30 BYTE), 
	"ENTRYDATE" DATE, 
	"EXPIRATIONDATE" DATE, 
	"CURRENTVISAPERMIT" VARCHAR2(100 BYTE), 
	"ISSUEDATE" DATE, 
	"ISSUINGAUTHORITY" VARCHAR2(100 BYTE), 
	"ISSUINGCOUNTRY" VARCHAR2(100 BYTE), 
	"ISSUINGLOCATION" VARCHAR2(100 BYTE), 
	"PROFESSION" VARCHAR2(100 BYTE), 
	"VISAPERMITCATEGORY" VARCHAR2(100 BYTE), 
	"VISAPERMITNUMBER" VARCHAR2(30 BYTE), 
	"VISAPERMITSTATUS" VARCHAR2(30 BYTE), 
	"VISAPERMITSTATUSDATE" DATE, 
	"VISAPERMITTYPE" VARCHAR2(10 BYTE), 
	"METADATA" VARCHAR2(10 BYTE) DEFAULT 'MERGE', 
	"OBJECT_NAME" VARCHAR2(200 BYTE) DEFAULT 'PersonVisa', 
	"SOURCESYSTEMOWNER" VARCHAR2(30 BYTE), 
	"SOURCESYSTEMID" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PER_VISA_F_XFM" TO "XXMX_CORE";
