--------------------------------------------------------
--  Constraints for Table XXMX_OLC_OFFER_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("OFFERING_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("OFFERING_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("LANGUAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("COORDINATOR_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_OFFER_XFM" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
