--------------------------------------------------------
--  DDL for Table XXMX_PPM_LIC_UNPAID_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" 
   (	"BUSINESS_UNIT" VARCHAR2(240 BYTE), 
	"INVOICE_ID" NUMBER(15,0), 
	"PROJECT_ID" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(25 BYTE), 
	"ORG_ID" NUMBER(15,0), 
	"EXP_ORG_ID" NUMBER(15,0), 
	"EXP_ORG_NAME" VARCHAR2(240 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVOICE_CURRENCY" VARCHAR2(15 BYTE), 
	"INVOICE_DIST_AMOUNT" NUMBER, 
	"INVOICE_DATE" DATE, 
	"INVOICE_TYPE" VARCHAR2(25 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(25 BYTE), 
	"ACCOUNTING_DATE" DATE, 
	"CONVERSION_RATE" NUMBER, 
	"CONVERSION_RATE_TYPE" VARCHAR2(30 BYTE), 
	"CONVERSION_DATE" DATE, 
	"PAY_GROUP" VARCHAR2(25 BYTE), 
	"SUPPLIER" VARCHAR2(240 BYTE), 
	"SUPPLIERSITE" VARCHAR2(15 BYTE), 
	"DISTRIBUTION_LINE_NUMBER" NUMBER, 
	"LINE_DESCRIPTION" VARCHAR2(240 BYTE), 
	"TYPE" VARCHAR2(25 BYTE), 
	"TAX_CLASSIFICATION" VARCHAR2(30 BYTE), 
	"TAX_CONTROL" NUMBER, 
	"CODE_COMBINATION" VARCHAR2(155 BYTE), 
	"DIST_CODE_COMBINATION_ID" NUMBER(15,0), 
	"AR_INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"AR_INVOICE_DATE" DATE, 
	"COST_TYPE" VARCHAR2(9 BYTE), 
	"EXPENDITURE_TYPE" VARCHAR2(30 BYTE), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"AP_LIC_FEE_RANK" NUMBER, 
	"BATCH_NAME" VARCHAR2(50 BYTE), 
	"MIGRATION_SET_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PPM_LIC_UNPAID_XFM" TO "XXMX_CORE";
