--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RES_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_XFM" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
