--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COMM_RS_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM_ARCH" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM_ARCH" MODIFY ("COMMUNITY_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COMM_RS_XFM_ARCH" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
