--------------------------------------------------------
--  Constraints for Table XXMX_BEN_DE_DD_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("BEN_PLAN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("BEN_OPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("ORIGINAL_ENROLLMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("DEPENDENT_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("DEPENDENT_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("DEPENDENT_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("DEPENDENT_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_DD_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
