--------------------------------------------------------
--  Constraints for Table XXMX_PER_PHONES_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM" MODIFY ("PHONE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_PHONES_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
