--------------------------------------------------------
--  Constraints for Table XXMX_RESP_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("EBS_RESPONSIBILITY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("EBS_RESPONSIBILITY_KEY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("EBS_APPLICATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_RESP_XFM" MODIFY ("ADD_REMOVE_ROLE" NOT NULL ENABLE);
