--------------------------------------------------------
--  Constraints for Table XXMX_ASG_GRADESTEP_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ASG_GRADESTEP_XFM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_GRADESTEP_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_GRADESTEP_XFM" MODIFY ("GRADENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_GRADESTEP_XFM" MODIFY ("GRADESTEPNAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_GRADESTEP_XFM" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
