--------------------------------------------------------
--  Constraints for Table XXMX_BEN_PBB_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("BENEFIT_BALANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("BENEFIT_RELATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("UOM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM_ARCH" MODIFY ("VAL" NOT NULL ENABLE);
