--------------------------------------------------------
--  Constraints for Table XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH" MODIFY ("RELATION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH" MODIFY ("GLOBAL_ACCESS_GROUP_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH" MODIFY ("LEARNING_ITEM_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_GLOB_ACC_GRP_XFM_ARCH" MODIFY ("PRIORITY" NOT NULL ENABLE);
