--------------------------------------------------------
--  Constraints for Table XXMX_BEN_DE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("PARTICIPANT_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("PARTICIPANT_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("BENEFIT_RELATIONSHIP" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("LIFE_EVENT" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_DE_XFM_ARCH" MODIFY ("LIFE_EVENT_OCCURED_DATE" NOT NULL ENABLE);
