--------------------------------------------------------
--  DDL for Table XXMX_AP_SUPP_TAX_REG_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" 
   (	"SEGMENT1" VARCHAR2(100 BYTE), 
	"BUSINESS_UNIT" VARCHAR2(240 BYTE), 
	"VENDOR_SITE_CODE" VARCHAR2(240 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"PARTY_TYPE_CODE" VARCHAR2(80 BYTE), 
	"PARTY_NUMBER" VARCHAR2(30 BYTE), 
	"PARTY_NAME" VARCHAR2(150 BYTE), 
	"TAX_REGIME_CODE" VARCHAR2(30 BYTE), 
	"TAX" VARCHAR2(30 BYTE), 
	"TAX_JURISDICTION_CODE" VARCHAR2(30 BYTE), 
	"TAX_REGISTRATION_TYPE" VARCHAR2(80 BYTE), 
	"REGISTRATION_NUMBER" VARCHAR2(50 BYTE), 
	"EFFECTIVE_FROM" VARCHAR2(30 BYTE), 
	"EFFECTIVE_TO" VARCHAR2(30 BYTE), 
	"DEFAULT_REGISTRATION" VARCHAR2(3 BYTE), 
	"TAX_REGISTRATION_REASON" VARCHAR2(30 BYTE), 
	"TAX_REGISTRATION_STATUS" VARCHAR2(30 BYTE), 
	"SOURCE" VARCHAR2(30 BYTE), 
	"COMPANY_REPORTING_NAME" VARCHAR2(80 BYTE), 
	"ROUNDING_RULE" VARCHAR2(80 BYTE), 
	"ROUNDING_LEVEL" VARCHAR2(80 BYTE), 
	"SET_AS_SELF_ASS" VARCHAR2(3 BYTE), 
	"SET_INVOICE_VALUES_AS_TAX_INCLUSIVE" VARCHAR2(3 BYTE), 
	"TAX_POINT_BASIS" VARCHAR2(80 BYTE), 
	"ISSUE_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"COLLECTING_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"REPORTING_TAX_AUTHORITY" VARCHAR2(30 BYTE), 
	"VALIDATION_TYPE" VARCHAR2(30 BYTE), 
	"DELTA_TOLERANCE_LIMIT_TYPE" VARCHAR2(30 BYTE), 
	"MIN_DELTA_TOLERANCE_LIMIT" NUMBER, 
	"MAX_DELTA_TOLERANCE_LIMIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_READONLY";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_AP_SUPP_TAX_REG_XFM" TO "XXMX_CORE";
