--------------------------------------------------------
--  Constraints for Table XXMX_ASG_PAYROLL_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM_ARCH" MODIFY ("PAYROLL_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ASG_PAYROLL_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
