--------------------------------------------------------
--  Constraints for Table XXMX_POSITIONS_F_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_POSITIONS_F_XFM" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_POSITIONS_F_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_POSITIONS_F_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
