--------------------------------------------------------
--  Constraints for Table XXMX_BEN_BE_DB_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BEN_PLAN" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BEN_OPTION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("ORIGINAL_ENROLLMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("LINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_BE_DB_XFM_ARCH" MODIFY ("BENEFICIARY_FIRST_NAME" NOT NULL ENABLE);
