--------------------------------------------------------
--  Constraints for Table XXMX_OLC_SPEC_DEF_ACC_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_DEF_ACC_XFM" MODIFY ("DEFAULT_ACCESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_DEF_ACC_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_SPEC_DEF_ACC_XFM" MODIFY ("SPECIALIZATION_NUMBER" NOT NULL ENABLE);
