--------------------------------------------------------
--  Constraints for Table XXMX_PER_ABSENCE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM_ARCH" MODIFY ("ABSENCENAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM_ARCH" MODIFY ("STARTDATEDURATION" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ABSENCE_XFM_ARCH" MODIFY ("ENDDATEDURATION" NOT NULL ENABLE);
