--------------------------------------------------------
--  Constraints for Table XXMX_PER_ASG_SALARY_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM_ARCH" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM_ARCH" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM_ARCH" MODIFY ("PROPOSED_SALARY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_ASG_SALARY_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
