--------------------------------------------------------
--  DDL for Table XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" 
   (	"BATCH_ID" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"INT_REC_ID" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER, 
	"SOURCENAME" VARCHAR2(80 BYTE), 
	"SOURCEREF" VARCHAR2(80 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
	"CONTRACT_TYPE_NAME" VARCHAR2(150 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(120 BYTE), 
	"CONTRACT_LINE_NUMBER" VARCHAR2(150 BYTE), 
	"EVENT_TYPE_NAME" VARCHAR2(240 BYTE), 
	"EVENT_DESC" VARCHAR2(240 BYTE), 
	"COMPLETION_DATE" VARCHAR2(240 BYTE), 
	"BILL_TRNS_CURRENCY_CODE" VARCHAR2(15 BYTE), 
	"BILL_TRNS_AMOUNT" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"BILL_HOLD_FLAG" VARCHAR2(1 BYTE), 
	"REVENUE_HOLD_FLAG" VARCHAR2(1 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR11" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR12" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR13" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR14" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR15" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR16" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR17" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR18" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR19" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR20" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR21" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR22" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR23" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR24" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR25" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR26" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR27" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR28" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR29" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_CHAR30" VARCHAR2(240 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"REVERSE_ACCRUAL_FLAG" VARCHAR2(1 BYTE), 
	"ITEM_EVENT_FLAG" VARCHAR2(1 BYTE), 
	"QUANTITY" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(300 BYTE), 
	"UNIT_OF_MEASURE" VARCHAR2(25 BYTE), 
	"UNIT_PRICE" NUMBER, 
	"LOAD_STATUS" VARCHAR2(10 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(64 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PPM_PRJ_BILLEVENT_XFM_ARCH" TO "XXMX_CORE";
