--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACTS_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACTS_XFM_ARCH" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACTS_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACTS_XFM_ARCH" MODIFY ("CNTPERSONNUMBER" NOT NULL ENABLE);
