--------------------------------------------------------
--  Constraints for Table XXMX_OLC_INSTR_RES_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RES_XFM_ARCH" MODIFY ("INSTRUCTOR_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RES_XFM_ARCH" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_INSTR_RES_XFM_ARCH" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
