--------------------------------------------------------
--  Constraints for Table XXMX_OLC_CLASS_RES_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_TL_XFM" MODIFY ("CLASSROOM_RESOURCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_CLASS_RES_TL_XFM" MODIFY ("TITLE" NOT NULL ENABLE);
