--------------------------------------------------------
--  Constraints for Table XXMX_BEN_PBB_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("BENEFIT_BALANCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("BENEFIT_RELATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("UOM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_BEN_PBB_XFM" MODIFY ("VAL" NOT NULL ENABLE);
