--------------------------------------------------------
--  Constraints for Table XXMX_ORG_UNITS_F_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNITS_F_TL_XFM" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNITS_F_TL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNITS_F_TL_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_ORG_UNITS_F_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
