--------------------------------------------------------
--  Constraints for Table XXMX_PER_DISABILITY_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM_ARCH" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM_ARCH" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_DISABILITY_XFM_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
