--------------------------------------------------------
--  Constraints for Table XXMX_PER_RELIGION_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_RELIGION_XFM_ARCH" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_RELIGION_XFM_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_RELIGION_XFM_ARCH" MODIFY ("RELIGION" NOT NULL ENABLE);
