--------------------------------------------------------
--  Constraints for Table XXMX_PER_CONTACT_REL_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM_ARCH" MODIFY ("EFFECTIVESTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM_ARCH" MODIFY ("CONTACTTYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM_ARCH" MODIFY ("RELATEDPERSONNUM" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_PER_CONTACT_REL_XFM_ARCH" MODIFY ("CONTACT_PERSONNUM" NOT NULL ENABLE);
