--------------------------------------------------------
--  Constraints for Table XXMX_LOC_DETAILS_F_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_LOC_DETAILS_F_XFM" MODIFY ("LOCATION_DETAILS_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_LOC_DETAILS_F_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_LOC_DETAILS_F_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
