--------------------------------------------------------
--  DDL for Table XXMX_HCM_IREC_CJA_QSTN_RESP_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'QuestionResponse', 
	"ANSWER_TEXT" VARCHAR2(4000 BYTE), 
	"QSTN_RESPONSE_ID" NUMBER(18,0), 
	"QSTNR_QUESTION_ID" NUMBER(18,0), 
	"QSTNR_RESPONSE_ID" NUMBER(18,0), 
	"QUESTION_ID" NUMBER(18,0), 
	"QSTNR_SECTION_ID" NUMBER(18,0), 
	"QUESTION_CODE" VARCHAR2(240 BYTE), 
	"QSTN_VERSION_NUM" NUMBER(18,0), 
	"ATTEMPT_NUM" NUMBER(18,0), 
	"QSTNR_VERSION_NUM" NUMBER(18,0), 
	"QUESTIONNAIRE_ID" NUMBER(18,0), 
	"SUBJECT_ID" NUMBER(18,0), 
	"QUESTIONNAIRE_CODE" VARCHAR2(240 BYTE), 
	"REQUISITION_ID" NUMBER(18,0), 
	"PERSON_ID" NUMBER(18,0), 
	"REQUISITION_NUMBER" VARCHAR2(240 BYTE), 
	"CANDIDATE_NUMBER" VARCHAR2(30 BYTE), 
	"SECTION_SEQ_NUM" NUMBER(18,0), 
	"ANSWER_CODE" VARCHAR2(100 BYTE), 
	"ANSWER_CODES" VARCHAR2(100 BYTE), 
	"GUID" VARCHAR2(32 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_HCM_IREC_CJA_QSTN_RESP_XFM" TO "XXMX_CORE";
