--------------------------------------------------------
--  DDL for Table XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"INTERFACE_LINE_LOCATION_KEY" VARCHAR2(50 BYTE), 
	"INTERFACE_LINE_KEY" VARCHAR2(50 BYTE), 
	"SHIPMENT_NUM" NUMBER, 
	"SHIP_TO_LOCATION" VARCHAR2(60 BYTE), 
	"SHIP_TO_ORGANIZATION_CODE" VARCHAR2(18 BYTE), 
	"QUANTITY" NUMBER, 
	"PRICE_OVERRIDE" NUMBER, 
	"PRICE_DISCOUNT" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE15" VARCHAR2(150 BYTE), 
	"ATTRIBUTE16" VARCHAR2(150 BYTE), 
	"ATTRIBUTE17" VARCHAR2(150 BYTE), 
	"ATTRIBUTE18" VARCHAR2(150 BYTE), 
	"ATTRIBUTE19" VARCHAR2(150 BYTE), 
	"ATTRIBUTE20" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_NUMBER1" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER2" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER3" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER4" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER5" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER6" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER7" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER8" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER9" NUMBER(18,0), 
	"ATTRIBUTE_NUMBER10" NUMBER(18,0), 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP6" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP7" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP8" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP9" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP10" TIMESTAMP (6), 
	"PO_HEADER_ID" VARCHAR2(30 BYTE), 
	"PO_LINE_ID" VARCHAR2(30 BYTE), 
	"LINE_LOCATION_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_READONLY";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_SCM_PO_LINE_LOCATIONS_BPA_XFM_ARCH" TO "XXMX_CORE";
