--------------------------------------------------------
--  Constraints for Table XXMX_OLC_COURSE_XFM_ARCH
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_XFM_ARCH" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_XFM_ARCH" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_XFM_ARCH" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_OLC_COURSE_XFM_ARCH" MODIFY ("OWNED_BY_PERSON_NUMBER" NOT NULL ENABLE);
