--------------------------------------------------------
--  DDL for Table XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(100 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BATCH_ID" VARCHAR2(80 BYTE), 
	"BATCH_NAME" VARCHAR2(240 BYTE), 
	"TXN_CTRL_REFERENCE" VARCHAR2(240 BYTE), 
	"PROJECT_NAME" VARCHAR2(240 BYTE), 
	"PROJECT_NUMBER" VARCHAR2(25 BYTE), 
	"TASK_NUMBER" VARCHAR2(100 BYTE), 
	"TASK_NAME" VARCHAR2(255 BYTE), 
	"EXPENDITURE_CATEGORY_NAME" VARCHAR2(240 BYTE), 
	"EXPENDITURE_TYPE" VARCHAR2(240 BYTE), 
	"NON_LABOR_RESOURCE" VARCHAR2(240 BYTE), 
	"PERSON_NUMBER" VARCHAR2(30 BYTE), 
	"PERSON_NAME" VARCHAR2(2000 BYTE), 
	"PERSON_EMAIL" VARCHAR2(360 BYTE), 
	"PERSON_TYPE" VARCHAR2(20 BYTE), 
	"JOB_NAME" VARCHAR2(240 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(240 BYTE), 
	"CHARGEABLE_FLAG" VARCHAR2(1 BYTE), 
	"BILLABLE_FLAG" VARCHAR2(1 BYTE), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT ALTER ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT DELETE ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT INDEX ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT INSERT ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_READONLY";
  GRANT SELECT ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT UPDATE ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT REFERENCES ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT READ ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT QUERY REWRITE ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT DEBUG ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT FLASHBACK ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
  GRANT ON COMMIT REFRESH ON "XXMX_XFM"."XXMX_PPM_PRJ_TRX_CONTROL_XFM_ARCH" TO "XXMX_CORE";
