--------------------------------------------------------
--  DDL for Table XXMX_HCM_IREC_CAN_JOBAPPL_XFM
--------------------------------------------------------

  CREATE TABLE "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOBAPPL_XFM" 
   (	"FILE_SET_ID" VARCHAR2(30 BYTE), 
	"MIGRATION_SET_ID" NUMBER, 
	"MIGRATION_SET_NAME" VARCHAR2(150 BYTE), 
	"MIGRATION_STATUS" VARCHAR2(50 BYTE), 
	"BG_NAME" VARCHAR2(240 BYTE), 
	"BG_ID" NUMBER(15,0), 
	"METADATA" VARCHAR2(150 BYTE) DEFAULT 'MERGE', 
	"OBJECTNAME" VARCHAR2(150 BYTE) DEFAULT 'Candidate', 
	"CANDIDATE_NUMBER" VARCHAR2(200 BYTE), 
	"OBJECT_STATUS" VARCHAR2(30 BYTE), 
	"AVAILABILITY_DATE" VARCHAR2(80 BYTE), 
	"SEARCH_DATE" DATE, 
	"CAND_LAST_MODIFIED_DATE" DATE, 
	"ADDED_BY_FLOW_CODE" VARCHAR2(30 BYTE), 
	"CONFIRMED_FLAG" VARCHAR2(1 BYTE), 
	"VISIBLE_TO_CANDIDATE_FLAG" VARCHAR2(1 BYTE), 
	"START_DATE" VARCHAR2(80 BYTE), 
	"SOURCE" VARCHAR2(500 BYTE), 
	"SOURCE_MEDIUM" VARCHAR2(500 BYTE), 
	"CATEGORY_CODE" VARCHAR2(80 BYTE), 
	"PHONE_VERIFIED_FLAG" VARCHAR2(30 BYTE), 
	"GUID" VARCHAR2(32 BYTE), 
	"SOURCE_SYSTEM_ID" VARCHAR2(2000 BYTE), 
	"SOURCE_SYSTEM_OWNER" VARCHAR2(256 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30 BYTE), 
	"ATTRIBUTE1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"REQUISITION_NUMBER" VARCHAR2(80 BYTE), 
	"CURRENT_PHASE_CODE" VARCHAR2(120 BYTE), 
	"CURRENT_STATE_CODE" VARCHAR2(120 BYTE), 
	"NOTES" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XXMX_XFM" ;
  GRANT SELECT ON "XXMX_XFM"."XXMX_HCM_IREC_CAN_JOBAPPL_XFM" TO "XXMX_READONLY";
