--------------------------------------------------------
--  Constraints for Table XXMX_USER_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("MIGRATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("MIGRATION_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("MIGRATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("METADATA" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("RECORD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("ORIG_USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_USER_XFM" MODIFY ("GENERATE_USER_ACCOUNT" NOT NULL ENABLE);
