--------------------------------------------------------
--  Constraints for Table XXMX_GRADES_F_TL_XFM
--------------------------------------------------------

  ALTER TABLE "XXMX_XFM"."XXMX_GRADES_F_TL_XFM" MODIFY ("GRADE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_GRADES_F_TL_XFM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_GRADES_F_TL_XFM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXMX_XFM"."XXMX_GRADES_F_TL_XFM" MODIFY ("LANGUAGE" NOT NULL ENABLE);
