LOAD DATA
INFILE XXMX_OLC_CLASSROOM_RESERVATION.dat
REPLACE 
INTO  TABLE XXMX_OLC_CLASS_RESV_STG
FIELDS TERMINATED BY "|" TRAILING NULLCOLS 
(ACTIVITY_NUMBER                ,
MIGRATION_SET_ID               ,
MIGRATION_SET_NAME             ,
MIGRATION_STATUS               ,
BG_NAME                        ,
BG_ID                          ,
CLASSROOM_RESERVATION_NUMBER   ,
CLASSROOM_RESOURCE_NUMBER      
)

