EXEC DROPTABLE ( 'XXMX_MAPPING_HCM_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_MAPPING_HCM_EXT" 
   (	"SIMPLE_OR_COMPLEX" VARCHAR2(30 BYTE), 
	"APPLICATION_SUITE" VARCHAR2(30 BYTE), 
	"APPLICATION" VARCHAR2(30 BYTE), 
	"SOURCE_VALUE" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_2" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_3" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_4" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"TARGET_VALUE" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_1_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6_DESC" VARCHAR2(1000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'Mapping_Master_Maximise_HCM.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'Mapping_Master_Maximise_HCM*.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


EXEC DROPTABLE ( 'XXMX_MAPPING_SCM_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_MAPPING_SCM_EXT" 
   (	"SIMPLE_OR_COMPLEX" VARCHAR2(30 BYTE), 
	"APPLICATION_SUITE" VARCHAR2(30 BYTE), 
	"APPLICATION" VARCHAR2(30 BYTE), 
	"SOURCE_VALUE" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_2" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_3" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_4" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"TARGET_VALUE" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_1_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6_DESC" VARCHAR2(1000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'Mapping_Master_Maximise_SCM.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'Mapping_Master_Maximise_SCM*.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;



EXEC DROPTABLE ( 'XXMX_MAPPING_FIN_EXT')
  CREATE TABLE "XXMX_CORE"."XXMX_MAPPING_FIN_EXT" 
   (	"SIMPLE_OR_COMPLEX" VARCHAR2(30 BYTE), 
	"APPLICATION_SUITE" VARCHAR2(30 BYTE), 
	"APPLICATION" VARCHAR2(30 BYTE), 
	"SOURCE_VALUE" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_2" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_3" VARCHAR2(1000 BYTE), 
	"INPUT_VALUE_4" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"INPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"CATEGORY_CODE" VARCHAR2(30 BYTE), 
	"TARGET_VALUE" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_1_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_2_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_3_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_4_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_5_DESC" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6" VARCHAR2(1000 BYTE), 
	"OUTPUT_CODE_6_DESC" VARCHAR2(1000 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'Mapping_Master_Maximise_FIN.log' fields terminated by "|" optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'Mapping_Master_Maximise_FIN*.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;



