EXEC DropTable ('XXMX_GL_BALANCES_EXT')
CREATE TABLE XXMX_CORE.XXMX_GL_BALANCES_EXT
(
   FILE_SET_ID                         VARCHAR2(30),  
   FUSION_STATUS_CODE                  VARCHAR2(50),  
   LEDGER_ID                           NUMBER(18),    
   ACCOUNTING_DATE                     VARCHAR2(20),          
   USER_JE_SOURCE_NAME                 VARCHAR2(25),  
   USER_JE_CATEGORY_NAME               VARCHAR2(25),  
   CURRENCY_CODE                       VARCHAR2(15),  
   DATE_CREATED                        VARCHAR2(20),          
   ACTUAL_FLAG                         VARCHAR2(1),   
   SEGMENT1                            VARCHAR2(25),  
   SEGMENT2                            VARCHAR2(25),  
   SEGMENT3                            VARCHAR2(25),  
   SEGMENT4                            VARCHAR2(25),  
   SEGMENT5                            VARCHAR2(25),  
   SEGMENT6                            VARCHAR2(25),  
   SEGMENT7                            VARCHAR2(25),  
   SEGMENT8                            VARCHAR2(25),  
   SEGMENT9                            VARCHAR2(25),  
   SEGMENT10                           VARCHAR2(25),  
   ENTERED_DR                          NUMBER,        
   ENTERED_CR                          NUMBER,        
   ACCOUNTED_DR                        NUMBER,        
   ACCOUNTED_CR                        NUMBER,        
   REFERENCE1                          VARCHAR2(100), 
   REFERENCE2                          VARCHAR2(240), 
   REFERENCE3                          VARCHAR2(100), 
   REFERENCE4                          VARCHAR2(100), 
   REFERENCE5                          VARCHAR2(240), 
   REFERENCE6                          VARCHAR2(100), 
   REFERENCE7                          VARCHAR2(100), 
   REFERENCE8                          VARCHAR2(100), 
   REFERENCE9                          VARCHAR2(100), 
   REFERENCE10                         VARCHAR2(240), 
   STAT_AMOUNT                         NUMBER,        
   USER_CURRENCY_CONVERSION_TYPE       VARCHAR2(30),  
   CURRENCY_CONVERSION_DATE            VARCHAR2(20),          
   CURRENCY_CONVERSION_RATE            NUMBER,        
   GROUP_ID                            NUMBER(18),    
   ATTRIBUTE_CATEGORY                  VARCHAR2(150), 
   ATTRIBUTE1                          VARCHAR2(150), 
   ATTRIBUTE2                          VARCHAR2(150), 
   ATTRIBUTE3                          VARCHAR2(150), 
   ATTRIBUTE4                          VARCHAR2(150), 
   ATTRIBUTE5                          VARCHAR2(150), 
   ATTRIBUTE6                          VARCHAR2(150), 
   ATTRIBUTE7                          VARCHAR2(150), 
   ATTRIBUTE8                          VARCHAR2(150), 
   ATTRIBUTE9                          VARCHAR2(150), 
   ATTRIBUTE10                         VARCHAR2(150), 
   ATTRIBUTE11                         VARCHAR2(150), 
   ATTRIBUTE12                         VARCHAR2(150), 
   ATTRIBUTE13                         VARCHAR2(150), 
   ATTRIBUTE14                         VARCHAR2(150), 
   ATTRIBUTE15                         VARCHAR2(150), 
   ATTRIBUTE16                         VARCHAR2(150), 
   ATTRIBUTE17                         VARCHAR2(150), 
   ATTRIBUTE18                         VARCHAR2(150), 
   ATTRIBUTE19                         VARCHAR2(150), 
   ATTRIBUTE20                         VARCHAR2(150), 
   ATTRIBUTE_CATEGORY3                 VARCHAR2(150), 
   AVERAGE_JOURNAL_FLAG                VARCHAR2(1),
   ORIGINATING_BAL_SEG_VALUE           VARCHAR2(25),  
   LEDGER_NAME                         VARCHAR2(30),  
   ENCUMBRANCE_TYPE_ID                 NUMBER,        
   JGZZ_RECON_REF                      VARCHAR2(240), 
   PERIOD_NAME                         VARCHAR2(15),  
   ATTRIBUTE_DATE1                     VARCHAR2(20),          
   ATTRIBUTE_DATE2                     VARCHAR2(20),          
   ATTRIBUTE_DATE3                     VARCHAR2(20),          
   ATTRIBUTE_DATE4                     VARCHAR2(20),          
   ATTRIBUTE_DATE5                     VARCHAR2(20),          
   ATTRIBUTE_DATE6                     VARCHAR2(20),          
   ATTRIBUTE_DATE7                     VARCHAR2(20),          
   ATTRIBUTE_DATE8                     VARCHAR2(20),          
   ATTRIBUTE_DATE9                     VARCHAR2(20),          
   ATTRIBUTE_DATE10                    VARCHAR2(20),          
   ATTRIBUTE_NUMBER1                   NUMBER,        
   ATTRIBUTE_NUMBER2                   NUMBER,        
   ATTRIBUTE_NUMBER3                   NUMBER,        
   ATTRIBUTE_NUMBER4                   NUMBER,        
   ATTRIBUTE_NUMBER5                   NUMBER,        
   ATTRIBUTE_NUMBER6                   NUMBER,        
   ATTRIBUTE_NUMBER7                   NUMBER,        
   ATTRIBUTE_NUMBER8                   NUMBER,        
   ATTRIBUTE_NUMBER9                   NUMBER,        
   ATTRIBUTE_NUMBER10                  NUMBER,        
   GLOBAL_ATTRIBUTE_CATEGORY           VARCHAR2(30),  
   GLOBAL_ATTRIBUTE1                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE2                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE3                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE4                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE5                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE6                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE7                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE8                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE9                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE10                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE11                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE12                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE13                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE14                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE15                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE16                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE17                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE18                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE19                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE20                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE_DATE1              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE2              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE3              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE4              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE5              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_NUMBER1            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER2            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER3            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER4            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER5            NUMBER  
)
  ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_GL_BALANCES_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_GL_BALANCES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;   

EXEC DropTable ('XXMX_GL_OPENING_BALANCES_EXT')


CREATE TABLE XXMX_CORE.XXMX_GL_OPENING_BALANCES_EXT
(
   FILE_SET_ID                         VARCHAR2(30),  
   FUSION_STATUS_CODE                  VARCHAR2(50),  
   LEDGER_ID                           NUMBER(18),    
   ACCOUNTING_DATE                     VARCHAR2(20),          
   USER_JE_SOURCE_NAME                 VARCHAR2(25),  
   USER_JE_CATEGORY_NAME               VARCHAR2(25),  
   CURRENCY_CODE                       VARCHAR2(15),  
   DATE_CREATED                        VARCHAR2(20),                 
   ACTUAL_FLAG                         VARCHAR2(1),   
   SEGMENT1                            VARCHAR2(25),  
   SEGMENT2                            VARCHAR2(25),  
   SEGMENT3                            VARCHAR2(25),  
   SEGMENT4                            VARCHAR2(25),  
   SEGMENT5                            VARCHAR2(25),  
   SEGMENT6                            VARCHAR2(25),  
   SEGMENT7                            VARCHAR2(25),  
   SEGMENT8                            VARCHAR2(25),  
   SEGMENT9                            VARCHAR2(25),  
   SEGMENT10                           VARCHAR2(25),  
   ENTERED_DR                          NUMBER,        
   ENTERED_CR                          NUMBER,        
   ACCOUNTED_DR                        NUMBER,        
   ACCOUNTED_CR                        NUMBER,        
   REFERENCE1                          VARCHAR2(100), 
   REFERENCE2                          VARCHAR2(240), 
   REFERENCE3                          VARCHAR2(100), 
   REFERENCE4                          VARCHAR2(100), 
   REFERENCE5                          VARCHAR2(240), 
   REFERENCE6                          VARCHAR2(100), 
   REFERENCE7                          VARCHAR2(100), 
   REFERENCE8                          VARCHAR2(100), 
   REFERENCE9                          VARCHAR2(100), 
   REFERENCE10                         VARCHAR2(240), 
   STAT_AMOUNT                         NUMBER,        
   USER_CURRENCY_CONVERSION_TYPE       VARCHAR2(30),  
   CURRENCY_CONVERSION_DATE            VARCHAR2(20),          
   CURRENCY_CONVERSION_RATE            NUMBER,        
   GROUP_ID                            NUMBER(18),    
   ATTRIBUTE_CATEGORY                  VARCHAR2(150), 
   ATTRIBUTE1                          VARCHAR2(150), 
   ATTRIBUTE2                          VARCHAR2(150), 
   ATTRIBUTE3                          VARCHAR2(150), 
   ATTRIBUTE4                          VARCHAR2(150), 
   ATTRIBUTE5                          VARCHAR2(150), 
   ATTRIBUTE6                          VARCHAR2(150), 
   ATTRIBUTE7                          VARCHAR2(150), 
   ATTRIBUTE8                          VARCHAR2(150), 
   ATTRIBUTE9                          VARCHAR2(150), 
   ATTRIBUTE10                         VARCHAR2(150), 
   ATTRIBUTE11                         VARCHAR2(150), 
   ATTRIBUTE12                         VARCHAR2(150), 
   ATTRIBUTE13                         VARCHAR2(150), 
   ATTRIBUTE14                         VARCHAR2(150), 
   ATTRIBUTE15                         VARCHAR2(150), 
   ATTRIBUTE16                         VARCHAR2(150), 
   ATTRIBUTE17                         VARCHAR2(150), 
   ATTRIBUTE18                         VARCHAR2(150), 
   ATTRIBUTE19                         VARCHAR2(150), 
   ATTRIBUTE20                         VARCHAR2(150), 
   ATTRIBUTE_CATEGORY3                 VARCHAR2(150), 
   AVERAGE_JOURNAL_FLAG                VARCHAR2(1),
   ORIGINATING_BAL_SEG_VALUE           VARCHAR2(25),  
   LEDGER_NAME                         VARCHAR2(30),  
   ENCUMBRANCE_TYPE_ID                 NUMBER,        
   JGZZ_RECON_REF                      VARCHAR2(240), 
   PERIOD_NAME                         VARCHAR2(15),  
   ATTRIBUTE_DATE1                     VARCHAR2(20),          
   ATTRIBUTE_DATE2                     VARCHAR2(20),          
   ATTRIBUTE_DATE3                     VARCHAR2(20),          
   ATTRIBUTE_DATE4                     VARCHAR2(20),          
   ATTRIBUTE_DATE5                     VARCHAR2(20),          
   ATTRIBUTE_DATE6                     VARCHAR2(20),          
   ATTRIBUTE_DATE7                     VARCHAR2(20),          
   ATTRIBUTE_DATE8                     VARCHAR2(20),          
   ATTRIBUTE_DATE9                     VARCHAR2(20),          
   ATTRIBUTE_DATE10                    VARCHAR2(20),          
   ATTRIBUTE_NUMBER1                   NUMBER,        
   ATTRIBUTE_NUMBER2                   NUMBER,        
   ATTRIBUTE_NUMBER3                   NUMBER,        
   ATTRIBUTE_NUMBER4                   NUMBER,        
   ATTRIBUTE_NUMBER5                   NUMBER,        
   ATTRIBUTE_NUMBER6                   NUMBER,        
   ATTRIBUTE_NUMBER7                   NUMBER,        
   ATTRIBUTE_NUMBER8                   NUMBER,        
   ATTRIBUTE_NUMBER9                   NUMBER,        
   ATTRIBUTE_NUMBER10                  NUMBER,        
   GLOBAL_ATTRIBUTE_CATEGORY           VARCHAR2(30),  
   GLOBAL_ATTRIBUTE1                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE2                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE3                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE4                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE5                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE6                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE7                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE8                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE9                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE10                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE11                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE12                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE13                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE14                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE15                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE16                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE17                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE18                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE19                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE20                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE_DATE1              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE2              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE3              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE4              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE5              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_NUMBER1            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER2            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER3            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER4            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER5            NUMBER  
)
  ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_GL_OPENING_BALANCES_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_GL_OPENING_BALANCES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;   


EXEC DropTable ('XXMX_GL_SUMMARY_BALANCES_EXT')

CREATE TABLE XXMX_CORE.XXMX_GL_SUMMARY_BALANCES_EXT
(
   FILE_SET_ID                         VARCHAR2(30),  
   FUSION_STATUS_CODE                  VARCHAR2(50),  
   LEDGER_ID                           NUMBER(18),    
   ACCOUNTING_DATE                     VARCHAR2(20),          
   USER_JE_SOURCE_NAME                 VARCHAR2(25),  
   USER_JE_CATEGORY_NAME               VARCHAR2(25),  
   CURRENCY_CODE                       VARCHAR2(15),  
   DATE_CREATED                        VARCHAR2(20),                    
   ACTUAL_FLAG                         VARCHAR2(1),   
   SEGMENT1                            VARCHAR2(25),  
   SEGMENT2                            VARCHAR2(25),  
   SEGMENT3                            VARCHAR2(25),  
   SEGMENT4                            VARCHAR2(25),  
   SEGMENT5                            VARCHAR2(25),  
   SEGMENT6                            VARCHAR2(25),  
   SEGMENT7                            VARCHAR2(25),  
   SEGMENT8                            VARCHAR2(25),  
   SEGMENT9                            VARCHAR2(25),  
   SEGMENT10                           VARCHAR2(25),  
   ENTERED_DR                          NUMBER,        
   ENTERED_CR                          NUMBER,        
   ACCOUNTED_DR                        NUMBER,        
   ACCOUNTED_CR                        NUMBER,        
   REFERENCE1                          VARCHAR2(100), 
   REFERENCE2                          VARCHAR2(240), 
   REFERENCE3                          VARCHAR2(100), 
   REFERENCE4                          VARCHAR2(100), 
   REFERENCE5                          VARCHAR2(240), 
   REFERENCE6                          VARCHAR2(100), 
   REFERENCE7                          VARCHAR2(100), 
   REFERENCE8                          VARCHAR2(100), 
   REFERENCE9                          VARCHAR2(100), 
   REFERENCE10                         VARCHAR2(240), 
   STAT_AMOUNT                         NUMBER,        
   USER_CURRENCY_CONVERSION_TYPE       VARCHAR2(30),  
   CURRENCY_CONVERSION_DATE            VARCHAR2(20),          
   CURRENCY_CONVERSION_RATE            NUMBER,        
   GROUP_ID                            NUMBER(18),    
   ATTRIBUTE_CATEGORY                  VARCHAR2(150), 
   ATTRIBUTE1                          VARCHAR2(150), 
   ATTRIBUTE2                          VARCHAR2(150), 
   ATTRIBUTE3                          VARCHAR2(150), 
   ATTRIBUTE4                          VARCHAR2(150), 
   ATTRIBUTE5                          VARCHAR2(150), 
   ATTRIBUTE6                          VARCHAR2(150), 
   ATTRIBUTE7                          VARCHAR2(150), 
   ATTRIBUTE8                          VARCHAR2(150), 
   ATTRIBUTE9                          VARCHAR2(150), 
   ATTRIBUTE10                         VARCHAR2(150), 
   ATTRIBUTE11                         VARCHAR2(150), 
   ATTRIBUTE12                         VARCHAR2(150), 
   ATTRIBUTE13                         VARCHAR2(150), 
   ATTRIBUTE14                         VARCHAR2(150), 
   ATTRIBUTE15                         VARCHAR2(150), 
   ATTRIBUTE16                         VARCHAR2(150), 
   ATTRIBUTE17                         VARCHAR2(150), 
   ATTRIBUTE18                         VARCHAR2(150), 
   ATTRIBUTE19                         VARCHAR2(150), 
   ATTRIBUTE20                         VARCHAR2(150), 
   ATTRIBUTE_CATEGORY3                 VARCHAR2(150), 
   AVERAGE_JOURNAL_FLAG                VARCHAR2(1),
   ORIGINATING_BAL_SEG_VALUE           VARCHAR2(25),  
   LEDGER_NAME                         VARCHAR2(30),  
   ENCUMBRANCE_TYPE_ID                 NUMBER,        
   JGZZ_RECON_REF                      VARCHAR2(240), 
   PERIOD_NAME                         VARCHAR2(15),  
   ATTRIBUTE_DATE1                     VARCHAR2(20),          
   ATTRIBUTE_DATE2                     VARCHAR2(20),          
   ATTRIBUTE_DATE3                     VARCHAR2(20),          
   ATTRIBUTE_DATE4                     VARCHAR2(20),          
   ATTRIBUTE_DATE5                     VARCHAR2(20),          
   ATTRIBUTE_DATE6                     VARCHAR2(20),          
   ATTRIBUTE_DATE7                     VARCHAR2(20),          
   ATTRIBUTE_DATE8                     VARCHAR2(20),          
   ATTRIBUTE_DATE9                     VARCHAR2(20),          
   ATTRIBUTE_DATE10                    VARCHAR2(20),          
   ATTRIBUTE_NUMBER1                   NUMBER,        
   ATTRIBUTE_NUMBER2                   NUMBER,        
   ATTRIBUTE_NUMBER3                   NUMBER,        
   ATTRIBUTE_NUMBER4                   NUMBER,        
   ATTRIBUTE_NUMBER5                   NUMBER,        
   ATTRIBUTE_NUMBER6                   NUMBER,        
   ATTRIBUTE_NUMBER7                   NUMBER,        
   ATTRIBUTE_NUMBER8                   NUMBER,        
   ATTRIBUTE_NUMBER9                   NUMBER,        
   ATTRIBUTE_NUMBER10                  NUMBER,        
   GLOBAL_ATTRIBUTE_CATEGORY           VARCHAR2(30),  
   GLOBAL_ATTRIBUTE1                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE2                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE3                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE4                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE5                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE6                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE7                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE8                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE9                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE10                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE11                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE12                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE13                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE14                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE15                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE16                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE17                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE18                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE19                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE20                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE_DATE1              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE2              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE3              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE4              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE5              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_NUMBER1            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER2            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER3            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER4            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER5            NUMBER  
)
  ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_GL_SUMMARY_BALANCES_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_GL_SUMMARY_BALANCES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;   


EXEC DropTable ('XXMX_GL_DETAIL_BALANCES_EXT')

CREATE TABLE XXMX_CORE.XXMX_GL_DETAIL_BALANCES_EXT
(
   FILE_SET_ID                         VARCHAR2(30),  
   FUSION_STATUS_CODE                  VARCHAR2(50),  
   LEDGER_ID                           NUMBER(18),    
   ACCOUNTING_DATE                     VARCHAR2(20),          
   USER_JE_SOURCE_NAME                 VARCHAR2(25),  
   USER_JE_CATEGORY_NAME               VARCHAR2(25),  
   CURRENCY_CODE                       VARCHAR2(15),  
   DATE_CREATED                        VARCHAR2(20),                   
   ACTUAL_FLAG                         VARCHAR2(1),   
   SEGMENT1                            VARCHAR2(25),  
   SEGMENT2                            VARCHAR2(25),  
   SEGMENT3                            VARCHAR2(25),  
   SEGMENT4                            VARCHAR2(25),  
   SEGMENT5                            VARCHAR2(25),  
   SEGMENT6                            VARCHAR2(25),  
   SEGMENT7                            VARCHAR2(25),  
   SEGMENT8                            VARCHAR2(25),  
   SEGMENT9                            VARCHAR2(25),  
   SEGMENT10                           VARCHAR2(25),  
   ENTERED_DR                          NUMBER,        
   ENTERED_CR                          NUMBER,        
   ACCOUNTED_DR                        NUMBER,        
   ACCOUNTED_CR                        NUMBER,        
   REFERENCE1                          VARCHAR2(100), 
   REFERENCE2                          VARCHAR2(240), 
   REFERENCE3                          VARCHAR2(100), 
   REFERENCE4                          VARCHAR2(100), 
   REFERENCE5                          VARCHAR2(240), 
   REFERENCE6                          VARCHAR2(100), 
   REFERENCE7                          VARCHAR2(100), 
   REFERENCE8                          VARCHAR2(100), 
   REFERENCE9                          VARCHAR2(100), 
   REFERENCE10                         VARCHAR2(240), 
   STAT_AMOUNT                         NUMBER,        
   USER_CURRENCY_CONVERSION_TYPE       VARCHAR2(30),  
   CURRENCY_CONVERSION_DATE            VARCHAR2(20),          
   CURRENCY_CONVERSION_RATE            NUMBER,        
   GROUP_ID                            NUMBER(18),    
   ATTRIBUTE_CATEGORY                  VARCHAR2(150), 
   ATTRIBUTE1                          VARCHAR2(150), 
   ATTRIBUTE2                          VARCHAR2(150), 
   ATTRIBUTE3                          VARCHAR2(150), 
   ATTRIBUTE4                          VARCHAR2(150), 
   ATTRIBUTE5                          VARCHAR2(150), 
   ATTRIBUTE6                          VARCHAR2(150), 
   ATTRIBUTE7                          VARCHAR2(150), 
   ATTRIBUTE8                          VARCHAR2(150), 
   ATTRIBUTE9                          VARCHAR2(150), 
   ATTRIBUTE10                         VARCHAR2(150), 
   ATTRIBUTE11                         VARCHAR2(150), 
   ATTRIBUTE12                         VARCHAR2(150), 
   ATTRIBUTE13                         VARCHAR2(150), 
   ATTRIBUTE14                         VARCHAR2(150), 
   ATTRIBUTE15                         VARCHAR2(150), 
   ATTRIBUTE16                         VARCHAR2(150), 
   ATTRIBUTE17                         VARCHAR2(150), 
   ATTRIBUTE18                         VARCHAR2(150), 
   ATTRIBUTE19                         VARCHAR2(150), 
   ATTRIBUTE20                         VARCHAR2(150), 
   ATTRIBUTE_CATEGORY3                 VARCHAR2(150), 
   AVERAGE_JOURNAL_FLAG                VARCHAR2(1),
   ORIGINATING_BAL_SEG_VALUE           VARCHAR2(25),  
   LEDGER_NAME                         VARCHAR2(30),  
   ENCUMBRANCE_TYPE_ID                 NUMBER,        
   JGZZ_RECON_REF                      VARCHAR2(240), 
   PERIOD_NAME                         VARCHAR2(15),  
   ATTRIBUTE_DATE1                     VARCHAR2(20),          
   ATTRIBUTE_DATE2                     VARCHAR2(20),          
   ATTRIBUTE_DATE3                     VARCHAR2(20),          
   ATTRIBUTE_DATE4                     VARCHAR2(20),          
   ATTRIBUTE_DATE5                     VARCHAR2(20),          
   ATTRIBUTE_DATE6                     VARCHAR2(20),          
   ATTRIBUTE_DATE7                     VARCHAR2(20),          
   ATTRIBUTE_DATE8                     VARCHAR2(20),          
   ATTRIBUTE_DATE9                     VARCHAR2(20),          
   ATTRIBUTE_DATE10                    VARCHAR2(20),          
   ATTRIBUTE_NUMBER1                   NUMBER,        
   ATTRIBUTE_NUMBER2                   NUMBER,        
   ATTRIBUTE_NUMBER3                   NUMBER,        
   ATTRIBUTE_NUMBER4                   NUMBER,        
   ATTRIBUTE_NUMBER5                   NUMBER,        
   ATTRIBUTE_NUMBER6                   NUMBER,        
   ATTRIBUTE_NUMBER7                   NUMBER,        
   ATTRIBUTE_NUMBER8                   NUMBER,        
   ATTRIBUTE_NUMBER9                   NUMBER,        
   ATTRIBUTE_NUMBER10                  NUMBER,        
   GLOBAL_ATTRIBUTE_CATEGORY           VARCHAR2(30),  
   GLOBAL_ATTRIBUTE1                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE2                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE3                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE4                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE5                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE6                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE7                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE8                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE9                   VARCHAR2(150), 
   GLOBAL_ATTRIBUTE10                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE11                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE12                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE13                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE14                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE15                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE16                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE17                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE18                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE19                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE20                  VARCHAR2(150), 
   GLOBAL_ATTRIBUTE_DATE1              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE2              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE3              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE4              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_DATE5              VARCHAR2(20),          
   GLOBAL_ATTRIBUTE_NUMBER1            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER2            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER3            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER4            NUMBER,        
   GLOBAL_ATTRIBUTE_NUMBER5            NUMBER  
)
  ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SOURCE_DATAFILE"
      ACCESS PARAMETERS
      ( records delimited by newline skip 1 logfile 'XXMX_GL_DETAIL_BALANCES_STG.log' fields terminated by "," optionally enclosed by '"' missing field values are null )
      LOCATION
       ( 'XXMX_GL_DETAIL_BALANCES_STG.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;   
