--*****************************************************************************
--**
--**                 Copyright (c) 2022 Version 1
--**
--**                           Millennium House,
--**                           Millennium Walkway,
--**                           Dublin 1
--**                           D01 F5P8
--**
--**                           All rights reserved.
--**
--*****************************************************************************
--**
--**
--** FILENAME  :  XXMX_HCM_LRN_V3_STG_TAB.sql
--**
--** FILEPATH  :  /home/oracle/MXDM/install/STG
--**
--** VERSION   :  1.0
--**
--** EXECUTE
--** IN SCHEMA :  XXMX_STG
--**
--** AUTHORS   :  Shaik Latheef
--**
--** PURPOSE   :  This script installs the XXMX_STG DB Objects for the Maximise
--**              HCM Learning V3 Data Migration.
--**
--** NOTES     :
--**
--******************************************************************************
--**
--** PRE-REQUISITIES
--** ---------------
--**
--** If this script is to be executed as part of an installation script, ensure
--** that the installation script performs the following tasks prior to calling
--** this script.
--**
--** Task  Description
--** ----  ---------------------------------------------------------------------
--** 1.    None
--**
--** If this script is not to be executed as part of an installation script,
--** ensure that the tasks above are, or have been, performed prior to executing
--** this script.
--**
--******************************************************************************
--**
--** CALLING INSTALLATION SCRIPTS
--** ----------------------------
--**
--** The following installation scripts call this script:
--**
--** File Path                                     File Name
--** --------------------------------------------  ------------------------------
--** N/A                                           N/A
--**
--******************************************************************************
--**
--** PARAMETERS
--** ----------
--**
--** Parameter                       IN OUT  Type
--** -----------------------------  ------  ------------------------------------
--** [parameter_name]                IN OUT
--**
--******************************************************************************
--**
--** [previous_filename] HISTORY
--** -----------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  -----------------------------------
--**
--******************************************************************************
--**
--** xxcust_common_pkg.sql HISTORY
--** ------------------------------------
--**
--**   Vsn  Change Date  Changed By          Change Description
--** -----  -----------  ------------------  ---------------------------------------------
--** [ 1.0  24-AUG-2022  Shaik Latheef  	 Created Learning V3 STG tables for Maximise.]
--**
--****************************************************************************************
--
--
PROMPT
PROMPT
PROMPT **********************************************************************
PROMPT **
PROMPT ** Installing Database Objects for Maximise Learning V3 Data Migration
PROMPT **
PROMPT **********************************************************************
PROMPT
PROMPT
--
--
--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Dropping Tables
PROMPT ******************
PROMPT
PROMPT
--
--

EXEC DropTable ('XXMX_OLC_COURSE_V3_STG')
EXEC DropTable ('XXMX_OLC_COURSE_ACC_V3_STG')
EXEC DropTable ('XXMX_OLC_OFFER_V3_STG')
EXEC DropTable ('XXMX_OLC_EVAL_ACT_V3_STG')
EXEC DropTable ('XXMX_OLC_OFFER_ACT_V3_STG')
EXEC DropTable ('XXMX_OLC_INSTR_LED_V3_STG')
EXEC DropTable ('XXMX_OLC_ADHOC_V3_STG')
EXEC DropTable ('XXMX_OLC_CLASS_RESV_V3_STG')
EXEC DropTable ('XXMX_OLC_INSTR_RESV_V3_STG')
EXEC DropTable ('XXMX_OLC_SELFPACE_V3_STG')
EXEC DropTable ('XXMX_OLC_OFFER_ACC_V3_STG')
EXEC DropTable ('XXMX_OLC_COURSE_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_OFFER_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_OFFER_ACT_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_INSTR_ACT_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_SELFPACE_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_EVAL_ACT_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_SPEC_V3_STG')
EXEC DropTable ('XXMX_OLC_SPEC_DEF_ACC_V3_STG')
EXEC DropTable ('XXMX_OLC_SPEC_SXN_V3_STG')
EXEC DropTable ('XXMX_OLC_SPEC_SXN_ACT_V3_STG')
EXEC DropTable ('XXMX_OLC_SPEC_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_SPEC_SXN_V3_TL_STG')
EXEC DropTable ('XXMX_OLC_LEARN_RCD_ACT_V3_STG')



--
--
PROMPT
PROMPT
PROMPT ******************
PROMPT ** Creating Tables
PROMPT ******************
--
--

-- *****************
-- **Course V3 Table
-- *****************
CREATE TABLE XXMX_OLC_COURSE_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'CourseV3',
	--
	COURSE_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	COURSE_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	SHORT_DESCRIPTION					VARCHAR2(4000),
	SYLLABUS							CLOB,
	PUBLISH_START_DATE					DATE,
	PUBLISH_END_DATE					DATE,
	MINIMUM_EXPECTED_EFFORT				NUMBER,
	MAXIMUM_EXPECTED_EFFORT				NUMBER,
	CURRENCY_CODE						VARCHAR2(30),
	MINIMUM_PRICE						NUMBER,
	MAXIMUM_PRICE						NUMBER,
	COVER_ART_FILE						CLOB,
	COVER_ART_FILE_NAME					VARCHAR2(255),
	OWNED_BY_PERSON_ID					NUMBER,
	OWNED_BY_PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_TYPE							VARCHAR2(30),
	SOURCE_ID							NUMBER,
	SOURCE_INFO							VARCHAR2(240),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SYLLABUS_TEXT						VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ********************************
-- **Course Default Access V3 Table
-- ********************************
CREATE TABLE XXMX_OLC_COURSE_ACC_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'CourseDefaultAccessV3',
	--
	DEFAULT_ACCESS_ID					NUMBER,
	DEFAULT_ACCESS_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	FOLLOW_COMMUNITY					VARCHAR2(30) DEFAULT 'N',
	FOLLOW_SPECIALIZATION				VARCHAR2(30) DEFAULT 'N',
	SELF_VIEW_MODE						VARCHAR2(30) NOT NULL ENABLE,
	SELF_INITIAL_STATUS					VARCHAR2(30) NOT NULL ENABLE,
	SELF_ENROLL_FORM					VARCHAR2(30) DEFAULT 'N',
	SELF_ACTIVATE_APPROVE				VARCHAR2(30),
	SELF_ENROLL_QUESTIONNAIRE			VARCHAR2(30) DEFAULT 'N',
	SELF_QUESTIONNAIRE_CODE				VARCHAR2(240),
	SELF_PREREQ_TYPE					VARCHAR2(30),
	SELF_WITHDRAW_PREREQ_DAYS			NUMBER,
	MGR_INITIAL_STATUS					VARCHAR2(30) NOT NULL ENABLE,
	MGR_ACTIVATE_APPROVE				VARCHAR2(30),
	MGR_WITHDRAW_PREREQ_DAYS			NUMBER,
	MGR_MARK_COMPLETE					VARCHAR2(30) DEFAULT 'N',
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	COURSE_ID                           NUMBER,
	COURSE_NUMBER                       VARCHAR2(30) NOT NULL ENABLE,
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- *******************
-- **Offering V3 Table
-- *******************
CREATE TABLE XXMX_OLC_OFFER_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'OfferingV3',
	--
	OFFERING_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	OFFERING_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	OWNED_BY_PERSON_ID					NUMBER,	
	SOURCE_ID							NUMBER,
	SOURCE_INFO							VARCHAR2(240),
	SOURCE_TYPE							VARCHAR2(30),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	LANGUAGE_CODE						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	DESCRIPTION							CLOB,
	MAXIMUM_CAPACITY					NUMBER,
	MINIMUM_CAPACITY					NUMBER,
	OFFERING_TYPE						VARCHAR2(30) NOT NULL ENABLE,
	COURSE_ID							NUMBER,
	COURSE_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	ENABLE_CAPACITY						VARCHAR2(1),
	ENABLE_WAITLIST						VARCHAR2(1),
	PRIMARY_LOCATION_ID					NUMBER,
	PRIMARY_INSTRUCTOR_ID				NUMBER,
	TRAINING_SUPPLIER_ID				NUMBER,
	FACILITATOR_TYPE					VARCHAR2(30),
	COORDINATOR_ID						NUMBER,
	COORDINATOR_NUMBER					VARCHAR2(30) NOT NULL ENABLE,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	OFFERING_START_DATE					DATE,
	OFFERING_END_DATE					DATE,
	OWNED_BY_PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	PRIMARY_INSTRUCTOR_NUMBER			VARCHAR2(30),
	PRIMARY_LOCATION_NUMBER				VARCHAR2(30),
	PUBLISH_START_DATE					DATE,
	PUBLISH_END_DATE					DATE,
	TRAINING_SUPPLIER_NUMBER			VARCHAR2(30),
	SINGLE_SELECT_EXISTS_SEC_SHOW		VARCHAR2(1),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- ******************************
-- **Evaluation Activity V3 Table
-- ******************************
CREATE TABLE XXMX_OLC_EVAL_ACT_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'EvaluationActivityV3',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	OFFERING_ID							NUMBER,
	OFFERING_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	QUESTIONNAIRE_CODE					VARCHAR2(240),
	QSTNR_REQUIRED_FOR_COMPLETION		VARCHAR2(1),
	SOURCE_SYSTEM_ID					VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER					VARCHAR2(256),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- ************************************
-- **Offering Activity Section V3 Table
-- ************************************
CREATE TABLE XXMX_OLC_OFFER_ACT_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'OfferingActivitySectionV3',
	--
	OFFERING_SECTION_ID					NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	OFFERING_SECTION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_SYSTEM_OWNER					VARCHAR2(256),
	SOURCE_SYSTEM_ID					VARCHAR2(2000),
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	DESCRIPTION							CLOB,
	NUM_OF_ACTIVITIES_TO_COMPLETE		NUMBER,
	COMPLETION_RULE_TYPE				VARCHAR2(30) NOT NULL ENABLE,
	OFFERING_ID							NUMBER,
	SECTION_POSITION					NUMBER NOT NULL ENABLE,
	SEQUENCE_RULE_TYPE					VARCHAR2(30) NOT NULL ENABLE,
	OFFERING_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	SEQUENCE_RULE_SECTION_NUMBER		VARCHAR2(30),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );   

-- **********************************
-- **Instructor Led Activity V3 Table
-- **********************************
CREATE TABLE XXMX_OLC_INSTR_LED_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'InstructorLedActivityV3',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	EXPECTED_EFFORT						NUMBER,
	SOURCE_INFO							VARCHAR2(240),
	SOURCE_TYPE							VARCHAR2(30),
	SOURCE_ID							NUMBER,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	SHORT_DESCRIPTION					VARCHAR2(4000),
	DESCRIPTION							CLOB,
	COMPLETION_RULE_TYPE				VARCHAR2(30),
	VIRTUAL_CLASSROOM_URL				VARCHAR2(500),
	SELF_COMPLETE_FLAG					VARCHAR2(1) DEFAULT 'N',
	TIME_ZONE							VARCHAR2(30) NOT NULL ENABLE,
	OFFERING_SECTION_ID					NUMBER,
	ACTIVITY_POSITION					NUMBER,
	SEQUENCE_RULE_TYPE					VARCHAR2(30) NOT NULL ENABLE,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	OFFERING_SECTION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	ACTIVITY_DATE						DATE NOT NULL ENABLE,
	ACTIVITY_START_TIME					VARCHAR2(50) NOT NULL ENABLE,
	ACTIVITY_END_TIME					VARCHAR2(50) NOT NULL ENABLE,
	SEQUENCE_RULE_ACTIVITY_NUMBER		VARCHAR2(30),
	CLASSROOM_RESOURCE_ID				NUMBER,
	CLASSROOM_RESOURCE_NUMBER			VARCHAR2(30),
	VIRTUAL_PROVIDER_ID					NUMBER,
	VIRTUAL_PROVIDER_NUMBER				VARCHAR2(30),
	VIRTUAL_PROVIDER_PRODUCT			VARCHAR2(30),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- *************************
-- **Adhoc Resource V3 Table
-- *************************
CREATE TABLE XXMX_OLC_ADHOC_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'AdhocResourceV3',
	--
	ADHOC_RESOURCE_ID					NUMBER,
	ADHOC_RESOURCE_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(100) NOT NULL ENABLE,
	DESCRIPTION							VARCHAR2(4000),
	QUANTITY							NUMBER,
	ACTIVITY_ID							NUMBER,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );  


-- ********************************
-- **Classroom Reservation V3 Table
-- ********************************
CREATE TABLE XXMX_OLC_CLASS_RESV_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'ClassroomReservationV3',
	--
	CLASSROOM_RESERVATION_ID			NUMBER,
	CLASSROOM_RESERVATION_NUMBER		VARCHAR2(30) NOT NULL ENABLE,
	CLASSROOM_RESOURCE_ID				NUMBER,
	CLASSROOM_RESOURCE_NUMBER			VARCHAR2(30) NOT NULL ENABLE,
	ACTIVITY_ID							NUMBER,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- *********************************
-- **Instructor Reservation V3 Table
-- *********************************
CREATE TABLE XXMX_OLC_INSTR_RESV_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'InstructorReservationV3',
	--
	INSTRUCTOR_RESERVATION_ID			NUMBER,
	INSTRUCTOR_RESERVATION_NUMBER		VARCHAR2(30) NOT NULL ENABLE,
	INSTRUCTOR_RESOURCE_ID				NUMBER,
	INSTRUCTOR_RESOURCE_NUMBER			VARCHAR2(30) NOT NULL ENABLE,
	ACTIVITY_ID							NUMBER,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- ******************************
-- **Self Paced Activity V3 Table
-- ******************************
CREATE TABLE XXMX_OLC_SELFPACE_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SelfPacedActivityV3',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	EXPECTED_EFFORT						NUMBER,
	SOURCE_INFO							VARCHAR2(240),
	SOURCE_TYPE							VARCHAR2(30),
	SOURCE_ID							NUMBER,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	SHORT_DESCRIPTION					VARCHAR2(4000),
	DESCRIPTION							CLOB,
	CONTENT_ID							NUMBER,
	COMPLETION_RULE_TYPE				VARCHAR2(30),
	SELF_COMPLETE_FLAG					VARCHAR2(30) DEFAULT 'N',
	OFFERING_SECTION_ID					NUMBER,
	ACTIVITY_POSITION					NUMBER NOT NULL ENABLE,
	SEQUENCE_RULE_TYPE					VARCHAR2(30) NOT NULL ENABLE,
	OFFERING_SECTION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	DESCRIPTION_TEXT					VARCHAR2(2000),
	CONTENT_NUMBER						VARCHAR2(30),
	SEQUENCE_RULE_ACTIVITY_NUMBER		VARCHAR2(30),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- **********************************
-- **Offering Default Access V3 Table
-- **********************************
CREATE TABLE XXMX_OLC_OFFER_ACC_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'OfferingDefaultAccessV3',
	--
	DEFAULT_ACCESS_ID					NUMBER,
	DEFAULT_ACCESS_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	SELF_VIEW_MODE						VARCHAR2(30) NOT NULL ENABLE,
	SELF_INITIAL_STATUS					VARCHAR2(30) NOT NULL ENABLE,
	SELF_ENROLL_FORM					VARCHAR2(30) DEFAULT 'N',
	SELF_ACTIVATE_APPROVE				VARCHAR2(30),
	SELF_ENROLL_QUESTIONNAIRE			VARCHAR2(30) DEFAULT 'N',
	SELF_QUESTIONNAIRE_CODE				VARCHAR2(30),
	MGR_INITIAL_STATUS					VARCHAR2(30) NOT NULL ENABLE,
	MGR_ACTIVATE_APPROVE				VARCHAR2(30),
	MGR_WITHDRAW_PREREQ_DAYS			NUMBER,
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	OFFERING_ID							NUMBER,
	OFFERING_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- *****************************
-- **Course V3 Translation Table
-- *****************************
CREATE TABLE XXMX_OLC_COURSE_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'CourseV3Translation',
	--
	COURSE_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	COURSE_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250),
	SHORT_DESCRIPTION					VARCHAR2(4000),
	SYLLABUS							CLOB,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SYLLABUS_TEXT						VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- *******************************
-- **Offering V3 Translation Table
-- *******************************
CREATE TABLE XXMX_OLC_OFFER_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'OfferingV3Translation',
	--
	OFFERING_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	OFFERING_NUMBER						VARCHAR2(30) NOT NULL ENABLE, 
	TITLE								VARCHAR2(240), 
	DESCRIPTION							CLOB,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	DESCRIPTION_TEXT					VARCHAR2(4000), 
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ************************************************
-- **Offering Activity Section V3 Translation Table
-- ************************************************
CREATE TABLE XXMX_OLC_OFFER_ACT_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'OfferingActivitySectionV3Translation',
	--
	OFFERING_SECTION_ID					NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	OFFERING_SECTION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(240),
	DESCRIPTION							CLOB,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	SOURCE_SYSTEM_OWNER					VARCHAR2(256),
	SOURCE_SYSTEM_ID					VARCHAR2(2000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );







-- **********************************************
-- **Instructor Led Activity V3 Translation Table
-- **********************************************
CREATE TABLE XXMX_OLC_INSTR_ACT_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'InstructorLedActivityV3Translation',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(240), 
	DESCRIPTION							CLOB,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SHORT_DESCRIPTION					VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ******************************************
-- **Self Paced Activity V3 Translation Table
-- ******************************************
CREATE TABLE XXMX_OLC_SELFPACE_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SelfPacedActivityV3Translation',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(240), 
	DESCRIPTION							CLOB,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SHORT_DESCRIPTION					,
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ******************************************
-- **Evaluation Activity V3 Translation Table
-- ******************************************
CREATE TABLE XXMX_OLC_EVAL_ACT_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'EvaluationActivityV3Translation',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	TITLE								VARCHAR2(240),
	SOURCE_SYSTEM_OWNER					VARCHAR2(256),
	SOURCE_SYSTEM_ID					VARCHAR2(2000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- *************************
-- **Specialization V3 Table
-- *************************
CREATE TABLE XXMX_OLC_SPEC_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationV3',
	--
	SPECIALIZATION_ID					NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	SPECIALIZATION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	SHORT_DESCRIPTION					VARCHAR2(4000),
	DESCRIPTION							CLOB,
	PUBLISH_START_DATE					DATE,
	PUBLISH_END_DATE					DATE,
	COVER_ART_FILE						BLOB,
	COVER_ART_FILE_NAME					VARCHAR2(255),
	SOURCE_TYPE							VARCHAR2(30),
	SOURCE_ID							NUMBER,
	SOURCE_INFO							VARCHAR2(240),
	OWNED_BY_PERSON_ID					NUMBER,
	OWNED_BY_PERSON_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	MINIMUM_EXPECTED_EFFORT				NUMBER,
	MAXIMUM_EXPECTED_EFFORT				NUMBER,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	DESCRIPTION_TEXT					VARCHAR2(4000),
	SINGLE_SELECT_EXISTS_SEC_SHOW		VARCHAR2(1),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ****************************************
-- **Specialization Default Access V3 Table
-- ****************************************
CREATE TABLE XXMX_OLC_SPEC_DEF_ACC_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationDefaultAccessV3',
	--
	DEFAULT_ACCESS_ID					NUMBER,
	DEFAULT_ACCESS_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	FOLLOW_COMMUNITY					VARCHAR2(30) DEFAULT 'N',
	SELF_VIEW_MODE						VARCHAR2(30),
	SELF_INITIAL_STATUS					VARCHAR2(30),
	SELF_ENROLL_FORM					VARCHAR2(30) DEFAULT 'N',
	SELF_ACTIVATE_APPROVE				VARCHAR2(30),
	SELF_ENROLL_QUESTIONNAIRE			VARCHAR2(30) DEFAULT 'N',
	SELF_QUESTIONNAIRE_CODE				VARCHAR2(30),
	SELF_PREREQ_TYPE					VARCHAR2(30),
	SELF_WITHDRAW_PREREQ_DAYS			NUMBER,
	MGR_INITIAL_STATUS					VARCHAR2(30),
	MGR_ACTIVATE_APPROVE				VARCHAR2(30),
	MGR_WITHDRAW_PREREQ_DAYS			NUMBER,
	MGR_MARK_COMPLETE					VARCHAR2(30) DEFAULT 'N',
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SPECIALIZATION_ID					NUMBER,
	SPECIALIZATION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,	
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- *********************************
-- **Specialization Section V3 Table
-- *********************************
CREATE TABLE XXMX_OLC_SPEC_SXN_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationSectionV3',
	--
	SPECIALIZATION_SECTION_ID			NUMBER,
	SPECIALIZATION_SECTION_NUMBER		VARCHAR2(30) NOT NULL ENABLE,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	TITLE								VARCHAR2(250) NOT NULL ENABLE,
	DESCRIPTION							CLOB,
	DESCRIPTION_TEXT					VARCHAR2(4000),
	COMPLETION_RULE_TYPE				VARCHAR2(30) NOT NULL ENABLE,
	NUM_OF_ACTIVITIES_TO_COMPLETE		NUMBER,
	SEQUENCE_RULE_TYPE					VARCHAR2(30) NOT NULL ENABLE,
	SEQUENCE_RULE_SECTION_NUMBER		VARCHAR2(30),
	INIT_ASSIGN_STATUS_ACTIVITIES		VARCHAR2(30),
	SECTION_POSITION					NUMBER NOT NULL ENABLE,
	SPECIALIZATION_ID					NUMBER,
	SPECIALIZATION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- ******************************************
-- **Specialization Section Activity V3 Table
-- ******************************************
CREATE TABLE XXMX_OLC_SPEC_SXN_ACT_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationSectionActivityV3',
	--
	ACTIVITY_ID							NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	SPECIALIZATION_SECTION_ID			NUMBER,
	SPECIALIZATION_SECTION_NUMBER		VARCHAR2(30) NOT NULL ENABLE,
	COURSE_LEARNING_ITEM_ID				NUMBER,
	COURSE_LEARNING_ITEM_NUMBER			VARCHAR2(30),
    SEQUENCE_RULE_TYPE					VARCHAR2(30) NOT NULL ENABLE,
    SEQUENCE_RULE_ACTIVITY_NUMBER		VARCHAR2(30),
    ACTIVITY_POSITION					NUMBER NOT NULL ENABLE,
	ACTIVITY_COMPLETION_TYPE			VARCHAR2(30),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );
   
-- *************************************
-- **Specialization V3 Translation Table
-- *************************************
CREATE TABLE XXMX_OLC_SPEC_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationV3Translation',
	--
	SPECIALIZATION_ID					NUMBER,
	EFFECTIVE_START_DATE				DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE					DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	SPECIALIZATION_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	TITLE								VARCHAR2(250),
	DESCRIPTION							CLOB,
	SHORT_DESCRIPTION					VARCHAR2(4000),
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	DESCRIPTION_TEXT					VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- *********************************************
-- **Specialization Section V3 Translation Table
-- *********************************************
CREATE TABLE XXMX_OLC_SPEC_SXN_V3_TL_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'SpecializationSectionV3Translation',
	--
	SPECIALIZATION_SECTION_ID           NUMBER,
	EFFECTIVE_START_DATE                DATE NOT NULL ENABLE,
	EFFECTIVE_END_DATE                  DATE,
	LANGUAGE							VARCHAR2(4) NOT NULL ENABLE,
	SPECIALIZATION_SECTION_NUMBER       VARCHAR2(30) NOT NULL ENABLE,
	TITLE                               VARCHAR2(250),
	DESCRIPTION                         CLOB,
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	DESCRIPTION_TEXT                    VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );

-- *******************************************
-- **Learning Record Activity Attempt V3 Table
-- *******************************************
CREATE TABLE XXMX_OLC_LEARN_RCD_ACT_V3_STG
   (
   	FILE_SET_ID							VARCHAR2(30),   
	MIGRATION_SET_ID					NUMBER,
	MIGRATION_SET_NAME 					VARCHAR2(150),
	MIGRATION_STATUS					VARCHAR2(50),
	BG_NAME   							VARCHAR2(240), 
	BG_ID            					NUMBER(15),	
	METADATA							VARCHAR2(150) DEFAULT 'MERGE',
	OBJECTNAME							VARCHAR2(150) DEFAULT 'LearningRecordActivityAttemptV3',
	SOURCE_SYSTEM_OWNER   				VARCHAR2(256),
	SOURCE_SYSTEM_ID	  				VARCHAR2(2000),
	--
	ACTIVITY_ATTEMPT_ID					NUMBER,
	ACTIVITY_ATTEMPT_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	LEARNING_RECORD_ID					NUMBER,
	LEARNING_RECORD_NUMBER				VARCHAR2(30) NOT NULL ENABLE,
	ACTIVITY_ID							NUMBER,
	ACTIVITY_NUMBER						VARCHAR2(30) NOT NULL ENABLE,
	ACTIVITY_ATTEMPT_STATUS				VARCHAR2(30),
	ACTIVITY_ATTEMPT_DATE				DATE,
	ACTIVITY_ATTEMPT_REASON_CODE		VARCHAR2(30),
	ACTIVITY_ATTEMPT_ACTUAL_SCORE		NUMBER,
	ACTIVITY_ATTEMPT_ACTUAL_EFFORT		VARCHAR2(30),
	ACTIVITY_ATTEMPT_NOTE				VARCHAR2(4000),
	--
	ATTRIBUTE_CATEGORY 					VARCHAR2(30), 
	ATTRIBUTE1 							VARCHAR2(150), 
	ATTRIBUTE2 							VARCHAR2(150), 
	ATTRIBUTE3 							VARCHAR2(150), 
	ATTRIBUTE4 							VARCHAR2(150), 
	ATTRIBUTE5 							VARCHAR2(150), 
	ATTRIBUTE6 							VARCHAR2(150), 
	ATTRIBUTE7 							VARCHAR2(150), 
	ATTRIBUTE8 							VARCHAR2(150), 
	ATTRIBUTE9 							VARCHAR2(150), 
	ATTRIBUTE10 						VARCHAR2(150),
	ATTRIBUTE_NUMBER1 					NUMBER, 
	ATTRIBUTE_NUMBER2 					NUMBER, 
	ATTRIBUTE_NUMBER3 					NUMBER, 
	ATTRIBUTE_NUMBER4 					NUMBER, 
	ATTRIBUTE_NUMBER5 					NUMBER, 
	ATTRIBUTE_DATE1 					DATE, 
	ATTRIBUTE_DATE2 					DATE, 
	ATTRIBUTE_DATE3 					DATE, 
	ATTRIBUTE_DATE4 					DATE, 
	ATTRIBUTE_DATE5 					DATE
   );



--------------------------
---SYNONYMS AND GRANTS
--------------------------

--
--
PROMPT
PROMPT
PROMPT ****************************
PROMPT ** CREATE OR REPLACE SYNONYM
PROMPT ****************************
--
--


CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_COURSE_V3_STG FOR XXMX_OLC_COURSE_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_COURSE_ACC_V3_STG FOR XXMX_OLC_COURSE_ACC_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_OFFER_V3_STG FOR XXMX_OLC_OFFER_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_EVAL_ACT_V3_STG FOR XXMX_OLC_EVAL_ACT_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_OFFER_ACT_V3_STG FOR XXMX_OLC_OFFER_ACT_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_INSTR_LED_V3_STG FOR XXMX_OLC_INSTR_LED_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_ADHOC_V3_STG FOR XXMX_OLC_ADHOC_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_CLASS_RESV_V3_STG FOR XXMX_OLC_CLASS_RESV_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_INSTR_RESV_V3_STG FOR XXMX_OLC_INSTR_RESV_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SELFPACE_V3_STG FOR XXMX_OLC_SELFPACE_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_OFFER_ACC_V3_STG FOR XXMX_OLC_OFFER_ACC_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_COURSE_V3_TL_STG FOR XXMX_OLC_COURSE_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_OFFER_V3_TL_STG FOR XXMX_OLC_OFFER_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_OFFER_ACT_V3_TL_STG FOR XXMX_OLC_OFFER_ACT_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_INSTR_ACT_V3_TL_STG FOR XXMX_OLC_INSTR_ACT_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SELFPACE_V3_TL_STG FOR XXMX_OLC_SELFPACE_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_EVAL_ACT_V3_TL_STG FOR XXMX_OLC_EVAL_ACT_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_V3_STG FOR XXMX_OLC_SPEC_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_DEF_ACC_V3_STG FOR XXMX_OLC_SPEC_DEF_ACC_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_SXN_V3_STG FOR XXMX_OLC_SPEC_SXN_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_SXN_ACT_V3_STG FOR XXMX_OLC_SPEC_SXN_ACT_V3_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_V3_TL_STG FOR XXMX_OLC_SPEC_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_SPEC_SXN_V3_TL_STG FOR XXMX_OLC_SPEC_SXN_V3_TL_STG;
CREATE OR REPLACE PUBLIC SYNONYM XXMX_OLC_LEARN_RCD_ACT_V3_STG FOR XXMX_OLC_LEARN_RCD_ACT_V3_STG;

--
--
PROMPT
PROMPT
PROMPT ***********************
PROMPT ** Granting permissions
PROMPT ***********************
--
--


GRANT ALL ON XXMX_OLC_COURSE_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_COURSE_ACC_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_OFFER_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_EVAL_ACT_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_OFFER_ACT_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_INSTR_LED_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_ADHOC_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_CLASS_RESV_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_INSTR_RESV_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SELFPACE_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_OFFER_ACC_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_COURSE_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_OFFER_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_OFFER_ACT_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_INSTR_ACT_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SELFPACE_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_EVAL_ACT_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_DEF_ACC_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_SXN_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_SXN_ACT_V3_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_SPEC_SXN_V3_TL_STG TO XXMX_CORE;
GRANT ALL ON XXMX_OLC_LEARN_RCD_ACT_V3_STG TO XXMX_CORE;


--
--
--
--
PROMPT
PROMPT
PROMPT **********************************
PROMPT **                                
PROMPT ** End of Database Object Creation
PROMPT **                                
PROMPT **********************************
PROMPT
PROMPT
--
--

