/*
--------------------------------------------------------------------------
CREATION OF THE VALIDATION TABLE FOR AP_INVOICES 
(VALIDATION_ERROR_MESSAGE: New Column added as per the package) 
--------------------------------------------------------------------------
*/

DROP TABLE XXMX_CORE.XXMX_AP_INVOICES_VAL ; 
  --
Create Table XXMX_CORE.XXMX_AP_INVOICES_VAL
(    
	 VALIDATION_ERROR_MESSAGE		VARCHAR2(3000 BYTE)
	,MIGRATION_SET_ID				NUMBER
	,MIGRATION_SET_NAME				VARCHAR2(100 BYTE)
	,MIGRATION_STATUS				VARCHAR2(50 BYTE)
	,INVOICE_ID						NUMBER(15,0)
	,OPERATING_UNIT					VARCHAR2(240 BYTE)
	,LEDGER_NAME					VARCHAR2(30 BYTE)
	,INVOICE_NUM					VARCHAR2(50 BYTE)
	,INVOICE_AMOUNT					NUMBER
	,INVOICE_DATE					DATE
	,VENDOR_NAME					VARCHAR2(240 BYTE)
	,VENDOR_NUM						VARCHAR2(30 BYTE)
	,VENDOR_SITE_CODE				VARCHAR2(15 BYTE)
	,INVOICE_CURRENCY_CODE			VARCHAR2(15 BYTE)
	,PAYMENT_CURRENCY_CODE			VARCHAR2(15 BYTE)
	,DESCRIPTION					VARCHAR2(240 BYTE)
	,INVOICE_TYPE_LOOKUP_CODE		VARCHAR2(25 BYTE)
	,LEGAL_ENTITY_NAME				VARCHAR2(50 BYTE)
	,CUST_REGISTRATION_NUMBER		VARCHAR2(30 BYTE)
	,CUST_REGISTRATION_CODE			VARCHAR2(30 BYTE)
	,FIRST_PARTY_REGISTRATION_NUM	VARCHAR2(60 BYTE)
	,THIRD_PARTY_REGISTRATION_NUM	VARCHAR2(60 BYTE)
	,TERMS_NAME						VARCHAR2(50 BYTE)
	,TERMS_DATE						DATE
	,GOODS_RECEIVED_DATE			DATE
	,INVOICE_RECEIVED_DATE			DATE
	,GL_DATE						DATE
	,PAYMENT_METHOD_CODE			VARCHAR2(30 BYTE)
	,PAY_GROUP_LOOKUP_CODE			VARCHAR2(25 BYTE)
	,EXCLUSIVE_PAYMENT_FLAG			VARCHAR2(1 BYTE)
	,AMOUNT_APPLICABLE_TO_DISCOUNT	NUMBER
	,PREPAY_NUM						VARCHAR2(50 BYTE)
	,PREPAY_LINE_NUM				NUMBER
	,PREPAY_APPLY_AMOUNT			NUMBER
	,PREPAY_GL_DATE					DATE
	,INVOICE_INCLUDES_PREPAY_FLAG	VARCHAR2(1 BYTE)
	,EXCHANGE_RATE_TYPE				VARCHAR2(30 BYTE)
	,EXCHANGE_DATE					DATE
	,EXCHANGE_RATE					NUMBER
	,ACCTS_PAY_CODE_CONCATENATED	VARCHAR2(250 BYTE)
	,DOC_CATEGORY_CODE				VARCHAR2(30 BYTE)
	,VOUCHER_NUM					VARCHAR2(50 BYTE)
	,REQUESTER_FIRST_NAME			VARCHAR2(150 BYTE)
	,REQUESTER_LAST_NAME			VARCHAR2(150 BYTE)
	,REQUESTER_EMPLOYEE_NUM			VARCHAR2(30 BYTE)
	,DELIVERY_CHANNEL_CODE			VARCHAR2(30 BYTE)
	,BANK_CHARGE_BEARER				VARCHAR2(30 BYTE)
	,REMIT_TO_SUPPLIER_NAME			VARCHAR2(240 BYTE)
	,REMIT_TO_SUPPLIER_NUM			VARCHAR2(30 BYTE)
	,REMIT_TO_ADDRESS_NAME			VARCHAR2(240 BYTE)
	,PAYMENT_PRIORITY				NUMBER(2,0)
	,SETTLEMENT_PRIORITY			VARCHAR2(30 BYTE)
	,UNIQUE_REMITTANCE_IDENTIFIER	VARCHAR2(30 BYTE)
	,URI_CHECK_DIGIT				VARCHAR2(2 BYTE)
	,PAYMENT_REASON_CODE			VARCHAR2(30 BYTE)
	,PAYMENT_REASON_COMMENTS		VARCHAR2(240 BYTE)
	,REMITTANCE_MESSAGE1			VARCHAR2(150 BYTE)
	,REMITTANCE_MESSAGE2			VARCHAR2(150 BYTE)
	,REMITTANCE_MESSAGE3			VARCHAR2(150 BYTE)
	,AWT_GROUP_NAME					VARCHAR2(25 BYTE)
	,SHIP_TO_LOCATION				VARCHAR2(40 BYTE)
	,TAXATION_COUNTRY				VARCHAR2(30 BYTE)
	,DOCUMENT_SUB_TYPE				VARCHAR2(150 BYTE)
	,TAX_INVOICE_INTERNAL_SEQ		VARCHAR2(150 BYTE)
	,SUPPLIER_TAX_INVOICE_NUMBER	VARCHAR2(150 BYTE)
	,TAX_INVOICE_RECORDING_DATE		DATE
	,SUPPLIER_TAX_INVOICE_DATE		DATE
	,SUPPLIER_TAX_EXCHANGE_RATE		NUMBER
	,PORT_OF_ENTRY_CODE				VARCHAR2(30 BYTE)
	,CORRECTION_YEAR				NUMBER
	,CORRECTION_PERIOD				VARCHAR2(15 BYTE)
	,IMPORT_DOCUMENT_NUMBER			VARCHAR2(50 BYTE)
	,IMPORT_DOCUMENT_DATE			DATE
	,CONTROL_AMOUNT					NUMBER
	,CALC_TAX_DURING_IMPORT_FLAG	VARCHAR2(1 BYTE)
	,ADD_TAX_TO_INV_AMT_FLAG		VARCHAR2(1 BYTE)
	,IMAGE_DOCUMENT_URI				VARCHAR2(4000 BYTE)
	,LOAD_BATCH						VARCHAR2(300 BYTE)
	,EXTERNAL_BANK_ACCOUNT_NUMBER	VARCHAR2(100 BYTE)
	,EXT_BANK_ACCOUNT_IBAN_NUMBER	VARCHAR2(50 BYTE)
	,REQUESTER_EMAIL_ADDRESS		VARCHAR2(240 BYTE)
	,FUSION_BUSINESS_UNIT			VARCHAR2(240 BYTE)

);
/*
--------------------------------------------------------------------------
CREATION OF THE VALIDATION TABLE FOR AP_INVOICE_LINES
(VALIDATION_ERROR_MESSAGE: New Column added as per the package)
--------------------------------------------------------------------------
*/

DROP TABLE XXMX_CORE.XXMX_AP_INVOICE_LINES_VAL ;
--
Create Table XXMX_CORE.XXMX_AP_INVOICE_LINES_VAL
(
	 VALIDATION_ERROR_MESSAGE			  VARCHAR2(3000 BYTE)
	,MIGRATION_SET_ID                     NUMBER         
	,MIGRATION_SET_NAME                   VARCHAR2(100)  
	,MIGRATION_STATUS                     VARCHAR2(50)   
	,INVOICE_ID                           NUMBER(15)     
	,LINE_NUMBER                          NUMBER(18)     
	,LINE_TYPE_LOOKUP_CODE                VARCHAR2(25)   
	,AMOUNT                               NUMBER         
	,QUANTITY_INVOICED                    NUMBER         
	,UNIT_PRICE                           NUMBER         
	,UNIT_OF_MEAS_LOOKUP_CODE             VARCHAR2(25)   
	,DESCRIPTION                          VARCHAR2(240)  
	,PO_NUMBER                            VARCHAR2(20)   
	,PO_LINE_NUMBER                       NUMBER         
	,PO_SHIPMENT_NUM                      NUMBER         
	,PO_DISTRIBUTION_NUM                  NUMBER         
	,ITEM_DESCRIPTION                     VARCHAR2(240)  
	,RELEASE_NUM                          NUMBER         
	,PURCHASING_CATEGORY                  VARCHAR2(2000) 
	,RECEIPT_NUMBER                       VARCHAR2(30)   
	,RECEIPT_LINE_NUMBER                  VARCHAR2(25)   
	,CONSUMPTION_ADVICE_NUMBER            VARCHAR2(20)   
	,CONSUMPTION_ADVICE_LINE_NUMBER       NUMBER         
	,PACKING_SLIP                         VARCHAR2(25)   
	,FINAL_MATCH_FLAG                     VARCHAR2(1)    
	,DIST_CODE_CONCATENATED               VARCHAR2(250)  
	,DISTRIBUTION_SET_NAME                VARCHAR2(50)   
	,ACCOUNTING_DATE                      DATE           
	,ACCOUNT_SEGMENT                      VARCHAR2(25)   
	,BALANCING_SEGMENT                    VARCHAR2(25)   
	,COST_CENTER_SEGMENT                  VARCHAR2(25)   
	,TAX_CLASSIFICATION_CODE              VARCHAR2(30)   
	,SHIP_TO_LOCATION_CODE                VARCHAR2(60)   
	,SHIP_FROM_LOCATION_CODE              VARCHAR2(60)   
	,FINAL_DISCHARGE_LOCATION_CODE        VARCHAR2(60)   
	,TRX_BUSINESS_CATEGORY                VARCHAR2(240)  
	,PRODUCT_FISC_CLASSIFICATION          VARCHAR2(240)  
	,PRIMARY_INTENDED_USE                 VARCHAR2(30)   
	,USER_DEFINED_FISC_CLASS              VARCHAR2(240)  
	,PRODUCT_TYPE                         VARCHAR2(240)  
	,ASSESSABLE_VALUE                     NUMBER         
	,PRODUCT_CATEGORY                     VARCHAR2(240)  
	,CONTROL_AMOUNT                       NUMBER         
	,TAX_REGIME_CODE                      VARCHAR2(30)   
	,TAX                                  VARCHAR2(30)   
	,TAX_STATUS_CODE                      VARCHAR2(30)   
	,TAX_JURISDICTION_CODE                VARCHAR2(30)   
	,TAX_RATE_CODE                        VARCHAR2(150)  
	,TAX_RATE                             NUMBER         
	,AWT_GROUP_NAME                       VARCHAR2(25)   
	,TYPE_1099                            VARCHAR2(10)   
	,INCOME_TAX_REGION                    VARCHAR2(10)   
	,PRORATE_ACROSS_FLAG                  VARCHAR2(1)    
	,LINE_GROUP_NUMBER                    NUMBER         
	,COST_FACTOR_NAME                     VARCHAR2(80)   
	,STAT_AMOUNT                          NUMBER         
	,ASSETS_TRACKING_FLAG                 VARCHAR2(1)    
	,ASSET_BOOK_TYPE_CODE                 VARCHAR2(30)   
	,ASSET_CATEGORY_ID                    NUMBER(18)     
	,SERIAL_NUMBER                        VARCHAR2(35)   
	,MANUFACTURER                         VARCHAR2(30)   
	,MODEL_NUMBER                         VARCHAR2(40)   
	,WARRANTY_NUMBER                      VARCHAR2(15)   
	,PRICE_CORRECTION_FLAG                VARCHAR2(1)    
	,PRICE_CORRECT_INV_NUM                VARCHAR2(50)   
	,PRICE_CORRECT_INV_LINE_NUM           NUMBER         
	,REQUESTER_FIRST_NAME                 VARCHAR2(150)  
	,REQUESTER_LAST_NAME                  VARCHAR2(150)  
	,REQUESTER_EMPLOYEE_NUM               VARCHAR2(30)     
	,DEF_ACCTG_START_DATE                 DATE           
	,DEF_ACCTG_END_DATE                   DATE           
	,DEF_ACCRUAL_CODE_CONCATENATED        DATE           
	,PJC_PROJECT_NAME                     VARCHAR2(240)  
	,PJC_TASK_NAME                        VARCHAR2(255)  
	,LOAD_BATCH                           VARCHAR2(300)  
	,PJC_WORK_TYPE                        VARCHAR2(240)  
	,PJC_CONTRACT_NAME                    VARCHAR2(300)  
	,PJC_CONTRACT_NUMBER                  VARCHAR2(120)  
	,PJC_FUNDING_SOURCE_NAME              VARCHAR2(360)  
	,PJC_FUNDING_SOURCE_NUMBER            VARCHAR2(50)   
	,REQUESTER_EMAIL_ADDRESS              VARCHAR2(240)  
	,RCV_TRANSACTION_ID                   NUMBER(20)
);