    /*
	 ******************************************************************************
     ** FILENAME  :  XXMX_CUSTOMER_VALIDATION_TABLES.pls
     **
     ** VERSION   :  1.0
     **
     ** EXECUTE
     ** IN SCHEMA :  APPS
     **
     ** AUTHORS   :  Meenakshi Rajendran
     **
     ** PURPOSE   :  This script installs the validation tables for Customers.
     **
     ** NOTES     :
	 
     **   Vsn  Change Date  Changed By          Change Description
     ** -----  -----------  ------------------  -----------------------------------
     ** [ 1.0  DD-Mon-YYYY  Change Author       Created.                          ]
     **
     ******************************************************************************
     **
     ** XXMX_CUSTOMER_VALIDATIONS_PKG HISTORY
     ** ------------------------------------
     **
     **   Vsn  Change Date  Changed By                 Change Description
     ** -----  -----------  ------------------         -----------------------------------
     **   1.0  07-FEB-2023  Meenakshi Rajendran        Initial implementation
     ******************************************************************************
     */
--
--	 
PROMPT
PROMPT
PROMPT **************************************************************
PROMPT **
PROMPT ** Installing validation tables for Customers.
PROMPT **
PROMPT **************************************************************
PROMPT
PROMPT
--
--
PROMPT
PROMPT
PROMPT *********************
PROMPT ** Dropping Tables
PROMPT *********************
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_PARTIES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_PARTIES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_PARTY_SITES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_PARTY_SITES_VAL')
--
PROMPT
PROMPT Dropping Table XXMX_HZ_PARTY_SITE_USES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_PARTY_SITE_USES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CUST_ACCOUNTS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CUST_ACCOUNTS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CUST_ACCT_SITES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CUST_ACCT_SITES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CUST_SITE_USES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CUST_SITE_USES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_LOCATIONS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_LOCATIONS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CUST_PROFILES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CUST_PROFILES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CONTACT_POINTS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CONTACT_POINTS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_CUST_ACCT_CONTACTS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_CUST_ACCT_CONTACTS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_ORG_CONTACTS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_ORG_CONTACTS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_ORG_CONTACT_ROLES_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_ORG_CONTACT_ROLES_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_RELATIONSHIPS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_RELATIONSHIPS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_HZ_ROLE_RESPS_VAL
PROMPT
--
EXEC DropTable ('XXMX_HZ_ROLE_RESPS_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_ZX_TAX_PROFILE_VAL
PROMPT
--
EXEC DropTable ('XXMX_ZX_TAX_PROFILE_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_ZX_PARTY_CLASSIFIC_VAL
PROMPT
--
EXEC DropTable ('XXMX_ZX_PARTY_CLASSIFIC_VAL')
--
--
PROMPT
PROMPT Dropping Table XXMX_ZX_TAX_REGISTRATION_VAL
PROMPT
--
EXEC DropTable ('XXMX_ZX_TAX_REGISTRATION_VAL')
--
--
PROMPT
PROMPT Creating Tables
PROMPT
--
  CREATE TABLE XXMX_CORE.XXMX_HZ_PARTIES_VAL
   (VALIDATION_ERROR_MESSAGE     VARCHAR2(3000),
    FILE_SET_ID                  VARCHAR2(30),
	MIGRATION_SET_ID             NUMBER,
	MIGRATION_SET_NAME           VARCHAR2(150),
	MIGRATION_STATUS             VARCHAR2(50),
	BATCH_ID                     NUMBER,
	PARTY_ORIG_SYSTEM            VARCHAR2(30),
	PARTY_ORIG_SYSTEM_REFERENCE  VARCHAR2(240),
	INSERT_UPDATE_FLAG           VARCHAR2(1),
	PARTY_TYPE                   VARCHAR2(30),
	PARTY_NUMBER                 VARCHAR2(30),
	SALUTATION                   VARCHAR2(60),
	PARTY_USAGE_CODE             VARCHAR2(30),
	JGZZ_FISCAL_CODE             VARCHAR2(60),
	ORGANIZATION_NAME            VARCHAR2(360),
	DUNS_NUMBER_C                VARCHAR2(30),
	PERSON_FIRST_NAME            VARCHAR2(150),
	PERSON_LAST_NAME             VARCHAR2(150),
	PERSON_LAST_NAME_PREFIX      VARCHAR2(30),
	PERSON_SECOND_LAST_NAME      VARCHAR2(150),
	PERSON_MIDDLE_NAME           VARCHAR2(60),
	PERSON_NAME_SUFFIX           VARCHAR2(30),
	PERSON_TITLE                 VARCHAR2(60),
	LOAD_REQUEST_ID              NUMBER,
	CREATION_DATE                DATE,
	CREATED_BY                   VARCHAR2(100),
	LAST_UPDATE_DATE             DATE,
	LAST_UPDATED_BY              VARCHAR2(100),
	LOAD_BATCH                   VARCHAR2(300)
   );
   
   --
  
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_PARTY_SITES_VAL
  ( VALIDATION_ERROR_MESSAGE	    VARCHAR2(3000),
	FILE_SET_ID	                    VARCHAR2(30),
	MIGRATION_SET_ID	            NUMBER,
	MIGRATION_SET_NAME	            VARCHAR2(150),
	MIGRATION_STATUS	            VARCHAR2(50),
	BATCH_ID	                    NUMBER,
	PARTY_ORIG_SYSTEM	            VARCHAR2(30),
	PARTY_ORIG_SYSTEM_REFERENCE	    VARCHAR2(240),
	SITE_ORIG_SYSTEM	            VARCHAR2(30),
	SITE_ORIG_SYSTEM_REFERENCE	    VARCHAR2(240),
	LOCATION_ORIG_SYSTEM	        VARCHAR2(30),
	LOCATION_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	INSERT_UPDATE_FLAG	            VARCHAR2(1),
	PARTY_SITE_NAME	                VARCHAR2(240),
	PARTY_SITE_NUMBER	            VARCHAR2(30),
	START_DATE_ACTIVE	            DATE,
	END_DATE_ACTIVE	                DATE,
	MAILSTOP	                    VARCHAR2(60),
	IDENTIFYING_ADDRESS_FLAG	    VARCHAR2(1),
	PARTY_SITE_LANGUAGE	            VARCHAR2(4),
	REL_ORIG_SYSTEM	                VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE	    VARCHAR2(240),
	LOAD_REQUEST_ID	                NUMBER,
	CREATION_DATE	                DATE,
	CREATED_BY	                    VARCHAR2(100),
	LAST_UPDATE_DATE	            DATE,
	LAST_UPDATED_BY	                VARCHAR2(100),
	LOAD_BATCH	                    VARCHAR2(300)
  );
  
    --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_PARTY_SITE_USES_VAL
  ( VALIDATION_ERROR_MESSAGE	      VARCHAR2(3000),
	FILE_SET_ID                       VARCHAR2(30), 
	MIGRATION_SET_ID                  NUMBER,  
	MIGRATION_SET_NAME                VARCHAR2(150),
	MIGRATION_STATUS                  VARCHAR2(50),
	BATCH_ID                          NUMBER, 
	PARTY_ORIG_SYSTEM                 VARCHAR2(30),
	PARTY_ORIG_SYSTEM_REFERENCE       VARCHAR2(240), 
	SITE_ORIG_SYSTEM                  VARCHAR2(30),
	SITE_ORIG_SYSTEM_REFERENCE        VARCHAR2(240), 
	SITE_USE_TYPE                     VARCHAR2(30),
	PRIMARY_FLAG                      VARCHAR2(1), 
	INSERT_UPDATE_FLAG                VARCHAR2(1),  
	START_DATE                        DATE,  
	END_DATE                          DATE,         
	SITEUSE_ORIG_SYSTEM               VARCHAR2(30),
	SITEUSE_ORIG_SYSTEM_REF           VARCHAR2(240), 
	LOAD_REQUEST_ID                   NUMBER,
	CREATION_DATE                     DATE,       
	CREATED_BY                        VARCHAR2(100),
	LAST_UPDATE_DATE                  DATE,
	LAST_UPDATED_BY                   VARCHAR2(100),
	LOAD_BATCH                        VARCHAR2(300)
  );
  
      --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CUST_ACCOUNTS_VAL
  ( VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID	                VARCHAR2(30),
	MIGRATION_SET_ID	        NUMBER,
	MIGRATION_SET_NAME	        VARCHAR2(150),
	MIGRATION_STATUS	        VARCHAR2(50),
	BATCH_ID	                NUMBER,
	CUST_ORIG_SYSTEM	        VARCHAR2(30),
	CUST_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	PARTY_ORIG_SYSTEM	        VARCHAR2(30),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	ACCOUNT_NUMBER	            VARCHAR2(30),
	INSERT_UPDATE_FLAG	        VARCHAR2(1),
	CUSTOMER_TYPE	            VARCHAR2(30),
	CUSTOMER_CLASS_CODE	        VARCHAR2(30),
	ACCOUNT_NAME	            VARCHAR2(240),
	ACCOUNT_ESTABLISHED_DATE	DATE,
	ACCOUNT_TERMINATION_DATE	DATE,
	XXMX_STATUS              	VARCHAR2(1),
	LOAD_REQUEST_ID	            NUMBER,
	CREATION_DATE	            DATE,
	CREATED_BY	                VARCHAR2(100),
	LAST_UPDATE_DATE	        DATE,
	LAST_UPDATED_BY	            VARCHAR2(100),
	LOAD_BATCH	                VARCHAR2(300)
  );


      --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CUST_ACCT_SITES_VAL
  ( VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID	                VARCHAR2(30),
	MIGRATION_SET_ID	        NUMBER,
	MIGRATION_SET_NAME	        VARCHAR2(150),
	MIGRATION_STATUS	        VARCHAR2(50),
	BATCH_ID	                NUMBER,
	CUST_ORIG_SYSTEM	        VARCHAR2(30),
	CUST_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	CUST_SITE_ORIG_SYSTEM	    VARCHAR2(30),
	CUST_SITE_ORIG_SYS_REF	    VARCHAR2(240),
	SITE_ORIG_SYSTEM	        VARCHAR2(30),
	SITE_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	ACCT_SITE_LANGUAGE	        VARCHAR2(4),
	INSERT_UPDATE_FLAG	        VARCHAR2(1),
	CUSTOMER_CATEGORY_CODE	    VARCHAR2(30),
	TRANSLATED_CUSTOMER_NAME	VARCHAR2(360),
	SET_CODE	                VARCHAR2(30),
	START_DATE	                DATE,
	END_DATE	                DATE,
	KEY_ACCOUNT_FLAG	        VARCHAR2(1),
	ACCOUNT_NUMBER	            VARCHAR2(30),
	PARTY_SITE_NUMBER	        VARCHAR2(30),
	XXMX_STATUS	                VARCHAR2(1),
	LOAD_REQUEST_ID	            NUMBER,
	CREATION_DATE	            DATE,
	CREATED_BY	                VARCHAR2(100),
	LAST_UPDATE_DATE	        DATE,
	LAST_UPDATED_BY	            VARCHAR2(100),
	OU_NAME	                    VARCHAR2(500),
	LOAD_BATCH	                VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	NUMBER(15)
  );
  
       --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CUST_SITE_USES_VAL
  ( VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID	                VARCHAR2(30),
	MIGRATION_SET_ID	        NUMBER,
	MIGRATION_SET_NAME	        VARCHAR2(150),
	MIGRATION_STATUS	        VARCHAR2(50),
	BATCH_ID	                NUMBER,
	CUST_SITE_ORIG_SYSTEM	    VARCHAR2(30),
	CUST_SITE_ORIG_SYS_REF	    VARCHAR2(240),
	CUST_SITEUSE_ORIG_SYSTEM	VARCHAR2(30),
	CUST_SITEUSE_ORIG_SYS_REF	VARCHAR2(240),
	SITE_USE_CODE	            VARCHAR2(30),
	PRIMARY_FLAG	            VARCHAR2(1),
	INSERT_UPDATE_FLAG	        VARCHAR2(1),
	LOCATION	                VARCHAR2(150),
	SET_CODE	                VARCHAR2(30),
	START_DATE	                DATE,
	END_DATE	                DATE,
	ACCOUNT_NUMBER	            VARCHAR2(30),
	PARTY_SITE_NUMBER	        VARCHAR2(30),
	LOAD_REQUEST_ID        	    NUMBER,
	CREATION_DATE	            DATE,
	CREATED_BY	                VARCHAR2(100),
	LAST_UPDATE_DATE	        DATE,
	LAST_UPDATED_BY	            VARCHAR2(100),
	OU_NAME	                    VARCHAR2(500),
	LOAD_BATCH	                VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240)
  );
  
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_LOCATIONS_VAL
  ( VALIDATION_ERROR_MESSAGE	    VARCHAR2(3000),
	FILE_SET_ID	                    VARCHAR2(30),
	MIGRATION_SET_ID	            NUMBER,
	MIGRATION_SET_NAME	            VARCHAR2(150),
	MIGRATION_STATUS	            VARCHAR2(50),
	BATCH_ID	                    NUMBER,
	LOCATION_ORIG_SYSTEM	        VARCHAR2(30),
	LOCATION_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	INSERT_UPDATE_FLAG	            VARCHAR2(1),
	COUNTRY	                        VARCHAR2(2),
	ADDRESS1	                    VARCHAR2(240),
	ADDRESS2	                    VARCHAR2(240),
	ADDRESS3	                    VARCHAR2(240),
	ADDRESS4	                    VARCHAR2(240),
	CITY	                        VARCHAR2(60),
	STATE	                        VARCHAR2(60),
	PROVINCE	                    VARCHAR2(60),
	COUNTY	                        VARCHAR2(60),
	POSTAL_CODE	                    VARCHAR2(60),
	POSTAL_PLUS4_CODE	            VARCHAR2(10),
	LOCATION_LANGUAGE	            VARCHAR2(4),
	DESCRIPTION	                    VARCHAR2(2000),
	SHORT_DESCRIPTION				VARCHAR2(240),
	SALES_TAX_GEOCODE				VARCHAR2(30),
	SALES_TAX_INSIDE_CITY_LIMITS	VARCHAR2(1),
	TIMEZONE_CODE					VARCHAR2(50),
	ADDRESS1_STD					VARCHAR2(240),
	ADAPTER_CONTENT_SOURCE			VARCHAR2(30),
	ADDR_VALID_STATUS_CODE			VARCHAR2(30),
	DATE_VALIDATED					DATE,
	ADDRESS_EFFECTIVE_DATE			DATE,
	ADDRESS_EXPIRATION_DATE			DATE,
	VALIDATED_FLAG					VARCHAR2(1),
	DO_NOT_VALIDATE_FLAG			VARCHAR2(1),
	INTERFACE_STATUS				VARCHAR2(30),
	ERROR_ID						NUMBER,
	GNR_STATUS						VARCHAR2(4),
	LOAD_REQUEST_ID					NUMBER,
	CREATION_DATE					DATE,
	CREATED_BY						VARCHAR2(100),
	LAST_UPDATE_DATE				DATE,
	LAST_UPDATED_BY					VARCHAR2(100),
	LOAD_BATCH						VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE		VARCHAR2(240)
);
  
  
   --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CUST_PROFILES_VAL
  ( VALIDATION_ERROR_MESSAGE	     VARCHAR2(3000),
	FILE_SET_ID	                     VARCHAR2(30),
	MIGRATION_SET_ID				 NUMBER,
	MIGRATION_SET_NAME				 VARCHAR2(150),
	MIGRATION_STATUS				 VARCHAR2(50),
	BATCH_ID						 NUMBER,
	INSERT_UPDATE_FLAG				 VARCHAR2(1),
	CUST_ORIG_SYSTEM		  		 VARCHAR2(240),
	CUST_ORIG_SYSTEM_REFERENCE		 VARCHAR2(240),
	CUST_SITE_ORIG_SYSTEM			 VARCHAR2(240),
	CUST_SITE_ORIG_SYS_REF			 VARCHAR2(240),
	CUSTOMER_PROFILE_CLASS_NAME	     VARCHAR2(30),
	COLLECTOR_NAME				     VARCHAR2(30),
	CREDIT_BALANCE_STATEMENTS	     VARCHAR2(1),
	CREDIT_CHECKING					 VARCHAR2(1),
	CREDIT_HOLD					     VARCHAR2(1),
	DISCOUNT_TERMS					 VARCHAR2(1),
	DUNNING_LETTERS					 VARCHAR2(1),
	INTEREST_CHARGES				 VARCHAR2(1),
	STATEMENTS					     VARCHAR2(1),
	TOLERANCE						 NUMBER,
	TAX_PRINTING_OPTION				 VARCHAR2(30),
	ACCOUNT_STATUS					 VARCHAR2(30),
	AUTOCASH_HIERARCHY_NAME			 VARCHAR2(30),
	CREDIT_RATING					 VARCHAR2(30),
	DISCOUNT_GRACE_DAYS				 NUMBER,
	INTEREST_PERIOD_DAYS			 NUMBER,
	OVERRIDE_TERMS				     VARCHAR2(1),
	PAYMENT_GRACE_DAYS			     NUMBER,
	PERCENT_COLLECTABLE	             NUMBER,
	RISK_CODE	                     VARCHAR2(30),
	STANDARD_TERM_NAME	             VARCHAR2(15),
	STATEMENT_CYCLE_NAME	         VARCHAR2(15),
	CHARGE_ON_FINANCE_CHARGE_FLAG	 VARCHAR2(1),
	GROUPING_RULE_NAME	             VARCHAR2(40),
	CURRENCY_CODE	                 VARCHAR2(15),
	AUTO_REC_MIN_RECEIPT_AMOUNT	     NUMBER,
	INTEREST_RATE	                 NUMBER,
	MAX_INTEREST_CHARGE	             NUMBER,
	MIN_DUNNING_AMOUNT	             NUMBER,
	MIN_DUNNING_INVOICE_AMOUNT	     NUMBER,
	MIN_FC_BALANCE_AMOUNT	         NUMBER,
	MIN_FC_INVOICE_AMOUNT	         NUMBER,
	MIN_STATEMENT_AMOUNT	         NUMBER,
	OVERALL_CREDIT_LIMIT	         NUMBER,
	TRX_CREDIT_LIMIT	             NUMBER,
	PARTY_ORIG_SYSTEM	             VARCHAR2(240),
	PARTY_ORIG_SYSTEM_REFERENCE	     VARCHAR2(240),
	AUTO_REC_INCL_DISPUTED_FLAG	     VARCHAR2(1),
	CLEARING_DAYS					 NUMBER,
	ORG_ID	                         NUMBER,
	CONS_INV_FLAG	                 VARCHAR2(1),
	CONS_INV_TYPE	                 VARCHAR2(30),
	LOCKBOX_MATCHING_OPTION	         VARCHAR2(30),
	AUTOCASH_HIERARCHY_NAME_ADR	     VARCHAR2(30),
	CREDIT_CLASSIFICATION	         VARCHAR2(30),
	CONS_BILL_LEVEL	                 VARCHAR2(30),
	LATE_CHARGE_CALCULATION_TRX	     VARCHAR2(30),
	CREDIT_ITEMS_FLAG	             VARCHAR2(1),
	DISPUTED_TRANSACTIONS_FLAG	     VARCHAR2(1),
	LATE_CHARGE_TYPE	             VARCHAR2(30),
	INTEREST_CALCULATION_PERIOD	     VARCHAR2(30),
	HOLD_CHARGED_INVOICES_FLAG	     VARCHAR2(1),
	MULTIPLE_INTEREST_RATES_FLAG	 VARCHAR2(1),
	CHARGE_BEGIN_DATE	             DATE,
	EXCHANGE_RATE_TYPE	             VARCHAR2(30),
	MIN_FC_INVOICE_OVERDUE_TYPE	     VARCHAR2(30),
	MIN_FC_INVOICE_PERCENT	         NUMBER,
	MIN_FC_BALANCE_OVERDUE_TYPE	     VARCHAR2(30),
	MIN_FC_BALANCE_PERCENT	         NUMBER,
	INTEREST_TYPE	                 VARCHAR2(30),
	INTEREST_FIXED_AMOUNT	         NUMBER,
	PENALTY_TYPE					 VARCHAR2(30),
	PENALTY_RATE					 NUMBER,
	MIN_INTEREST_CHARGE				 NUMBER,
	PENALTY_FIXED_AMOUNT			 NUMBER,
	CREDIT_ANALYST_NAME				 VARCHAR2(240),
	CREDIT_REVIEW_CYCLE				 VARCHAR2(20),
	LAST_CREDIT_REVIEW_DATE	         DATE,
	NEXT_CREDIT_REVIEW_DATE	         DATE,
	AUTOMATCH_RULE_NAME	             VARCHAR2(30),
	MATCH_BY_AUTOUPDATE_FLAG	     VARCHAR2(1),
	PRINTING_OPTION_CODE	         VARCHAR2(30),
	TXN_DELIVERY_METHOD	             VARCHAR2(30),
	STMT_DELIVERY_METHOD	         VARCHAR2(30),
	XML_INV_FLAG	                 VARCHAR2(1),
	XML_DM_FLAG	                     VARCHAR2(1),
	XML_CB_FLAG	                     VARCHAR2(1),
	XML_CM_FLAG	                     VARCHAR2(1),
	CMK_CONFIG_FLAG	                 VARCHAR2(1),
	SERVICE_PROVIDER_NAME	         VARCHAR2(256),
	PARTNER_ID	                     VARCHAR2(100),
	PARTNER_ID_TYPE_CODE	         VARCHAR2(100),
	AR_OUTBOUND_TRANSACTION_FLAG	 VARCHAR2(1),
	AR_INBOUND_CONFIRM_BOD_FLAG	     VARCHAR2(1),
	ACCOUNT_NUMBER	                 VARCHAR2(30),
	PARTY_NUMBER	                 VARCHAR2(30),
	PREF_CONTACT_METHOD				 VARCHAR2(30),
	INTEREST_SCHEDULE_ID			 NUMBER,
	PENALTY_SCHEDULE_ID	  			 NUMBER,
	LOAD_REQUEST_ID			         NUMBER,
	CREATION_DATE				     DATE,
	CREATED_BY		          		 VARCHAR2(100),
	LAST_UPDATE_DATE				 DATE,
	LAST_UPDATED_BY					 VARCHAR2(100),
	OU_NAME						     VARCHAR2(100),
	LOAD_BATCH						 VARCHAR2(300)
);

 --
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CONTACT_POINTS_VAL
  ( VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID	                VARCHAR2(30),
	MIGRATION_SET_ID	        NUMBER,
	MIGRATION_SET_NAME	        VARCHAR2(150),
	MIGRATION_STATUS	        VARCHAR2(50),
	BATCH_ID	                NUMBER,
	CP_ORIG_SYSTEM	            VARCHAR2(30),
	CP_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	PARTY_ORIG_SYSTEM	        VARCHAR2(30),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	SITE_ORIG_SYSTEM	        VARCHAR2(30),
	SITE_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	PRIMARY_FLAG	            VARCHAR2(1),
	INSERT_UPDATE_FLAG	        VARCHAR2(1),
	CONTACT_POINT_TYPE	        VARCHAR2(30),
	CONTACT_POINT_PURPOSE	    VARCHAR2(30),
	EMAIL_ADDRESS	            VARCHAR2(320),
	EMAIL_FORMAT	            VARCHAR2(30),
	PHONE_AREA_CODE	            VARCHAR2(10),
	PHONE_COUNTRY_CODE	        VARCHAR2(10),
	PHONE_EXTENSION	            VARCHAR2(20),
	PHONE_LINE_TYPE	            VARCHAR2(30),
	PHONE_NUMBER	            VARCHAR2(40),
	URL	                        VARCHAR2(2000),
	PHONE_CALLING_CALENDAR	    VARCHAR2(30),
	START_DATE				    DATE,
	END_DATE	                DATE,
	REL_ORIG_SYSTEM	            VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	LOAD_REQUEST_ID	            NUMBER,
	CREATION_DATE	            DATE,
	CREATED_BY	                VARCHAR2(100),
	LAST_UPDATE_DATE	        DATE,
	LAST_UPDATED_BY	            VARCHAR2(100),
	LOAD_BATCH	                VARCHAR2(300)
);
  
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_CUST_ACCT_CONTACTS_VAL
   (VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID			NUMBER,
	MIGRATION_SET_NAME			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BATCH_ID					NUMBER,
	CUST_ORIG_SYSTEM			VARCHAR2(30),
	CUST_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	CUST_SITE_ORIG_SYSTEM		VARCHAR2(30),
	CUST_SITE_ORIG_SYS_REF		VARCHAR2(240),
	CUST_CONTACT_ORIG_SYSTEM	VARCHAR2(30),
	CUST_CONTACT_ORIG_SYS_REF	VARCHAR2(240),
	ROLE_TYPE					VARCHAR2(30),
	PRIMARY_FLAG				VARCHAR2(1),
	INSERT_UPDATE_FLAG			VARCHAR2(1),
	SOURCE_CODE					VARCHAR2(150),
	REL_ORIG_SYSTEM				VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	LOAD_REQUEST_ID				NUMBER,
	CREATION_DATE				DATE,
	CREATED_BY					VARCHAR2(100),
	LAST_UPDATE_DATE			DATE,
	LAST_UPDATED_BY				VARCHAR2(100),
	LOAD_BATCH					VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240)
   );
   
     
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_ORG_CONTACTS_VAL
   (VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID			NUMBER,
	MIGRATION_SET_NAME			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BATCH_ID					NUMBER,
	INSERT_UPDATE_FLAG			VARCHAR2(1),
	CONTACT_NUMBER				VARCHAR2(30),
	DEPARTMENT_CODE				VARCHAR2(30),
	DEPARTMENT					VARCHAR2(60),
	JOB_TITLE					VARCHAR2(100),
	JOB_TITLE_CODE				VARCHAR2(30),
	REL_ORIG_SYSTEM				VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	PS_ORIG_SYSTEM				VARCHAR2(30),
	PS_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	LOAD_REQUEST_ID				NUMBER,
	CREATION_DATE				DATE,
	CREATED_BY					VARCHAR2(100),
	LAST_UPDATE_DATE			DATE,
	LAST_UPDATED_BY				VARCHAR2(100),
	LOAD_BATCH					VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240)
   );
   
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_ORG_CONTACT_ROLES_VAL
   (VALIDATION_ERROR_MESSAGE		VARCHAR2(3000),
	FILE_SET_ID						VARCHAR2(30),
	MIGRATION_SET_ID				NUMBER,
	MIGRATION_SET_NAME				VARCHAR2(150),
	MIGRATION_STATUS				VARCHAR2(50),
	BATCH_ID						NUMBER,
	INTERFACE_ROW_ID				VARCHAR2(80),
	INSERT_UPDATE_CODE				VARCHAR2(30),
	INSERT_UPDATE_FLAG				VARCHAR2(1),
	CONTACT_ROLE_ORIG_SYSTEM		VARCHAR2(30),
	CONTACT_ROLE_ORIG_SYS_REF		VARCHAR2(240),
	REL_ORIG_SYSTEM					VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE		VARCHAR2(240),
	ROLE_TYPE						VARCHAR2(30),
	ROLE_LEVEL						VARCHAR2(1),
	PRIMARY_FLAG					VARCHAR2(1),
	PRIMARY_CONTACT_PER_ROLE_TYPE	VARCHAR2(1),
	LOAD_REQUEST_ID					NUMBER,
	CREATION_DATE					DATE,
	CREATED_BY						VARCHAR2(100),
	LAST_UPDATE_DATE				DATE,
	LAST_UPDATED_BY					VARCHAR2(100),
	LOAD_BATCH						VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE		VARCHAR2(240)
   );
   
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_RELATIONSHIPS_VAL
   (VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID			NUMBER,
	MIGRATION_SET_NAME			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BATCH_ID					NUMBER,
	SUB_ORIG_SYSTEM				VARCHAR2(30),
	SUB_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	OBJ_ORIG_SYSTEM				VARCHAR2(30),
	OBJ_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	RELATIONSHIP_TYPE			VARCHAR2(30),
	RELATIONSHIP_CODE			VARCHAR2(30),
	START_DATE					DATE,
	INSERT_UPDATE_FLAG			VARCHAR2(1),
	END_DATE					DATE,
	SUBJECT_TYPE				VARCHAR2(30),
	OBJECT_TYPE					VARCHAR2(30),
	REL_ORIG_SYSTEM				VARCHAR2(30),
	REL_ORIG_SYSTEM_REFERENCE	VARCHAR2(240),
	LOAD_REQUEST_ID				NUMBER,
	CREATION_DATE				DATE,
	CREATED_BY					VARCHAR2(100),
	LAST_UPDATE_DATE			DATE,
	LAST_UPDATED_BY				VARCHAR2(100),
	LOAD_BATCH					VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240)
   );
   
  --
  CREATE TABLE XXMX_CORE.XXMX_HZ_ROLE_RESPS_VAL
   (VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),
	FILE_SET_ID					VARCHAR2(30),
	MIGRATION_SET_ID			NUMBER,
	MIGRATION_SET_NAME			VARCHAR2(150),
	MIGRATION_STATUS			VARCHAR2(50),
	BATCH_ID					NUMBER,
	INSERT_UPDATE_CODE			VARCHAR2(30),
	INSERT_UPDATE_FLAG			VARCHAR2(1),
	CUST_CONTACT_ORIG_SYSTEM	VARCHAR2(30),
	CUST_CONTACT_ORIG_SYS_REF	VARCHAR2(240),
	ROLE_RESP_ORIG_SYSTEM		VARCHAR2(30),
	ROLE_RESP_ORIG_SYS_REF		VARCHAR2(240),
	RESPONSIBILITY_TYPE			VARCHAR2(30),
	PRIMARY_FLAG				VARCHAR2(1),
	LOAD_REQUEST_ID				NUMBER,
	CREATION_DATE				DATE,
	CREATED_BY					VARCHAR2(100),
	LAST_UPDATE_DATE			DATE,
	LAST_UPDATED_BY				VARCHAR2(100),
	LOAD_BATCH					VARCHAR2(300),
	PARTY_ORIG_SYSTEM_REFERENCE	VARCHAR2(240)
   );
   
  --
  CREATE TABLE XXMX_CORE.XXMX_ZX_TAX_PROFILE_VAL
   (VALIDATION_ERROR_MESSAGE		VARCHAR2(3000),
	FILE_SET_ID						VARCHAR2(30),
	MIGRATION_SET_ID				NUMBER,
	MIGRATION_SET_NAME				VARCHAR2(100),
	MIGRATION_STATUS				VARCHAR2(50),
	PARTY_TYPE_CODE					VARCHAR2(80),
	PARTY_NUMBER					VARCHAR2(30),
	PARTY_NAME						VARCHAR2(150),
	PROCESS_FOR_APPLICABILITY_FLAG	VARCHAR2(3),
	ROUNDING_LEVEL_CODE				VARCHAR2(80),
	ROUNDING_RULE_CODE				VARCHAR2(80),
	TAX_CLASSIFICATION_CODE			VARCHAR2(30),
	INCLUSIVE_TAX_FLAG				VARCHAR2(3),
	ALLOW_OFFSET_TAX_FLAG			VARCHAR2(3),
	COUNTRY_CODE					VARCHAR2(2),
	REGISTRATION_TYPE_CODE			VARCHAR2(80),
	REP_REGISTRATION_NUMBER			VARCHAR2(50),
	LOAD_BATCH						VARCHAR2(300)
   );
   
  DROP TABLE XXMX_CORE.XXMX_ZX_PARTY_CLASSIFIC_VAL ;
  --
  CREATE TABLE XXMX_CORE.XXMX_ZX_PARTY_CLASSIFIC_VAL
   (VALIDATION_ERROR_MESSAGE	VARCHAR2(3000),	
	FILE_SET_ID					VARCHAR2(30),	
	MIGRATION_SET_ID			NUMBER,	
	MIGRATION_SET_NAME			VARCHAR2(100),
	MIGRATION_STATUS			VARCHAR2(50),	
	PARTY_TYPE_CODE				VARCHAR2(80),	
	PARTY_NUMBER				VARCHAR2(30),	
	PARTY_NAME					VARCHAR2(150),	
	CLASS_CATEGORY				VARCHAR2(30),	
	CLASSIFICATION_TYPE_CODE	VARCHAR2(30),	
	CLASSIFICATION_TYPE_NAME	VARCHAR2(150),	
	TAX_REGIME_CODE				VARCHAR2(30),	
	FISCAL_CLASSIFICATION_CODE	VARCHAR2(30),	
	CLASS_CODE					VARCHAR2(80),	
	EFFECTIVE_FROM				DATE,
	EFFECTIVE_TO				DATE,	
	LOAD_BATCH					VARCHAR2(300)	
   );
   
  --
  CREATE TABLE XXMX_CORE.XXMX_ZX_TAX_REGISTRATION_VAL
   (VALIDATION_ERROR_MESSAGE		VARCHAR2(3000),
	FILE_SET_ID						VARCHAR2(30),
	MIGRATION_SET_ID				NUMBER,
	MIGRATION_SET_NAME				VARCHAR2(100),
	MIGRATION_STATUS				VARCHAR2(50),
	PARTY_TYPE_CODE					VARCHAR2(80),
	PARTY_NUMBER					VARCHAR2(30),
	PARTY_NAME						VARCHAR2(150),
	TAX_REGIME_CODE					VARCHAR2(30),
	TAX								VARCHAR2(30),
	TAX_JURISDICTION_CODE			VARCHAR2(30),
	REGISTRATION_TYPE_CODE			VARCHAR2(80),
	REGISTRATION_NUMBER				VARCHAR2(50),
	EFFECTIVE_FROM					DATE,
	EFFECTIVE_TO					DATE,
	DEFAULT_REGISTRATION_FLAG		VARCHAR2(3),
	REGISTRATION_REASON_CODE		VARCHAR2(30),
	REGISTRATION_STATUS_CODE		VARCHAR2(30),
	REGISTRATION_SOURCE_CODE		VARCHAR2(30),
	REP_PARTY_TAX_NAME				VARCHAR2(80),
	ROUNDING_RULE_CODE				VARCHAR2(80),
	ROUNDING_LEVEL_CODE				VARCHAR2(80),
	SELF_ASSESS_FLAG				VARCHAR2(3),
	INCLUSIVE_TAX_FLAG				VARCHAR2(3),
	TAX_POINT_BASIS					VARCHAR2(80),
	ISSUING_TAX_AUTHORITY			VARCHAR2(30),
	COLLECTING_TAX_AUTHORITY		VARCHAR2(30),
	REPORTING_TAX_AUTHORITY			VARCHAR2(30),
	VALIDATION_TYPE					VARCHAR2(30),
	SELF_ASSESS_DIFF_TOL_LMT_FLAG	VARCHAR2(30),
	MIN_SELF_ASSESS_DIFF_TOL_LIMIT	NUMBER,
	MAX_SELF_ASSESS_DIFF_TOL_LIMIT	NUMBER,
	LOAD_BATCH						VARCHAR2(300)
   );